### ISSUE TITLE
list of dependencies for Viper is incomplete

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#100]
Viper depends on the numpy and VTK modules, but currently no dependencies are listed

Because VTK and numpy are not available, the `import viper` sanity check fails.

To get around this issue, the Viper example easyconfigs are currently using

``` python
options = {'modulename': 'os'}
```

**Comment by migueldiascosta** [comment]
Viper easyconfigs have been archived
