### ISSUE TITLE
Checksum of tbb-2019_U9-GCCcore-8.3.0.eb

### ISSUE THREAD

**Issue by sassy-crick** [easybuilders/easybuild-easyconfigs#10238]
The checksum of the build recipe tbb-2019_U9-GCCcore-8.3.0.eb is not correct any more as upstream has changed some folder names. The new build file was uploaded to PR #10237 .
In PR#10237 the build file contains both the original and new sha256 checksums.
This is not a bug in Easybuild but a problem from the upstream source.

**Comment by Micket** [comment]
That PR was merged, so this is solved.
