### ISSUE TITLE
SCons config needs to set SCONS_LIB_DIR

### ISSUE THREAD

**Issue by pforai** [easybuilders/easybuild-easyconfigs#1023]
Just encountered this when trying to run EB provided SCons. It seems SCons versions >= ~2.0 need to set `$SCONS_LIB_DIR` in order for SCons to be able to pick up it's own files. 

On our systems this something like this helps: 
`export SCONS_LIB_DIR=$EBROOTSCONS/lib/scons-2.3.0`

**Comment by Micket** [comment]
This does not seem to be the case anymore (at least when easybuild uses scons to build packages itself, this has never shown it self to be a requirement (scons claims that it should be able to deduce this path automatically). Closing.
