### ISSUE TITLE
Proper blas and lapack not being found in QuantumESPRESSO

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyconfigs#1024]
Looking at the output from the configure step of QuantumESPRESSO I noticed it says:

```
The following libraries have been found:
  BLAS_LIBS=/usr/local/eb/hierarchical/installed/software/MPI/GCC/4.9.1/MPICH2/Parastation-5.0.27/QuantumESPRESSO/5.0.2/espresso-5.0.2/BLAS/blas.a
  LAPACK_LIBS=/usr/local/eb/hierarchical/installed/software/MPI/GCC/4.9.1/MPICH2/Parastation-5.0.27/QuantumESPRESSO/5.0.2/espresso-5.0.2/lapack-3.2/lapack.a
  FFT_LIBS= -lfftw3 
```

so it looks like it is failing to find the installed libraries and building its own instead.

**Comment by Micket** [comment]
Very sure this isn't happening anymore with any of the recent QE', so sometime in the past 9.5 years this eventually got fixed. I hope :)
