### ISSUE TITLE
CVS is not included in EasyBuild releases

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#10325]
The whole folder https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/c/CVS is removed from EasyBuild source distributions.

This happens as part of `python setup.py sdist`.

https://docs.python.org/2/distutils/sourcedist.html#principle
> exclude the entire build tree, and any RCS, CVS, .svn, .hg, .git, .bzr and _darcs directories

https://packaging.python.org/guides/using-manifest-in/
>After processing the MANIFEST.in file, setuptools removes the build/ directory as well as any directories named RCS, CVS, or .svn from the sdist, and it adds a PKG-INFO file and an *.egg-info directory. This behavior cannot be changed with MANIFEST.in.

**Comment by akesandgren** [comment]
Finally a really good feature of setup.py :-) Good riddance...
