### ISSUE TITLE
Are variables related to dependencies accessible within an EasyConfig?

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-easyconfigs#10376]
I am working on writing an EasyConfig for one of my experiment's software packages (i.e., not something out there for public distribution).  It uses CMake and make, so I was hoping to just use that easyblock directly, instead of writing a custom one.  

The package depends on Geant4, and wants the user to specify `-DGeant4_DIR=<G4-top-level-directory>` as a CMake option.  I can do this with `configopts`, but I don't know how to get the directory specification.  At the command line, with the G4 module loaded, I would just write `cmake -DGeant4_DIR=$EBROOTGEANT4 . . .`  But how do I do the equivalent in my EasyConfig `.eb` file?

Do I need to write a custom EasyBlock, and use `get_software_root('Geant4')`?  I don't think I can have arbitrary Python code in my `.eb` file, can I?

Is this something that should be in the documentation?  If so, what magic words should I have used to find it?

**Comment by kelseymh** [comment]
I wrote a custom EasyBlock and put it into my search (--include-easyblocks`) and it worked.

I'm still interested in knowing whether this is possible without an EasyBlock.

**Comment by kelseymh** [comment]
I am running into several other packages in my collaboration's software which have this issue.  Both Make-based and CMake-based, they need build options set to point to other packages' directories.  

Am I going to have write custom EasyBlocks (essentially one-liners, except for all the extra surrounding code) for each of these packages, just to set configopts with a dependent's directory path?

**Comment by akesandgren** [comment]
For a simple example look at the Tk easyconfig, Tk-8.6.8-GCCcore-7.3.0.eb, it show you how to access installdirs for Tcl in this case.
The same can be applied to any (build)dependency in an easyconfig file.

EBROOTxxx and EBVERSIONxxx are available for any package xxx

**Comment by kelseymh** [comment]
Great!  That's just what I was looking for.  And those get set by the dependency=[...] within `eb`, so it should work even with a bare `module purge` session?  Thank you very much!

**Comment by akesandgren** [comment]
Exactly.

And when using EB you should usually only have EB loaded.

Note: EasyBuild should normally complain if you have any other modules loaded when running it. 
If it doesn't then something is off in the configuration file.

**Comment by kelseymh** [comment]
> Note: EasyBuild should normally complain if you have any other modules loaded when running it.  If it doesn't then something is off in the configuration file.

It does.  I have `--detect-loaded-modules=purge` set for all my EB running.  Your suggestion worked perfectly; just what I needed.  Thank you!
