### ISSUE TITLE
PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4  and ibverbs.

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyconfigs#10402]
When trying to install `PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4` from EasyBuild 4.2.0 on RHEL8, it broke due to ibverbs not being found. After some prodding by @Flamefire and @branfosj I installed `rdma-core-devel` which provides `/usr/include/infiniband/verbs.h`, which resolved the issue. It is worth noting that under RHEL8 there is a package called `libibverbs`, but there is no corresponding `libibverbs-devel` -- that role is clearly filled by `rdma-core-devel`.

Should this be a system dependency for PyTorch?

**Comment by Flamefire** [comment]
The package on RHEL 7.7 es reported by `rpm -qf /usr/include/infiniband/verbs.h` is `libibverbs-devel-41mlnx1-OFED.4.7.0.0.2.47100.x86_64`

So I guess we could make it either `libibverbs-devel` or `rdma-core-devel` and it would work for both

**Comment by terjekv** [comment]
The libibverbs-devel-41mlnx1-OFED.4.7.0.0.2.47100.x86_64 RHEL7 package comes from the Mellanox repos: https://linux.mellanox.com/public/repo/mlnx_ofed/4.5-1.0.1.0/rhel7.6/x86_64/

Hopefully other vendors retain the core name of libibverbs-devel, otherwise this is going to be a fun game of whack-a-mole. :-(

**Comment by terjekv** [comment]
Fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/10540

**Comment by boegel** [comment]
fixed in #10540, so closing...
