### ISSUE TITLE
WRF-4.0.2-foss-2018b-dmpar.eb

### ISSUE THREAD

**Issue by ESSinclair** [easybuilders/easybuild-easyconfigs#10409]
Dear All

I am facing issues installing WRF-4.0.2-foss-2018b-dmpar.eb
It seems to  fail at some validation step and the installation does not finish.

ERROR: Build of /tmp/eb-1nEGvG/reprod_20200415122933_108742/WRF-4.0.2-foss-2018b-dmpar.eb failed (err: 'build failed (first 300 chars):
 Test em_b_wave failed with exit code 132, output: FILE NOT FOUND')

I have had this error in other versions and it could be solved editting  configure.wrf

Modify line		

FC              =       $(DM_FC)
instead

FC              =       time $(DM_FC)

Is this possible using EasyBuild? I mean the tar is uncompressed from scracth while installing and the changes in the file will not remain
Is this right or I have missunderstood some steps?

Other option could be compiling wrf from source but using easyBuild for the dependencies, but in this case I rececive the error as follows

NETCDF4 IO features are requested, but this installation of NetCDF
  /software/shared/apps/netCDF-Fortran/4.4.4-foss-2018b
DOES NOT support these IO features.

Please make sure NETCDF version is 4.1.3 or later and was built with
--enable-netcdf4

OR set NETCDF_classic variable
   bash/ksh : export NETCDF_classic=1
      echo  csh : setenv NETCDF_classic 1

Then re-run this configure script

!!! configure.wrf has been REMOVED !!!

Is there any chance for solving this? would it require to write a new EasyConfig?

Any suggestion will be really apreciated

Best Regards

**Comment by lexming** [comment]
@ESSinclair Thanks for reporting this issue. I've been able to reproduce various errors with the easyconfigs of WRF on my side. I did not experience your exact same situation, but I suspect that the issues I found will be related to yours as well.

The errors stem from the `wrf` easyblock handling those builds and, as you said, affect the easyconfigs of several versions of WRF. I've opened a PR with fixes for it in https://github.com/easybuilders/easybuild-easyblocks/pull/2079. If possible, please test your issue with the fixes from there and report back.
