### ISSUE TITLE
Duplicate: o/OpenPyXL and o/openpyxl

### ISSUE THREAD

**Issue by crubb** [easybuilders/easybuild-easyconfigs#10611]
Hey guys,

there is [o/OpenPyXL](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/o/OpenPyXL) with v2.6.4 by @lexming (used by [f/FusionCatcher/FusionCatcher-1.20-foss-2019b-Python-2.7.16.eb](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/f/FusionCatcher/FusionCatcher-1.20-foss-2019b-Python-2.7.16.eb))

and there is [o/openpyxl](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/o/openpyxl) with v2.6.2 by @boegel and v3.0.3 (by me), used by [c/csvkit/csvkit-1.0.4-GCCcore-8.2.0.eb](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/c/csvkit/csvkit-1.0.4-GCCcore-8.2.0.eb) and csvkit v1.0.5, which is #10610.

Spelling seems to be openpyxl, according to https://pypi.org/project/openpyxl/

Some merging required? ;)

Best,
crubb

**Comment by lexming** [comment]
@crubb thanks for reporting this issue. This is my fault, somehow I overlooked the existing easyconfigs for `openpyxl` in my PR for `FusionCatcher`.
