### ISSUE TITLE
Building Perl-5.30.0-GCCcore-8.3.0: cannot find compatible libtinfo

### ISSUE THREAD

**Issue by willfurnass** [easybuilders/easybuild-easyconfigs#10663]
My setup: Centos 7.8 and EasyBuild 4.2.1

Tried to build `Perl-5.30.0-GCCcore-8.3.0` to complement my `foss-2019b` toolchain and got:

```console
$ grep tinfo Perl-5.30.0-GCCcore-8.3.0-1168025.out 
/usr/local/packages/staging/eb/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: warning: skipping incompatible //lib/libtinfo.so while searching for tinfo
/usr/local/packages/staging/eb/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: warning: skipping incompatible //usr/lib/libtinfo.so while searching for tinfo
/usr/local/packages/staging/eb/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: error: cannot find -ltinfo
```

`libtinfo` is one of the ncurses libs.

In the `ncurses*.eb` easyconfigs that use the `SYSTEM` toolchain relevant symlinks are created: 

```python
# Symlink libtinfo to libncurses (since it can handle the API) so it doesn't get picked up from the OS
postinstallcmds = [
    "ln -s %(installdir)s/lib/libncurses.so %(installdir)s/lib/libtinfo.so",
    "ln -s %(installdir)s/lib/libncurses.a %(installdir)s/lib/libtinfo.a"
]
```

but no symlinks are created by the `ncurses` easyconfigs for non-`SYSTEM` toolchains (e.g. the `GCCcore-8.3.0` toolchain that I want to use).  There is apparently a good reason for symlinks not being created by those non-`SYSTEM` easyconfigs this but nobody seems to remember why (see https://github.com/easybuilders/easybuild-easyconfigs/pull/5863).

A possible workaround is to add the symlinks to ncurses-6.1-GCCcore-8.3.0.eb (provided it does not break other software of course) but I've created this issue as it seems surprising that others haven't encountered this.

**Comment by willfurnass** [comment]
Tried installing the `foss-2020a` toolchain, which has `Perl-5.30.2-GCCcore-9.3.0` as a dependency and encountered the same issue.

**Comment by willfurnass** [comment]
Ah, installing the ncurses-devel RPM that matches the machine architecture helped:

I previously had:

```console
$ rpm -qa | grep ncurses
ncurses-5.9-14.20130511.el7_4.x86_64
ncurses-devel-5.9-14.20130511.el7_4.i686  <- NB 32-bit version required by Abaqus
ncurses-libs-5.9-14.20130511.el7_4.x86_64
ncurses-libs-5.9-14.20130511.el7_4.i686
ncurses-base-5.9-14.20130511.el7_4.noarch
```

I was able to build `Perl-5.30.2-GCCcore-9.3.0` after installing `ncurses-devel-5.9-14.20130511.el7_4.x86_64`!

Not a bug in the Perl/ncurses easyblocks/easyconfigs then?

**Comment by akesandgren** [comment]
That Perl easyconfig should not use the system installed ncurses, so if it does there is a problem somewhere.

**Comment by willfurnass** [comment]
Yep, `Perl-5.30.2-GCCcore-9.3.0` depends on `ncurses-6.1-GCCcore-8.3.0` *but* Perl wants a `libtinfo` (see original comment in this Issue) but `ncurses-6.1-GCCcore-8.3.0` doesn't provide one, only the Centos ncurses RPMs do: 

```console
$ find /usr/local/packages/staging/eb/ncurses/6.2-GCCcore-9.3.0 -iname 'libtinfo*'
$ 
$ rpm -ql ncurses-libs | grep tinfo 
/usr/lib64/libtinfo.so.5
/usr/lib64/libtinfo.so.5.9
/usr/lib/libtinfo.so.5
/usr/lib/libtinfo.so.5.9
```

**Comment by boegel** [comment]
@willfurnass #5067 has some context on symlinking `libtinfo.so` for the `ncurses` built with the `system` toolchain, which mentions "We had the split libtinfo before, and that caused problems".

So I *think* the conservatism w.r.t. not symlinking actually stems from some confusion: we've seen problems when having a separate `libtinfo` that is *not* a symlink, see for example #4049 .

We're adding `libtinfo` symlinks for ncurses 6.2 in #13660...
