### ISSUE TITLE
OpenBLAS-0.3.7-GCC-8.3.0: tests fails on Power8

### ISSUE THREAD

**Issue by zdemat** [easybuilders/easybuild-easyconfigs#10748]
OpenBLAS-0.3.7-GCC-8.3.0.eb: cblas_cgemv and other tests are failing on Power8 (POWER8NVL, ppc64le, CentOS 7.5.1804)

```bash
 ......
 ......
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (  -0.342872    ,   0.714919E-02)  (  -0.170330E+10,   0.883616E+10)
       2  (   0.233743    ,  -0.822020E-01)  (  -0.342872    ,   0.714919E-02)
       3  (   0.376182E-01,   0.161061    )  (   0.233743    ,  -0.822020E-01)
       4  (   0.144652    ,   0.137748    )  (   0.376182E-01,   0.161061    )
 ******* cblas_cgemv  FAILED ON CALL NUMBER:
    440: cblas_cgemv (  CblasNoTrans,  4,  2,( 1.0, 0.0), A,
            5, X, 1,( 0.0, 0.0), Y, 1) .
 ******* cblas_cgemv  FAILED ON CALL NUMBER:
      4: cblas_cgemv (  CblasNoTrans,  2,  1,( 0.0, 0.0), A,
            3, X, 1,( 0.0, 0.0), Y, 1) .

 ******* FATAL ERROR - TESTS ABANDONED *******
 ......
 ......
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
```

The issue seems to be resolved in OpenBLAS-0.3.9 and applying [OpenBLAS/#pr2243](https://github.com/xianyi/OpenBLAS/pull/2243) seems to allow to pass the tests and finish the build. Other consequences are unknown at the moment.

**Comment by boegel** [comment]
@branfosj @edmondac Thoughts on this? Should we apply that patch into the OpenBLAS 0.3.7 easyconfig?

**Comment by branfosj** [comment]
Testing on POWER9 both before and after applying https://github.com/xianyi/OpenBLAS/pull/2243 we have
```
 cblas_cgemv  PASSED THE TESTS OF ERROR-EXITS

 cblas_cgemv  PASSED THE COMPUTATIONAL TESTS (  4324 CALLS)
 cblas_cgemv  PASSED THE COMPUTATIONAL TESTS (  4324 CALLS)
```

I've looked at the patch and the OpenBLAS 0.3.7 code and I think I have to trust that OpenBLAS developers.

I'm currently testing SciPy-bundle to see if it has any impact on the numpy/scipy tests.

**Comment by zdemat** [comment]
I tried once more with different SMT settings and no difference. Without a patch it cannot pass the test on POWER8NVL. After the patch I could install also the SciPy-bundle.

**Comment by boegel** [comment]
Not really relevant anymore now, so closing...
