### ISSUE TITLE
PETSc requires python.

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyconfigs#10865]
PETSc calls `/usr/bin/env python` during build. This breaks RHEL8 (and other distributions) where there is no `python`.

**Comment by terjekv** [comment]
Hm, PETSc also wants a python with `numpy` and `mpi4py`, so giving it `SciPy-bundle` is fine, but shouldn't the module then be named `PETSc-3.12.4-foss-2019b-Python-3.7.4.eb` as `SciPy-bundle` uses a versionsuffix for Python?

**Comment by boegel** [comment]
@terjekv Yes, it seems we somehow overlooked these requirements in PETSc...

For the latest easyconfigs it's fixed (see #10532), but we may want to fix previous ones too.

**Comment by terjekv** [comment]
How do we want this fixed? Adding a versionsuffix will break any dependencies. Is not adding versionsuffix while adding Python 3.7.4 as a dependency an option?

**Comment by boegel** [comment]
@terjekv The proper thing would be adding the missing `versionsuffix` along with the missing dependency, and fix any easyconfigs in the repository that depend on `PETSc` accordingly.

**Comment by lexming** [comment]
First round of fixes for this issue

1. As suggested, I'm adding new easyconfigs for those versions of PETSc that currently lack dependencies on Python and `numpy` from EB. The new easyconfigs have a `versionsuffix` on Python. They follow what has already been done in `2020a`. Affected versions are
    * v3.9.3 in `2018a`
    * v3.11.1 in `2019a`
    * v3.12.4 in `2019b`.
2. Regarding the existing easyconfigs of PETSc without `numpy`, I suggest to add an `osdependency` on `numpy`. In this way we ensure that those easyconfigs will not generate totally different installations in next releases of EB and at the same time there won't be missing dependencies. Linked PRs include this change.
