### ISSUE TITLE
Tensorflow 2.2.0 fails 'pip check'

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyconfigs#10898]
```
== 2020-07-01 00:52:18,033 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd "pip check" exited with exit code 1 and output:
tensorflow 2.2.0 requires numpy, which is not installed.
tensorflow 2.2.0 requires scipy, which is not installed.
```

It seems that something from #9308 is still here.

**Comment by boegel** [comment]
@surak Which easyconfig file are you using here?

**Comment by surak** [comment]
A slightly modified version of Tensorflow-2.2.0-fosscuda. (uploaded as .txt here) 
[TensorFlow-2.2.0-GCCcore-8.3.0-GPU-Python-3.6.8-1.eb.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/4859405/TensorFlow-2.2.0-GCCcore-8.3.0-GPU-Python-3.6.8-1.eb.txt)

**Comment by surak** [comment]
It's strange, because we use a SciPy-Stack bundle, which clearly has numpy:

### SciPy-Stack-2019a.1-gcccoremkl-8.3.0-2019.3.199-Python-3.6.8-1.eb
```
numpyversion = '1.18.5'
...
exts_list = [
...
    ('numpy', numpyversion, dict(common_opts.items() + [
        ('modulename', 'numpy'),
        ('source_urls', ['https://github.com/numpy/numpy/releases/download/v%s/' % numpyversion]),
        ('patches', [
            'numpy-1.14.2-mkl.patch',
            'numpy-1.14.2-xhost.patch',
        ]),
```
