### ISSUE TITLE
gflags-2.2.2-GCCcore-8.3.0.eb. does not build (error)

### ISSUE THREAD

**Issue by patoddh** [easybuilders/easybuild-easyconfigs#10962]
Can't build PyTorch (PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb) beacuse its gflags dependency won't buiild.

 "eb gflags-2.2.2-GCCcore-8.3.0.eb" gives "error: mkdir was not declared in this scope" (numerous times).

Log file attached.

[easybuild-gflags-2.2.2-20200710.142916.bdJUi.log](https://github.com/easybuilders/easybuild-easyconfigs/files/4904769/easybuild-gflags-2.2.2-20200710.142916.bdJUi.log)

This is on CentOS 8.2

**Comment by patoddh** [comment]
This was solved by the same solution as for #11032. In other words, rebuilding GCCcore-8.30 from scratch on CentOS 8.2 (everything, not with --rebuild).

**Comment by boegel** [comment]
Just in case people hit this: more info in #10666
