### ISSUE TITLE
Installing kim-api fails when using opt as the prefix

### ISSUE THREAD

**Issue by alirezaghavaminia** [easybuilders/easybuild-easyconfigs#10991]
Hello, 
I was installing the `kim-api-2.1.3-foss-2019b.eb` during which I encountered a strange error.
The error occurred at the make install process. which is as follows:
I summarised the log
```bash
Install the project...
/opt/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /opt/software/kim-api/2.1.3-foss-2019b/lib64/libkim-api.so.2
-- Set runtime path of "/opt/software/kim-api/2.1.3-foss-2019b/lib64/libkim-api.so.2" to "/opt/software/kim-api/2.1.3-foss-2019b/lib64"
[...]
-- Installing: /opt/software/kim-api/2.1.3-foss-2019b/share/cmake/Modules/FindKIM-API.cmake
CMake Error at completions/cmake_install.cmake:49 (file):
  file cannot create directory:
  /etc/opt/software/kim-api/2.1.3-foss-2019b/bash_completion.d.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:89 (include)
```
apparently it is trying to put something in the `/etc/opt/software/kim-api ...` which obviously has not the permission to do that. The actual installation path is `/opt/software` which is writable by the easybuild.

as suggested by friends, I repeated the installation in another directory with the `eb --installpath-software=/tmp/test kim-api-2.1.3-foss-2019b.eb` command, which worked fine. 

As posted by @boegel 

> looks like it's completed to https://github.com/openkim/kim-api/blob/e76b6cc6632e7f0df6e266db2b0bdcf8d236d007/cmake/Modules/CompletionConfig.cmake#L46

## Tried things:

Adding `-DCMAKE_INSTALL_FULL_SYSCONFDIR=%(installdir)s/etc` to the `configopts` in the easyconfig file didn't work either which resulted in the same error.

**Comment by alirezaghavaminia** [comment]
The Cmake has added some special cases to their make system which can be found [here](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#special-cases) 
This is the source of the problem. 

The following solution is proposed by @Micket 

Changed the `configopts` in the easyconfig file to `configopts = '-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_SYSCONFDIR=%(installdir)s/etc'` 

This solution has worked for me.

**Comment by alirezaghavaminia** [comment]
It seems that these special cases must be considered in the `cmake` easyblock.

**Comment by lexming** [comment]
@alirezaghavaminia thanks for reporting this issue, it has been fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/2105
