### ISSUE TITLE
R-3.6.2-foss-2019b.eb fails to build under CentOS 8.2

### ISSUE THREAD

**Issue by patoddh** [easybuilders/easybuild-easyconfigs#11032]
This built OK under CentOS 8.1

Under CentOS 8.2 the configure step fails with:

configure: error: Building R requires the 'popen' system call

**Comment by casparvl** [comment]
Hm, it seems that indeed that the `popen` syscall is a hard requirement for R: https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#FOOT48

I'm no CentOS 8.2 expert. Would there be any changes regarding the `popen` syscall between 8.1 and 8.2? (I would doubt it, but who knows...

@boegel weren't you playing with CentOS 8.2? Have you compiled R there yet by any chance?

**Comment by patoddh** [comment]
Got the same error  trying to configure R without the R easyconfig, but with GCC-8.3.0 loaded as a module (since R configures with the system gcc).

So I tried rebuilding GCCcore (with --rebuild), and it crashed without the log file, but with a test_report file, which I am uploading here...


[easybuild-GCCcore-8.3.0-20200803.140237.hZwbZ_test_report.md.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/5017705/easybuild-GCCcore-8.3.0-20200803.140237.hZwbZ_test_report.md.txt)

**Comment by casparvl** [comment]
Can you attach the build log so we can see the detailed error message? Also: did you try building with another GCC (either manually or through EB)?

**Comment by patoddh** [comment]
That's the thing. I looked for the log referenced in the EB run, and it did not exist. But that test_report file did.

Instead of "--rebuild on GCCcore (and binutils prior to it), I am trying rebuilding everything from the start. GCCcore/GCC built OK. I then used it to configure R without getting the popen error. I am currently building Python and R.

So unless it is something specific to my system, I would conjecture that when moving from CentOS 8.1 to 8.2 you may need to rebuild GCCcore/GCC.

**Comment by casparvl** [comment]
Thanks for sharing that experience, will be useful if others run into the same issue. Since you have found a workaround yourself (rebuild GCCcore & it's dependencies), and since I don't think we'll get into more detail on this: can we close this ticket?

**Comment by patoddh** [comment]
Yes, it can be closed.

**Comment by boegel** [comment]
@patoddh Just to clarify things a bit: you indeed need to reinstall GCC after updating from CentOS 8.1 to 8.2, because of a change in `glibc`. More information on this issue is available in #10666 .

We have taken some measures in the GCC installation produced by EasyBuild to prevent problems like this going forward (see https://github.com/easybuilders/easybuild-easyblocks/pull/2087), but existing GCC installations that were done on CentOS 8.1 (or earlier) will still be broken on CentOS 8.2. Reinstalling fixes the issue.
