### ISSUE TITLE
imkl link changed

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyconfigs#11037]
Latest one at 

`http://registrationcenter-download.intel.com/akdlm/IRC_NAS/tec/16849/l_mkl_2020.2.254.tgz`

the current easyconfig has `https://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16533/`

note the `IRC_NAS`'s capitalization - not just the forum page number.

**Comment by fenz** [comment]
I wrote it 2 days ago here: https://github.com/easybuilders/easybuild-easyconfigs/issues/11031 but no answer so far. I tested
http/https, both are working but capital letters (as you also mentioned) are changed in all intel softwares (icc, impi, etc. )

**Comment by surak** [comment]
Ok, sorry for the noise. Closing as duplicate of #11031
