### ISSUE TITLE
GDAL won't accept  "--with-xml2=$EBROOTLIBXML2" anymore

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyconfigs#11065]
As one can see here https://github.com/OSGeo/gdal/blob/master/gdal/configure.ac#L4227

the argument is yes/no, not the location.

so, the right argument is 
`configopts += ' --with-xml2=yes' `

**Comment by Micket** [comment]
Since then GDAL has even switched to CMake, and seems to happily be relying on that and pkgconf to find xml2, so nothing left to fix here. Closing.
