### ISSUE TITLE
TensorFlow: Build also for lower compute capabilities

### ISSUE THREAD

**Issue by peci1** [easybuilders/easybuild-easyconfigs#11139]
The current TensorFlow builds use a pretty high compute capability requirement (e.g. TF 1.15 requires compute capability 6.0). That leads to older/slower GPUs being ignored by CUDA.

Could you please set environment variable `TF_CUDA_COMPUTE_CAPABILITIES=3.5,6.0` for the build? I'm not sure how to plug this into the pip build process, though...

**Comment by koekie** [comment]
I assume you are building TensorFlow something like the following:
`eb TensorFlow-2.2.0-fosscuda-2019b-Python-3.7.4.eb --robot `

When you want to set the CUDA compute capabilities for the TF build you could add that to the `eb` command like so:
`eb TensorFlow-2.2.0-fosscuda-2019b-Python-3.7.4.eb --robot --cuda-compute-capabilities 3.5,6.0`

**Comment by peci1** [comment]
Thanks, that seems to solve the issue.
