### ISSUE TITLE
building with intel/2014b fails under HierarchicalMNS if gimkl/1.5.9 is available

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#1117]
Since the Intel compilers included in `intel/2014b` include a dependency on `GCC/4.8.3`, the `$MODULEPATH` is also extended with `Compiler/GCC/4.8.3` when their modules are loaded.

If `gimkl/1.5.9` is already available, the `impi/4.1.3.049` module will be available both under `Compiler/intel/2013.5.192-GCC-4.8.3` and `Compiler/GCC/4.8.3`, which leads to problems when building something with `intel/2014b`:

```
Not all FFTW interface libraries ['fftw3xc_intel', 'fftw3x_cdft_lp64', 'mkl_cdft_core', 'mkl_blacs_intelmpi_lp64', 'mkl_intel_lp64', 'mkl_sequential', 'mkl_core'] are found in ...
```

**Comment by Micket** [comment]
Long since outdated/resolved as we don't include GCC as a builddep for intel toolchains and keep the hierarchy clean.
