### ISSUE TITLE
libepoxy-1.5.4-GCCcore-8.3.0 is missing symbol epoxy_eglGetProcAddress

### ISSUE THREAD

**Issue by mstud** [easybuilders/easybuild-easyconfigs#11197]
I've been trying to install OpenCV which depends on `GTK+/3.24.13-GCCcore-8.3.0`, but building the latter failed with the error:
> ```/usr/bin/gtk-encode-symbolic-svg: symbol lookup error: /lib64/libgdk-3.so.0: undefined symbol: epoxy_eglGetProcAddress```

Turns out that usually, libgdk-3.so.0 links to /lib64/libepoxy.so.0 which has this symbol, however, as soon as module "libepoxy" built with EasyBuild is loaded, this symbol is missing.

> ```nm $EBROOTLIBEPOXY/lib/libepoxy.so.0 | grep epoxy_eglGetProcAddress```

returns nothing. So either libepoxy needs to be fixed to include this symbol, or maybe the build process of GTK+ shouldn't use `gtk-encode-symbolic-svg` from /usr/bin and `libgdk-3.so.0` from /lib64 at all?

**Comment by boegel** [comment]
@mstud Some questions:

* On which OS are you seeing this?
* Which OS package provides `/usr/bin/gtk-encode-symbolic-svg`? Same question for `/lib64/libgdk-3.so.0`.
* Also, which version of `libepoxy` provides `/lib64/libepoxy.so.0` that does include the missing symbol?

**Comment by bosniancoyote** [comment]
Ran into this issue as well with GCCcore/9.3.0.  The libepoxy-1.5.4-GCCcore-9.3.0.eb easyconfig specifies the build opts:
configopts = '-Degl=no --libdir %(installdir)s/lib '
which seems like it would compile libepoxy without any of the egl* functions.

**Comment by cjroberts** [comment]
Hi, I am trying to build the RELION software package and run into this error building GTK+ as a dependency.
`/bin/gtk-encode-symbolic-svg: symbol lookup error: /lib64/libgdk-3.so.0: undefined symbol: epoxy_eglGetProcAddress`
This is occurring on CentOS 7.
`gtk3-devel-3.22.30-5.el7.x86_64` provides `/bin/gtk-encode-symbolic-svg`
`gtk3-3.22.30-5.el7.x86_64` provides `/lib64/libgdk-3.so.0`
`libepoxy-1.5.2-1.el7.x86_64` provides `/lib64/libepoxy.so.0`
Would the solution be to recompile libepoxy without the `-Degl=no` option?
