### ISSUE TITLE
missing xxd requirement for PLUMED

### ISSUE THREAD

**Issue by sjpb** [easybuilders/easybuild-easyconfigs#11209]
On a Centos-7 system this failed with 

```
checking for xxd... no
configure: error: xxd should be installed for PLUMED to compile properly
```

in the logfile.

The terminal output was not very helpful:

```
== FAILED: Installation ended unsuccessfully (build directory: /mnt/nfs/centos/easybuild/build/PLUMED/2.5.1/foss-2019a): build failed (first 300 chars): cmd "env FC=$MPIF90 LIBS="$LIBLAPACK $LIBS"  ./configure --prefix=/mnt/nfs/centos/easybuild/software/PLUMED/2.5.1-foss-2019a  --build=x86_64-pc-linux-gnu  --host=x86_64-pc-linux-gnu  --exec-prefix=/mnt/nfs/centos/easybuild/software/PLUMED/2.5.1-foss-2019a --enable-gsl --enable-modules=all" exited wi (took 22 sec)
== Results of the build can be found in the log file(s) /tmp/eb-mzwwxyip/easybuild-PLUMED-2.5.1-20200903.094415.jjyqr.log
ERROR: Build of /mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-foss-2019a.eb failed (err: 'build failed (first 300 chars): cmd "env FC=$MPIF90 LIBS="$LIBLAPACK $LIBS"  ./configure --prefix=/mnt/nfs/centos/easybuild/software/PLUMED/2.5.1-foss-2019a  --build=x86_64-pc-linux-gnu  --host=x86_64-pc-linux-gnu  --exec-prefix=/mnt/nfs/centos/easybuild/software/PLUMED/2.5.1-foss-2019a --enable-gsl --enable-modules=all" exited wi')
```

There doesn't appear to be an EasyConfig for `xxd` so I had to install via yum:

`sudo yum install -y vim-common`

**Comment by ocaisa** [comment]
There are easyconfigs for `Vim` which provides xxd:
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/v/Vim/Vim-8.1.1209-GCCcore-8.2.0-Python-3.7.2.eb

Adding that as a dependency would solve this, but I wonder if this is a generic requirement for PLUMED?

**Comment by boegel** [comment]
Wait, so we should add `Vim` as a (hopefully build only) dependency for PLUMED?! 🤯

**Comment by akesandgren** [comment]
Ohh, we have vim as part of the singularity container we're building in. No wonder it finds xxd.

But we could potentially make a xxd package, ripping the xxd dir out of vim sources, it's a simple make file in there,
$(CC) $(CFLAGS) $(LDFLAGS) -DUNIX -o xxd xxd.c
is what it does.
