### ISSUE TITLE
TensorFlow 1.13.1 fails to download correct ICU archive

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#11253]
Building TF 1.13.1 fails with
`
ERROR: /tmp/s3248973-EasyBuild/TensorFlow/1.13.1/foss-2019a-Python-3.7.2/TensorFlow/tensorflow-1.13.1/tensorflow/tools/pip_package/BUILD:149:1: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to /tmp/easybuild-tmp/eb-Wo2MDj/tmp2YEuqs-bazel-build/external/icu/release-62-1.tar.gz: Checksum was 86b85fbf1b251d7a658de86ce5a0c8f34151027cc60b01e1b76f167379acf181 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761 and referenced by '//tensorflow/tools/pip_package:licenses'`

Reason is that both URLs provide ICU sources containing git LFS pointers instead of real files. TF 1.14.x uses http://mirror.tensorflow.org/github.com/unicode-org/icu/archive/release-62-1.tar.gz instead as the primary URL which has resolved files.

Checksums:

- LFS pointers: 86b85fbf1b251d7a658de86ce5a0c8f34151027cc60b01e1b76f167379acf181
- Resolved: e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761

Possible solutions from worse to good:

- Add other checksum
- Add new Download location from 1.14.x with real files instead of LFS pointers
- Update EasyBlock to enable system libs for 1.x, at least for ICU and add that to the EC

**Comment by boegel** [comment]
@Flamefire What's the best option here to get this fixed?

I'm inclined to get with the one that's least effort, since this concerns an old TensorFlow version, so option 1?

**Comment by Flamefire** [comment]
Inner me is fighting to get it right vs get it fast. I wouldn't use option 1 as that uses pointer files which might cause issues later. So option 2 at least. However updating the EasyBlock is quite easy. Just need to run a python command on cmdline onto TF sources in that version to collect known dependencies. Might make sense for 2019b ECs as they likely suffer from the same curl issue I've seen recently so when that comes up we'd need that anyway.

**Comment by boegel** [comment]
Looks like this will be fixed with #13326?
