### ISSUE TITLE
PyQt5 needs egg-info/dist-info for PIP compatibility

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#11304]
@branfosj mentioned this was already fixed for VTK, so, adapting that, doing something like
```python
local_egg_info_src = '%(builddir)s/PyQt5-%(version)s/PyQt5-version.egg-info'
local_egg_info_dest = '%(installdir)s/lib/python%(pyshortver)s/site-packages/PyQt5-%(version)s.egg-info'
postinstallcmds = [
    'sed "s/#PyQt5_VERSION#/%%(version)s/" %s > %s' % (local_egg_info_src, local_egg_info_dest),
]
```
and, presumably, we should do this for `SIP` and `PyQtWebEngine` that's also part of the PyQt5 bundle.

Ref: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/v/VTK/vtk-version.egg-info
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/v/VTK/VTK-8.2.0-intel-2020a-Python-3.8.2.eb

**Comment by Flamefire** [comment]
We can just let PyQt5 install it's own dist-info by removing the request to NOT do that: https://github.com/easybuilders/easybuild-easyconfigs/blob/6518373349ba0e2d1e648c3a89665d3bb4834062/easybuild/easyconfigs/p/PyQt5/PyQt5-5.13.2-GCCcore-8.3.0-Python-3.7.4.eb#L47

Any idea why that was used?
Oh and maybe the pip sanity check etc should be enabled too.

**Comment by Flamefire** [comment]
CCing @akesandgren as he introduced that EC

**Comment by Flamefire** [comment]
Correcting: It was @Darkless012 who introduced that option in https://github.com/easybuilders/easybuild-easyconfigs/commit/fa814a3c44c90c2bfd0416d4730156aca657e0b3
