### ISSUE TITLE
missing requirement for OpenImageIO (git)

### ISSUE THREAD

**Issue by MadejaJiri** [easybuilders/easybuild-easyconfigs#11316]
OpenImageIO-2.0.12-gompi-2019b.eb (probably other versions as well) requires git.

**Comment by boegel** [comment]
@MadejaJiri What kind of errors/problems are you running into on a system that doesn't have `git` installed?

That's good to mention in case people go searching for those error messages...

**Comment by MadejaJiri** [comment]
Sorry.


From log file: _/tmp/eb-imuf5w_0/easybuild-OpenImageIO-2.0.12-20200922.202717.WCmLJ.log_

```
CMake Error at /home/george/.local/easybuild/software/CMake/3.15.3-GCCcore-8.3.0/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Git (missing: GIT_EXECUTABLE)
Call Stack (most recent call first):
  /home/george/.local/easybuild/software/CMake/3.15.3-GCCcore-8.3.0/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/george/.local/easybuild/software/CMake/3.15.3-GCCcore-8.3.0/share/cmake-3.15/Modules/FindGit.cmake:96 (find_package_handle_standard_args)
  src/cmake/externalpackages.cmake:663 (find_package)
  CMakeLists.txt:155 (find_or_download_robin_map)
```

Installing git, for example with:
`sudo apt-get install git`
solves it.

**Comment by rarensu** [comment]
This issue isn't quite resolved. The current build dep ( 'git', '2.23.0' )  does not take into account '-nodocs' variant.
