### ISSUE TITLE
Anaconda3 configs do not work on ppc64

### ISSUE THREAD

**Issue by zdemat** [easybuilders/easybuild-easyconfigs#11342]
Hi,

Anaconda3 configs do not work on ppc64le. They would obviously need an alternative source link and checksum.
`Linux-ppc64le` instead of `Linux-x86_64` is needed in the source link and an appropriate checksum.
Maybe somebody knows how to do it?

Thanks, Zdenek

**Comment by boegel** [comment]
@edmondac Something you can help with?

**Comment by branfosj** [comment]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/11362

**Comment by boegel** [comment]
fixed in #11362, thanks @branfosj !
