### ISSUE TITLE
Use OpenBLAS 0.3.11 in 2020b toolchain

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#11420]
0.3.11 will (likely) contain the following 2 PRs: ~~https://github.com/xianyi/OpenBLAS/pull/2876~~ and ~~https://github.com/xianyi/OpenBLAS/pull/2765~~
The latter is a must for correctness on POWER, so I'd add that as a patch to all existing ECs of a reasonable age. The former is a (likely serious) performance issue

Going forward we should use 0.3.11+

**Comment by boegel** [comment]
fixed in #11489 (OpenBLAS 0.3.12 in `foss/2020b`)
