### ISSUE TITLE
QIIME2/2020.8

### ISSUE THREAD

**Issue by hannah-doris** [easybuilders/easybuild-easyconfigs#11447]
Could QIIME2/2020.8 get added to the QIIME2 easybuild-easyconfigs?

https://docs.qiime2.org/2020.8/install/#core-distribution

**Comment by hannah-doris** [comment]
@boegel I am new to using github (besides reading posts to get help and advice on pipelines I am attempting). I was wondering if you could explain what a 4.x milestone means. Does it correspond to an estimated time line for the request? Thanks again and let me know if there are any steps I should take to help this request process.

**Comment by boegel** [comment]
@hannah-doris It doesn't mean much, just that the issue has been triaged as a feature request.

We have more specific milestones for things that we want to tackle for a specific future EasyBuild release.

Unfortunately requests for specific software like this are unlikely to get resolved timely, unless somebody has a use case for QIIME themselves.

Are you up for looking into this update yourself?

**Comment by boegel** [comment]
Easyconfig for QIIME2 2020.08 was added in #11874 (included with EasyBuild v4.3.3 and newer), and easyconfigs for more recent QIIME2 versions have been added too already (see #14001 for QIIME2 2021.08), so closing this.
