### ISSUE TITLE
Move IPython and Jupyterlab to GCCcore starting 2020b

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#11459]
I would like to see IPython (and Jupyterlab) moved down to GCCcore.
IPython needlessly depends on matplotlib right now, forcing it to, though that's not a requirement for it at all for the packages listed.

I have a working Jupyterlab and IPython configs at GCCcore/9.3.0 currently, and will be bumping them to whatever we end up with at 2020b.

**Comment by boegel** [comment]
fixed in #11526
