### ISSUE TITLE
Moving python packages from bundles into Python package

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#11460]
There is also a bunch of python packages that appear in 2 or more bundles by now. Some which i spotted working on IPython were
pytoml
flit-core
parso
wcwidth
defusedxml
pexpect
entrypoints
pyrsistent
webencodings
nest-asyncio
async_generator
html5lib
bleach

Perhaps even include poetry with Python?

I'm sure there are others that are even more commonly used, but perhaps it's something we should take an extra look at when  we create the next Python config.

**Comment by boegel** [comment]
@Micket As discussed, I think it makes a lot of sense to include `poetry` (and everything it requires) into `Python` starting with #11490...

**Comment by boegel** [comment]
@Micket Can we close this now #11490 is merged?

**Comment by Micket** [comment]
yes
