### ISSUE TITLE
GCCcore 10.2 system gives ``ld.gold: fatal error: ./libgcc_s.so.1.tmp: Unknown error 524`` error

### ISSUE THREAD

**Issue by 0luhancheng0** [easybuilders/easybuild-easyconfigs#11544]
I encoutered an error 
```
ld.gold: fatal error: ./libgcc_s.so.1.tmp: Unknown error 524
```
when running eb `GCCcore-10.2.0.eb -r -T -d` with easybuild version 4.3.0

I have also uploaded detailed log message here
[easybuild-GCCcore-10.2.0-20201020.211153.WILjm.log](https://github.com/easybuilders/easybuild-easyconfigs/files/5408036/easybuild-GCCcore-10.2.0-20201020.211153.WILjm.log)

Thank you

**Comment by boegel** [comment]
@0luhancheng0 On what type of filesystem are you running here, in particular what type of filesystem is `/fs03/nq46/luhanc`?

It's highly recommended to use a local filesystem (like `/tmp`) or `/dev/shm` as location of build directories (see https://easybuild.readthedocs.io/en/latest/Configuration.html#buildpath)

**Comment by 0luhancheng0** [comment]
Hi @boegel , Thank you for helping!
I successfully built it by specifying `--buildpath /tmp`. 
For your information, previously the build directory was on the lustre file system. 
Much appreciate!
