### ISSUE TITLE
Python-3.8.2-GCCcore-9.3.0.eb build fails on CentOS 6

### ISSUE THREAD

**Issue by golivag** [easybuilders/easybuild-easyconfigs#11551]
Hi,
build of Python 3.8.2 on CentOS 6 fails with the following error:

== 2020-10-21 12:36:50,913 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/4.3.0/lib/python2.7/site-packages/easybuild/base/exceptions.py:124 in __init__): cmd "python -c 'from cryptography.hazmat.bindings.openssl import binding'" exited with exit code 1 and output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/software/easybuild/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 203, in <module>
    Binding.init_static_locks()
  File "/opt/software/easybuild/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 143, in init_static_locks
    __import__("_ssl")
ModuleNotFoundError: No module named '_ssl'
 (at easybuild/software/EasyBuild/4.3.0/lib/python2.7/site-packages/easybuild/tools/run.py:533 in parse_cmd_output)
== 2020-10-21 12:36:50,914 filetools.py:1610 INFO Removing lock /opt/software/easybuild/software/.locks/_opt_software_easybuild_software_Python_3.8.2-GCCcore-9.3.0.lock...
== 2020-10-21 12:36:50,915 filetools.py:330 INFO Path /opt/software/easybuild/software/.locks/_opt_software_easybuild_software_Python_3.8.2-GCCcore-9.3.0.lock successfully removed.
== 2020-10-21 12:36:50,915 filetools.py:1614 INFO Lock removed: /opt/software/easybuild/software/.locks/_opt_software_easybuild_software_Python_3.8.2-GCCcore-9.3.0.lock
== 2020-10-21 12:36:50,915 easyblock.py:3311 WARNING build failed (first 300 chars): cmd "python -c 'from cryptography.hazmat.bindings.openssl import binding'" exited with exit code 1 and output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/software/easybuild/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/cryptography/hazmat
== 2020-10-21 12:36:50,916 easyblock.py:295 INFO Closing log for application name Python version 3.8.2

any clue?
Best regards
-- 
golivag

**Comment by dithwick** [comment]
You may have already fixed this but Python 3.8.2 needs a newer version of OpenSSL than is available with CentOS 6. If you look in the dependency list of the Python-3.8.2-GCCcore-9.3.0.eb (https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb) there is a 

`    # ('OpenSSL', '1.1.1e'),`

Make a local copy of the easyconfig, uncomment that dependency and see if it then builds.

**Comment by golivag** [comment]
Thank you!
