### ISSUE TITLE
ERROR: Failed to process easyconfig

### ISSUE THREAD

**Issue by farzad685** [easybuilders/easybuild-easyconfigs#11572]
Hi. I've installed EasyBuild 4.3.0 on ubuntu 20.04 LTS then when I run this command `eb ioapi-3.2-2020111-gompi-2019b-nocpl.eb`, 
 I received error 
== temporary log file in case of crash /tmp/eb-gukf53lx/easybuild-8ktg0d8w.log
== found valid index for /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs, so using it...
ERROR: Failed to process easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/i/ioapi/ioapi-3.2-2020111-gompi-2019b-nocpl.eb: Failed to process easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/g/gompi/gompi-2019b.eb: Failed to process easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-GCC-8.3.0.eb: Failed to process easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/h/hwloc/hwloc-1.11.12-GCCcore-8.3.0.eb: Failed to process easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/n/numactl/numactl-2.0.12-GCCcore-8.3.0.eb: Failed to process easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/a/Autotools/Autotools-20180311-GCCcore-8.3.0.eb: Failed to process easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-8.3.0.eb: Failed to process easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb: One or more OS dependencies were not found: [('openssl-devel', 'libssl-dev', 'libopenssl-devel')]
Best regards.

**Comment by akesandgren** [comment]
As the error clearly says at the end, "One or more OS dependencies were not found: [('openssl-devel', 'libssl-dev', 'libopenssl-devel')]"

I.e., you need to install the development package for ssl on your system. The above 3 are the names we know of for it for Debian and RedHat based systems, pick the one appropriate for you.

**Comment by farzad685** [comment]
@akesandgren. Thanks for your answering .
I tried to install them by `sudo apt install ` but ubuntu has not them in its repositories.

**Comment by akesandgren** [comment]
libssl-dev is the one for Ubuntu.

**Comment by farzad685** [comment]
@akesandgren. you're right.
Thanks a lot.

**Comment by farzad685** [comment]
@akesandgren. I run this command `eb xorg-macros-1.19.2-GCCcore-8.3.0.eb
` but I got to receive an error : 
== temporary log file in case of crash /tmp/eb-wkly0ch5/easybuild-apv43jjb.log
== found valid index for /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs, so using it...
== processing EasyBuild easyconfig /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-8.3.0.eb
== building and installing devel/xorg-macros/1.19.2-GCCcore-8.3.0...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /home/farzad/.local/easybuild/build/xorgmacros/1.19.2/GCCcore-8.3.0): build failed (first 300 chars): Couldn't find file macros-util-macros-1.19.2.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/x/xorg-macros/x/xorg-macros/macros-util-macros-1.19.2.tar.gz, /home/farzad/.local/easybuild/ (took 30 sec)
== Results of the build can be found in the log file(s) /tmp/eb-wkly0ch5/easybuild-xorg-macros-1.19.2-20201026.163107.LXMdK.log
ERROR: Build of /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-8.3.0.eb failed (err: "build failed (first 300 chars): Couldn't find file macros-util-macros-1.19.2.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/x/xorg-macros/x/xorg-macros/macros-util-macros-1.19.2.tar.gz, /home/farzad/.local/easybuild/")
could you help me ?
Best regards.

**Comment by akesandgren** [comment]
By default eb only builds the easyconfigs you give it on the command line, not the dependencies.

If you look at the output of
eb xorg-macros-1.19.2-GCCcore-8.3.0.eb --dry-run
you will see that there are a bunch of packages it need to build.
Use --robot (or -r for short) to ask it to build everything.

And if you have a cluster at hand I strongly recomend looking at the --job options.
Check the docco for details, https://easybuild.readthedocs.io/

**Comment by farzad685** [comment]
@akesandgren. my main command is `eb ioapi-3.2-2020111-gompi-2019b-nocpl.eb --robot ` and has the same error in last comment.I just wanted to show the error briefly.

**Comment by boegel** [comment]
@farzad685 You should check the log file why the download of that source file failed, it could be for all sorts of reasons...

You can try to work around it by downloading manually and relocating the file to the EasyBuild source path (see output of `eb --show-config`) for the right location; see also https://easybuild.readthedocs.io/en/latest/Configuration.html#source-path-sourcepath

**Comment by farzad685** [comment]
@boegel.I am surprised because `xorg-macros-1.19.2-GCCcore-8.3.0.eb` exists but EasyBuild could not find it. I tried your guide but I received the same error. I located the tar pkg of xorg-macros in the desired path but it did not work.
I run this `eb xorg-macros-1.19.2-GCCcore-8.3.0.eb --dry-run`

== temporary log file in case of crash /tmp/eb-j854gnx7/easybuild-ge54jo2r.log
== found valid index for /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs, so using it...
Dry run: printing build status of easyconfigs and dependencies
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/m/M4/M4-1.4.18.eb (module: devel/M4/1.4.18)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/b/Bison/Bison-3.3.2.eb (module: lang/Bison/3.3.2)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb (module: lib/zlib/1.2.11)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/h/help2man/help2man-1.47.4.eb (module: tools/help2man/1.47.4)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/f/flex/flex-2.6.4.eb (module: lang/flex/2.6.4)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/b/binutils/binutils-2.32.eb (module: tools/binutils/2.32)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/g/GCCcore/GCCcore-8.3.0.eb (module: compiler/GCCcore/8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/h/help2man/help2man-1.47.8-GCCcore-8.3.0.eb (module: tools/help2man/1.47.8-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.3.0.eb (module: devel/M4/1.4.18-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-8.3.0.eb (module: lib/zlib/1.2.11-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/b/Bison/Bison-3.3.2-GCCcore-8.3.0.eb (module: lang/Bison/3.3.2-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-8.3.0.eb (module: lang/flex/2.6.4-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-8.3.0.eb (module: tools/binutils/2.32-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-8.3.0.eb (module: lib/libtool/2.4.6-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/e/expat/expat-2.2.7-GCCcore-8.3.0.eb (module: tools/expat/2.2.7-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-8.3.0.eb (module: devel/ncurses/6.1-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/l/libreadline/libreadline-8.0-GCCcore-8.3.0.eb (module: lib/libreadline/8.0-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb (module: lang/Perl/5.30.0-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-8.3.0.eb (module: devel/Autoconf/2.69-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-8.3.0.eb (module: devel/Automake/1.16.1-GCCcore-8.3.0)
 * [x] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/a/Autotools/Autotools-20180311-GCCcore-8.3.0.eb (module: devel/Autotools/20180311-GCCcore-8.3.0)
 * [ ] /home/farzad/.local/easybuild/software/EasyBuild/4.3.0/easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-8.3.0.eb (module: devel/xorg-macros/1.19.2-GCCcore-8.3.0)
== Temporary log file(s) /tmp/eb-j854gnx7/easybuild-ge54jo2r.log* have been removed.
== Temporary directory /tmp/eb-j854gnx7 has been removed.

**Comment by farzad685** [comment]
@boegel. I think I find out the problem what it is.
I located util-macros-1.19.2.tar.gz in the source path but EasyBuild were finding macros-util-macros-1.19.2.tar.gz, as you see EasyBuild is finding the wrong name for the pkg.
But I do not know what should I do.

**Comment by farzad685** [comment]
@boegel.Am I right?

**Comment by farzad685** [comment]
@boegel. I found out what problem it is.
It was because of being a filter source-URL for me. I just install a VPN and the problem solved.
