### ISSUE TITLE
protobuf-python pip check error

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#11580]
I see this error building `protobuf-python-3.10.0-foss2019b-Python-3.7.4`:

```
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/protobufpython/3.10.0/foss-2019b-Python-3.7.4): build failed (first 300 chars): cmd "pip check" exited with exit code 1 and output:
pylatex 1.3.3 requires ordered-set, which is not installed.
 (took 5 sec)
```

**Comment by verdurin** [comment]
This was caused by an exciting local error. Closing.

**Comment by boegel** [comment]
@verdurin Care to provide some more info on that local error, to avoid a [wisdom of the ancients](https://xkcd.com/979) situation when somebody finds this issue when searching for similar problems?

**Comment by verdurin** [comment]
@boegel it was caused by a local `easyconfig` that included `pylatex`, so I thought it was very unlikely anyone else would see this. That said, I do plan to submit that at some point.

The fix was to remove the results of building that local module.
