### ISSUE TITLE
building modules with easybuild fails with conflict

### ISSUE THREAD

**Issue by jgphpc** [easybuilders/easybuild-easyconfigs#11591]
I am trying to write a recipe that can install modules but it will fail as eb depends on modules...

```
Sanity check failed: loading fake module failed: "modules/4.6.0(24):ERROR:150: Module 'modules/4.6.0' conflicts with the currently loaded module(s) 'modules/3.2.11.4'"
```

Is there a way to build modules with eb ?
[modules-4.6.0.eb.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/5459623/modules-4.6.0.eb.txt)

**Comment by boegel** [comment]
@jgphpc Hmm, that's a tough one...

EasyBuild is happy as long as it finds the actual `modulecmd` binary or `modulecmd.tcl` script in `$PATH`, so you could make sure the location to that is in `$PATH` without having the `modules` module loaded?

**Comment by jgphpc** [comment]
yes, one shall not be more royalist than the king, I'll close it.
thanks!
