### ISSUE TITLE
LLVM-3.8.1-foss-2016b

### ISSUE THREAD

**Issue by Furciferi** [easybuilders/easybuild-easyconfigs#11644]
I had to change CMake version to 3.5.2 in order to configure without build error.
 This follows the changes made to the intel-2016b easyconfig for LLVM.

I am not familiar enough with easybuild git integration to add a pull request for the change.

**Comment by boegel** [comment]
Since this concerns an ancient LLVM easyconfig using a toolchain that is not deprecated, I'll close this issue.

@Furciferi My apologies for never picking up on this...
