### ISSUE TITLE
TensorFlow 2.3.1-fosscuda-2019b-Python-3.7.4

### ISSUE THREAD

**Issue by ysagon** [easybuilders/easybuild-easyconfigs#11796]
Hello,
I've tried to build this version of TensorFlow and it failed during the build of the latest extension (TensorFlow itself).

eb version: ```This is EasyBuild 4.3.1 (framework: 4.3.1, easyblocks: 4.3.1)```

eb file: ```TensorFlow-2.3.1-fosscuda-2019b-Python-3.7.4.eb```

Error msg: ```tensorflow/core/platform/numbers.cc:28:10: fatal error: double-conversion/double-conversion.h: No such file or directory```

Thanks

**Comment by reedts** [comment]
I'm encountering the same error with both `TensorFlow-2.3.1-fosscuda-2019b-Python-3.7.4.eb` and also `TensorFlow-2.4.1-fosscuda-2019b-Python-3.7.4.eb`

**Comment by boegel** [comment]
A re-installing of `double-conversion` is required to fix this problem, see #9659
