### ISSUE TITLE
Use Github mirror to fix g2log after disappearance of Bitbucket

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#11865]
https://github.com/hb3p8/g2log may be a lifeline for `g2log`, which is required by `Sailfish`.

**Comment by boegel** [comment]
@verdurin Or we could check whether we're allowed to redistribute the `g2log` sources, and upload them to https://sources.easybuild.io, which is used as fallback source URL by EasyBuild v4.3.3 & later...

**Comment by boegel** [comment]
Looks like redistributing the sources is not a problem, based on [`g3log` license](https://github.com/KjellKod/g3log/blob/master/LICENSE), so I've made the original g2log 1.0 source tarball available via https://sources.easybuild.io/g/g2log/
