### ISSUE TITLE
$GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS should be set when installing grpcio

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#11872]
I ran into problems when installing TensorFlow, the installation failed during the installation of the `grpcio` extension because the build was being done too parallel (system had 256 cores, but a hard limit of 4096 open files).

The level of parallelism used by `grpcio` can be controlled via the `GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS` environment variable. If it's not set, the number of available cores is auto-detected via `multiprocessing.cpu_count()` (which is not the correct way anyway), and all "available" cores are used; see https://github.com/grpc/grpc/blob/8f5dcdf5543f2184b4ce1f75f2169f974d3fdd4d/src/python/grpcio/_parallel_compile_patch.py#L24 .

**Comment by akesandgren** [comment]
Fixed by #14728, #14729 and #14730
