### ISSUE TITLE
Use wrappers for OpenSSL starting 2021a

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#11895]
As discussed on biweekly meetings, i figured it would be good to make a ticket for it:

Instead of relying on OS, which is getting more and more painful on older OS'es, we should just build OpenSSL (and friends) in EB and keep updating them. This of course requires wrappers, like we do for Java. So, I would expect there to something like a `OpenSSL-1.1.1x-GCCcore-11.a.b.eb` + `OpenSSL-1.1-GCCcore-11.a.b.eb`-wrapper starting with with the 2021 toolchains.

For those wishing to keep osdependency they can filter OpenSSL. We should also make sure to enhance the PR-testsuite so that we don't miss switching over as we bump new easyconfigs to 2021a.

(We might also want to do so for stuff like `gnutls.`, but I suspect osdep works well there still.)

**Comment by akesandgren** [comment]
I'd vote for doing it the other way around, i.e. make sure EB builds of openssl exist, but let people filter out the osdeps in easyconfigs using hooks, or manually changing the .eb, when they want to go that route.

Using the OS openssl by default is way better then having to remember to filter the EB build out.
It's much safer to use the OS build by default, and only fall back to EB version when absolutely needed.

**Comment by boegel** [comment]
Some relevant info on this: it is possible to install OpenSSL 1.1.x in CentOS 7, but it's in a non-default location, so tricky to ensure it's actually picked up consistently. See also https://stackoverflow.com/questions/63508872/upgrading-centos-7-to-openssl-1-1-1-by-yum-install-openssl11

**Comment by Micket** [comment]
A note on ModuleRC modules: Creating a wrapper like Java will not work, because of rpath. It might work with a different type of wrapper though (something with a lib64 and include symlink maybe?), but, it has the downside of affecting running stuff.

**Comment by Micket** [comment]
Another comment on openssl11; we might make EB pick this on when building, but what about runtime? We'd also have to make sure at least that library is rpath'ed, no other practical way of handling it i think. 

We halso have to be consistent, everything we build must use the same libssl.so, else I can only imagine symbols collisions and a really really bad time ahead.

**Comment by Micket** [comment]
Another fun issue:
OpenSSL has a builddep on Perl
Perl's Net::SSLeay has a dependency on OpenSSL.

I don't know much about Perl insfrastructure, do we even know how important this Net::SSLeay module is? I think we just have to break that out, no other way around it.

**Comment by lexming** [comment]
Since this is blocking Python in 2021a, we should find a solution. I propose to make wrappers for OpenSSL in the **system** toolchain. This deviates the least from the current situation where we already link to libs in the system.
@Micket I don't see the problem with rpath, any new installations linking with rpath should pick the lib through the wrappers. There might be a problem with existing installations, as those will continue to link to whatever they do now, but that is inherent to rpath.

**Comment by Micket** [comment]
@lexming I was working under the assumption that we wouldn't ever let something be stuck with an old ssl. 
To be honest, I'm actually not to concerned about old ssl versions, since so many of my users are already providing binary installs via containers and such, so they are already using old versions or everything and there isn't much one can do about that.


But, I really like your idea of a system level OpenSSL system level wrapper, that could really work. Just a small custom easyblock that looks for a system level libssl 1.1. That.. actually just solves all problems doesn't it?
We could just have that always enabled instead of an os-dependency and just have that module deal with it?

**Comment by lexming** [comment]
> we wouldn't ever let something be stuck with an old ssl

That is an impossible goal in my opinion. I remember seeing software statically link openssl, so we are already dead on that front :smile: rpathing is not as impossible to undo as static links, but still a lot of effort. The only solution for such cases is to ensure that openssl is always dynamically linked and remove any rpaths/static links from software doing the wrong thing.

Regarding wrapping around the system openssl, I replied in my PR: https://github.com/easybuilders/easybuild-easyconfigs/pull/12858#issuecomment-840874844

**Comment by lexming** [comment]
Following the discussion in https://github.com/easybuilders/easybuild-easyconfigs/pull/12858, I got something that works along the lines suggested by @Micket . I made an easyblock to automatically wrap OpenSSL either if the installation is located in the host system or in EasyBuild.

The easyblock can be found in https://github.com/lexming/easybuild-easyblocks/blob/1c877396af4822b41d29f64be2457b7d5e659508/easybuild/easyblocks/o/openssl_wrapper.py

For the moment, I quickly made it work with the same wrapper easyconfigs of #12858 ([OpenSSL-1.0.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/1cad87c0c6200ac65c79d57a5d052ba5589755c8/easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.eb), [OpenSSL-1.1.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/1cad87c0c6200ac65c79d57a5d052ba5589755c8/easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.eb)). But this could be changed. For instance, the dependency on the _real_ OpenSSL could be changed to an extra option.

This easyblock locates the openssl library in the host system by loading the respective `libssl.so` in Python and it retrieves the include paths from `gcc`, detecting the headers for the required version of OpenSSL  (v1.0.x or v1.1.x). So it is resilient to installations in exotic paths and does not need to crawl through any environment variables.

* If the host system has the libs and headers of the required version of OpenSSL (v1.0.x or v1.1.x), the installation directory is populated with symlinks to the system files.
* If the host system does **not** have  the required version of OpenSSL, the installation directory of the wrapper is populated with symlinks to the files of OpenSSL from EB (_ie_ the installation directory of the OpenSSL dependency defined in the wrapper easyconfig)
* in both cases the resulting OpenSSL module (the wrapper) does not load any other OpenSSL module

Why symlinking?
* it's a safe way to wrap to the system openssl, as prepending any system paths can break the environment of any other modules loaded by the user.
* it provides a transparent way to update OpenSSL without breaking dynamic links and _probably_ without breaking rpaths either. Any packages build with the wrappers in place should use the paths to the installation directory of the wrapper, not the actual libraries in the system or EB.

What do you think? Should I open a PR for this easyblock? 
@boegel  do you agree with this approach?

**Comment by Micket** [comment]
I like this. Another bonus is that we could check so that we don't miss linking to this version (of the module is loaded). Currently, I'm sure we are missing places that unexpectedly link to libssl (which would create issues on CentOS7 since mixing -> crash)

**Comment by boegel** [comment]
@lexming +1, I like this approach too. It should indeed work when using RPATH too (as long as a symlink to *files*, not directories).

Please open the PR for the easyblock, there's a couple of minor things I'd like to see changed in what you have now (after taking a 30sec glance at it).
