### ISSUE TITLE
OpenBLAS-0.3.12-GCC-10.2.0.eb fails on build

### ISSUE THREAD

**Issue by bphusted** [easybuilders/easybuild-easyconfigs#11941]
I tried to build foss-2020b, - it all went well (all other dependencies could build), except the building of OpenBLAS-0.3.12-GCC-10.2.0.eb.
Previous build of foss-2020a went well.

I get the following error message
```
== configuring...
== building...
== FAILED: Installation ended unsuccessfully (build directory: /sw/easybuild/build/OpenBLAS/0.3.12/GCC-10.2.0): build failed (first 300 chars): cmd " make -j 6 libs netlib shared  BINARY='64'  CC='gcc'  FC='gfortran'  MAKE_NB_JOBS='-1'  USE_OPENMP='1'  USE_THREAD='1'  CFLAGS='-O2 -ftree-vectorize -march=x86-64 -mtune=generic -fno-math-errno' " exited with exit code 2 and output:
FUNCOBJS = {[    saxpy.o sswap.o scopy.o sscal.o sdot.o sdsdot (took 1 min 11 sec)
== Results of the build can be found in the log file(s) /tmp/eb-4n1Abo/easybuild-OpenBLAS-0.3.12-20201231.161103.LhzPP.log
ERROR: Build of /sw/easybuild/software/EasyBuild/4.3.2/easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.12-GCC-10.2.0.eb failed (err: 'build failed (first 300 chars): cmd " make -j 6 libs netlib shared  BINARY=\'64\'  CC=\'gcc\'  FC=\'gfortran\'  MAKE_NB_JOBS=\'-1\'  USE_OPENMP=\'1\'  USE_THREAD=\'1\'  CFLAGS=\'-O2 -ftree-vectorize -march=x86-64 -mtune=generic -fno-math-errno\' " exited with exit code 2 and output:\nFUNCOBJS = {[    saxpy.o sswap.o scopy.o sscal.o sdot.o sdsdot')
```

**Comment by boegel** [comment]
@bphusted You'll need to open the log file and try to determine the build problem. The guidelines at https://easybuilders.github.io/easybuild-tutorial/troubleshooting/#navigating-log-files are useful if you're new to this.

**Comment by bphusted** [comment]
@boegel Thanks for tips. It seems that the problem it linked to the presence of AVX. It is a heterogenous cluster, so all software have been compiled with generic (eb --show-config shows:  optarch  (E) = GENERIC), but for some reason this was not picked up when compiling OpenBLAS. So I did an export of the target:  export  TARGET=GENERIC  and than it worked.

**Comment by boegel** [comment]
@bphusted That problem should get fixed with the changes to the OpenBLAS easyblock proposed in #1946.

Glad to hear you managed to figure it out!
