### ISSUE TITLE
libexpat sources are no longer on sourceforge - moved to github

### ISSUE THREAD

**Issue by jedokaplan** [easybuilders/easybuild-easyconfigs#11954]
sources for libexpat are no longer on sourceforge, changing `expat-2.2.9-GCCcore-10.2.0.eb` to have the following allowed the code to be located correctly, although I don't know if this is right way of forming the source url

```
source_urls = ['https://github.com/libexpat/libexpat/releases/download/R_2_2_9/']
sources = ['expat-%(version)s.tar.gz']
checksums = ['4456e0aa72ecc7e1d4b3368cd545a5eec7f9de5133a8dc37fdb1efa6174c4947']

```

**Comment by boegel** [comment]
Fixed with #11960, thanks for reporting @jedokaplan!
