### ISSUE TITLE
download of sources for UDUNITS v2.2.26 no longer works

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#11951]
https://www.unidata.ucar.edu/downloads/udunits/udunits-2.2.26.tar.gz yields a `403 Forbidden`...

**Comment by boegel** [comment]
I've contacted the support team to see if they're aware of this.

**Comment by boegel** [comment]
I got a reply from support:

```
It's an unintended consequence of converting the UDUNITS CI/CD pipeline to use our Nexus repository server.
Hopefully, it'll be fixed soon.

(Ticket ID: SHN-992901)
```

**Comment by GrahamDB** [comment]
Not sure if this helps any, but by browsing the site I found v2.2.28 (not v2.2.26) at:
https://artifacts.unidata.ucar.edu/repository/downloads-udunits/udunits-2.2.28.tar.gz

checksum:
590baec83161a3fd62c00efa66f6113cec8a7c461e3f61a5182167e0cc5d579e

**Comment by boegel** [comment]
We fixed the issue by relaying on a mirror, see #12020

Apparently the support team has no interest in keeping old source tarballs around:

```
Version 2.2.26 is no longer available for download.
The third component is the bug-fix version number.
Version 2.2.28 has been released and I don't want people downloading a version with known bugs.
```

**Comment by boegel** [comment]
The alternate download location we switched to in #12020 is now also broken... 🤐  (hat tip @SethosII)

**Comment by boegel** [comment]
UDUNITS sources are available at http://sources.easybuild.io/u/UDUNITS/
