### ISSUE TITLE
"multiple definition" error in binutils-2.35-GCCcore-10.2.0.eb

### ISSUE THREAD

**Issue by krometis** [easybuilders/easybuild-easyconfigs#11988]
I was trying to build `binutils-2.35-GCCcore-10.2.0.eb` and it was failing with
```
3524 /apps/easybuild/software/infer-skylake/binutils/2.35/bin/ld: ../libiberty/libiberty.a(concat.o): in function `concat_length':
3525 concat.c:(.text+0x0): multiple definition of `concat_length'; /apps/easybuild/software/infer-skylake/binutils/2.35/lib64/libiberty.a(concat.o):/dev/shm/jkrometi/build/binutils/2.35/system-system/binutils-2.35/libiberty/./concat.c:91: first defined here 
```
After debugging it with Kenneth Hoste (boegel), it appears that the issue was related to the default to `-fno-common` in gcc 10 (https://gcc.gnu.org/gcc-10/porting_to.html) and to our use of gcc/9.2 as our default gcc (rather than the CentOS default). We were able to get it to build successfully by adding the following to `binutils-2.35-GCCcore-10.2.0`:
```
# add -fcommon to $CFLAGS to avoid that build fails with "multiple definition" linking errors
prebuildopts = 'export CFLAGS="$CFLAGS -fcommon" && '
```

**Comment by boegel** [comment]
I'm still a bit puzzled by this, but since adding `-fcommon` fixes the problem, and that should be pretty harmless, it seems like a viable workaround.

Hopefully this problem will disappear in newer `binutils` versions without having to use `-fcommon`.

@krometis Thanks for reporting the issue and helping out with pinpointing it!

**Comment by Flamefire** [comment]
Potential alternative: https://src.fedoraproject.org/rpms/binutils/blob/f27/f/binutils-2.28-ignore-gold-duplicates.patch (found by googling related issues but can't check as I can't reproduce it

**Comment by krometis** [comment]
It looks like this issue is resolved by https://github.com/easybuilders/easybuild-easyblocks/pull/2323. That is, by rebuilding `binutils-2.35.eb` with PR 2323 and then rebuilding `GCCcore-10.2.0.eb`, we can then build `binutils-2.35-GCCcore-10.2.0.eb` without adding `-fcommon` to `CFLAGS` as described here.

**Comment by boegel** [comment]
Thanks a lot for following up @krometis!
