### ISSUE TITLE
"signed integer is greater than maximum" error when downloading CUDA installation file

### ISSUE THREAD

**Issue by elc42** [easybuilders/easybuild-easyconfigs#12021]
Hello,
When I try to install gcccuda-2020b (ubuntu 20.4) I get the following error:  "signed integer is greater than maximum".
Is it related to the size of file cuda_11.1.1_455.32.00_linux.run  ?

Regards

```
$ eb gcccuda-2020b.eb --robot
== temporary log file in case of crash /tmp/eb-mk0ug27z/easybuild-0_x03d2s.log

WARNING: Deprecated functionality, will no longer work in v5.0: Support for Lmod version < 7.0.0 is deprecated, found version 6.6; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== found valid index for /work/EB/software/EasyBuild/4.3.2/easybuild/easyconfigs, so using it...
== resolving dependencies ...
== found valid index for /work/EB/software/EasyBuild/4.3.2/easybuild/easyconfigs, so using it...
== processing EasyBuild easyconfig /work/EB/software/EasyBuild/4.3.2/easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.1.1.eb
== building and installing CUDAcore/11.1.1...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /work/EB/build/CUDAcore/11.1.1/system-system): build failed (first 300 chars): Unexpected error occurred when trying to download https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda_11.1.1_455.32.00_linux.run to /work/EB/sources/c/CUDAcore/cuda_11.1.1_455.32.00_linux.run: signed integer is greater than maximum (took 0 sec)
== Results of the build can be found in the log file(s) /tmp/eb-mk0ug27z/easybuild-CUDAcore-11.1.1-20210118.211721.bMmit.log
ERROR: Build of /work/EB/software/EasyBuild/4.3.2/easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.1.1.eb failed (err: 'build failed (first 300 chars): Unexpected error occurred when trying to download https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda_11.1.1_455.32.00_linux.run to /work/EB/sources/c/CUDAcore/cuda_11.1.1_455.32.00_linux.run: signed integer is greater than maximum')
```

**Comment by Mormacill** [comment]
@elc42:
I tried to enclose your problem.
A test with your setup (Ubuntu 20.04) also gives me this error.
Trying it with Ubuntu 18.04 and CentOS 7 results in a successful build.

It seems to me that Ubuntu 20.04 delivers a too new Python version for easybuild, it comes with Python 3.8.* while CentOS 7 and Ubuntu 18.04 are equipped with Python 3.6.*.

**Comment by boegel** [comment]
@Mormacill Thanks for the extra info, that's really useful!

This same issue is also discussed at https://github.com/easybuilders/easybuild-framework/issues/3455, but we haven't worked out a proper solution for it yet...

cc @zao

**Comment by boegel** [comment]
You should be able to work around the problem by manually downloading the installation file for CUDA.

The actual installation is fine, it's the downloading part that goes wrong...

**Comment by guignont** [comment]
I did a test with python 3.6 (deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main) and it work fine like for @Mormacill .
Using deadsnakes package repository makes installing python3.6 possible without downgrade ubuntu python install.
A+

**Comment by guimou** [comment]
Extra info: same behaviour on Fedora 32 with Python 3.8.6.
Oddly enough I did not have this problem on F33 with Python 3.9.
I worked around by downloading the file manually.
