### ISSUE TITLE
GDRcopy 2.1 not downloading files - 404 error

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#12035]
Hi, 

When trying to build fosscuda/2020a or fosscuda/2020b, the source for GDRcopy 2.1 will not download from github.  I get

```
WARNING URL https://github.com/NVIDIA/GDRCopy/archive/2.1.tar.gz was not found (HTTP response code 404), not trying again
```

So far I have not located an alternative source for the tar-ball.

J.

**Comment by Micket** [comment]
I don't understand why you have that url.
The sources are named `v2.1.tar.gz` in the corresponding easyconfigs.

**Comment by Micket** [comment]
Already fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/11887
