### ISSUE TITLE
makeinfo/6.7-GCCcore-9.3.0 needs perl libraries

### ISSUE THREAD

**Issue by justbennet** [easybuilders/easybuild-easyconfigs#12067]
I got an error when installing `makeinfo-6.7-GCCcore-9.3.0.eb` as a dependency for `BWA-0.7.17-GCC-9.3.0.eb` because the CentOS system `perl-Data-Dumper` wasn't installed.  The check was for that and `perl-Encode`.

From the installation error log,
```
checking Perl version and modules... no
configure: error: perl >= 5.7.3 with Encode and Data::Dumper required by Texinfo.
 (at easybuild/software/EasyBuild/4.3.2/lib/python3.6/site-packages/easybuild/tools/run.py:533 in parse_cmd_output)
```
I ran `yum install -y perl-Data-Dumper` and reran the `eb` installation of `BWA-0.7.17-GCC-9.3.0.eb` and it succeeded.

Should `makeinfo-6.7-GCCcore-9.3.0.eb` have `Perl-5.30.2-GCCcore-9.3.0.eb` as a dependency or build-dependency, as the `Perl-5.30.2-GCCcore-9.3.0.eb` installs both `Encode` and `Data::Dumper` and would keep all the Perl within the GCCcore-9.3.0 family?

**Comment by boegel** [comment]
Yes, adding `Perl` as a build dependency for `makeinfo` should help in dancing around this problem...

Are you up for opening a pull request for this?

**Comment by justbennet** [comment]
I can give it a try.  I think it really depends on two sub-libraries.  The proper way to do that would be to list those as the dependencies, and they will force installation of the base Perl, correct?

**Comment by justbennet** [comment]
That should be a dependency, yes, not just a build dependency, I think.  If it gets removed from the OS after EB installs `makeinfo`, then
```
[bennet@studentpc3 ~]$ makeinfo --help
Can't locate Data/Dumper.pm in @INC (@INC contains: CODE(0x26ddb38) /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/lib/texinfo /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/share/texinfo/lib/Text-Unidecode/lib /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/share/texinfo/lib/Unicode-EastAsianWidth/lib /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/share/texinfo/lib/libintl-perl/lib /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/share/texinfo /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/share/texinfo /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/share/texinfo/Texinfo/Common.pm line 2455.
BEGIN failed--compilation aborted at /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/share/texinfo/Texinfo/Common.pm line 2455.
Compilation failed in require at /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/bin/makeinfo line 98.
BEGIN failed--compilation aborted at /sw/arcts/EasyBuilt/software/makeinfo/6.7-GCCcore-9.3.0/bin/makeinfo line 98.
```

Or should this be something that people _should_ install via the OS?  Some comments in Slack lead me to believe that people want to minimize the modules required for each EC.

**Comment by justbennet** [comment]
Tried to this, but adding Perl as a dependency creates a circular reference.  From Slack, Sat, Feb 6.

> ake_s  2:27:02 PM (Eastern time)
> Yes, Perl depends on groff which depends on makeinfo. Can be worked around, but it's not worth the trouble

**Comment by akesandgren** [comment]
I'm currently trying to fix this circular dependency.
1 - create Perl-minimal with no extensions, no man pages (since no groff, and thus needs a fix to perl.py)
2 - create makeinfo-minimal using Perl-minimal as full dep, mainly since building groff requires perl too.
3 - build normal groff using makeinfo-minimal as builddep
4 - build Perl using new groff
5 - build real makeinfo using Perl as dep as it really needs it during runs.

**Comment by akesandgren** [comment]
The above works, the question now is if we want to do this.

@boegel ?

**Comment by justbennet** [comment]
I was wondering about the seeming inconsistency, but also whether there should be a list of some sort of packages that should be installed as part of the OS system for EasyBuild `system` toolchain to be fully enabled?  Maybe I'm not phrasing that correctly, but hopefully the meaning is clear.

These two Perl libraries would be on it, and I think maybe it would not be bad to include the libraries and Python libraries needed for using GitHub integration on the list, as well.

People with more experience than me should decide which is the better course.

**Comment by boegel** [comment]
@akesandgren Just `Perl` without extensions is not enough for `makeinfo` though? The `Data::Dumper` and `Encode` extensions are required?

**Comment by akesandgren** [comment]
The minimal makeinfo I have has:
configopts = '--disable-perl-xs --disable-perl-api-texi-build --disable-pod-simple-texinfo-tests
and uses a Perl-minimal as builddep, which has no extra modules, just plain Perl.

I could PR them but I'd perfer to get the versionsuffix part fixed first, i.e. should it be -base, -bare, -minimal, or somthing else?

**Comment by justbennet** [comment]
Are the configure options removing things from a standard Perl installation?  If they are, then 'minimal' might be better.  It's used with Linux installations to imply a functional but far from usual installation, so it might be good to continue that connotation?

To me, seeing 'base' as a prefix would imply just the package with default options (or very close).

I am not a fan of 'bare'.

**Comment by akesandgren** [comment]
The version I intended is pure perl tar file, nothing added, nothing removed.

**Comment by justbennet** [comment]
Oh, jeez, sorry.  I meant makeinfo not Perl, but same principles.

**Comment by akesandgren** [comment]
The makeinfo  easyconfig I have has some features turned off so it doesn't need more than basic perl.

**Comment by akesandgren** [comment]
Solved by https://github.com/easybuilders/easybuild-easyconfigs/pull/13163
