### ISSUE TITLE
bintray URLs (e.g. Boost) will become invalid on May, 1st -> Use alternate URLs

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#12099]
There is an announcement from JFrog/Bintray:
>  We are and continue to be a community-focused company, and in the spirit of transparency we’re giving you advance notice that as of May 2021, we will be sunsetting Bintray.
> [...]
> Repositories Hosted on Bintray
    Your repositories for module types including Docker, Maven (Java), Npm, NuGet, RPM, Vagrant, and Generic will need to be migrated off of Bintray service on or before May 1st to avoid any disruption in service.
Conan OSS Users
    Conan packages for C/C++ have been migrated to ConanCenter.
Migrate to the Free Subscription of Artifactory
    JFrog has a new free subscription tier that gives you the ability to manage and distribute artifacts with automated security scanning. You can sign up for a free subscription and start migrating your Bintray artifacts. Unlike Bintray, this service also offers Continuous Integration and is suitable for hosting CI artifacts, such as Snapshot builds.

Hence the Boost download URLs should be changed/added to e.g. `https://sourceforge.net/projects/boost/files/boost/${VERSION}/${FILE_NAME}.tar.bz2/download`

**Comment by branfosj** [comment]
Use of bintray in ecs:

Boost and Boost.Python:
```
Boost-1.71.0-gompi-2019b.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost-1.71.0-gompic-2019b.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost-1.71.0-iimpi-2019b.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost-1.71.0-iimpic-2019b.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost-1.72.0-gompi-2020a.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost-1.72.0-iimpi-2020a.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost-1.74.0-GCC-10.2.0.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost-1.74.0-iccifort-2020.4.304.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost.Python-1.71.0-gompi-2019b.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost.Python-1.71.0-gompic-2019b.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost.Python-1.71.0-iimpi-2019b.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost.Python-1.71.0-iimpic-2019b.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost.Python-1.72.0-gompi-2020a.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
Boost.Python-1.72.0-iimpi-2020a.eb:source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
```

DB:
```
DB-18.1.25-GCCcore-7.3.0.eb:source_urls = ['https://bintray.com/homebrew/mirror/download_file?file_path=']
DB-18.1.32-GCCcore-8.2.0.eb:source_urls = ['https://bintray.com/homebrew/mirror/download_file?file_path=']
DB-18.1.32-GCCcore-8.3.0.eb:source_urls = ['https://bintray.com/homebrew/mirror/download_file?file_path=']
DB-18.1.32-GCCcore-9.3.0.eb:source_urls = ['https://bintray.com/homebrew/mirror/download_file?file_path=']
DB-18.1.40-GCCcore-10.2.0.eb:source_urls = ['https://bintray.com/homebrew/mirror/download_file?file_path=']
```

FDS:
```
FDS-6.0.1-no-OFED.eb:# download .sh from https://bintray.com/nist-fire-research/releases/FDS-SMV/6.0.1/view/files to create tarball
```

Groovy:
```
Groovy-2.5.9-Java-11.eb:source_urls = ['https://dl.bintray.com/groovy/maven/']
```

Transrate:
```
Transrate-1.0.3.eb:source_urls = ['https://bintray.com/artifact/download/blahah/generic']
```

**Comment by Micket** [comment]
I complete forgot about this when i merged DB. So, add DB-18.1.40-GCCcore-10.3.0.eb to the list as well.

**Comment by branfosj** [comment]
I've added the extra DB to the list and I also added a Boost.Python that has been merged since I generated it.

**Comment by boegel** [comment]
Transrate looks like a lost cause, cfr. https://github.com/blahah/transrate/issues/242 

FDS 6.0.1 is ancient, and the bintray URL is only in a comment, so that's a "won't fix" imho.

Fix for latest DB (1.18.40) in #12974, I don't see a way out currently for older versions?

**Comment by LHurst-JM** [comment]
RE Berkeley DB (d/DB) v 18.1.32 - I found (via their package ebuild) Gentoo mirrors have the sources, for example https://mirror.bytemark.co.uk/gentoo/distfiles/ . They don't have a package for DB-18.1.25, just 18.1.32.

**Comment by Micket** [comment]
If others feel they can host these sources, does it mean that the license permits it? If so, we can just host this on the source mirror?

**Comment by LHurst-JM** [comment]
> If others feel they can host these sources, does it mean that the license permits it? If so, we can just host this on the source mirror?

That's a good question but I am not sure Gentoo is the best organisation to take hints from - my impression has been their approach is "seek forgiveness rather than ask permission" when it comes to hosting sources.

**Comment by boegel** [comment]
With #13813 merged, I think we can close this. The rest is either not worth fixing, or there's simply no alternative...
