### ISSUE TITLE
Problem building Serf/1.3.0-GCCcore-8.3.0

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#12127]
Hi

As one of `Subversion` module dependencies, I am trying to build `Serf/1.3.0-GCCcore-8.3.0`; However, I get a funky error message (emitted by SCone, I guess). Here it goes:

```
scons: Reading SConscript files ...
  File "myShm/easybuild/Serf/1.3.9/GCCcore-8.3.0/serf-1.3.9/SConstruct", line 186
    print 'Warning: Used unknown variables:', ', '.join(unknown.keys())
SyntaxError: invalid syntax
```

Any idea how to handle this?
I have attached the build log (in debug-mode).

Thanks in advance
Ehsan
[Serf.tar.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/5951647/Serf.tar.gz)

**Comment by Micket** [comment]
This just looks like python3 complaining about the python2 script (SConstruct). I suspect you have tried to use python3 here? You can't.

**Comment by moravveji** [comment]
Well, after loading EB, I see that the system python is still the first one in the `PATH`:

``` bash
$ module list

Currently Loaded Modules:
  1) EasyBuild/4.2.0

$ which python
/usr/bin/python

$ python --version
Python 2.7.5
```
The EB configuration file also does not specify any other path for python! So, I presume this python 2.7.5 is the one used under the hood (?)

**Comment by Micket** [comment]
Well, that is the system python, which you might not be using when you are building.
E.g. here we specify to depend on the python 2.7.15: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-8.2.0.eb#L17

**Comment by Micket** [comment]
Skimming from your log file there is definitely Python/3.7.4-GCCcore-8.3.9 that gets picked up indirectly, or you perhaps had those modules loaded when you tried building.

**Comment by moravveji** [comment]
The leaking in of Python3 is apparently a side effect of loading SCons. What I read from `module show SCons/3.1.1-GCCcore-8.3.0` is the dependency on Python3 ...
```bash
...
module-whatis    Compatible modules: Python/3.7.4-GCCcore-8.3.0 (default), Python/2.7.16-GCCcore-8.3.0
conflict         SCons
module           load GCCcore/8.3.0
module           load Python/3.7.4-GCCcore-8.3.0...
```
... although SCons should be compatible with Python2(?).
I will try [`SCons/3.0.5-GCCcore-8.2.0-Python-2.7.15`](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SCons/SCons-3.0.5-GCCcore-8.2.0-Python-2.7.15.eb), and see.

**Comment by Micket** [comment]
None of this is really surprising; It is the build-script in Serf that is stuck in the past. You need to do just like we do in this repo. Either have a build dep on Python 2 
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-8.2.0.eb#L17
 or patch Serf like we already do
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-10.2.0.eb#L16
I don't think there is any issue with this easyconfigs repo.
