### ISSUE TITLE
Build failure for Perl-5.32.0-GCCcore-10.2.0

### ISSUE THREAD

**Issue by Ghepardo** [easybuilders/easybuild-easyconfigs#12195]
I am getting a failure to build Perl-5.32.0-GCCcore-10.2.0.  The log file contains, towards the end:

```
./miniperl -Ilib -f write_buildcustomize.pl
do "lib/buildcustomize.pl" failed, '.' is no longer in @INC; did you mean do "./lib/buildcustomize.pl"? at write_buildcustomize.pl line 106.
Can't load generated lib/buildcustomize.pl:  at write_buildcustomize.pl line 117.
make: *** [lib/buildcustomize.pl] Error 13
 (at easybuild/tools/run.py:533 in parse_cmd_output)
```

I have no idea how to go about debugging this.  I do not know where the command 'miniperl' comes from: it is not in my path, and it is not supplied by any package in my OS repositories (for CentOS 7).  And I do not know where to find the script write_buildcustomize.pl.  Any help would be appreciated.  

Regards
Ed

**Comment by branfosj** [comment]
The first part of building Perl is to build `miniperl` which is used to bootstrap the build of Perl. This, and the mentioned scripts, should be in the build directory being used. The build directory will be a subdirectory of the `buildpath`, which you can find by running `eb --show-config`.

**Comment by Ghepardo** [comment]
Thanks very much @branfosj.  That has helped me get started.  I have found that even a manual build of this Perl version, not using EasyBuild at all, fails at the same point.  Therefore I shall take this forward with the Perl maintainers.

**Comment by Ghepardo** [comment]
Just a postscript to this.  The problem was that a previous sysadmin had "kindly" given me a custom Perl installation, complete with environment variable settings pointing to it.  I wasn't even aware I had this.  Clearing those environment variables enabled the EasyBuild build to succeed beautifully.  Luckily I spotted this before wasting the Perl maintainers' time on it.  Living and learning...
