### ISSUE TITLE
Normalize base-level build deps for foss and intel toolchains?

### ISSUE THREAD

**Issue by justbennet** [easybuilders/easybuild-easyconfigs#12196]
In the past, there was general agreement on which versions of the most common and base level build tools would be included in the toolchain releases, but there was some divergence.  For example, in the GCC/8.3.0 and GCCcore/8.3.0, GCC built `Automake/1.15` but GCCcore built `Automake/1.16.1`.  Multiple versions of Bison, M4, and others creep in regularly.

I asked in Slack about possibly having a 'buildtools' easyconfig that would be a single dependency for many of the higher-level packages and versioned in the same sequence as the foss and intel toolchains.  Most importantly to the level of compiler and MPI, as I think that makes it much easier to provide to our developers the same compiler and tools used to build it.  I am still not clear how easy/hard it would be for a software developer to inadvertantly include something from the system that might cause some kind of problem, but perhaps having a `buildtools`.

There was some strong resistance to that idea in Slack, but I wonder whether something looser like a list of versions of these tools to be used for software in each of the toolchains might help reduce the proliferation of extra versions, but, more importantly, insure that we give to our users the same build environment setup that was used to create the compilers and libraries we are providing them.

Is this an old idea that has been rejected previously for good reason?  Any thoughts on whether this would be considered useful or just more tedium?

Thanks for considering.

**Comment by Micket** [comment]
I'm going to have to completely disagree with your initial premise here. First off, Bison, M4, has never had multiple versions compiled under the same toolchain version. I can only assume you looked at the system level bootstrapping packages. Those are a bit of their own thing; a necessary evil in order to build the first GCC, which we don't use afterwards.
Regarding Automake, 1.15 is not build under GCC, there is no such version. There is a system level bootstrap version `Automake-1.15.eb` but it's not part of any toolchain. Though, in this case, there is a `Automake-1.15.1-GCCcore-8.3.0.eb` and a `Automake-1.16.1-GCCcore-8.3.0.eb`, which is a very rare occurrence (and, presumable, it was required for some software).

Almost always, there is the same, single, version throughout each toolchain generation. It's more consistent than ever since a lot have been moved into GCCcore level.

**Comment by justbennet** [comment]
It seems like it would be easier all round to be able to use something like `builddependencies = ('build_deps', '2019a')` than listing them individually.  In every context I know, the more things that have to be entered by hand, the more likely a mistake will occur.  This seems like a way to reduce some handwork.  But, it also seems obvious, so I am thinking I am missing something, even if it is the preferences of those who came before me.

I was trying to ask whether something like that had been considered, or even tried, in the past, and what the arguments for rejection might have been.

You folks have much more experience with EB that I have, so I wanted some wisdom.

**Comment by Micket** [comment]
*Obvious disclaimer first; I don't speak for anyone but myself here*
Well, it's not like you couldn't make such a bundle. Arguably, the toolchain itself is a bit of a bundle like that. 
I suppose some arguments against could be:
1. What stuff goes into the build_deps bundle? We don't want to force on extra stuff for packages that don't need it.
2. What about the typical build deps themselves; what do they depend on? They'll have to list them explicitly, so, it would need to be inconsistent.
3. Nothing about this is specific to *build* deps; you'll have to work through the many dependencies either way, so why treat (on verage) ~1 builddeps you might have differently?

I think the preference is just to be explicit about package dependencies. 
There are tools like --try-toolchain-version and --try-update-deps that simplify updating packages.
The idea of having inequalities in version requirements has been thrown around, but it's not a trivial thing to support, but maybe something like that.

**Comment by justbennet** [comment]
Excellent!  Thank you.  Those are exactly the kinds of thing I was wondering about.  It's hard to think of them from a point of ignorance.  ;-)  I'll go ahead and close this issue on that note.

Thanks, again.
