### ISSUE TITLE
Testing step fails for for Bazel-3.7.2-GCCcore-10.2.0

### ISSUE THREAD

**Issue by Sabryr** [easybuilders/easybuild-easyconfigs#12212]
https://github.com/easybuilders/easybuild-easyconfigs/blob/37eba27a7ac05fbf8b0e76d6859ae8f44d72ce03/easybuild/easyconfigs/b/Bazel/Bazel-3.7.2-GCCcore-10.2.0.eb#L30
Error:

Unknown command type ('<class 'bool'>'): True 

Could be due to some local setting, but wanted to check with others just in case

**Comment by boegel** [comment]
@Sabryr Can you share the full error/traceback you are seeing?

Which EasyBuild version are you using? Any updated easyblocks?

**Comment by Flamefire** [comment]
To find the issue we need more information. I.e. the quoted line and the error seem to be unrelated.
Can you share the full log please?

**Comment by Sabryr** [comment]
Sorry for lack of details. Here they come. 

Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7552 48-Core Processor

NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"

[itf-fox-sw@gpu-3 ~]$ nvidia-smi 
Sun Feb 21 12:46:59 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-PCIE-40GB      Off  | 00000000:01:00.0 Off |                    0 |
| N/A   28C    P0    36W / 250W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

eb --version
This is EasyBuild 4.3.2 (framework: 4.3.2, easyblocks: 4.3.2) on host gpu-3.

[easybuild-Bazel-3.7.2-20210221.123836.FAbOE.log](https://github.com/easybuilders/easybuild-easyconfigs/files/6017623/easybuild-Bazel-3.7.2-20210221.123836.FAbOE.log)

**Comment by branfosj** [comment]
There have been some changes to the TensorFlow easyblock (https://github.com/easybuilders/easybuild-easyblocks/pull/2285) that are required to support the latest easyconfig (`Bazel-3.7.2-GCCcore-10.2.0`).

With the new easyblock `runtest = True` gets converted to `runtest = 'test'` in the easyblock. Without this the `True` gets passed on to the generic `test_step` (https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/framework/easyblock.py#L2178) and that fails as the boolean `True` is not a command.

**Comment by Flamefire** [comment]
Ah yes, that makes sense: So in short the problem is caused by using a develop EasyConfig with an older (e.g. release) EasyBlock.

**Comment by Sabryr** [comment]
Thanks for the input, yes, the older easyblocks were used. Let me pull the latest and check again.

**Comment by boegel** [comment]
@Sabryr Did you manage to solve this?

Another (recommended) way is to update to the latest EasyBuild release (v4.3.3), which includes all changes necessary to build Bazel 3.7.2 and TensorFlow 2.4.1.

**Comment by Sabryr** [comment]
Everything went well with  EasyBuild release v4.3.3.
