### ISSUE TITLE
PETSc-3.12.4-foss-2020a-Python-3.8.2 Build Issue

### ISSUE THREAD

**Issue by oxford-arc** [easybuilders/easybuild-easyconfigs#12250]
Hi,

We're seeing the issue below during the "configure" stage when attempting to build the PETSc foss versions - all seems fine with the Intel versions.

We have have tried the build on CentOS 7.7 and 8.1 machines with the same result.

Any ideas?

Thanks,

Andy

```
TESTING: setupFrameworkCompilers from config.compilers(/apps/system/easybuild/build/PETSc/3.12.4/foss-2020a-Python-3.8.2/petsc-3.12.4/config/BuildSystem/config/compilers.py:1455)
TESTING: configureClosure from config.utilities.closure(/apps/system/easybuild/build/PETSc/3.12.4/foss-2020a-Python-3.8.2/petsc-3.12.4/config/BuildSystem/config/utilities/closure.py:17)
*******************************************************************************
    TypeError or ValueError possibly related to ERROR in COMMAND LINE ARGUMENT while running ./configure
-------------------------------------------------------------------------------
'latin-1' codec can't encode character '\u2018' in position 89: ordinal not in range(256)
*******************************************************************************
 (at easybuild/software/EasyBuild/4.3.2/lib/python3.6/site-packages/easybuild/tools/run.py:533 in parse_cmd_output)
```

**Comment by verdurin** [comment]
These kinds of errors are often associated with `locale` settings.

What do you have on those systems?

I was just able to build `PETSc` successfully on a `CentOS 7.9` instance with the following:
`LANG=en_US.UTF-8` and a `Fedora 32` instance with `LANG=en_GB.UTF-8`

**Comment by oxford-arc** [comment]
Perfect. Thanks Adam, what confused me was the fact that the Intel recipes worked... 

Anyhow, en_GB.UTF-8 fixed it for foss. 

Thanks,

Andy
