### ISSUE TITLE
GCCcore-8.3.0 fails to build because of file permissions in MPC

### ISSUE THREAD

**Issue by akutuzov** [easybuilders/easybuild-easyconfigs#12321]
I was trying to bootstrap a full building environment with EasyBuild 4.3.3, using only the raw unmodified off-the-shelf easyconfigs.
However, when it got to building [GCCcore-8.3.0](https://github.com/easybuilders/easybuild-easyconfigs/blob/main/easybuild/easyconfigs/g/GCCcore/GCCcore-8.3.0.eb), it failed with the following error:

`== 2021-03-02 03:28:46,210 easyblock.py:3113 INFO Running method configure_step part of step configure`

`== 2021-03-02 03:28:51,885 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Failed to copy src build/GCCcore/8.3.0/system-system/mpc-1.1.0 to dst build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc: [('build/GCCcore/8.3.0/system-system/mpc-1.1.0/compile', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/compile', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/compile'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/missing', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/missing', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/missing'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/ar-lib', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/ar-lib', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/ar-lib'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/install-sh', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/install-sh', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/install-sh'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/test-driver', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/test-driver', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/test-driver'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/doc/texinfo.tex', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/doc/texinfo.tex', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/doc/texinfo.tex'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/doc/mdate-sh', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/doc/mdate-sh', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/doc/mdate-sh'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/ltmain.sh', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/ltmain.sh', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/ltmain.sh'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/m4/ltsugar.m4', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/ltsugar.m4', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/ltsugar.m4'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/m4/ltversion.m4', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/ltversion.m4', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/ltversion.m4'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/m4/lt~obsolete.m4', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/lt~obsolete.m4', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/lt~obsolete.m4'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/m4/ltoptions.m4', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/ltoptions.m4', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/ltoptions.m4'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/m4/libtool.m4', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/libtool.m4', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/m4/libtool.m4'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/config.guess', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/config.guess', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/config.guess'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/config.sub', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/config.sub', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/config.sub'"), ('build/GCCcore/8.3.0/system-system/mpc-1.1.0/depcomp', 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/depcomp', "[Errno 13] Permission denied: 'build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc/depcomp'")] (at easybuild/easyblocks/g/gcc.py:251 in prep_extra_src_dirs)`

It seems this happens because of file permissions in the `mpc-1.1.0.tar.gz` archive. More precisely, several files in it lack the write permission for anyone. At the configuring stage, when  EasyBuild attempts to copy these files from `system-system/mpc-1.1.0` to `system-system/gcc-8.3.0/mpc`, for some reason they are already present there, and because of file permissions, it is impossible to overwrite them. 

Simply changing the file permissions in the `mpc-1.1.0.tar.gz` archive fixes the problem, and then the building completes successfully. But this means a manual intervention and changing the check-sums is needed.

I just wonder: is it an issue with EasyBuild, an issue with the easyconfig for GCCcore-8.3.0, or an issue with MPC? GCC is a pretty fundamental piece of software, to say the least, so I was a bit surprised to find out that the easyconfig does not work out of the box.

Interestingly, more recent MPC versions (for example, [1.2.0](http://www.multiprecision.org/downloads/mpc-1.2.0.tar.gz)), move these problematic files into a separate `build-aux` directory and fix the write permissions.

**Comment by Micket** [comment]
I can't reproduce a problem here. Indeed, `build/GCCcore/8.3.0/system-system/mpc-1.1.0` contains files without write permissions, but that's the src of the copy. The destination `build/GCCcore/8.3.0/system-system/gcc-8.3.0/mpc` doesn't even exist before copying (and EB seems to have no issues copying the mpc-1.1.0 directory over to gcc-8.3.0/mpc.

I would be interested in knowing what files you have and what permissions they have inside the gcc-8.3.0 directory after EB fails. I would also start with deleting the failed build directory to make sure it starts off from a clean directory.

**Comment by boegel** [comment]
@akutuzov What kind of filesystem are the build directories on? (`buildpath` in the output of `eb --show-config`).

I think I've hit this problem when using a Lustre filesystem for the build directories, which usually doesn't work out very well...
Try configuring EasyBuild to use a local directory (like `/tmp/$USER`) for the build directories, see https://docs.easybuild.io/en/latest/Configuration.html#build-path-buildpath

**Comment by akutuzov** [comment]
@boegel the filesystem is indeed Lustre, this is an HPC cluster.
I will try to change the build directory to a local one, and report the results here.

**Comment by akutuzov** [comment]
Sorry for the late answer. 
Indeed, the problem was with the Lustre filesystem. Moving the build directory to a local filesystem solved the issue.

**Comment by jedokaplan** [comment]
I can confirm that I had the same issue when my build directory was on a Panasas shared FS. In my case, the issue was fixed by specifying `export EASYBUILD_BUILDPATH=/dev/shm`

**Comment by sassy-crick** [comment]
To add to this: when building on a shared compute node it might be a good idea to use a unique name for a folder in `/dev/shm`, like for example `/dev/shm/$USERNAME` so you can tidy up easily afterwards. This way, you are not filling up the RAM disc.
