### ISSUE TITLE
OpenFOAM-v2012-foss-2020a.eb sanity check fails

### ISSUE THREAD

**Issue by flowgeek** [easybuilders/easybuild-easyconfigs#12374]
Hi

the installation runs all the way (with --robot installing all the dependencies like a charm! :-)) but the sanity check at the end of the OpenFOAM installation fails:

== 2021-03-11 02:27:46,177 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Sanity check failed: no file found at 'OpenFOAM-v2012/platforms/linux64GccDPInt32Opt/lib/mpi/libPstream.so' in /pstore/home/meiera24/.local/easybuild/software/OpenFOAM/v2012-foss-2020a

no file found at 'OpenFOAM-v2012/platforms/linux64GccDPInt32Opt/lib/mpi/libptscotchDecomp.so' in /pstore/home/meier

--> what i noticed: the path to the file on the system is different. Instead of "/lib/mpi/" it is /lib/eb-mpi/
--> also somehow the path for libptscotchDecom.so seems to be missing a lot after "meier"

thanks
alex

**Comment by boegel** [comment]
@flowgeek Which version of EasyBuild are you using for this?

Any chance you can share the full log file of the installation?

**Comment by flowgeek** [comment]
you're fast, thanks! :-)

Easybuild version: 4.3.0

[easybuild-OpenFOAM-v2012-20210310.212018.qOTjh.log](https://github.com/easybuilders/easybuild-easyconfigs/files/6122508/easybuild-OpenFOAM-v2012-20210310.212018.qOTjh.log)

it's only the log for the failed OpenFOAM installation. (If i understood the terminal messages right, the complete toolchain was installed from scratch)

**Comment by boegel** [comment]
Please upgrade your EasyBuild installation to version 4.3.3, you're missing the changes we made in https://github.com/easybuilders/easybuild-easyblocks/pull/2321, and that's leading to the failing sanity check for your installation.

When using EasyBuild v4.3.3, you can try using `eb OpenFOAM-v2012-foss-2020a.eb --module-only` to avoid having to redo the installation. If the sanity check passes, you should be good to go. If not, try to reinstall without `--module-only`.

Keep us posted in this issue whether this helps, and please close the issue if it worked out well.

**Comment by flowgeek** [comment]
that worked - thanks!
