### ISSUE TITLE
LAMMPS-3Mar2020-foss-2020a-Python-3.8.2-kokkos.eb build hang

### ISSUE THREAD

**Issue by gwolosh** [easybuilders/easybuild-easyconfigs#12373]
When building parallel, i. e. make -j 32, the build hangs on sphinx-config. Inlcuding LAMMPS-3Mar2020_fix-docs-build.patch in the easyconfig resolves the issue.

**Comment by boegel** [comment]
See also #12211? Not sure if that's the same problem...

**Comment by ocaisa** [comment]
I've disabled building the docs by default in https://github.com/easybuilders/easybuild-easyblocks/pull/2213 as it causes all kinds of issues.
