### ISSUE TITLE
Qt5 source packages fail to download from original source

### ISSUE THREAD

**Issue by sassy-crick** [easybuilders/easybuild-easyconfigs#12421]
The two Qt5 source code packages are failing to download:
qt-everywhere-src-5.10.1.tar.xz
qt-everywhere-src-5.11.2.tar.xz
I could not find them here either
https://download.qt.io/official_releases/qt/
http://download.qt.io/archive/qt/
Unfortunately I don't have them else I would have requested to put them on the EasyBuild source-code-ancient site. 
I am aware it is older code but other versions are still around. Given they are used in EasyBuild, I am wondering if putting them in the EasyBuild repository makes sense here. 
Thanks.

**Comment by branfosj** [comment]
There are some options available here:

* From Qt - the sources now are at https://master.qt.io/new_archive/qt/
  * https://master.qt.io/new_archive/qt/5.10/5.10.1/single/qt-everywhere-src-5.10.1.tar.xz
  * https://master.qt.io/new_archive/qt/5.11/5.11.2/single/qt-everywhere-src-5.11.2.tar.xz
* Other open source mirrors - i.e. OSUOSL:
  * https://ftp.osuosl.org/pub/blfs/conglomeration/qt5/
  * http://ftp.oregonstate.edu/.1/blfs/conglomeration/qt5/

**Comment by sassy-crick** [comment]
I was, of course, only looking in the EC files in question and thus did not find the 'new_archive' link. Given I did not find them in the 2 links I posted, but older and newer versions, I suspected they were left off for one reason or another. 
Thanks for the links.
Maybe it is a good idea to put these two tarballs in the EB repository as well, as that is where it looks too?
