### ISSUE TITLE
dask/2.18.1-Python-3.8.2 missing tornado

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#12463]
Hi,

If we `load foss/2020a`
and `dask/2.18.1-Python-3.8.2`we get a `pip check`failing:

```distributed 2.18.0 requires tornado, which is not installed```

If we add an IPython module which has a `tornado` pip check passes.  We discovered that in sanity checks failing when build new python bundle easyconfigs.   

How should that be fixed, to avoid version chaos.  It seems that recent `IPython` and `bokeh` have references to toranda.  Olders dask configs had tornado as well.

**Comment by jhein32** [comment]
Hi,

We had local issues with our bokeh modules being broken.  Rebuilding this fixed the issue.  I close the issue report as obsolete.

**Comment by boegel** [comment]
Just to be clear: adding missing extensions via `eb --rebuild --skip` would have helped too probably, but of course a reinstall has the same effect.
