### ISSUE TITLE
libcerf fails to set path for pkg-config

### ISSUE THREAD

**Issue by hattom** [easybuilders/easybuild-easyconfigs#12479]
The `lib/pkgconfig/libcerf.pc` file I get after building `libcerf/1.14-GCCcore-10.2.0` looks like the below.
It comes from: https://jugit.fz-juelich.de/mlz/libcerf: file `libcerf.pc.in` + CMake stuff near the bottom of the `CMakeLists.txt`.

The prefix is not set, which leads to pkg-config not finding the library.

```
prefix=
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libcerf
Description: Complex error function library
Version: 1.14
Libs: -L${libdir} -lcerf
Libs.private: -lm
Cflags: -I${includedir}
```

**Comment by Flamefire** [comment]
You basically need to patch this line https://jugit.fz-juelich.de/mlz/libcerf/-/blob/master/libcerf.pc.in#L1 to use CMAKE_INSTALL_PREFIX instead of destination. Alternatively you can use `configopts="-Ddestination='%(prefix)s'` in the EC as a workaround

**Comment by hattom** [comment]
Fixed upstream. Thanks.
