### ISSUE TITLE
Older versions of g2lib and g2clib sources unavailable

### ISSUE THREAD

**Issue by FokkeDijkstra** [easybuilders/easybuild-easyconfigs#12506]
When trying to install NCL, I ran into an issue with the dependencies g2lib and g2clib. The source files g2lib-3.1.0.tar and g2clib-1.6.0.tar were no longer available in the given download location at: https://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/

When asking about the possibility of having these older versions restored, these versions were restored temporarily. When requesting long term access to these older versions, I was informed that the software development has moved to github, and that the software is now available at: https://github.com/NOAA-EMC/NCEPLIBS.

This leads to the following issues, that may need to be addressed:
1. The source location has changed to github
1. The software names, as used on github, are NCEPLIBS-g2 and NCEPLIBS-g2c.
1. The packaging has changed:
    * The main change is that the source code is now in a directory src, within the archive. 
    * For g2lib there is also an added piece of source code getidxes.f, which has the same subroutine as getidx.f, which is weird.
    * The makefiles are different and probably need adjustment
   
How should this issue be adressed? 
1. Should the software name be changed? If yes, only for newer versions?
1. What to do about older versions, before 3.1.0 and 1.6.0?
1. What to do about changes between the old tar file and the release from github?

**Comment by boegel** [comment]
@FokkeDijkstra Going forward, it seems like we should use the changed software name.

For the older versions, we could consider making the source tarballs available via https://sources.easybuild.io (which is automatically considered by recent EasyBuild versions as a fallback source URL), but we need to make sure we're allowed to redistribute those source tarballs first...

**Comment by FokkeDijkstra** [comment]
The code on https://github.com/NOAA-EMC/NCEPLIBS is licensed under GPLv3. So this should not be an issue.

**Comment by boegel** [comment]
Old sources for `g2lib` and `g2clib` now available via https://sources.easybuild.io/g/g2clib/ and https://sources.easybuild.io/g/g2lib/
