### ISSUE TITLE
GCC-10.2 build fails due to CUDA 11.0

### ISSUE THREAD

**Issue by upsj** [easybuilders/easybuild-easyconfigs#12518]
When trying to compile GCC 10.2 with Easybuild with a CUDA 11.0 module loaded, the compilation fails with 

```
checking for suffix of object files... configure: error: in `/.../GCCcore/10.2.0/system-system/gcc-10.2.0/build-nvptx-gcc/nvptx-none/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
```

The corresponding `nvptx-none/libgcc/config.log` file sheds some light on the situation:
```
configure:3566: /.../GCCcore/10.2.0/system-system/gcc-10.2.0/build-nvptx-gcc/./gcc/xgcc -B/.../GCCcore/10.2.0/system-system/gcc-10.2.0/build-nvptx-gcc/./gcc/ -nostdinc -B/.../GCCcore/10.2.0/system-system/gcc-10.2.0/build-nvptx-gcc/nvptx-none/newlib/ -isystem /.../GCCcore/10.2.0/system-system/gcc-10.2.0/build-nvptx-gcc/nvptx-none/newlib/targ-include -isystem /.../GCCcore/10.2.0/system-system/gcc-10.2.0/newlib/libc/include -B/.../software/GCCcore/10.2.0/nvptx-none/bin/ -B/.../software/GCCcore/10.2.0/nvptx-none/lib/ -isystem /.../software/GCCcore/10.2.0/nvptx-none/include -isystem /.../software/GCCcore/10.2.0/nvptx-none/sys-include    -o conftest -g -O2   conftest.c  >&5
ptxas fatal   : Value 'sm_30' is not defined for option 'gpu-name'
nvptx-as: ptxas returned 255 exit status
```

`sm_30` has been deprecated with CUDA 11.0, so the compilation is missing a `-misa=sm_35` flag here. Not sure how that translates to configure parameters though. Might even be an upstream GCC issue? Let me know if you need any additional information.

My software environment: 
Red Hat Enterprise Linux release 8.2 (Ootpa)
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Cuda compilation tools, release 11.0, V11.0.194

I'll try to see if I can manage to compile everything for CUDA 10.2

**Comment by boegel** [comment]
@bartoldeman Any suggestions on this?

**Comment by Micket** [comment]
Same issue in spack i believe https://github.com/spack/spack/issues/18444

For reference, we currently set these flags: 
https://github.com/easybuilders/easybuild-easyblocks/blob/2cf59d379b923239558c9570b494da3e7877a34e/easybuild/easyblocks/g/gcc.py#L366-L372

I thought PTX meant that it didn't need to know the particular hardware, but compiled at runtime instead?

**Comment by upsj** [comment]
It looks like the configure script is still compiling a full executable for a specific architecture, I rarely see any kind of JIT used for NVIDIA GPUs (or AMD GPUs for that matter, only Intel does JIT with their SPIR-V code by default)

**Comment by verdurin** [comment]
Think I'm seeing something similar albeit with `GCC-9.3.0`. There has been a fix committed in Spack:
https://github.com/spack/spack/pull/23165

**Comment by bartoldeman** [comment]
in principle the build does not depend on anything cuda (i.e. you can build it without any cuda installed), but it may disturb it.
let me double check

**Comment by verdurin** [comment]
In my case, it's that `CUDA` is made available via other means (an Nvidia DeepOps cluster).

**Comment by bartoldeman** [comment]
ok, it seems we need to add this commit as a patch:
https://gcc.gnu.org/git/?p=gcc.git;a=patch;h=383400a6078d

**Comment by Micket** [comment]
Would it not be better to attempt to isolate the GCC build from these system libraries? (of course, I'm not against #13290, but that solution seem like a moving target)

**Comment by bartoldeman** [comment]
yes that's another idea, making sure it uses `nvptx-none-as` instead of `ptxas`.
I believe the configure script will try to find `ptxas` in `$PATH`, but only uses it for test verification purposes; to compile GPU offloaded binaries it's using `nvptx-none-as`.

**Comment by bartoldeman** [comment]
I looked a little deeper.

What actually happens is that `nvptx-none-as` *at runtime* detects if `ptxas` is in `$PATH` and if so, uses it to verify the output.

The patch to GCC works around a hardcoded `-m sm_30` as default.
However, newer nvptx-tools use the target architecture from the `.target` directive in the file instead, so no longer hardcode.
(see https://github.com/MentorEmbedded/nvptx-tools/issues/24)

So probably simply upgrading nvptx-tools (for 9.3/10.2 only; our 10.3 has a new enough version) will fix this without needing to patch GCC (to be tested).

**Comment by verdurin** [comment]
As noted in https://github.com/easybuilders/easybuild-easyconfigs/pull/13298 my attempt to build with the new version of `nvptx-tools` for `9.3.0` failed on a CUDA node.
