### ISSUE TITLE
TensorFlow-1.15.5-fosscuda-2019b-Python-3.7.4.eb failed at sanity check 

### ISSUE THREAD

**Issue by Falkor** [easybuilders/easybuild-easyconfigs#12526]
Build of [`TensorFlow-1.15.5-fosscuda-2019b-Python-3.7.4.eb`](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.5-fosscuda-2019b-Python-3.7.4.eb) failed with the following error (EasyBuild 4.3.3, on a GPU node) -- seems linked to the dependencies listed: 

```
== 2021-04-06 12:05:49,538 run.py:222 INFO running cmd: pip check
== 2021-04-06 12:05:52,132 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd "pip check" exited with exit code 1 and output:
tensorflow-gpu 1.13.1 has requirement tensorboard<1.14.0,>=1.13.0, but you have tensorboard 1.15.0.
tensorflow-gpu 1.13.1 has requirement tensorflow-estimator<1.14.0rc0,>=1.13.0, but you have tensorflow-estimator 1.15.1.
lvis 0.5.3 has requirement numpy>=1.18.2, but you have numpy 1.17.3.
gym 0.18.0 has requirement Pillow<=7.2.0, but you have pillow 8.1.0.
 (at easybuild/tools/run.py:533 in parse_cmd_output)
```

**Comment by Falkor** [comment]
-- indeed [SciPy-bundle  2019.10](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-fosscuda-2019b-Python-3.7.4.eb)  (listed as dependency) comes with  numpy 1.17.3

**Comment by branfosj** [comment]
```
tensorflow-gpu 1.13.1
lvis 0.5.3
gym 0.18.0
```

The sanity check is picking up TensorFlow 1.13.1. Also, `lvis` and `gym` are not installed as part of a TensorFlow install (either directly or as a dependency). So, can you find out where those packages are installed?

**Comment by Falkor** [comment]
I don't know otherwise how to reproduce the `pip check` step...

**Comment by Falkor** [comment]
OK, further debugging seems to indicate that the _default_  Python/3.7.4-GCCcore-8.3.0 module may be involved as it already reports broken requirements: 

```bash 
$ ml lang/Python/3.7.4-GCCcore-8.3.0
=> loading module lang/Python/3.7.4-GCCcore-8.3.0
$ which python
/opt/apps/resif/iris/2019b/gpu/software/Python/3.7.4-GCCcore-8.3.0/bin/python
$ python -s -m pip check
tensorflow-gpu 2.4.1 requires flatbuffers, which is not installed.
-ensorflow-gpu 1.13.1 has requirement tensorboard<1.14.0,>=1.13.0, but you have tensorboard 2.4.1.
-ensorflow-gpu 1.13.1 has requirement tensorflow-estimator<1.14.0rc0,>=1.13.0, but you have tensorflow-estimator 2.4.0.
tensorflow-gpu 2.4.1 has requirement grpcio~=1.32.0, but you have grpcio 1.33.1.
tensorflow-gpu 2.4.1 has requirement numpy~=1.19.2, but you have numpy 1.20.2.
gym 0.18.0 has requirement Pillow<=7.2.0, but you have pillow 8.1.0.
```
Any recommandation to first resolve that?

**Comment by Falkor** [comment]
Ok, we trace it -- there was a corrupted site-package site-package directory.
Situation is sanitised now and the package installed successfully.

**Comment by boegel** [comment]
Thanks for closing this issue with a detailed description @Falkor!
