### ISSUE TITLE
Berkeley DB (easyconfig DB-...) fails to fetch sources

### ISSUE THREAD

**Issue by trz42** [easybuilders/easybuild-easyconfigs#12573]
Tested with DB-18.1.32-GCCcore-9.3.0.eb and EB 4.3.4.

EB results in some cryptic error

`== 2021-04-12 20:09:19,378 filetools.py:747 INFO Attempt 1 of downloading https://bintray.com/homebrew/mirror/download_file?file_path=berkeley-db-18.1.32.tar.gz to /tmp/thomarob/easybuild/sources/d/DB/db-18.1.32.tar.gz failed, trying again...
== 2021-04-12 20:09:19,397 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): SSL issues with urllib2. If you are using RHEL/CentOS 6.x please install the python-requests and pyOpenSSL RPM packages and try again. (at easybuild/tools/filetools.py:750 in download_file)`

Opening https://bintray.com/homebrew/mirror/download_file?file_path=berkeley-db-18.1.32.tar.gz in a browser results in a `Forbidden!` message. Doing `wget https://bintray.com/homebrew/mirror/download_file?file_path=berkeley-db-18.1.32.tar.gz` results in a redirection

`HTTP request sent, awaiting response... 302 Found
Location: https://dl.bintray.com/homebrew/mirror/berkeley-db-18.1.32.tar.gz?expiry=1618258642744&signature=fqPajS6bah%2FadpYCv3seet7K%2F4mvVcn82Zx1TfpGaFQsI5P64cfjBAfXhYOf15TTWPOCTkGAVkYHkDJXHV8h5w%3D%3D [following]`

The expiry time corresponds to "Monday, April 12, 2021 8:17:22.744 PM".

Replacing the expiry time with some date+time in the future "1618259936109" (Monday, April 12, 2021 8:38:56.109 PM) and removing the signature part lets one circumvent the issue. Likely not the best way to do this?

**Comment by terjekv** [comment]
This is being tracked in #12099

**Comment by Micket** [comment]
I'll close this as a duplicate since so that we organize any discussion in #12099
