### ISSUE TITLE
wget: Starting 1.19 libidn2 is required instead of libidn(1).

### ISSUE THREAD

**Issue by robert-mijakovic** [easybuilders/easybuild-easyconfigs#12663]
Current ECs are using libidn(1), however, the wget configure requires libidn2.
```
$ ./configure --help
...
  --with-libidn=DIR       Support IDN2008/IRIs (needs GNU libidn2 +
                          libunicode)
...
```
Also, wget installation log shows:
```
checking for library containing idn2_lookup_u8... no
configure: WARNING: *** LIBIDN2 was not found. You will not be able to use IDN2008 support
```

**Comment by boegel** [comment]
@robert-mijakovic Is this a problem with current  `wget` easyconfigs already?

**Comment by robert-mijakovic** [comment]
> @robert-mijakovic Is this a problem with current `wget` easyconfigs already?

Yes, with the existing ECs.

**Comment by robert-mijakovic** [comment]
I fixed everything except while compiling GCCcore 6.4.0 I face https://github.com/easybuilders/easybuild-easyconfigs/issues/10950.
It probably makes no sense in fixing it.
