### ISSUE TITLE
Error checksum patch in WRF-3.9.1.1-foss-2020b

### ISSUE THREAD

**Issue by Takdanais** [easybuilders/easybuild-easyconfigs#12756]
I meet error checksum every patch in WRF-3.9.1.1-foss-2020b error 

== FAILED: Installation ended unsuccessfully (build directory: .local/easybuild/software/WRF/3.9.1.1-foss-2020b-dmpar): build failed (first 300 chars): Checksum verification for /software/WRF_easy/WRF-3.9.1.1_GCC-10-allow-argument-mismatch.patch using 3cc8a43838c7d821d02a7c64acbc08b730691af5ab6bc5f6ba0afd6356c4af01 failed. (took 0 sec)

**Comment by akesandgren** [comment]
According to my copy of the file from the develop tree, the correct checksum is 3cc8a43838c7d821d02a7c64acbc08b730691af5ab6bc5f6ba0afd6356c4af01
So if yours is different, compare it to what's in EB upstream

**Comment by Takdanais** [comment]
> 
> 
> According to my copy of the file from the develop tree, the correct checksum is 3cc8a43838c7d821d02a7c64acbc08b730691af5ab6bc5f6ba0afd6356c4af01
> So if yours is different, compare it to what's in EB upstream

In my eb file is 3cc8a43838c7d821d02a7c64acbc08b730691af5ab6bc5f6ba0afd6356c4af01. after check in eb file, it's correct.

**Comment by Takdanais** [comment]
I'm download patch and use sha256sum to patch files and edit checksum in eb file. It's work
