### ISSUE TITLE
rhdf5filters (R-bundle-Bioconductor-3.12-foss-2020b-R-4.0.3.eb) fails to install on aarch64

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-easyconfigs#12817]
Installing extension rhdf5filters 1.2.0 (in R-bundle-Bioconductor-3.12-foss-2020b-R-4.0.3.eb) fails on aarch64 with the error:
```
configure: error: Need GCC to support X86 CPU features tests
```

Workaround is to use the following
```
    ('rhdf5filters', '1.2.0', {
        'checksums': ['58df019a2c8626cc236ebe19d44b830a6c3b5f787ea4090d5b57454a88d676cb'],
        'installopts': '--configure-args="ax_cv_gcc_check_x86_cpu_init=yes ax_cv_gcc_x86_cpu_supports_sse2=no"',
    }),
```
but this will not be wanted on x86_64. Instead some patching of the configure file should be used.

(From a report on slack - I did not see this issue when installing on POWER.)

**Comment by boegel** [comment]
It looks like this was fixed in a more recent version of `rhdf5filters`, see https://github.com/grimbough/rhdf5filters/commit/9dc35243dde38886df3b22a95a81b421fb712b85
