### ISSUE TITLE
libibverbs-1.1.4-GCC-4.7.2.eb hompage broken link

### ISSUE THREAD

**Issue by waleedlotfy** [easybuilders/easybuild-easyconfigs#1281]
Dear developers,

Kindly note that installing libibverbs-1.1.4-GCC-4.7.2.eb yields http response 400, due to the home page of the project using 'https' not 'http'.

Upon fixing the home page url everything works fine.

Thank you for your efforts.

**Comment by Micket** [comment]
This is a os dep these days, so no homepage to fix
