### ISSUE TITLE
Building Clang with gcccuda requires elfutils

### ISSUE THREAD

**Issue by nordmoen** [easybuilders/easybuild-easyconfigs#13006]
When building `Clang/11.0.1-gcccuda-2020b` on our cluster it was never able to properly offload to our Nvidia GPUs, however, the compiler never failed to compile and OpenMP still worked, it was just not able to detect any GPUs on the system. After a bit of digging I found the following in the build log of `Clang`:

```bash
-- LIBOMPTARGET: Building offloading runtime library libomptarget.                        
-- LIBOMPTARGET: Not building aarch64 offloading plugin: machine not found in the system. 
-- LIBOMPTARGET: Not building CUDA offloading plugin: libelf dependency not found.        
-- LIBOMPTARGET: Not building PPC64 offloading plugin: machine not found in the system.   
-- LIBOMPTARGET: Not building PPC64le offloading plugin: machine not found in the system. 
-- LIBOMPTARGET: Not building nec-aurora plugin: libveo or libveosinfo not found.         
-- LIBOMPTARGET: Not building x86_64 offloading plugin: libelf dependency not found.      
-- LIBOMPTARGET: Building CUDA offloading device RTL.                                     
```

Which shows that it is build some part of the offloading support, but since `-- LIBOMPTARGET: Not building CUDA offloading plugin: libelf dependency not found.` I guess it was never able to properly generate the offload code.

Adding `elfutils/0.183` to the build dependencies of `Clang` solved the problem and a very simple offloading program, that did not work before adding `elfutils`, was able to detect and offload to the Nvidia GPU.

**Comment by akesandgren** [comment]
elfutils likely need to be a run time dependency but you should properly check if it is only used during building of clang first.

**Comment by nordmoen** [comment]
It worked on our cluster by just adding it as a build dependency.

**Comment by boegel** [comment]
I've re-opened this since #13015 should get merged too before closing this...
