### ISSUE TITLE
Integrate OpenFOAM-v2106

### ISSUE THREAD

**Issue by olesenm** [easybuilders/easybuild-easyconfigs#13276]
[OpenFOAM v2106 was just released](https://www.openfoam.com/news/main-news/openfoam-v2106) - would be nice to have an EasyBuild pack to follow.

@boegel From what I can see, the config restructuring for the v2012 release should pay off. Likely only need to copy the `.eb` file with a new name and adjust the SHA values for the new tar file.

**Comment by rarensu** [comment]
/me is also interested in this ticket

**Comment by boegel** [comment]
We already have a work-in-progress pull request for OpenFOAM v2106 by @robert-mijakovic, see #13266 .

As soon as we get the Paraview easyconfig merged (#13269), that's probably good to go in...
