### ISSUE TITLE
build step fails for manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#13337]
```
In file included from /software/Boost/1.74.0-GCC-10.2.0/include/boost/detail/workaround.hpp:8,
                 from /software/Boost/1.74.0-GCC-10.2.0/include/boost/serialization/level.hpp:20,
                 from /software/Boost/1.74.0-GCC-10.2.0/include/boost/serialization/nvp.hpp:33,
                 from /tmp/easybuild_build/manta/1.6.0/GCC-10.2.0-Python-2.7.18/manta-1.6.0/src/c++/lib/appstats/SVFinderStats.hpp:26,
                 from /tmp/easybuild_build/manta/1.6.0/GCC-10.2.0-Python-2.7.18/manta-1.6.0/src/c++/lib/appstats/SVFinderStats.cpp:24:
/software/Boost/1.74.0-GCC-10.2.0/include/boost/type_traits/detail/config.hpp:85:69: error: "__clang_major___WORKAROUND_GUARD" is not defined, evaluates to 0 [-Werror=undef]
   85 |       && !BOOST_WORKAROUND(BOOST_MSVC, < 1900) && !BOOST_WORKAROUND(__clang_major__, <= 4)
      |                                                                     ^~~~~~~~~~~~~~~
```

`manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb` installs fine with EasyBuild, even on top of a Boost that was installed with the enhanced easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/2456.

It looks like this issue could be related to the changes in https://github.com/easybuilders/easybuild-easyblocks/pull/2461...

**Comment by boegel** [comment]
Installation of `manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb` works fine with current `develop` on top of old Boost installation (with EasyBuild 4.3.4).

So the problem seems to be that `-DBoost_NO_BOOST_CMAKE=ON` is no longer being used.

**Comment by boegel** [comment]
When using `-DBoost_NO_BOOST_CMAKE=ON`, the CMake output includes:

```
-- Found Boost: /software/Boost/1.74.0-GCC-10.2.0/include (found suitable version "1.74.0", minimum required is "1.58.0")
```

and then the compiler command for `AlignmentUtil.cpp` (which fails in the failing build) includes `-isystem /software/Boost/1.74.0-GCC-10.2.0/include`.

In the failing build, without `-DBoost_NO_BOOST_CMAKE=ON` the CMake output is different:

```
- Found Boost: /software/Boost/1.74.0-GCC-10.2.0/lib64/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.58.0")
```

And then there's no `-isystem` flag in the compilation command for `AlignmentUtil.cpp`.

So an obvious fix would be to add `-DBoost_NO_BOOST_CMAKE=ON` to the `manta` easyconfig, but it would be good to figure out why it fails without that...

cc @akesandgren @Flamefire @zao

**Comment by boegel** [comment]
Some more info: `"__clang_major___WORKAROUND_GUARD" is not defined` is only popping up because `manta` hard injects `-Wundef` as compiler flag, which makes the compiler trip over undefined stuff...

Also, this problem is not popping up at all with `manta-1.6.0-gompi-2019b-Python-2.7.16.eb` or `manta-1.6.0-gompi-2020a-Python-2.7.18.eb`, so this smells a lot like bug in CMake or Boost (probably the latter) to me...

And yep: https://github.com/boostorg/type_traits/issues/107

So I'll just work around this by adding `-DBoost_NO_BOOST_CMAKE=ON` to `manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb`...

**Comment by Flamefire** [comment]
> So I'll just work around this by adding -DBoost_NO_BOOST_CMAKE=ON to manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb...

I don't think this is an appropriate fix because it only does a workaround which happens to work.

The actual problems in order are:
- Boost uses an undefined preprocessor macro -> "Bug" in Boost (one can argue here)
- manta adds `-Wundef` which makes the prior thing visible
- manta also adds `-Werror` which turns the prior warning into a hard error
- FindBoost adds boost as SYSTEM headers silencing all warnings from there -> Happens to succeed despite the above
- BoostConfig (the new, better system to get boost libs) doesn't use SYSTEM to add headers -> Bug from Boost now an error

--> Better fix is to not enable Werror from manta by changing this here to false: https://github.com/Illumina/manta/blob/75b5c38d4fcd2f6961197b28a41eb61856f2d976/CMakeLists.txt#L56 as is done in their actual releases: https://github.com/Illumina/manta/blob/75b5c38d4fcd2f6961197b28a41eb61856f2d976/scratch/make_release_tarball.bash#L63

**Comment by Flamefire** [comment]
Or just use the actual release sources: https://github.com/Illumina/manta/releases/download/v1.6.0/manta-1.6.0.release_src.tar.bz2

**Comment by Flamefire** [comment]
@boegel 
> And then there's no -isystem flag in the compilation command for AlignmentUtil.cpp.

I see the opposite(!). As per the design of the IMPORTED targets (i.e. for Boost_NO_BOOST_CMAKE=OFF) the include paths are always SYSTEM while they are NOT for the FindBoost versions.
So something is odd here...

**Comment by Flamefire** [comment]
Ok, it is a bug in manta: https://github.com/Illumina/manta/issues/265

Anyway: Using the release builds will (likely) have worked but given their use of CMake the current solution is acceptable
