### ISSUE TITLE
Rust 1.52.2 builds own LLVM depending on Python3 (dropped Python2 fallback support)

### ISSUE THREAD

**Issue by seb45tian** [easybuilders/easybuild-easyconfigs#13350]
While building foss/2021 and therefore Rust on CentOS 7.9  ( #12904 ) I got a CMake error stating that it cannot find any Python3 executable. Rust is building its own LLVM, and apparently LLVM dropped a Python2 fallback hook back in December (cf. https://github.com/rust-lang/llvm-project/commit/5e31e226b5b2b682607a6578ff5adb33daf4fe39 ). Since Rust itself is now a dependency of Python3 (cf.  #12755) the only solution I can see right now is to require a system installation of Python3 (3.6 or above is required) to be able to compile Rust and ... Python3 🤨. 

Any thoughts on this?

**Comment by Micket** [comment]
We have a `Python-3.9.5-GCCcore-10.3.0-base.eb`. Can you try adding a builddep `('Python', '3.9.5', '-bare')` to see if that helps?

**Comment by seb45tian** [comment]
Ah, didn't know about the bare Python3 version, yet. This should work. Will test it and make a PR when confirmed.
