### ISSUE TITLE
"NINJA" easyconfig will name collide with "Ninja"

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#13412]
I happened to see that there was a easyconfig named "NINJA" now, and, since some naming schemes, as well as our environment variables, ignore case, this will conflict with "Ninja". 

https://github.com/easybuilders/easybuild-easyconfigs/blob/e679b333f74853d128e8fe3bfbb8725909e94d9e/easybuild/easyconfigs/n/NINJA/NINJA-0.97-cluster_only-GCC-10.2.0.eb

this package should be renamed ASAP

**Comment by jfgrimm** [comment]
just make sure never to load Ninja and NINJA, and switch to a case-sensitive MNS ;)

in all seriousness, I'd suggest something like `TWL-NINJA`?

**Comment by jfgrimm** [comment]
#13126 and its easyblock [#2470](https://github.com/easybuilders/easybuild-easyblocks/pull/2470) will need updating to match

**Comment by Micket** [comment]
I have no real suggestions for the name. Their about section is blank, and the acronym means nothing to me.

**Comment by boegel** [comment]
fixed in #13529, so closing this...
