### ISSUE TITLE
HDF5 fails to build on Debian Wheezy

### ISSUE THREAD

**Issue by sylmarien** [easybuilders/easybuild-easyconfigs#1341]
Hello, once again a problem on Debian Weezy.

This time the problem appears when trying to build HDF5-1.8.10-ictce-5.3.0-gpfs.  
The problem seems to be about MPI not being correctly linked, here is the full log:  
https://gist.github.com/sylmarien/9ddcaab99e310f8818af

Building the version without -gpfs works fine, but since it is a dependcy that is automatically picked up by EasyBuild when building NetCDF-C++, I cannot really choose what to install.

If you need any other information, as always I'll be here.  
Thanks in advance for your help.

**Comment by boegel** [comment]
@sylmarien: can you confirm that building and installing `HDF5-1.8.10-ictce-5.3.0.eb` is working fine, on the same system? (i.e. the exact same toolchain & HDF5 version)?

relevant part from the debug log:
```
checking for MPI_Init in -lmpi... no
checking for MPI_Init in -lmpich... no
checking for
            include 'mpif.h'
            integer:: ierr
            call mpi_file_open( ierr ) in -lmpi... ./configure: line 28311: ${ac_cv_lib_mpi_ ____________include__mpif_h_ ____________integer___ierr ____________call_mpi_file_open__ierr__+:}: bad substitution
./configure: line 28327: ac_cv_lib_mpi_: command not found
./configure: line 28328: ____________include__mpif_h_: command not found
./configure: line 28329: ____________integer___ierr: command not found
./configure: line 28333: ____________include__mpif_h_: command not found
```

it's weird that both `-lmpi` and `-lmpich` fail, since the libraries should be there

can you check what the following commands spit out on your end?

```
$ module load impi/4.1.0.030-iccifort-2013.3.163
$ ls $EBROOTIMPI/lib64/libmpi.so
/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/impi/4.1.0.030-iccifort-2013.3.163/lib64/libmpi.so
$ ls $EBROOTIMPI/lib64/libmpich.so
/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/impi/4.1.0.030-iccifort-2013.3.163/lib64/libmpich.so
$ ls $EBROOTIMPI/include64/mpif.h
/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/impi/4.1.0.030-iccifort-2013.3.163/include64/mpif.h
```

Maybe also include the output of `module show impi/4.1.0.030-iccifort-2013.3.163`

**Comment by boegel** [comment]
@wpoely86: are you experiencing this too on Debian (same OS version)?

**Comment by wpoely86** [comment]
Never tried the `-gpfs` version. The non-gpfs versions build and work fine.

**Comment by wpoely86** [comment]
@sylmarien can you add the config.log?

**Comment by sylmarien** [comment]
@boegel Firstly, yes I can confirm that building and installing HDF5-1.8.10-ictce-5.3.0.eb is woriking fine on the same machine.

Then for the command you asked, here are the outputs:  
```
$ module load impi/4.1.0.030-iccifort-2013.3.163

Lmod has detected the following error: 
The following module(s) are unknown: "impi/4.1.0.030-iccifort-2013.3.163"

   Please check the spelling or version number. Also try "module spider ..."

```
And then obviously the others cannot be executed correctly since the module doesn't load.  
So the problem seems to be this dependency, I could try to build it separately, but if it is a dependency, then it should have been built (I used the --robot flag).

@wpoely86 Here is the config.log:  
https://gist.github.com/sylmarien/ef5fd361de39f0a27107

**Comment by wpoely86** [comment]
This is the problem:
```
ld: cannot find -lgpfs
```
You don't have the gpfs libraries installed?

**Comment by sylmarien** [comment]
It seems I do:  
```
$ dpkg -l | grep gpfs
ii  gpfs.base                             4.1.0-3                        amd64        GPFS File Manager
ii  gpfs.docs                             4.1.0-3                        all          GPFS Server Manpages and Documentation
ii  gpfs.gpl                              4.1.0-3                        all          GPFS Open Source Modules
ii  gpfs.gskit                            8.0.50-16                      amd64        GPFS GSKit Cryptography Runtime
ii  gpfs.msg.en-us                        4.1.0-3                        all          GPFS Server Messages - U.S. English
```

Am I missing something here ?

**Comment by wpoely86** [comment]
Can you look for `libgpfs*`?

**Comment by sylmarien** [comment]
Ok, I have nothing for that.  
But why is the -gpfs version chosen by EasyBuild? Couldn't it use the normal version?

**Comment by wpoely86** [comment]
@sylmarien you can change it yourself it you want to. Just drop the `-gpfs` in the `netCDF` easyconfig.

No idea why it's on by default.

**Comment by sylmarien** [comment]
Indeed, it works. I will go with that solution for the time being.  
Maybe it could be interesting to split the easyconfig in two separate ones? One without -gpfs and one with it (and having the flag explicitly stated in the name) so that it avoids confusion. Or maybe there is a reason I don't know about to have it with -gpfs by default. (But since it is note the case on the netCDF-4.2, I doubt it)

**Comment by Micket** [comment]
We certainly don't use some exotic gpfs support by default these days so sylmarien was on to something.  :) 
(anyone wanting to still do something like that, it would be a site-specific hook to customize the builds)
