### ISSUE TITLE
some R packages with dependencies should be moved to their own module

### ISSUE THREAD

**Issue by JensTimmerman** [easybuilders/easybuild-easyconfigs#135]
png, Rniftilib, Rsamtools depend op zlib
shortread depends on genomegraphs which depends on XML (already in a separate module) which depends on libxml2
(shortread adn genomegraphs are bioconductor packages)

**Comment by Micket** [comment]
Closing this issue as it's long since resolved/outdated (we have proper dependencies nowadays, nothing is missing out on zlib)
