### ISSUE TITLE
bzip2: Patch is wrong for bzip2 version 1.0.8

### ISSUE THREAD

**Issue by klust** [easybuilders/easybuild-easyconfigs#13513]
Issue in https://github.com/easybuilders/easybuild-easyconfigs/tree/main/easybuild/easyconfigs/b/bzip2

Currently the .eb files for bzip2 1.0.8 use the same patch as those for 1.0.6. This creates a problem: One of the functions of the patch is to ensure that a proper .pc file for pkg-config is created. Line 17 of the patch contains the version number of bzip2 and that should be changed to 1.08.

Impact:
- Different patch needed in the 1.0.8 eb files - probably work with bzip2-%(version)s-pkgconfig.patch to remind that the patch depends on the version of bzip2?
- And of course this also implies adapting the checksum of the patch in those eb files.

I'm currently working on a Cray system without the GCCcore toolchain so it is not trivial for me to make a pull request with corrections without screwing up my own repository.,

**Comment by klust** [comment]
And while we're on it, I also wonder if https://www.sourceware.org/bzip2/ isn't a better home page for 1.0.8. It has seem more recent updates.

**Comment by Micket** [comment]
Yes to everything here. Feel free to open a PR for this

**Comment by SebastianAchilles** [comment]
I think this issue is solved by https://github.com/easybuilders/easybuild-easyconfigs/pull/13581

Can we close this issue?

**Comment by Micket** [comment]
yeah apparently i just put in the wrong ticket number in me "fixes ...." comment, referring to the PR itself and not this ticket.
