### ISSUE TITLE
CRAN package download fails due to wrong URL, EB 4.3.4, R 4.0.4

### ISSUE THREAD

**Issue by kelbstf** [easybuilders/easybuild-easyconfigs#13553]
Hello,

i have trouble installing/compiling "R-4.0.4-foss-2020b.eb" usign EB 4.3.4 (OHPC 2.2):

most of the packages fail to be downloaded in the early phase:

<pre>
== 2021-08-03 11:03:59,969 filetools.py:733 \
WARNING URL https://cran.r-project.org/src/contrib/Archive/ff/ff_4.0.4.tar.gz \
was not found (HTTP response code 404), not trying again
</pre>
Because those packages are not actually at 
"https://cran.r-project.org/src/contrib/Archive"
(where the "--fetch" procedure looks it up), but at 
"https://cran.r-project.org/src/contrib"
as is apparently true for all current/non-archived package releases for "R".
I can't figure out where this wrong URL path is actually coming from.
The "R-4.0.4-foss-2020b.eb" can't be it, as here everything is pefectly fine coded:
<pre>
exts_default_options = {
    'source_urls': [
        'https://cran.r-project.org/src/contrib/Archive/%(name)s',  # package archive
        'https://cran.r-project.org/src/contrib/',  # current version of packages
        'https://cran.freestatistics.org/src/contrib',  # mirror alternative for current packages
    ],
</pre>
Where can such a URL can origin from, and can i fix it there to make the download phase of the "R" installation work?

Environment:
EB 4.3.4
R-4.0.4
CentOS 8.3

Best regards

**Comment by kelbstf** [comment]
Hello,

i don't exactly know what happened before, but repeating the exact same attempt a couple of hours later, the second iterations of the fetcher to download the files from the "/contrib" section after they couldn't be found in the "/archive" section succeeded, and the files have been downloaded just fine. 
There are still problems with some checksum mismatches, but that's a different topic.

Best

**Comment by boegel** [comment]
@kelbstf The checksum mismatches have been fixed in more recent versions of EasyBuild.

You should consider installing the latest EasyBuild version (for example using `eb --install-latest-eb-release`, which will give you an `EasyBuild` module you can load), and use that (it should be a drop-in replacement for EasyBuild v4.3.4, but with some bugs fixed and lots of enhacements and software updates)

**Comment by kelbstf** [comment]
Hello boegel,

thank you very much for your reply and help.
This is good news, but forks the question, whether this can safely be done when living on OpenHPC(2.2), which ships EasyBuild bundled in/integrated. 
That's very likely a question to better put over there. 
Or do you accidently have experiences with that, in this scenario?

Best

**Comment by boegel** [comment]
@kelbstf `eb --install-latest-eb-release` will not touch the existing EasyBuild installation at all, it will install a new EasyBuild installation along with the other modules, and then you can start using it.

So yes, it should be safe to use this, regardless of how the EasyBuild you're using was installed.

See also https://docs.easybuild.io/en/latest/Installation.html#installing-easybuild-with-easybuild

**Comment by kelbstf** [comment]
Hello @boegel,

thank you very much!
That helps me a lot.
I'll use that solution.

Best
