### ISSUE TITLE
Help needed in Siesta 4.1.5

### ISSUE THREAD

**Issue by varun082021** [easybuilders/easybuild-easyconfigs#13559]
Hi All,

Did anyone tried to build Sieata 4.1.5 using EasyBuild? if yes can you please share the .eb files. @akesandgren @migueldiascosta 
Hi Miguel and Aka, It seems easyblock siesta.py needs some modification to accommodate Siesta V 4.1.5. I request you to have a look and help us on this request.

**Comment by varun082021** [comment]
@migueldiascosta @akesandgren 
Hi Miguel and Aka, It seems easyblock siesta.py needs some modification to accommodate Siesta V 4.1.5. I request you to have a look and help us on this request.

**Comment by migueldiascosta** [comment]
@varun082021 try

```diff
--- siesta.py.orig	2021-02-02 09:43:26.716786017 +0800
+++ siesta.py	2021-08-04 07:14:09.929750903 +0800
@@ -125,7 +125,7 @@
         # Populate start_dir with makefiles
         run_cmd(os.path.join(start_dir, 'Src', 'obj_setup.sh'), log_all=True, simple=True, log_output=True)
 
-        if loose_ver < LooseVersion('4.1-b2'):
+        if loose_ver < LooseVersion('4.1'):
             # MPI?
             if self.toolchain.options.get('usempi', None):
                 self.cfg.update('configopts', '--enable-mpi')
@@ -313,8 +313,6 @@
                 'Denchar/Src/denchar',
                 'DensityMatrix/cdf2dm', 'DensityMatrix/dm2cdf',
                 'Eig2DOS/Eig2DOS',
-                'Gen-basis/gen-basis', 'Gen-basis/ioncat',
-                'Gen-basis/ionplot.sh',
                 'Grid/cdf2grid', 'Grid/cdf2xsf', 'Grid/cdf_laplacian',
                 'Grid/g2c_ng', 'Grid/grid2cdf', 'Grid/grid2cube',
                 'Grid/grid2val', 'Grid/grid_rotate',
@@ -336,6 +334,11 @@
                 'WFS/wfsnc2wfsx', 'WFS/wfsx2wfs',
             ]
 
+            if self.version < LooseVersion('4.1.5'):
+                expected_utils.extend([
+                    'Gen-basis/gen-basis', 'Gen-basis/ioncat', 'Gen-basis/ionplot.sh',
+                ])
+
             # skip broken utils in 4.1-MaX-1.0 release, hopefully will be fixed later
             if self.version != '4.1-MaX-1.0':
                 expected_utils.extend([
```

**Comment by varun082021** [comment]
@migueldiascosta Hi, Its failing with below error.
== 2021-08-04 06:39:36,027 easyblock.py:3701 WARNING build failed (first 300 chars): cmd "make -j 40 transiesta" exited with exit code 2 and output:

**Comment by migueldiascosta** [comment]
@varun082021 sorry for the delay - can you paste the actual output (or upload the whole log to a github gist, for example)?

**Comment by akesandgren** [comment]
Solved by https://github.com/easybuilders/easybuild-easyblocks/pull/2553 and https://github.com/easybuilders/easybuild-easyblocks/pull/2553

**Comment by migueldiascosta** [comment]
closing since https://github.com/easybuilders/easybuild-easyblocks/pull/2553 was merged - @varun082021 feel free to re-open the issue if you're still having problems
