### ISSUE TITLE
Bazel 3.7.1 Install Issues

### ISSUE THREAD

**Issue by csayre** [easybuilders/easybuild-easyconfigs#13598]
I am getting the following error when attempting to install Bazel 3.7.1 with GCC Core 8.3.0

```
== FAILED: Installation ended unsuccessfully (build directory: /opt/apps/build/Bazel/3.7.1/GCCcore-8.3.0): build failed (first 300 chars): Failed to remove directory /opt/apps/build/Bazel/3.7.1/GCCcore-8.3.0 even after 3 attempts.
Reasons: [OSError(39, 'Directory not empty'), OSError(16, 'Device or resource busy'), OSError(16, 'Device or resource busy')] (took 31 mins 10 secs)
== Results of the build can be found in the log file(s) /opt/apps/tmp/eb-rg6lf3/easybuild-Bazel-3.7.1-20210804.081307.aYRfv.log
ERROR: Build of /opt/apps/software/EasyBuild/4.4.1/software/EasyBuild/4.4.1/easybuild/easyconfigs/b/Bazel/Bazel-3.7.1-GCCcore-8.3.0.eb failed (err: "build failed (first 300 chars): Failed to remove directory /opt/apps/build/Bazel/3.7.1/GCCcore-8.3.0 even after 3 attempts.\nReasons: [OSError(39, 'Directory not empty'), OSError(16, 'Device or resource busy'), OSError(16, 'Device or resource busy')]")
```

Any ideas as to what is causing this?

**Comment by boegel** [comment]
Are you able to remove the directory manually?

On which type of filesystem is this?
It's *strongly* recommended to not use a shared filesystem (like NFS, GPFS, etc.) for the build directories. You should use a local filesystem instead, by configuring EasyBuild to use `/tmp/$USER` for the build directories, for example.

**Comment by csayre** [comment]
So we do use NFS (/opt/apps). We have been using this NFS mount as far as I know since we have gotten this cluster without this issue. I have used Easybuild to install a few other apps since I have taken over managing this cluster. Is there a way around this?

**Comment by boegel** [comment]
You should tweak your EasyBuild configuration to not use a shared filesystem for `buildpath` (see https://docs.easybuild.io/en/latest/Configuration.html#buildpath).

If you need help with that, please share the output of `eb --show-config` (which will tell us how you're currently configuring EasyBuild), and we can provide some more specific suggestions.

**Comment by csayre** [comment]
eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (D) = /home/builduser/.local/easybuild/build
containerpath  (D) = /home/builduser/.local/easybuild/containers
installpath    (D) = /home/builduser/.local/easybuild
repositorypath (D) = /home/builduser/.local/easybuild/ebfiles_repo
robot-paths    (D) = /opt/apps/software/EasyBuild/4.4.1/software/EasyBuild/4.4.1/easybuild/easyconfigs
sourcepath     (D) = /home/builduser/.local/easybuild/sources

**Comment by csayre** [comment]
Not sure if this helps or not but this is what I was told to run when installing a program.

eb {package name] -r --prefix=/opt/apps --sourcepath=/opt/apps/EB_Downloads --tmpdir=/opt/apps/tmp

**Comment by boegel** [comment]
Ah the latter probably explains the problem you're seeing: `--tmpdir=/opt/apps/tmp` is not a good idea, that should really be a local directory. Please try without specifying that option, and using the default instead (which will be `/tmp`, usually).

**Comment by csayre** [comment]
When removing the --tmpdir I now get the following error. 

```
== FAILED: Installation ended unsuccessfully (build directory: /opt/apps/build/Bazel/3.7.1/GCCcore-8.3.0): build failed (first 300 chars): Failed to remove directory /opt/apps/build/Bazel/3.7.1/GCCcore-8.3.0 even after 3 attempts.
Reasons: [OSError(39, 'Directory not empty'), OSError(16, 'Device or resource busy'), OSError(16, 'Device or resource busy')] (took 32 mins 29 secs)
== Results of the build can be found in the log file(s) /tmp/eb-4iMYYc/easybuild-Bazel-3.7.1-20210805.153602.hwjEx.log
ERROR: Build of /opt/apps/software/EasyBuild/4.4.1/software/EasyBuild/4.4.1/easybuild/easyconfigs/b/Bazel/Bazel-3.7.1-GCCcore-8.3.0.eb failed (err: "build failed (first 300 chars): Failed to remove directory /opt/apps/build/Bazel/3.7.1/GCCcore-8.3.0 even after 3 attempts.\nReasons: [OSError(39, 'Directory not empty'), OSError(16, 'Device or resource busy'), OSError(16, 'Device or resource busy')]")
```

**Comment by boegel** [comment]
That looks like a filesystem issue. Can you try removing `/opt/apps/build/Bazel/3.7.1/GCCcore-8.3.0` manually?

Maybe also check if any Bazel processes are still running from the previous installation attempt, that tends to happen with Bazel, and it may explain why the previous build directory can't be cleaned up...

**Comment by csayre** [comment]
Running `eb Bazel-3.7.1-GCCcore-8.3.0.eb  -r --prefix=/opt/apps --sourcepath=/opt/apps/EB_Downloads --buildpath /tmp/$USER/easybuild_build` has resolved this issue. Thank you so much for your help.
