### ISSUE TITLE
Yasm download link fails for Yasm-1.3.0-GCCcore-10.2.0.eb

### ISSUE THREAD

**Issue by dithwick** [easybuilders/easybuild-easyconfigs#13637]
Hi,

The yasm download link is now failing 

```
FAILED: Installation ended unsuccessfully (build directory: /tmp/easybuild/Yasm/1.3.0/GCCcore-10.2.0): build failed (first 300 chars): Unexpected error occurred when trying to download https://www.tortall.net/projects/yasm/release
s/yasm-1.3.0.tar.gz to {path}/easybuild/sources/y/Yasm/yasm-1.3.0.tar.gz: hostname 'www.tortall.net' doesn't match either of 'tortall.com', 'tortall.net', 'tortall.org' (took 0 secs)
```

The web site now seems to be http://yasm.tortall.net/ however if I submit that change (which I'm happy to do), won't it fail the easyconfig style check as it's an http rather than https web site? The source is also available from github (https://github.com/yasm/yasm/) but that obviously doesn't resolve the home page issue. What's the best solution?

Thanks

**Comment by dithwick** [comment]
Now I'm confused, I think easybuild maybe failing because the certificate has expired. I can still download from

https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz

in a browser.

**Comment by branfosj** [comment]
The style check should only fail if the url uses http but the https version works.

Having said that, it seems sensible to switch to downloading from GitHub - https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-1.3.0.tar.gz has the same sha256sum as the one from the Yasm website.

**Comment by dithwick** [comment]
Thanks, that makes sense. I'll do that and submit the updated easyconfig.
