### ISSUE TITLE
cannot fetch files 

### ISSUE THREAD

**Issue by aahamid** [easybuilders/easybuild-easyconfigs#13657]
this is my easyconfig file

      easyblock = 'PythonPackage'
      
      name = 'SPARQLWrapper'
      version = '1.8.5'
      versionsuffix = '-Python-%(pyver)s'
      
      homepage = 'https://rdflib.dev/sparqlwrapper/'
      description = """This is a wrapper around a SPARQL service. It helps in creating the query URI and, possibly, convert the result into a more manageable format. """
      
      toolchain = {'name': 'fosscuda', 'version': '2020b'}
      
      source_urls = [PYPI_LOWER_SOURCE]
      sources = ['%(name)s-%(version)s.tar.gz']
      checksums = ['d6a66b5b8cda141660e07aeb00472db077a98d22cb588c973209c7336850fb3c']
      
      
      dependencies = [
          ('Python', '3.8.6'),
          
      ]
      unpack_sources = False
      
      exts_defaultclass = 'PythonPackage'
      
      exts_list = [
        
          ('rdflib', '5.0.0', {
             'source_urls': ['https://pypi.python.org/packages/source/r/rdflib/'],
             'checksums': ['78149dd49d385efec3b3adfbd61c87afaf1281c30d3fcaf1b323b34f603fb155'],
          }),
          ('isodate', '0.6.0', {
              'source_tmpl': ['isodate-0.6.0-py2.py3-none-any.whl'],
              'checksums': ['2e364a3d5759479cdb2d37cce6b9376ea504db2ff90252a2e5b7cc89cc9ff2d8'],
          }),
           ('six', '1.16.0', {
              'source_tmpl': ['six-1.16.0-py2.py3-none-any.whl'],
              'checksums': ['e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11'],
          }),
           ('pyparsing', '2.4.7', {
              'source_tmpl': ['pyparsing-2.4.7-py2.py3-none-any.whl'],
              'checksums': ['488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d'],
          }),
      
      ]
      
      download_dep_fail = True
      use_pip = True
      sanity_pip_check = True
      
      moduleclass = 'data'
      

when I write 

eb filename.en -r  i got this error 

== Temporary log file in case of crash /tmp/eb-m857cogh/easybuild-d8kd33nc.log
== found valid index for /shared/software/EasyBuild/4.4.0/easybuild/easyconfigs, so using it...
== found valid index for /shared/software/EasyBuild/4.4.0/easybuild/easyconfigs, so using it...
== resolving dependencies ...
== processing EasyBuild easyconfig /home/ebadmin/Culture_project_apps/ahmed/SPARQLWrapper-1.8.5-fosscuda-2020b-Python-3.8.6.eb
== building and installing SPARQLWrapper/1.8.5-fosscuda-2020b-Python-3.8.6...
== fetching files...
ERROR: Traceback (most recent call last):
  File "/shared/software/EasyBuild/4.4.0/lib/python3.6/site-packages/easybuild/main.py", line 117, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/shared/software/EasyBuild/4.4.0/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3633, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/shared/software/EasyBuild/4.4.0/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3531, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/shared/software/EasyBuild/4.4.0/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3386, in run_step
    step_method(self)()
  File "/shared/software/EasyBuild/4.4.0/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 1951, in fetch_step
    self.exts = self.fetch_extension_sources(skip_checksums=skip_checksums)
  File "/shared/software/EasyBuild/4.4.0/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 594, in fetch_extension_sources
    force_download=force_download)
  File "/shared/software/EasyBuild/4.4.0/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 678, in obtain_file
    if re.match(r"^(https?|ftp)://", filename):
  File "/usr/lib64/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

I really don't know why !!!

**Comment by boegel** [comment]
@aahamid You should replace this:

```python
    'source_tmpl': ['pyparsing-2.4.7-py2.py3-none-any.whl'],
```

with:

```python
    'source_tmpl': 'pyparsing-2.4.7-py2.py3-none-any.whl',
```

The value for `source_tmpl` must be a string (not a list of string values like `[...]`).

You can also use `sources` rather than `source_tmpl` instead:

```python
    'sources': ['pyparsing-2.4.7-py2.py3-none-any.whl'],
```

That'll work assuming the EasyBuild version you're using is recent enough.

Note that you need to do this for every entry in `exts_list`.

It's clear that we should include an extra check to ensure that `source_tmpl` is indeed a string value, rather than continuing under the assumption that it is, since the error reporting is not exactly great here...

**Comment by boegel** [comment]
I've implemented a small change in https://github.com/easybuilders/easybuild-framework/pull/3799 that will produce a clearer error message when the `source_tmpl` value is not a string, which will be included in the upcoming EasyBuild release (probably version 4.2.2) so I'll go ahead and close this...
