### ISSUE TITLE
OpenMPI does not build on machine with six cores

### ISSUE THREAD

**Issue by schiotz** [easybuilders/easybuild-easyconfigs#13945]
Hi,

Building OpenMPI/4.0.5-GCC-10.2.0 fails on a desktop with 6 cores and hyperthreading, because the sanity check attempts to run with 8 tasks, and mpiexec refuses to run with more tasks than there are physical cpus.  The error is "Not enough slots to satisfy the 8 slots that were requested."

Maybe the test suite should be run with an option to allow oversubscribing the cpu cores?

CC: @matthewhelmi

**Comment by branfosj** [comment]
I think building with `--parallel 6` will solve this issue.

More generally, we may want to reduce the `8` at https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/o/openmpi.py#L182 to be `6` (or `4`).

**Comment by boegel** [comment]
This should be fixed now, thanks to the tweak in the OpenMPI easyblock that was implemented in https://github.com/easybuilders/easybuild-easyblocks/pull/2611...
