### ISSUE TITLE
Biopython/1.78 may not be a perfect match for AlphaFold 2.0

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyconfigs#13953]
Got this warning in the output when running the T1050 full_db test case:
```
/hpc2n/eb/software/Biopython/1.78-foss-2020b/lib/python3.8/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 12192
```

We might have to check which version is really required and add it as an extension to AlphaFold itself.

**Comment by boegel** [comment]
https://github.com/deepmind/alphafold/blob/v2.0.0/requirements.txt specifies Biopython 1.79, can you check if that warning still pops up with that version?

**Comment by akesandgren** [comment]
I'll check

**Comment by akesandgren** [comment]
Nah, still the same:
```
/home/a/ake/Public/easybuild/software/Biopython/1.79-foss-2020b/lib/python3.8/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 12192
```
