### ISSUE TITLE
AlphaFold-2.0.0-fosscuda-2020b.eb fails with a CMake error if libcuda.so is not found

### ISSUE THREAD

**Issue by patoddh** [easybuilders/easybuild-easyconfigs#13968]
The OpenMM component of AlphaFold fails with:

`== installing bundle component OpenMM v7.5.1 (1/2)...
== ... (took 7 secs)
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/AlphaFold/2.0.0/fosscuda-2020b): build failed (first 300 chars): cmd " cmake -DCMAKE_INSTALL_PREFIX=/grid/it/data/elzar/easybuild/software/AlphaFold/2.0.0-fosscuda-2020b -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER='gcc' -DCMAKE_C_FLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_CXX_FLAGS='-O2 -ftree-vectorize -march= (took 23 secs)`

The log file shows this:

````
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "OpenMMCUDA" in directory /dev/shm/AlphaFold/2.0.0/fosscuda-2020b/openmm-7.5.1/platforms/cuda/sharedTarget

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_Fortran_COMPILER
    CMAKE_Fortran_FLAGS
CMake Generate step failed.  Build files cannot be regenerated correctly.
````

The easybuild-OpenMM-7.5.1-*.log file shows this:

````
CMake Warning (dev) at CMakeLists.txt:329 (FIND_PACKAGE):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

Environment variable CUDA_ROOT is set to:

    /grid/it/data/elzar/easybuild/software/CUDAcore/11.1.1

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.
````

**Comment by patoddh** [comment]
This occurs when libcuda.so cannot be found. A standard installation of the CUDA driver puts it in /usr/lib64.

If CUDA is installed into a non-standard location, the issue can be solved by putting the path to libcuda.so into LD_LIBRARY_PATH. On clusters managed by Bright, there may be multiple CUDA installations, accessible via "module load" commands. For example: `module load cuda11.2/toolkit `

**Comment by boegel** [comment]
@patoddh  Thanks a lot for the detailed report and sharing the solution!
