### ISSUE TITLE
ROOT builds seem to need to unset CPATH to avoid LLVM collisions

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-easyconfigs#13986]
We have been struggling to build recent versions of ROOT against both old (foss-2018b) and new (foss-2020b) toolchains.  The fatal errors are different in different cases, but everywhere they seem to revolve around collisions between ROOT's "builtin_llvm" subset and the LLVM module that gets loaded with Mesa as a dependence in the EB file.

With help from the ROOT developers, I managed to work around the collisions with
```
prebuildopts = "unset CPATH && "        # Avoid LLVM module collision in include search
preinstallopts = "unset CPATH && "      # ROOT does substantial building at the install stage
```

For my own convenience, I modified a local copy of root.py to do this for all of our EB files consistently.  Is it reasonable to add this to the repository?  Is it overkill, or maybe a problem specific to our local HPC installation?

**Comment by akesandgren** [comment]
Doing unset CPATH causes the build to fail since it can't find all include files then (like X11/Xlib.h), at least for me.
Unfortunately ROOT 6.20 requires LLVM v5.0.x so setting -Dbuiltin_llvm=OFF won't work.

No clear solution here at the moment.

**Comment by kelseymh** [comment]
We have our own ROOT EasyBuild files at the moment, in order to get the Python versions we want (I'd rather have a whole EB file than to use the "--try" modifications; it let's me keep track of what I'm doing).

For foss/2020b, we have ROOT-6.18.02-foss-2020b-Python-3.8.6.eb and ROOT-6.24.00-foss-2020b-Python-3.8.6.eb.  For ROOT-6.18.02, we have a patch file ROOT-6.18_davix_url.patch.

It definitely took us a lot of effort to get these things to finally build.

**Comment by akesandgren** [comment]
Please upload your root.py and 2020b easyconfigs to gist or something.

**Comment by kelseymh** [comment]
Well, my first Gist...

https://gist.github.com/kelseymh/cdb84499e56c71b40f50cf9fb5c63be9

It says "(Secret)", but I thought that I had created a "public gist."  If it doesn't work, please let me know.  Also, sorry for the time-zone lag...

**Comment by akesandgren** [comment]
I think I have a somewhat more correct way of solving this, just doing some double testing and then I'll make a PR for an updated root.py

**Comment by kelseymh** [comment]
Sounds great; thank you!

**Comment by akesandgren** [comment]
Acutally this is already solved in the current root.py as far back as EB 4.3.3 at least.

Which EB release are you using?

**Comment by kelseymh** [comment]
Hah.  We use whatever the latest EB is that the Texas A&M HPRC folks have installed.  They are pretty good about updating as soon as there's a new release, so I guess we're on 4.5.1 or whatever.

But that doesn't mean we clean up our local directory of easyconfigs and easyblocks as EB moves forward :-/  My guess is that I wrote that root.py file at least a year ago, maybe close to two years.  It was last modified back in September.

If it's been fixed in EB, I'll mark this issue closed; sorry for the trouble!
