### ISSUE TITLE
Source url no longer working for Trilinos-12.12.1-foss-2019b-Python-3.7.4.eb

### ISSUE THREAD

**Issue by dithwick** [easybuilders/easybuild-easyconfigs#14066]
Hi,

It looks like https://trilinos.org/oldsite/download/files/ is no longer working as a download location for Trilinos. Given the comments at https://github.com/trilinos/Trilinos/issues/3447 and https://github.com/easybuilders/easybuild-easyconfigs/pull/7197 noting that the github releases aren't the same as the original source package, I had a hunt around and found:

https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/trilinos/12.12.1-5/trilinos_12.12.1.orig.tar.bz2

which seems to be building (so far). Is it worth submitting an updated PR with this source address or should this be fixed via another route?

Thanks

**Comment by branfosj** [comment]
I unpacked `trilinos_12.12.1.orig.tar.bz2` (from the above link) as `trilinos_12.12.1_orig_tar_bz2` and `trilinos-12.12.1-Source.tar.gz` (that I already had) as `trilinos-12.12.1-Source_tar_gz` and they are the same:
```
$ diff -r trilinos-12.12.1-Source_tar_gz trilinos_12.12.1_orig_tar_bz2
diff: trilinos-12.12.1-Source_tar_gz/cmake/tribits/doc/developers_guide/TribitsBuildReference.html: No such file or directory
diff: trilinos_12.12.1_orig_tar_bz2/cmake/tribits/doc/developers_guide/TribitsBuildReference.html: No such file or directory
```

**Comment by dithwick** [comment]
Unfortunately it doesn't look like I can directly suggest the code changes for the new source to PR #14547.

**Comment by branfosj** [comment]
Changed in 9816700 (for `Trilinos-12.12.1-foss-2019b-Python-3.7.4.eb`)

**Comment by lexming** [comment]
There is a tagged release for v12.12.1 in their github repository at https://github.com/trilinos/Trilinos/archive/refs/tags/trilinos-release-12-12-1.tar.gz

It does not seem to be a drop-in replacement for the original tarball (I see a few packages missing), but it might be the path to follow moving forward. There are even new revisions for v12 in their repo.

**Comment by dithwick** [comment]
I think the later releases are fine to get from https://github.com/trilinos/Trilinos/releases, it's just v12 that's incomplete (pretty certain it failed when I tried it but that was a few months ago).

**Comment by branfosj** [comment]
I've set off a test build using that and I'll report back later as to how it goes.

**Comment by branfosj** [comment]
Well that went wrong very early on:
```
== 2021-12-17 09:43:16,308 easyblock.py:3709 INFO Running method patch_step part of step patch
== 2021-12-17 09:43:16,308 easyblock.py:2411 INFO Applying patch Trilinos-12.12.1_fix-CEpetra-LAPACK.patch
== 2021-12-17 09:43:17,206 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Can't patch directory /dev/shm/build-branfosj-admin/branfosj-admin-up/Trilinos/12.12.1/foss-2019b-Python-3.7.4/Trilinos-trilinos-release-12-12-1/packages/CTrilinos: no such directory (at easybuild/tools/filetools.py:1539 in apply_patch)
```

**Comment by branfosj** [comment]
OK, build finally finished. I removed `Trilinos-12.12.1_fix-CEpetra-LAPACK.patch` and `Trilinos-12.12.1_fix-Sundance.patch` as neither apply. The build fails in the sanity check: `lib/libmesquite.so` and `lib/libmoocho.so` are missing.

So, https://github.com/trilinos/Trilinos/archive/refs/tags/trilinos-release-12-12-1.tar.gz produces a different build. I think we should go with https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/trilinos/12.12.1-5/trilinos_12.12.1.orig.tar.bz2 as that has the same contents.

**Comment by lexming** [comment]
Ok to use the tarball from Ubuntu then :+1: 

Moving forward, we can stick to the releases from Trilinos github repo. Missing packages from the original sources seem to just be moved to their own repos. For instance, [CTrilinos](https://github.com/trilinos/CTrilinos) or [Sundance](https://github.com/trilinos/Sundance). So it would be a mater of adding those as extra sources or extensions of the easyconfig.
