### ISSUE TITLE
Directory prerequisites for most recent RStudio Server versions

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#14117]
With recent versions of `RStudio Server`, there is a default requirement for a directory at `/var/lib/rstudio-server`, where amongst other items an SQLite database is stored.

Without it, this is the error:
```
 rserver --verify-installation 1 --server-data-dir=/tmp
10 Oct 2021 18:34:46 [rserver] ERROR system error 13 (Permission denied) [path: /var/lib/rstudio-server, target-dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) const src/cpp/shared_core/FilePath.cpp:812; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:694
```

What I haven't tested yet is whether environment variables (cf. https://github.com/rstudio/rstudio/blob/v1.4.1103/NEWS.md#configurable-paths) allow a way around this.

**Comment by branfosj** [comment]
Create a file `database.conf`, with contents:
```
provider=sqlite
directory=/tmp/random
```
(changing `/tmp/random` to a per-user, per instance directory)

Then run the `rserver` command with `--database-config-file=/path/to/database.conf`.

I'm testing with 2021.09.0+351 where I also have to specify `--server-user`. I've not tested whether this also works for the 1.4.1103 version.

**Comment by verdurin** [comment]
Nice, that way we don't need to patch the code, if it works for the released version.

How do you suggest we proceed with the easyconfig - add a comment about the need for this workaround?

**Comment by branfosj** [comment]
See #14275, which restores the sanity check and adds a comment about it.
