### ISSUE TITLE
R-bundle-Bioconductor 3.13 easyconfig bug

### ISSUE THREAD

**Issue by Ghepardo** [easybuilders/easybuild-easyconfigs#14127]
When I tried to build R-bundle-Bioconductor 3.13, this failed because it could not find the library KEGG.db.  This library is specified as an extension in the easyconfig file, but it does not exist in any of the sources specified.  It does, however, exist (at the same library version) in the Bioconductor 3.12 repository.  

I have worked around this by adding the following line to my source_urls array, following the equivalent 3.13 line:

`'https://bioconductor.org/packages/3.12/data/annotation/src/contrib/',`

I wonder how this easyconfig made it through the QA process?  Perhaps that library did once exist for Bioconductor 3.13 but was removed?  

I have to say that it seems little crazy trying to maintain the installation of 330 independent libraries as part of the core Bioconductor installation.

**Comment by boegel** [comment]
@Ghepardo This problem was fixed in #14013, but the latest EasyBuild release doesn't include this change yet (the next one will).

The problem went undetected because the `KEGG.db` sources were already downloaded (through earlier easyconfigs for Bionconductor).

**Comment by Ghepardo** [comment]
Thanks @boegel .  I guess the automated tests should make a point of clearing out their 'sources' directory tree before each run, otherwise we could run into this kind of issue again...
