### ISSUE TITLE
bcl2fastq2 fails during configuring, picks up system Boost

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-easyconfigs#14149]
I tried to build `bcl2fastq2-2.20.0-GCC-10.3.0.eb` but it failed during the configuration step:

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_chrono"
  (requested version 1.71.0) with any of the following names:

    boost_chronoConfig.cmake
    boost_chrono-config.cmake

  Add the installation prefix of "boost_chrono" to CMAKE_PREFIX_PATH or set
  "boost_chrono_DIR" to a directory containing one of the above files.  If
  "boost_chrono" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /mnt/software/easybuild/20.04/software/CMake/3.20.1-GCCcore-10.3.0/share/cmake-3.20/Modules/FindBoost.cmake:594 (fin
d_package)
  cmake/boost.cmake:85 (find_package)
  cmake/cxxConfigure.cmake:88 (bcl2fastq_find_boost)
  cxx/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
```

It should use the included Boost (1.54) but it picks up the Boost from the system (1.71, Ubuntu 18.04). The patch `bcl2fastq2-2.20.0-find-boost.patch` should take care of it but it seems like that's not enough, allthough it uses the included Boost for something as the log shows this beforehand:

```
-- Boost 1.54.0 not found. Boost will be built from the distribution...
Decompressing /dev/shm/bcl2fastq2/2.20.0/GCC-10.3.0/bcl2fastq/src/../redist/boost_1_54_0.tar.bz2
```

**Comment by akesandgren** [comment]
bcl2fastq2-2.20.0-GCC-10.3.0.eb doesn't have a dependency on Boost in the distributed version.
Have you changed that locally? If so why not use the Boost version that is the official one for GCC/10.3.0, i.e. Boost/1.76.0

Or do you explicitly want it to use the once included with bcl2fastq source?

**Comment by SethosII** [comment]
@akesandgren Yes, it should be the included version. bcl2fastq is not compatible with recent Boost versions so it should be built with the version provided in the source of bcl2fastq. There is the [`find-boost.patch`](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-find-boost.patch) that should take care of it, but it seems to be not enough.

**Comment by akesandgren** [comment]
This is caused by a change in CMake versions newer than what bcl2fastaq was designed for.
The easy (and correct) fix is to add this
```
configopts += '-DBoost_NO_BOOST_CMAKE=ON '

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso
