### ISSUE TITLE
R goolf easyconfig is not using OpenBLAS lapack

### ISSUE THREAD

**Issue by pescobar** [easybuilders/easybuild-easyconfigs#1435]
When I compile R easyconfig with this options:

```
preconfigopts = 'BLAS_LIBS="$LIBBLAS" LAPACK_LIBS="$LIBLAPACK"'
```

I get this in the ./configure output  (OpenBLAS lapack is not used)

```
External libraries:        readline, BLAS(OpenBLAS), LAPACK(generic), lzma
```

When I change the preconfigopts to this:

```
preconfigopts = 'BLAS_LIBS="$LIBBLAS" '
```

OpenBLAS lapack is found (this is the output of ./configure)

```
External libraries:        readline, BLAS(OpenBLAS), LAPACK(in blas), lzma
```

**Comment by wpoely86** [comment]
that makes no sense. Can you post the `config.log`?

**Comment by boegel** [comment]
well, it may make sense... if you specify it what to do, it will not try to fall back on checking the BLAS setup

apparently `$LIBLAPACK` is wrong/incomplete (in some way, for R specifically)

**Comment by pescobar** [comment]
build log for the easyconfig now provided in easybuild:
https://gist.github.com/2ea318d5dc92a0c1350d

build log for the modified easyconfig (preconfigopts = 'BLAS_LIBS="$LIBBLAS" ')
https://gist.github.com/77e3bae86237871780c1

**Comment by pescobar** [comment]
config.log for the easyconfig now provided in easybuild
https://gist.github.com/d16123039211903a5fb5

config.log for the modified easyconfig
https://gist.github.com/9529abfaf1c5317eae32

**Comment by wpoely86** [comment]
I can't find anything in these logs indicating why it does something different...

**Comment by pescobar** [comment]
I have also noticed that my R build using ictce toolchain doesn't use the MKL BLAS

```
  External libraries:        readline, BLAS(generic), LAPACK(generic)
```

**Comment by boegel** [comment]
@pescobar is this the problem you mentioned during this week's conf call? Any idea on how to fix it?

**Comment by boegel** [comment]
Same problem is being reported for `foss` toolchain in #4773.

For an updated R easyconfig using `intel/2017b` (cfr. #5360), I'm seeing this:

```
External libraries:        readline, BLAS(MKL), LAPACK(generic), curl
```

So the same problem seems to apply here: Intel MKL is being used for BLAS, but not for LAPACK.

We should probably handle this correctly, with a check, in the `EB_R` easyblock, and clean up the easyconfigs not to specify `--with-blas` or `--with-lapack`...

**Comment by boegel** [comment]
Check implemented in https://github.com/easybuilders/easybuild-easyblocks/pull/1292 that will spit out a warning if `BLAS(generic)` or `LAPACK(generic)` is found in the configure output.

R easyblock now correctly configures BLAS/LAPACK support (i.e. only specfies `$BLAS_LIBS`), but R easyconfigs will need to be cleaned up accordingly...

**Comment by boegel** [comment]
Considering this to be fixed via https://github.com/easybuilders/easybuild-easyblocks/pull/1292
