### ISSUE TITLE
replace pkg-config with pkgconf

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#14390]
`pkg-config` has been stuck at 0.29.2 since a long time, but apparently there's a compatible actively maintained replacement: [pkgconf](https://github.com/pkgconf/pkgconf), we should look into migrating to it...

**Comment by boegel** [comment]
See also https://www.mail-archive.com/gentoo-dev@lists.gentoo.org/msg93072.html and https://fedoraproject.org/wiki/Changes/pkgconf_as_system_pkg-config_implementation

**Comment by Micket** [comment]
We have done this.
