### ISSUE TITLE
Tcl-8.6.11-GCCcore-10.3.0.eb fails checksum

### ISSUE THREAD

**Issue by sjpb** [easybuilders/easybuild-easyconfigs#14515]
This is an incomplete report but installing `Tcl-8.6.11-GCCcore-10.3.0.eb` fails due to a checksum error. I tried

```
$ eb --ignore-checksums --robot Tcl-8.6.11-GCCcore-10.3.0.eb
<snip>
 unexpected end of file\ntar: Child returned status 1\ntar: Error is not recoverable: exiting now\n')
<snip
```

will update with full info when I can.

**Comment by branfosj** [comment]
It looks like the `tcl8.6.11-src.tar.gz` file is broken, which is causing the checksum failure and the `unexpected end of file` error when running with `--ignore-checksums`. Can you try deleting the downloaded file and getting it to redownload?

**Comment by sjpb** [comment]
Ah thanks, didn't realise just trying `eb ...` again wouldn't re-download in that case.

**Comment by boegel** [comment]
Just to be complete: you can force EasyBuild to re-download with `eb --force-download`
