### ISSUE TITLE
Mistake in GPAW-20.1.0-Add-Easybuild-configuration-files.patch

### ISSUE THREAD

**Issue by dithwick** [easybuilders/easybuild-easyconfigs#14598]
Hi,

We've spotted a mistake in GPAW-20.1.0-Add-Easybuild-configuration-files.patch which is only apparent if you are doing a foss build of GPAW and add ELPA. Line 27 of https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-Add-Easybuild-configuration-files.patch has:

`@@ -0,0 +1,49 @@
`

However this results in a truncated patch that ends at:

```
+    library_dirs.append(os.path.join(elpa, 'lib'))
+    extra_link_args += ['-Wl,-rpath={}/lib'.format(elpa)]
```

and doesn't add the modified include paths. There is a quick fix of changing the line to 

`@@ -0,0 +1,53 @@
`

and adjusting the checksum accordingly (worked for me) but wasn't sure if there's a quick way of updating the patch and the checksums in the easyconfig repo.

**Comment by boegel** [comment]
Looks like this slipped in with #11523, where the patch was manually edited by @surak...

**Comment by boegel** [comment]
@dithwick This problem is fixed in #14619

**Comment by surak** [comment]
sorry for that, it was what came out of "eb --inject-checksums"...

**Comment by boegel** [comment]
@surak It's the patch file itself that was broken, essentially.
