### ISSUE TITLE
update for openfoam2112

### ISSUE THREAD

**Issue by olesenm** [easybuilders/easybuild-easyconfigs#14604]
source packs are now starting to appear - website announcement should be live very soon:
https://sourceforge.net/projects/openfoam/files/v2112/OpenFOAM-v2112.tgz

I believe that the adjustments in easybuild should be as simple as copying the existing v2106 easyconfig and adjusting the checksum
```
version('2112', sha256='3e838731e79db1c288acc27aad8cc8a43d9dac1f24e5773e3b9fa91419a8c3f7')
```

**Comment by boegel** [comment]
@olesenm Does OpenFOAM v2112 support CGAL 5.x already, or is CGAL 4.x still a hard requirement?

**Comment by olesenm** [comment]
Now official: https://www.openfoam.com/news/main-news/openfoam-v2112

**Comment by boegel** [comment]
Easyconfig for OpenFOAM v2112 is available in #14636, requires #14635 (ParaView) to be merged first...

**Comment by boegel** [comment]
#14636 is merged, so closing this...

**Comment by olesenm** [comment]
Thanks
