### ISSUE TITLE
! LaTeX Error: File `ae.sty' not found.... in eb R-4.1.2-foss-2021b.eb

### ISSUE THREAD

**Issue by hy1001** [easybuilders/easybuild-easyconfigs#14614]
Hi EasyBuilders,

I am installing R-4.1.2-foss-2021b.eb from scratch and I am almost there!

Thank you very much for your support.

I got this error in eb R-4.1.2-foss-2021b.eb

```
...
! LaTeX Error: File `ae.sty' not found.
...
```

I think I am missing a simple sty file...

How would I fix this?

Thank you!

```
$ time eb  R-4.1.2-foss-2021b.eb
/PHShome/hp911/easybuild/software/EasyBuild/4.5.1/bin/eb: line 73: [: error: integer expression expected
/PHShome/hp911/easybuild/software/EasyBuild/4.5.1/bin/eb: line 76: [: error: integer expression expected
== Temporary log file in case of crash /tmp/eb-88Znc0/easybuild-YKEODi.log

WARNING: Deprecated functionality, will no longer work in v5.0: Support for Lmod version < 7.0.0 is deprecated, found version 6.5.1; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== resolving dependencies ...
== processing EasyBuild easyconfig /PHShome/hp911/easybuild/easybuild-easyconfigs/easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
== building and installing R/4.1.2-foss-2021b...
== fetching files...
== ... (took 20 secs)
== creating build dir, resetting environment...
== unpacking...
== ... (took 1 secs)
== patching...
== preparing...
== ... (took 21 secs)
== configuring...
== ... (took 2 mins 44 secs)
== building...
== ... (took 4 mins 43 secs)
== FAILED: Installation ended unsuccessfully (build directory: /tmp/hp911/R/4.1.2/foss-2021b): build failed (first 300 chars): cmd " make  -j 12 " exited with exit code 2 and output:
make[1]: Entering directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/m4'
make[1]: Nothing to be done for `R'.
make[1]: Leaving directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/m4'
make[1]: Entering directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2 (took 8 mins 20 secs)
== Results of the build can be found in the log file(s) /tmp/eb-88Znc0/easybuild-R-4.1.2-20211222.135811.MXsJL.log
ERROR: Build of /PHShome/hp911/easybuild/easybuild-easyconfigs/easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb failed (err: 'build failed (first 300 chars): cmd " make  -j 12 " exited with exit code 2 and output:\nmake[1]: Entering directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/m4\'\nmake[1]: Nothing to be done for `R\'.\nmake[1]: Leaving directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/m4\'\nmake[1]: Entering directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2')

real	8m26.988s
user	8m5.313s
sys	7m41.416s
```

in the log file...

```
make[1]: Leaving directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2'
make[2]: Entering directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/doc/manual'
creating doc/manual/R-FAQ.html
creating doc/manual/version.texi
creating doc/manual/R-admin.html
creating doc/manual/R-data.html
creating doc/manual/R-exts.html
creating doc/manual/R-intro.html
creating doc/manual/R-ints.html
creating doc/manual/R-lang.html
Error: compiling TeX file 'reshape.tex' failed with message:
Running 'texi2dvi' on 'reshape.tex' failed.
LaTeX errors:
! LaTeX Error: File `ae.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

! Emergency stop.
<read *> 
         
l.30 \ifthenelse
                {\boolean{Sweave@inconsolata}}{%^^M
!  ==> Fatal error occurred, no output PDF file produced!
Execution halted
make[1]: *** [vignettes] Error 1
make[1]: Leaving directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/src/library'
make: *** [vignettes] Error 2
make: *** Waiting for unfinished jobs....
make[3]: Entering directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/doc/html'
make[3]: Leaving directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/doc/html'
make[2]: Leaving directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/doc/manual'
make[1]: Leaving directory `/tmp/hp911/R/4.1.2/foss-2021b/R-4.1.2/doc'
```

**Comment by hy1001** [comment]
fyi...

$ time eb  -D R-4.1.2-foss-2021b.eb
/PHShome/hp911/easybuild/software/EasyBuild/4.5.1/bin/eb: line 73: [: error: integer expression expected
/PHShome/hp911/easybuild/software/EasyBuild/4.5.1/bin/eb: line 76: [: error: integer expression expected
== Temporary log file in case of crash /tmp/eb-1aXExt/easybuild-mGbiv6.log

WARNING: Deprecated functionality, will no longer work in v5.0: Support for Lmod version < 7.0.0 is deprecated, found version 6.5.1; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

Dry run: printing build status of easyconfigs and dependencies
CFGS=/PHShome/hp911/easybuild/easybuild-easyconfigs/easybuild/easyconfigs
 * [x] $CFGS/m/M4/M4-1.4.19.eb (module: M4/1.4.19)
 * [x] $CFGS/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [x] $CFGS/m/M4/M4-1.4.18.eb (module: M4/1.4.18)
 * [x] $CFGS/b/Bison/Bison-3.7.6.eb (module: Bison/3.7.6)
 * [x] $CFGS/b/Bison/Bison-3.5.3.eb (module: Bison/3.5.3)
 * [x] $CFGS/f/flex/flex-2.6.4.eb (module: flex/2.6.4)
 * [x] $CFGS/b/binutils/binutils-2.37.eb (module: binutils/2.37)
 * [x] $CFGS/g/GCCcore/GCCcore-11.2.0.eb (module: GCCcore/11.2.0)
 * [x] $CFGS/h/help2man/help2man-1.48.3-GCCcore-11.2.0.eb (module: help2man/1.48.3-GCCcore-11.2.0)
 * [x] $CFGS/m/M4/M4-1.4.19-GCCcore-11.2.0.eb (module: M4/1.4.19-GCCcore-11.2.0)
 * [x] $CFGS/z/zlib/zlib-1.2.11-GCCcore-11.2.0.eb (module: zlib/1.2.11-GCCcore-11.2.0)
 * [x] $CFGS/b/Bison/Bison-3.7.6-GCCcore-11.2.0.eb (module: Bison/3.7.6-GCCcore-11.2.0)
 * [x] $CFGS/f/flex/flex-2.6.4-GCCcore-11.2.0.eb (module: flex/2.6.4-GCCcore-11.2.0)
 * [x] $CFGS/b/binutils/binutils-2.37-GCCcore-11.2.0.eb (module: binutils/2.37-GCCcore-11.2.0)
 * [x] $CFGS/p/pixman/pixman-0.40.0-GCCcore-11.2.0.eb (module: pixman/0.40.0-GCCcore-11.2.0)
 * [x] $CFGS/b/bzip2/bzip2-1.0.8-GCCcore-11.2.0.eb (module: bzip2/1.0.8-GCCcore-11.2.0)
 * [x] $CFGS/l/libtool/libtool-2.4.6-GCCcore-11.2.0.eb (module: libtool/2.4.6-GCCcore-11.2.0)
 * [x] $CFGS/n/ncurses/ncurses-6.2-GCCcore-11.2.0.eb (module: ncurses/6.2-GCCcore-11.2.0)
 * [x] $CFGS/l/libpng/libpng-1.6.37-GCCcore-11.2.0.eb (module: libpng/1.6.37-GCCcore-11.2.0)
 * [x] $CFGS/g/groff/groff-1.22.4-GCCcore-11.2.0.eb (module: groff/1.22.4-GCCcore-11.2.0)
 * [x] $CFGS/e/expat/expat-2.4.1-GCCcore-11.2.0.eb (module: expat/2.4.1-GCCcore-11.2.0)
 * [x] $CFGS/g/gperf/gperf-3.1-GCCcore-11.2.0.eb (module: gperf/3.1-GCCcore-11.2.0)
 * [x] $CFGS/p/pkg-config/pkg-config-0.29.2-GCCcore-11.2.0.eb (module: pkg-config/0.29.2-GCCcore-11.2.0)
 * [x] $CFGS/u/UnZip/UnZip-6.0-GCCcore-11.2.0.eb (module: UnZip/6.0-GCCcore-11.2.0)
 * [x] $CFGS/l/libreadline/libreadline-8.1-GCCcore-11.2.0.eb (module: libreadline/8.1-GCCcore-11.2.0)
 * [x] $CFGS/p/PCRE2/PCRE2-10.37-GCCcore-11.2.0.eb (module: PCRE2/10.37-GCCcore-11.2.0)
 * [x] $CFGS/l/libffi/libffi-3.4.2-GCCcore-11.2.0.eb (module: libffi/3.4.2-GCCcore-11.2.0)
 * [x] $CFGS/u/util-linux/util-linux-2.37-GCCcore-11.2.0.eb (module: util-linux/2.37-GCCcore-11.2.0)
 * [x] $CFGS/t/Tcl/Tcl-8.6.11-GCCcore-11.2.0.eb (module: Tcl/8.6.11-GCCcore-11.2.0)
 * [x] $CFGS/n/ncurses/ncurses-6.2.eb (module: ncurses/6.2)
 * [x] $CFGS/s/SQLite/SQLite-3.36-GCCcore-11.2.0.eb (module: SQLite/3.36-GCCcore-11.2.0)
 * [x] $CFGS/g/gettext/gettext-0.21.eb (module: gettext/0.21)
 * [x] $CFGS/x/XZ/XZ-5.2.5-GCCcore-11.2.0.eb (module: XZ/5.2.5-GCCcore-11.2.0)
 * [x] $CFGS/l/libxml2/libxml2-2.9.10-GCCcore-11.2.0.eb (module: libxml2/2.9.10-GCCcore-11.2.0)
 * [x] $CFGS/l/libunwind/libunwind-1.5.0-GCCcore-11.2.0.eb (module: libunwind/1.5.0-GCCcore-11.2.0)
 * [x] $CFGS/g/gettext/gettext-0.21-GCCcore-11.2.0.eb (module: gettext/0.21-GCCcore-11.2.0)
 * [x] $CFGS/g/gzip/gzip-1.10-GCCcore-11.2.0.eb (module: gzip/1.10-GCCcore-11.2.0)
 * [x] $CFGS/p/PCRE/PCRE-8.45-GCCcore-11.2.0.eb (module: PCRE/8.45-GCCcore-11.2.0)
 * [x] $CFGS/p/pkg-config/pkg-config-0.29.2.eb (module: pkg-config/0.29.2)
 * [x] $CFGS/o/OpenSSL/OpenSSL-1.1.eb (module: OpenSSL/1.1)
 * [x] $CFGS/c/cURL/cURL-7.78.0-GCCcore-11.2.0.eb (module: cURL/7.78.0-GCCcore-11.2.0)
 * [x] $CFGS/l/libarchive/libarchive-3.5.1-GCCcore-11.2.0.eb (module: libarchive/3.5.1-GCCcore-11.2.0)
 * [x] $CFGS/p/Python/Python-3.9.6-GCCcore-11.2.0-bare.eb (module: Python/3.9.6-GCCcore-11.2.0-bare)
 * [x] $CFGS/c/CMake/CMake-3.21.1-GCCcore-11.2.0.eb (module: CMake/3.21.1-GCCcore-11.2.0)
 * [x] $CFGS/d/DB/DB-18.1.40-GCCcore-11.2.0.eb (module: DB/18.1.40-GCCcore-11.2.0)
 * [x] $CFGS/b/Brotli/Brotli-1.0.9-GCCcore-11.2.0.eb (module: Brotli/1.0.9-GCCcore-11.2.0)
 * [x] $CFGS/p/Perl/Perl-5.34.0-GCCcore-11.2.0.eb (module: Perl/5.34.0-GCCcore-11.2.0)
 * [x] $CFGS/r/Rust/Rust-1.54.0-GCCcore-11.2.0.eb (module: Rust/1.54.0-GCCcore-11.2.0)
 * [x] $CFGS/f/freetype/freetype-2.11.0-GCCcore-11.2.0.eb (module: freetype/2.11.0-GCCcore-11.2.0)
 * [x] $CFGS/a/Autoconf/Autoconf-2.71-GCCcore-11.2.0.eb (module: Autoconf/2.71-GCCcore-11.2.0)
 * [x] $CFGS/i/intltool/intltool-0.51.0-GCCcore-11.2.0.eb (module: intltool/0.51.0-GCCcore-11.2.0)
 * [x] $CFGS/a/Automake/Automake-1.16.4-GCCcore-11.2.0.eb (module: Automake/1.16.4-GCCcore-11.2.0)
 * [x] $CFGS/f/fontconfig/fontconfig-2.13.94-GCCcore-11.2.0.eb (module: fontconfig/2.13.94-GCCcore-11.2.0)
 * [x] $CFGS/a/Autotools/Autotools-20210726-GCCcore-11.2.0.eb (module: Autotools/20210726-GCCcore-11.2.0)
 * [x] $CFGS/g/GMP/GMP-6.2.1-GCCcore-11.2.0.eb (module: GMP/6.2.1-GCCcore-11.2.0)
 * [x] $CFGS/g/git/git-2.33.1-GCCcore-11.2.0-nodocs.eb (module: git/2.33.1-GCCcore-11.2.0-nodocs)
 * [x] $CFGS/x/xorg-macros/xorg-macros-1.19.3-GCCcore-11.2.0.eb (module: xorg-macros/1.19.3-GCCcore-11.2.0)
 * [x] $CFGS/l/libpciaccess/libpciaccess-0.16-GCCcore-11.2.0.eb (module: libpciaccess/0.16-GCCcore-11.2.0)
 * [x] $CFGS/n/nettle/nettle-3.7.3-GCCcore-11.2.0.eb (module: nettle/3.7.3-GCCcore-11.2.0)
 * [x] $CFGS/p/Python/Python-3.9.6-GCCcore-11.2.0.eb (module: Python/3.9.6-GCCcore-11.2.0)
 * [x] $CFGS/m/Mako/Mako-1.1.4-GCCcore-11.2.0.eb (module: Mako/1.1.4-GCCcore-11.2.0)
 * [x] $CFGS/n/Ninja/Ninja-1.10.2-GCCcore-11.2.0.eb (module: Ninja/1.10.2-GCCcore-11.2.0)
 * [x] $CFGS/m/Meson/Meson-0.58.2-GCCcore-11.2.0.eb (module: Meson/0.58.2-GCCcore-11.2.0)
 * [x] $CFGS/g/GLib/GLib-2.69.1-GCCcore-11.2.0.eb (module: GLib/2.69.1-GCCcore-11.2.0)
 * [x] $CFGS/x/X11/X11-20210802-GCCcore-11.2.0.eb (module: X11/20210802-GCCcore-11.2.0)
 * [x] $CFGS/l/libdrm/libdrm-2.4.107-GCCcore-11.2.0.eb (module: libdrm/2.4.107-GCCcore-11.2.0)
 * [x] $CFGS/c/cairo/cairo-1.16.0-GCCcore-11.2.0.eb (module: cairo/1.16.0-GCCcore-11.2.0)
 * [x] $CFGS/l/libglvnd/libglvnd-1.3.3-GCCcore-11.2.0.eb (module: libglvnd/1.3.3-GCCcore-11.2.0)
 * [x] $CFGS/l/LLVM/LLVM-12.0.1-GCCcore-11.2.0.eb (module: LLVM/12.0.1-GCCcore-11.2.0)
 * [x] $CFGS/l/lz4/lz4-1.9.3-GCCcore-11.2.0.eb (module: lz4/1.9.3-GCCcore-11.2.0)
 * [x] $CFGS/n/NASM/NASM-2.15.05-GCCcore-11.2.0.eb (module: NASM/2.15.05-GCCcore-11.2.0)
 * [x] $CFGS/z/zstd/zstd-1.5.0-GCCcore-11.2.0.eb (module: zstd/1.5.0-GCCcore-11.2.0)
 * [x] $CFGS/l/libjpeg-turbo/libjpeg-turbo-2.0.6-GCCcore-11.2.0.eb (module: libjpeg-turbo/2.0.6-GCCcore-11.2.0)
 * [x] $CFGS/m/Mesa/Mesa-21.1.7-GCCcore-11.2.0.eb (module: Mesa/21.1.7-GCCcore-11.2.0)
 * [x] $CFGS/l/libGLU/libGLU-9.0.2-GCCcore-11.2.0.eb (module: libGLU/9.0.2-GCCcore-11.2.0)
 * [x] $CFGS/x/Xvfb/Xvfb-1.20.13-GCCcore-11.2.0.eb (module: Xvfb/1.20.13-GCCcore-11.2.0)
 * [x] $CFGS/j/jbigkit/jbigkit-2.1-GCCcore-11.2.0.eb (module: jbigkit/2.1-GCCcore-11.2.0)
 * [x] $CFGS/l/LibTIFF/LibTIFF-4.3.0-GCCcore-11.2.0.eb (module: LibTIFF/4.3.0-GCCcore-11.2.0)
 * [x] $CFGS/t/Tk/Tk-8.6.11-GCCcore-11.2.0.eb (module: Tk/8.6.11-GCCcore-11.2.0)
 * [x] $CFGS/j/Java/Java-11.0.2.eb (module: Java/11.0.2)
 * [x] $CFGS/j/Java/Java-11.eb (module: Java/11)
 * [x] $CFGS/n/NLopt/NLopt-2.7.0-GCCcore-11.2.0.eb (module: NLopt/2.7.0-GCCcore-11.2.0)
 * [x] $CFGS/i/ICU/ICU-69.1-GCCcore-11.2.0.eb (module: ICU/69.1-GCCcore-11.2.0)
 * [x] $CFGS/g/GCC/GCC-11.2.0.eb (module: GCC/11.2.0)
 * [x] $CFGS/l/libogg/libogg-1.3.5-GCCcore-11.2.0.eb (module: libogg/1.3.5-GCCcore-11.2.0)
 * [x] $CFGS/f/FLAC/FLAC-1.3.3-GCCcore-11.2.0.eb (module: FLAC/1.3.3-GCCcore-11.2.0)
 * [x] $CFGS/l/libvorbis/libvorbis-1.3.7-GCCcore-11.2.0.eb (module: libvorbis/1.3.7-GCCcore-11.2.0)
 * [x] $CFGS/l/libsndfile/libsndfile-1.0.31-GCCcore-11.2.0.eb (module: libsndfile/1.0.31-GCCcore-11.2.0)
 * [x] $CFGS/u/UDUNITS/UDUNITS-2.2.28-GCCcore-11.2.0.eb (module: UDUNITS/2.2.28-GCCcore-11.2.0)
 * [x] $CFGS/s/Szip/Szip-2.1.1-GCCcore-11.2.0.eb (module: Szip/2.1.1-GCCcore-11.2.0)
 * [x] $CFGS/g/GSL/GSL-2.7-GCC-11.2.0.eb (module: GSL/2.7-GCC-11.2.0)
 * [x] $CFGS/l/libevent/libevent-2.1.12-GCCcore-11.2.0.eb (module: libevent/2.1.12-GCCcore-11.2.0)
 * [x] $CFGS/n/numactl/numactl-2.0.14-GCCcore-11.2.0.eb (module: numactl/2.0.14-GCCcore-11.2.0)
 * [x] $CFGS/h/hwloc/hwloc-2.5.0-GCCcore-11.2.0.eb (module: hwloc/2.5.0-GCCcore-11.2.0)
 * [x] $CFGS/u/UCX/UCX-1.11.2-GCCcore-11.2.0.eb (module: UCX/1.11.2-GCCcore-11.2.0)
 * [x] $CFGS/g/GLPK/GLPK-5.0-GCCcore-11.2.0.eb (module: GLPK/5.0-GCCcore-11.2.0)
 * [x] $CFGS/l/libfabric/libfabric-1.13.2-GCCcore-11.2.0.eb (module: libfabric/1.13.2-GCCcore-11.2.0)
 * [x] $CFGS/g/Ghostscript/Ghostscript-9.54.0-GCCcore-11.2.0.eb (module: Ghostscript/9.54.0-GCCcore-11.2.0)
 * [x] $CFGS/n/nodejs/nodejs-14.17.6-GCCcore-11.2.0.eb (module: nodejs/14.17.6-GCCcore-11.2.0)
 * [x] $CFGS/p/PMIx/PMIx-4.1.0-GCCcore-11.2.0.eb (module: PMIx/4.1.0-GCCcore-11.2.0)
 * [x] $CFGS/j/JasPer/JasPer-2.0.33-GCCcore-11.2.0.eb (module: JasPer/2.0.33-GCCcore-11.2.0)
 * [x] $CFGS/o/OpenMPI/OpenMPI-4.1.1-GCC-11.2.0.eb (module: OpenMPI/4.1.1-GCC-11.2.0)
 * [x] $CFGS/g/gompi/gompi-2021b.eb (module: gompi/2021b)
 * [x] $CFGS/h/HDF5/HDF5-1.12.1-gompi-2021b.eb (module: HDF5/1.12.1-gompi-2021b)
 * [x] $CFGS/f/FFTW/FFTW-3.3.10-gompi-2021b.eb (module: FFTW/3.3.10-gompi-2021b)
 * [x] $CFGS/l/LittleCMS/LittleCMS-2.12-GCCcore-11.2.0.eb (module: LittleCMS/2.12-GCCcore-11.2.0)
 * [x] $CFGS/i/ImageMagick/ImageMagick-7.1.0-4-GCCcore-11.2.0.eb (module: ImageMagick/7.1.0-4-GCCcore-11.2.0)
 * [x] $CFGS/m/MPFR/MPFR-4.1.0-GCCcore-11.2.0.eb (module: MPFR/4.1.0-GCCcore-11.2.0)
 * [x] $CFGS/l/libgit2/libgit2-1.1.1-GCCcore-11.2.0.eb (module: libgit2/1.1.1-GCCcore-11.2.0)
 * [x] $CFGS/g/GEOS/GEOS-3.9.1-GCC-11.2.0.eb (module: GEOS/3.9.1-GCC-11.2.0)
 * [x] $CFGS/p/PROJ/PROJ-8.1.0-GCCcore-11.2.0.eb (module: PROJ/8.1.0-GCCcore-11.2.0)
 * [x] $CFGS/l/libiconv/libiconv-1.16-GCCcore-11.2.0.eb (module: libiconv/1.16-GCCcore-11.2.0)
 * [x] $CFGS/d/Doxygen/Doxygen-1.9.1-GCCcore-11.2.0.eb (module: Doxygen/1.9.1-GCCcore-11.2.0)
 * [x] $CFGS/n/netCDF/netCDF-4.8.1-gompi-2021b.eb (module: netCDF/4.8.1-gompi-2021b)
 * [x] $CFGS/l/libgeotiff/libgeotiff-1.7.0-GCCcore-11.2.0.eb (module: libgeotiff/1.7.0-GCCcore-11.2.0)
 * [x] $CFGS/b/BLIS/BLIS-0.8.1-GCC-11.2.0.eb (module: BLIS/0.8.1-GCC-11.2.0)
 * [x] $CFGS/o/OpenBLAS/OpenBLAS-0.3.18-GCC-11.2.0.eb (module: OpenBLAS/0.3.18-GCC-11.2.0)
 * [x] $CFGS/h/hypothesis/hypothesis-6.14.6-GCCcore-11.2.0.eb (module: hypothesis/6.14.6-GCCcore-11.2.0)
 * [x] $CFGS/f/FlexiBLAS/FlexiBLAS-3.0.4-GCC-11.2.0.eb (module: FlexiBLAS/3.0.4-GCC-11.2.0)
 * [x] $CFGS/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2021b-fb.eb (module: ScaLAPACK/2.1.0-gompi-2021b-fb)
 * [x] $CFGS/f/foss/foss-2021b.eb (module: foss/2021b)
 * [x] $CFGS/l/libtirpc/libtirpc-1.3.2-GCCcore-11.2.0.eb (module: libtirpc/1.3.2-GCCcore-11.2.0)
 * [x] $CFGS/h/HDF/HDF-4.2.15-GCCcore-11.2.0.eb (module: HDF/4.2.15-GCCcore-11.2.0)
 * [x] $CFGS/e/Eigen/Eigen-3.3.9-GCCcore-11.2.0.eb (module: Eigen/3.3.9-GCCcore-11.2.0)
 * [x] $CFGS/p/pybind11/pybind11-2.7.1-GCCcore-11.2.0.eb (module: pybind11/2.7.1-GCCcore-11.2.0)
 * [x] $CFGS/s/SciPy-bundle/SciPy-bundle-2021.10-foss-2021b.eb (module: SciPy-bundle/2021.10-foss-2021b)
 * [x] $CFGS/g/GDAL/GDAL-3.3.2-foss-2021b.eb (module: GDAL/3.3.2-foss-2021b)
 * [ ] $CFGS/r/R/R-4.1.2-foss-2021b.eb (module: R/4.1.2-foss-2021b)
== Temporary log file(s) /tmp/eb-1aXExt/easybuild-mGbiv6.log* have been removed.
== Temporary directory /tmp/eb-1aXExt has been removed.

real	0m9.552s
user	0m6.152s
sys	0m2.539s

**Comment by bedroge** [comment]
Hi @hy1001,

I had a look at the log for my R 4.1.0 installation, and it contains the following:

```
make[2]: Entering directory `/dev/shm/bob/R/4.1.0/foss-2021a/R-4.1.0/doc/manual'
'texi2any' v5.1 or later needed to make HTML docs but missing on your system.
file R-FAQ.html will be missing and linked from CRAN
```

So, it seems the installation will try to build these docs if you have latex installed on your system, e.g. using your OS package manager, but skip the step if you don't have it (and I guess a lot of EB users don't have this installed on their build/cluster nodes). You do have it, but apparently something is missing. I think you would need this package to solve the issue with that missing `ae.sty`: https://www.ctan.org/pkg/ae. Or perhaps you could try to build it on a (compute) node which doesn't have latex installed?

**Comment by boegel** [comment]
@bedroge We should take control here, and figure out how to disable the build of the docs?

**Comment by bedroge** [comment]
@boegel That would definitely be nicer, indeed. I had a quick look at the options for `./configure`, but did not find a flag to disable this. The admin manual also has a section on these manual pages (https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Making-the-manuals), but I can't find a(n easy) way to disable it there either :-( 
So we probably have to do that in some other way...

**Comment by bedroge** [comment]
Well, maybe it's possible by using specific targets for the `make` command, let me give that a try...

**Comment by bedroge** [comment]
Couldn't really find a nice and clean way to do this (yet), but there may be a slightly more hackish way to work around it: the `configure` step looks for a `texi2any` executable, and if it does not find it, the generated `Makefile` will skip the step that creates the manuals (not entirely sure if this is the only step where latex is being used) and print the message shown in https://github.com/easybuilders/easybuild-easyconfigs/issues/14614#issuecomment-1000123064.

In your case, it probably did find the tool, but some Latex package(s) is/are missing. However, you can try to fool the `configure` step into believing that `texi2any` is not available by overriding `$TEXI2ANY` to something else before running the `configure` step, e.g. `export TEXI2ANY=/usr/bin/true`. So, as a quick workaround you could try changing [this](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb#L60) line in the easyconfig to
```
preconfigopts = 'export FLIBS="$FLIBS -lm" TEXI2ANY=/usr/bin/true && '
```
But we should probably find some cleaner way of doing this, for instance by patching the Makefile.

**Comment by hy1001** [comment]
Hello @boegel 

It worked. Thank you so much for your help!

**Comment by stamenminkov** [comment]
I know this has been closed for some, time but wanted to add my bit to the topic (and didn't find any other thread for the same). I've been facing this issue for quite some time on our clusters but found a way to do the installation by skipping docs and vignettes:

```
prebuildopts = r'sed -i -E "s/^all:.*/all: Makefile Makeconf R recommended javaconf/" %(start_dir)s/Makefile && '
prebuildopts += r'sed -i -E "s/^SUBDIRS = (.*)doc(.*)/SUBDIRS = \1\2/" %(start_dir)s/Makefile && '
```

Not sure if that's the cleanest way of handling it, but hey 😛
