### ISSUE TITLE
GLib version 2.69.1 compilation error

### ISSUE THREAD

**Issue by varun082021** [easybuilders/easybuild-easyconfigs#14689]
Hi Team, 

I'm trying to use FOSS 2021b for one of the application compilation and along with other dependencies, easybuild is trying to compile GLib 2.69.1 wth GCCcore-11.2.0 and which is showing below error messages and failing.

I request your help to address this issue and let me know, if there are any work arounds.

```
/home/user1/easybuild/build/GLib/2.69.1/GCCcore-11.2.0/easybuild_obj/gio/glib-compile-resources: symbol lookup error: /home/user1/easybuild/build/GLib/2.69.1/GCCcore-11.2.0/easybuild_obj/gio/../gobject/libgobject-2.0.so.0: undefined symbol: g_pattern_spec_copy
[773/1235] Generating test_resources2.c with a custom command
FAILED: gio/tests/test_resources2.c
```

**Comment by boegel** [comment]
@varun082021 We'll need some additional background, this problem is new to us (to my knowledge)...

Can you please share the output of the following commands, so we have some more context?

* `eb --version`
* `eb --show-config`
* `eb --show-system-info`

In addition, would it be possible to share the full EasyBuild log file for this failing installation, for example by creating a gist (see https://gist.github.com/)?

**Comment by varun082021** [comment]
@boegel Hi Kenneth, Please find the below additional details and log file also available in gist. Please let me know, if you need more details.

gist url is https://gist.github.com/7af8af3f4a3acbeeca88b0810a7ca289.git

$ eb --version
This is EasyBuild 4.5.1 (framework: 4.5.1, easyblocks: 4.5.1) on host hostname.

$ eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (D) = /home/dell_emc/.local/easybuild/build
containerpath  (D) = /home/dell_emc/.local/easybuild/containers
installpath    (D) = /home/dell_emc/.local/easybuild
repositorypath (D) = /home/dell_emc/.local/easybuild/ebfiles_repo
robot-paths    (D) = /home/dell_emc/easybuild/software/EasyBuild/4.5.1/easybuild/easyconfigs
sourcepath     (D) = /home/dell_emc/.local/easybuild/sources

$ eb --show-system-info
System information (hostname):

* OS:
  -> name: RHEL
  -> type: Linux
  -> version: 7.2
  -> platform name: x86_64-unknown-linux

* CPU:
  -> vendor: Intel
  -> architecture: x86_64
  -> family: Intel
  -> arch name: UNKNOWN (archspec is not installed?)
  -> model: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
  -> speed: 3500.0
  -> cores: 28
  -> features: 3dnowprefetch,abm,acpi,adx,aes,aperfmperf,apic,arat,arch_perfmon,avx,avx2,bmi1,bmi2,bts,clflush,cmov,constant_tsc,cqm,cqm_llc,cqm_occup_llc,cx16,cx8,dca,de,ds_cpl,dtes64,dtherm,dts,eagerfpu,epb,ept,erms,est,f16c,flexpriority,fma,fpu,fsgsbase,fxsr,hle,ht,ida,invpcid,lahf_lm,lm,mca,mce,mmx,monitor,movbe,msr,mtrr,nonstop_tsc,nopl,nx,pae,pat,pbe,pcid,pclmulqdq,pdcm,pdpe1gb,pebs,pge,pln,pni,popcnt,pse,pse36,pts,rdrand,rdseed,rdtscp,rep_good,rtm,sep,smap,smep,smx,ss,sse,sse2,sse4_1,sse4_2,ssse3,syscall,tm,tm2,tpr_shadow,tsc,tsc_adjust,tsc_deadline_timer,vme,vmx,vnmi,vpid,x2apic,xsave,xsaveopt,xtopology,xtpr

* software:
  -> glibc version: 2.17
  -> Python binary: /bin/python
  -> Python version: 2.7.5
[dell_emc@uaeuhpclgn01 ~]$

**Comment by akesandgren** [comment]
That g_pattern_spec_copy should come from libglib-2.0.so.
Is it there in the, hopefully built, libglib-2.0.so in that build tree?

Are you using RPATH?

**Comment by Micket** [comment]
I would also check if there are some evil devel packages installed on the host, causing system level gobject/glib stuff being picked up

**Comment by akesandgren** [comment]
AH yes, forgot about that....

**Comment by varun082021** [comment]
> I would also check if there are some evil devel packages installed on the host, causing system level gobject/glib stuff being picked up

Thanks for highlighting this. There was a libglib in one of the custom LD_LIBRARY_PATH. After removing that path, now the GLIB 2.69.1 compilation is completed successfully. Thanks for your support.

**Comment by akesandgren** [comment]
If you're satisfied with the conclusion please close the case.
