### ISSUE TITLE
zlib-devel absent in OS => boost fails to build !!!

### ISSUE THREAD

**Issue by malcook** [easybuilders/easybuild-easyconfigs#1475]
In a fresh install of CentOS7 having NONE of zlib not zlib-deve and zlib1g-devl installed

My first eb:

 `eb BWA-0.7.5a-goolf-1.4.10.eb  --modules-tool=Lmod -r  --try-toolchain=goolf,1.7.20 --try-software-version=0.7.12`

fails, since the entailed `Boost-1.51.0-goolf-1.4.10-Python-2.7.3.eb`  has `osdependencies = [('zlib-devel','zlib1g-dev')]` which are not met.

If I first `yum install zlib zlib-devel` then BWA installs fine along with the toolchain and deps.

But, reading around other issues and it sounds like we don't want OS version of zlib or zlib-devel.... it just creates other problems.  Or am I misunderstanding the concern/issues?

Perhaps zlib-devel and zlib1g-dev should rather be added to biodeps and removed from boost osdependencies?   I'm just guessing.

A small round-up of related issues:

 #304 concluded that adding binutils as dependency to the toolchain should happen, thus bringing in zlib (but NOT zlib-devel).
#174 intended to "removed zlib-devel as dependency of boost " but this didn't happen
#1346 was recent forward movment on related issue.  Can it be that the build/test machine has OS zlib-devel and zlib1g-dev ?  If so, is that proper, considering this issue?

I am seeking both understanding of this issue and its fix, as well as short term solution.
Should I just `yum install zlib zlib-devel` and go back to the races?

**Comment by boegel** [comment]
@malcook: very recently (shortly before EB v2.0.0), a long-standing issue with zlib was fixed, that was the reason behind having OS dependencies for `zlib`, rather than a 'proper' dependency provided by EB

With this resolved, we should be able to drop the zlib OS dep for `Boost` (and others), and use an EB-provided zlib instead. Figuring out which version that should be may not be so trivial, though, since it depends on the context in which that Boost easyconfig is used (there an be only one zlib version in every dependency graph).

**Comment by malcook** [comment]
Thanks for trying to bring me up to speed, but, I'm not sure why you put it that way.  Please help me understand.  

As I see it...

 1. zlib currently does not appear in ANY osdependencies.  
 1. zlib-devel however _does_ appear in the osdependencies for Boost (and only in Boost), along with zlib1g-dev.

So, I don't know why you say we "should be able to drop the zlib OS dep for Boost".  There is none to drop.  Or, am I missing something?

Would it be a solution to:

1. create a zlib-devel.eb
1. include it within biodeps along with zlib
1. remove it as an osdependency in Boost 

??

I'm suspect of my thinking here because I don't see other examples of header files being named (and installed in ${PREFIX})

Are you tell me that Boost might be linked with something else, each of which want zlib but with possibly varying stringency on which version.  I guess the solution would have to be to somehow figure out the intersection of the  versions allowed by each component, and then maximize it.  But this is out of my realm.  Does this really happen?  Does something like my suggestion really need to be implemented?

FWIW: very few other libs appear in osdependencies.  They are: libX11-devel cairo-devel libXmu-devel
openssl-devel libssl-dev libopenssl-devel blcr-libs blcr-devel libXmu-devel libibverbs-devel xorg-x11-proto-devel gtk2-devel

How can I help?  What can I test?  What do you think I should do "in the mean time".   Just use system zlib-devel and zlib1g-dev and hope for the best?

**Comment by fgeorgatos** [comment]
Hi,

as regards this matter, it is very important to realise the following
matter, in Kenneth's words:
> "there an be only one zlib version in every dependency graph"

In effect, ideally there should be a single zlib version that is common dep
across all packages
(which are meant to be joined together). Easier said than done.

The science and art of biodeps (or any other common deps collections for
that matter)
is to find version numbers which are overall compatible and stable (ie.
bug-free for most).


Now, if someone is willing/ready to find the very optimal zlib version,
this should be tested
across multiple distros (I would do rhel5, rhel6, rhel7, debian6, debian7,
ubuntu14 etc),
with a slight bias in favour of the more modern variants, to make them
interesting for long term support.

This requires infrastructure that none of the current HPC sites has setup
(beyond mere VMs/containers)
and if someone has a pointer about which other OSS projects could provide a
template, please let us know.
People with experience in Continuous Integration efforts may have a hint on
optimal approach.

F.


On 14 March 2015 at 07:06, Malcolm Cook <notifications@github.com> wrote:

> Thanks for trying to bring me up to speed, but, I'm not sure why you put
> it that way. Please help me understand.
>
> As I see it...
>
>    1. zlib currently does not appear in ANY osdependencies.
>     2. zlib-devel however *does* appear in the osdependencies for Boost
>    (and only in Boost), along with zlib1g-dev.
>
> So, I don't know why you say we "should be able to drop the zlib OS dep
> for Boost". There is none to drop. Or, am I missing something?
>
> Would it be a solution to:
>
>    1. create a zlib-devel.eb
>    2. include it within biodeps along with zlib
>    3. remove it as an osdependency in Boost
>
> ??
>
> I'm suspect of my thinking here because I don't see other examples of
> header files being named (and installed in ${PREFIX})
>
> Are you tell me that Boost might be linked with something else, each of
> which want zlib but with possibly varying stringency on which version. I
> guess the solution would have to be to somehow figure out the intersection
> of the versions allowed by each component, and then maximize it. But this
> is out of my realm. Does this really happen? Does something like my
> suggestion really need to be implemented?
>
> FWIW: very few other libs appear in osdependencies. They are: libX11-devel
> cairo-devel libXmu-devel
> openssl-devel libssl-dev libopenssl-devel blcr-libs blcr-devel
> libXmu-devel libibverbs-devel xorg-x11-proto-devel gtk2-devel
>
> How can I help? What can I test? What do you think I should do "in the
> mean time". Just use system zlib-devel and zlib1g-dev and hope for the best?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-easyconfigs/issues/1475#issuecomment-80040739>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by Micket** [comment]
Long since fixed.
