### ISSUE TITLE
librsb: updates to version 1.2.0.10,1.2.0.11,1.3.0.0

### ISSUE THREAD

**Issue by michelemartone** [easybuilders/easybuild-easyconfigs#14860]
Hi. You may want to update configs for 1.2.0.10,1.2.0.11,1.3.0.0 tarballs (available on https://sourceforge.net/projects/librsb/files/ ), caring to avoid gcc-11.2 (there is a problem https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103995 affecting librsb-1.3's and its test suite suite -- gcc-11.3 should be fine).

**Comment by robert-mijakovic** [comment]
@boegel Do we want to patch our GCC 11.2.0 with [this patch](https://gcc.gnu.org/git/?p=gcc.git;a=blobdiff_plain;f=gcc/tree-vect-slp.c;h=a554c24e0fb68edb4a00269da8a11019d963ac3f;hp=07cc24a60e1bed9f95879bb6f843da36eb1e4e7c;hb=3c91efec15af4f92;hpb=8b06ccb20eaf2e7cb85e9dca23f1599ee37d17a7)?
