### ISSUE TITLE
AlphaFold-2.1.1-fosscuda-2020b.eb fails on numpy

### ISSUE THREAD

**Issue by JuergenUniVie** [easybuilders/easybuild-easyconfigs#14969]
== installing extension numpy 1.19.4 (1/8)...
== 	configuring...
== 	building...
== 	testing...
== 	... (took 3 mins 28 secs)
== ... (took 3 mins 30 secs)
== FAILED: Installation ended unsuccessfully (build directory: /cluster/build/SciPybundle/2020.11/fosscuda-2020b): build failed (first 300 chars): cmd "export PYTHONPATH=/tmp/eb-sme520g9/tmp3_djbso8/lib/python3.8/site-packages:$PYTHONPATH &&  unset LDFLAGS && cd .. && /cluster/software/Python/3.8.6-GCCcore-10.2.0/bin/python -c 'import sys; import numpy; sys.exit(not numpy.test(verbose=2))' " exited with exit code 1 and output:
NumPy version 1. (took 3 mins 37 secs)
== Results of the build can be found in the log file(s) /tmp/eb-sme520g9/easybuild-SciPy-bundle-2020.11-20220209.155022.lDIoI.log
ERROR: Build of /cluster/admin/easybuild/software/EasyBuild/4.5.2/easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-fosscuda-2020b.eb failed (err: 'build failed (first 300 chars): cmd "export PYTHONPATH=/tmp/eb-sme520g9/tmp3_djbso8/lib/python3.8/site-packages:$PYTHONPATH &&  unset LDFLAGS && cd .. && /cluster/software/Python/3.8.6-GCCcore-10.2.0/bin/python -c \'import sys; import numpy; sys.exit(not numpy.test(verbose=2))\' " exited with exit code 1 and output:\nNumPy version 1.')

any idea what i can do?

best wishes,
Juergen

**Comment by boegel** [comment]
@JuergenUniVie Apologies for the lack of a response here...

To get more information, you should look into the EasyBuild log file, and see the full error message.

Did you manage to work out the actual problem here?
