### ISSUE TITLE
GCCcore AMD offloading support requires ROCR-Runtime

### ISSUE THREAD

**Issue by nordmoen** [easybuilders/easybuild-easyconfigs#14992]
EasyBuild has support for building `GCCcore` with AMD support (easybuilders/easybuild-easyblocks#2578), however, without [`ROCR-Runtime`](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/ROCR-Runtime/ROCR-Runtime-4.5.0-GCCcore-11.2.0.eb) no devices are picked up.

I suspect it worked during the PR because ROCm is usually globally installed and always in `$PATH` on AMD systems. I detected the error on our local system once I had removed the global ROCm install and instead relied only on EasyBuild.

An easy fix would be to add `ROCR-Runtime` to the dependencies if built `withamdgcn` support.

**Comment by Micket** [comment]
If we can enable rocm support in GCC with just a minimal header like we do with nvptx we can also consider enabling it by default (but i have no means of testing of this works, so it would be up to someone to contribute this. 

But to add ROC* as dependencies by default for GCC won't be done as it would force most users to filter all that out instead, so this would need to be opt-in.

AMD users can achieve this with a custom parse hook
https://github.com/easybuilders/easybuild-framework/blob/develop/contrib/hooks/hpc2n_hooks.py
to anble the corresponding parameter, or just modify the GCC easyconfigs to add the flag and dependency.
