### ISSUE TITLE
Consider adding `local::lib` to future versions of Perl ebconfigs for easier user installs of Perl modules

### ISSUE THREAD

**Issue by rungitta** [easybuilders/easybuild-easyconfigs#15038]
I briefly discussed with @akesandgren on the EB Slack on including the extension `local::lib` in the Perl ebconfigs. If included then local sites don't have to install in manually. `local::lib` is needed for user installs of Perl modules. Åke also suggested adding the `Module::Path` extension.

There might be other best practices for user installs that I don't know about. Please let me know if you have suggestions!

Ref. 
https://metacpan.org/pod/local::lib
https://documentation.sigma2.no/software/userinstallsw/perl.html

**Comment by branfosj** [comment]
@rungitta we've added `local::lib` and `Module::Path` to Perl (5.34.1) that we are using in`2022a`. See #15529
