### ISSUE TITLE
check sum of norm 1.0-9.5 inconsistent with the one in CRAN

### ISSUE THREAD

**Issue by wdlingit** [easybuilders/easybuild-easyconfigs#15037]
The check sum of norm 1.0-9.5 in R-4.1.0-foss-2021a.eb and R-4.1.2-foss-2021b.eb is 305cbf007f3905cfd535ed9bf5ae3e2995e228cc8883d6482e5d3a2f02814106. The check sum of norm 1.0-9.5 downloaded from https://cran.r-project.org/web/packages/norm/index.html is 45016701291a5851d42452fc3ae682ff9bf86b0a9ba4619dc8b36a0187e4d0e4

**Comment by akesandgren** [comment]
This was fixed in PR #14987
If you want to build 4.1.2 you should use the develop tree due to needing both the above PR and #14993 since there was one more extension updated inplace on CRAN.

This will be available in the next release (4.5.4) of EB
