### ISSUE TITLE
Checksum failure with optmatch_0.9-15.tar.gz while building R-4.1.2-foss-2021b.eb

### ISSUE THREAD

**Issue by rmarable** [easybuilders/easybuild-easyconfigs#15123]
R-4.1.2-foss-2021b.eb is failing to build because of a checksum verification failure with optmatch-0.9-15.

Here is the exact error:

== 2022-03-11 23:45:39,932 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Checksum verification for extension source optmatch_0.9-15.tar.gz failed (at easybuild/framework/easyblock.py:631 in collect_exts_file_info)

The issue is resolved by updating the SHA256 checksum from:

```
('optmatch', '0.9-15', {
        'checksums': ['7500fdbed939b7f16603a097d734a332793a3ac68e6a80c7957bef2a567691d8'],
    }),
```
to:
```
('optmatch', '0.9-15', {
       'checksums': ['f37254b3af586ffa259f09914e27cba576b6f4ef023b794195014d29f715895b'],
    }),
```

Thanks,

Rodney

**Comment by boegel** [comment]
Yup, fixed in #14993
