### ISSUE TITLE
R-4.2.0-foss-2021b

### ISSUE THREAD

**Issue by cmfield** [easybuilders/easybuild-easyconfigs#15538]
I have had two issues installing this:

The first was the package `Rmpfr`, which I got around by adding `MPFR `to the build and load dependencies.

The second is the sanity check step at the end, where it cannot find `lib64/R/include/S.h` or `lib/R/include/S.h `- as I understand, the S legacy stuff has been rearranged in 4.2.0 and is no longer in its own header file. I am using Easybuild 4.4.2 so maybe you already fixed this if I update..

**Comment by branfosj** [comment]
Thanks.

We've now got MPFR as a dependency in the latest R easyconfigs.

In 4.5.5, we've changed the R easyblock to no longer check for `S.h` in newer versions of R. See https://github.com/easybuilders/easybuild-easyblocks/pull/2713
