### ISSUE TITLE
libxml2 seems to report include path off-by-one

### ISSUE THREAD

**Issue by rjeschmi** [easybuilders/easybuild-easyconfigs#1555]
The "official" way of getting the include path set right seems to be xml2config --cflags

CPATH seems to be the only environment variable that includes the libxml2 path, but it provides it at EBROOTLIBXML/include

So something like #include <libxml/tree.h> which libxslt does will fail.

**Comment by Micket** [comment]
Nothing really relies on CPATH, or just points to the include dir always, and software packages can use pkg-config or xml2-config to gt their include and link flags. Not sure the easyconfigs did something different way in the past, but nothing seem to be having problems with our libxml2 easyconfigs in the past couple of years so i assume it's fixed or there was never anything to fix here.
