### ISSUE TITLE
MVAPICH2-2.0.1-GCC-4.8.4.eb missing file to download from MVAPICH website

### ISSUE THREAD

**Issue by sguera** [easybuilders/easybuild-easyconfigs#1556]
Mvapich has removed the tar for the version 2.0.1 from their download folder, so that EB fails to install it.
This has been experienced while installing the toolchain gmvolf-1.7.20.eb
In particular it fails with the following error:
Couldn't find file mvapich2-2.0.1.tar.gz anywhere, and downloading it didn't work either...

I don't know where to get that version of mvapich2, so suggested change would be to use the recently released version 2.1

**Comment by Micket** [comment]
Long since outdated so I'm closing this.
