### ISSUE TITLE
GLib-2.68.2-GCCcore-10.3.0 (error while compiling)

### ISSUE THREAD

**Issue by juanjoaucar** [easybuilders/easybuild-easyconfigs#15590]
I was stucked on trying to install the package GLib-2.68.2-GCCcore-10.3.0.eb

After long trying, I founded that the error was reported at https://bugzilla.redhat.com/show_bug.cgi?id=1984625 and fixed according to https://gitlab.gnome.org/GNOME/glib/-/commit/b71117d89434db83d34bc1b981ca03d4be299576

So that in order to install the package I had to
1) Uncompress the file glib-2.68.2.tar.xz
2) Edit one line of the file "glib/gspawn.c" according to the last link
3) Comment the checksum line in GLib-2.68.2-GCCcore-10.3.0.eb

I wanted to report this in case anyone else have this problem.

**Comment by boegel** [comment]
@juanjoaucar Thanks for reporting, the problem should be fixed with the patch added in #15594

You can verify this using `eb --from-pr 15594`
