### ISSUE TITLE
pygmo tries to install stuff in Python install directory

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#15631]
When trying to install `pygmo` with EasyBuild configured with, it fails with:

```
-- Install configuration: "Release"
CMake Error at pygmo/plotting/cmake_install.cmake:54 (file):
  file cannot create directory:
  /software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/pygmo/plotting.
  Maybe need administrative privileges.
```

Note that it's trying to create a directory in `$EBROOTPYTHON` here, it shouldn't...

cc @Louwrensth

**Comment by mboisson** [comment]
Mmm, I bet this does not happen if the installation procedure is : build a wheel + install the built wheel.

**Comment by boegel** [comment]
@mboisson It's CMake being stupid, as usual. ;)

**Comment by mboisson** [comment]
Correction, it's the developers doing stupid stuff with CMake
