### ISSUE TITLE
AlphaFold-2.2.2-foss-2021a-CUDA-11.3.1.eb installation failed

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#15839]
![image](https://user-images.githubusercontent.com/49931482/178526754-259d62e1-3c42-4ef0-bb58-358013b487de.png)

**Comment by hezhiqiang8909** [comment]
@boegel

**Comment by Micket** [comment]
Screenshots of code and logs are never useful, and this issue barely contains any information or indicates any steps have been taken to debug the issue. Closing.
