### ISSUE TITLE
lammps recommends adding an accelerated version of foss-2022 cuda gpu

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#15841]
lammps recommends adding an accelerated version of foss-2022 cuda gpu

**Comment by ocaisa** [comment]
I'm not quite sure what you mean by this. Do you have a reference (for example a link to the LAMMPS mailing list)?

There are two open PRs for the latest stable release of LAMMPS for `foss/2021a` and `foss/2021b`

**Comment by hezhiqiang8909** [comment]
> 我不太清楚你的意思是什么。您有参考资料（例如 LAMMPS 邮件列表的链接）吗？
> 
> `foss/2021a` #15876 和#15877 LAMMPS 的最新稳定版本有两个开放 PR`foss/2021b` [](https://github.com/easybuilders/easybuild-easyconfigs/pull/15877)
Regarding the cuda version, I still did not compile successfully, my execution command is

eb --allow-use-as-root --from-pr=15900 --include-easyblocks-from-pr=2213 --robot --cuda-compute-capabilities=7.0,7.5,8.0,8.6 --skip-test-step --insecure-download

Is there any problem with this please?

**Comment by hezhiqiang8909** [comment]
> 
== FAILED: Installation ended unsuccessfully (build directory: /public/software/.local/easybuild/build/LAMMPS/23Jun2022/foss-2021a-kokkos-CUDA-11.3.1): build failed (first 300 chars): Sanity check failed: sanity check command cd /tmp/eb-SYS2Er/tmp9haMDo && mpirun -n 1 python -c 'from lammps import lammps; l=lammps(); l.file("/public/software/.local/easybuild/software/LAMMPS/23Jun2022-foss-2021a-kokkos-CUDA-11.3.1/examples/atm/in.atm")' exited with code 1 (output: Traceback (most  (took 52 mins 29 secs)
== Results of the build can be found in the log file(s) /tmp/eb-SYS2Er/easybuild-LAMMPS-23Jun2022-20220804.110832.ipfeI.log
ERROR: Build of /tmp/eb-SYS2Er/files_pr15900/l/LAMMPS/LAMMPS-23Jun2022-foss-2021a-kokkos-CUDA-11.3.1.eb failed (err: 'build failed (first 300 chars): Sanity check failed: sanity check command cd /tmp/eb-SYS2Er/tmp9haMDo && mpirun -n 1 python -c \'from lammps import lammps; l=lammps(); l.file("/public/software/.local/easybuild/software/LAMMPS/23Jun2022-foss-2021a-kokkos-CUDA-11.3.1/examples/atm/in.atm")\' exited with code 1 (output: Traceback (most ')


这是错误信息

**Comment by hezhiqiang8909** [comment]
> 

eb --allow-use-as-root --from-pr=15900 --include-easyblocks-from-pr=2765 --robot --cuda-compute-capabilities=7.0,7.5,8.0,8.6 --skip-test-step --insecure-download

This branch has been compiled successfully, thank you very much, this version is supported

**Comment by hezhiqiang8909** [comment]
> > 
> 
> eb --allow-use-as-root --from-pr=15900 --include-easyblocks-from-pr=2765 --robot --cuda-compute-capabilities=7.0,7.5,8.0,8.6 --skip-测试步骤--不安全下载
> 
> 这个分支已经编译成功，非常感谢，支持这个版本
The compilation and installation are successful, but when running, it will prompt that the GPU package has not been added @ocaisa

**Comment by ocaisa** [comment]
The build is for CUDA via Kokkos _not_ the GPU package, see http://www.hpc-carpentry.org/tuning_lammps/06-invoking-kokkos/index.html on how to use Kokkos

**Comment by ocaisa** [comment]
See here in particular, http://www.hpc-carpentry.org/tuning_lammps/08-kokkos-gpu/index.html

**Comment by hezhiqiang8909** [comment]
> The build is for CUDA via Kokkos _not_ the GPU package, see http://www.hpc-carpentry.org/tuning_lammps/06-invoking-kokkos/index.html on how to use Kokkos
I would like to suggest that you also add the GPU package, so that it can be compatible with a variety of computing scenarios, thank you

**Comment by ocaisa** [comment]
You can't have both, you can either have the GPU package _or_ Kokkos, not both in the same build. Kokkos is better supported in Lammps and has comparable performance to the GPU package on NVIDIA GPUs (in my tests)

**Comment by hezhiqiang8909** [comment]
> 你不能同时拥有，你可以拥有 GPU 包_或_Kokkos，而不是两者都在同一个版本中。Kokkos 在 Lampps 中得到了更好的支持，并且在 NVIDIA GPU 上具有与 GPU 包相当的性能（在我的测试中）

thank you, then i get it

**Comment by Micket** [comment]
This issue seems fully resolved.
