### ISSUE TITLE
Cannot change the installation directory to '/public/software/.local/easybuild/software/intel-compilers/2022.1.0'. It is locked to '/public/software/.local/easybuild/software/imkl/2022.1.0' because there is a product 'intel.oneapi.lin.mkl.product' installed there. Installer has failed.

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#15870]
eb --allow-use-as-root intel-2022a.eb --robot --insecure-download --accept-eula-for=Intel-oneAPI

![image](https://user-images.githubusercontent.com/49931482/179283638-0eabc753-49d8-4064-bac4-517ce3da0069.png)

**Comment by hezhiqiang8909** [comment]
![image](https://user-images.githubusercontent.com/49931482/179283838-c66e20f9-5b60-4547-b2c7-d6b951780e07.png)

**Comment by hezhiqiang8909** [comment]
![image](https://user-images.githubusercontent.com/49931482/179283949-f373947e-2a99-41c7-8f19-e4c2ed8020be.png)

**Comment by hezhiqiang8909** [comment]
Cannot change the installation directory to '/public/software/.local/easybuild/software/intel-compilers/2022.1.0'. It is locked to '/public/software/.local/easybuild/software/imkl/2022.1.0' because there is a product 'intel.oneapi.lin.mkl.product' installed there.
Installer has failed.

**Comment by hezhiqiang8909** [comment]
The installation can be performed by pointing the path here. Is there any solution for this? If I install intel-compilers/2022.1.0 first, the error message will still point here. Is this an Easybuild problem?

 /public/software/.local/easybuild/software/imkl/2022.1.0

**Comment by hezhiqiang8909** [comment]
My suggestion is that the intel.oneapi components are all installed together, because it seems that the official Intel installer is deliberately set this way, or is there a good solution?

**Comment by hezhiqiang8909** [comment]
Oops, this is a series of problems, how can I solve it
![image](https://user-images.githubusercontent.com/49931482/179299626-fd69887c-61e2-4308-a967-b90c41817d15.png)
![image](https://user-images.githubusercontent.com/49931482/179299626-fd69887c-61e2-4308-a967-b90c41817d15.png)

**Comment by Micket** [comment]
Hi @hezhiqiang8909 

It would really help if you could include the outputs text blocks instead of pictures. Can't search, hard and inconvenient to read. 

> My suggestion is that the intel.oneapi components are all installed together, because it seems that the official Intel installer is deliberately set this way, or is there a good solution?

That would break the entire toolchain design in EasyBuild. Things must be kept separate, and this is 
requirement from the installer must be squashed.

I'm not seeing this issue though. I'm not even sure how it detects you have another part of the installation, and i would suspect this is the issue itself. Perhaps due to being run as root (almost noone would ever do that, since it's ill advised, so i doubt any devs have tried that). 
Possibly an old intel-sw-install-history.json lying around causing problems here.

**Comment by hezhiqiang8909** [comment]
> 你好@hezhiqiang8909
> 
> 如果您可以包含输出文本块而不是图片，那将非常有帮助。无法搜索，阅读困难且不便。
> 
> > 我的建议是把intel.oneapi组件全部安装在一起，因为貌似Intel官方安装程序是故意这样设置的，还是有什么好的解决办法？
> 
> 这将破坏 EasyBuild 中的整个工具链设计。东西必须分开，这是 安装人员的要求必须被压扁。
> 
> 我没有看到这个问题。我什至不确定它是如何检测到您有安装的另一部分，我怀疑这就是问题本身。也许是因为以 root 身份运行（几乎没有人会这样做，因为这是不明智的，所以我怀疑任何开发人员都尝试过）。 可能是一个旧的 intel-sw-install-history.json 在这里造成了问题。

Thanks, I solved this problem, I switched to normal user installation, no error was reported, thank you very much
