### ISSUE TITLE
eb --allow-use-as-root R-4.2.1-foss-2022a.eb --robot --insecure-download fails here in nodejs

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#15970]
== ... (took 24 mins 16 secs)
== FAILED: Installation ended unsuccessfully (build directory: /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0): build failed (first 300 chars): cmd " make  -j 4 " exited with exit code 2 and output:
make -C out BUILDTYPE=Release V=0
make[1]: Entering directory `/public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out'
  touch /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/o (took 24 mins 20 secs)
== Results of the build can be found in the log file(s) /tmp/eb-X59fj7/easybuild-nodejs-16.15.1-20220805.093159.GtOAF.log
ERROR: Build of /opt/easybuild/easybuild/easyconfigs/n/nodejs/nodejs-16.15.1-GCCcore-11.3.0.eb failed (err: 'build failed (first 300 chars): cmd " make  -j 4 " exited with exit code 2 and output:\nmake -C out BUILDTYPE=Release V=0\nmake[1]: Entering directory `/public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out\'\n  touch /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/o')

**Comment by hezhiqiang8909** [comment]
[cloudam@Easybuild ~]$ eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (D) = /home/cloudam/.local/easybuild/build
containerpath  (D) = /home/cloudam/.local/easybuild/containers
installpath    (D) = /home/cloudam/.local/easybuild
prefix         (E) = /home/cloudam/.local/easybuild
repositorypath (D) = /home/cloudam/.local/easybuild/ebfiles_repo
robot-paths    (D) = /opt/easybuild/easybuild/easyconfigs
sourcepath     (D) = /home/cloudam/.local/easybuild/sources
[cloudam@Easybuild ~]$ eb --show-system-info
System information (Easybuild):

* OS:
  -> name: CentOS Linux
  -> type: Linux
  -> version: 7.6.1810
  -> platform name: x86_64-unknown-linux

* CPU:
  -> vendor: Intel
  -> architecture: x86_64
  -> family: Intel
  -> arch name: UNKNOWN (archspec is not installed?)
  -> model: Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
  -> speed: 2699.998
  -> cores: 4
  -> features: 3dnowprefetch,abm,adx,aes,apic,arat,arch_capabilities,avx,avx2,avx512_bitalg,avx512_vbmi2,avx512_vnni,avx512_vpopcntdq,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vl,bmi1,bmi2,clflush,clflushopt,clwb,cmov,constant_tsc,cx16,cx8,de,eagerfpu,erms,f16c,fma,fpu,fsgsbase,fxsr,gfni,ht,hypervisor,ibrs_enhanced,invpcid,lahf_lm,lm,mca,mce,mmx,monitor,movbe,msr,mtrr,nonstop_tsc,nopl,nx,ospke,pae,pat,pcid,pclmulqdq,pdpe1gb,pge,pku,pni,popcnt,pse,pse36,rdrand,rdseed,rdtscp,rep_good,sep,sha_ni,smap,smep,ss,sse,sse2,sse4_1,sse4_2,ssse3,syscall,tsc,tsc_adjust,vaes,vme,vpclmulqdq,x2apic,xgetbv1,xsave,xsavec,xsaveopt

* software:
  -> glibc version: 2.17
  -> Python binary: /bin/python
  -> Python version: 2.7.5

**Comment by hezhiqiang8909** [comment]
这有什么问题吗

**Comment by hezhiqiang8909** [comment]
cer.o /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/verifier.o /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/zone-stats.o /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/int64-lowering.o /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/wasm-compiler.o
  g++ -o /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/api/api-arguments.o ../deps/v8/src/api/api-arguments.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-DV8_HAVE_TARGET_OS' '-DV8_TARGET_OS_LINUX' '-DV8_EMBEDDER_STRING="-node.21"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ATOMIC_MARKING_STATE' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' -I../deps/v8 -I../deps/v8/include -I/public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj/gen/inspector-generated-output-root -I../deps/v8/third_party/inspector_protocol -I/public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj/gen -I/public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj/gen/generate-bytecode-output-root -I../deps/v8/third_party/zlib -I../deps/v8/third_party/zlib/google  -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/.deps//public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/api/api-arguments.o.d.raw -I/public/software/.local/easybuild/software/Python/3.10.4-GCCcore-11.3.0-bare/include -I/public/software/.local/easybuild/software/binutils/2.38-GCCcore-11.3.0/include -O2 -ftree-vectorize -march=native -fno-math-errno -c
  touch /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj.target/tools/v8_gypfiles/v8_compiler_for_mksnapshot.stamp
make[1]: execvp: printf: Argument list too long
make[1]: *** [/public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out/Release/obj.target/tools/v8_gypfiles/libv8_base_without_compiler.a] Error 127
rm 68679e541fee25f1a8457e2f011ecba6d84e03a7.intermediate 360eb182fa2467345aa87a42379c0cc29217ec3a.intermediate
make[1]: Leaving directory `/public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out'
make: *** [node] Error 2
 (at easybuild/lib/python3.6/site-packages/easybuild/tools/run.py:618 in parse_cmd_output)
== 2022-08-05 11:01:11,940 build_log.py:265 INFO ... (took 24 mins 15 secs)
== 2022-08-05 11:01:11,940 easyblock.py:4098 WARNING build failed (first 300 chars): cmd " make  -j 4 " exited with exit code 2 and output:
make -C out BUILDTYPE=Release V=0
make[1]: Entering directory `/public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/out'
  touch /public/software/.local/easybuild/build/nodejs/16.15.1/GCCcore-11.3.0/node-v16.15.1/o
== 2022-08-05 11:01:11,941 easyblock.py:318 INFO Closing log for application name nodejs version 16.15.1

**Comment by hezhiqiang8909** [comment]
This doesn't show what's wrong

**Comment by Micket** [comment]
> execvp: printf: Argument list too long

It does show what's wrong.

https://github.com/nodejs/node/issues/9137#issuecomment-954443010 seems relevant.  
`ulimit -s large_number` should resolve this issue (which has nothing to do with R-4.2.1). 

Also, don't use --allow-use-as-root and don't use --insecure-download, they are bad options.
