### ISSUE TITLE
OpenBLAS fails to build on CentOS6/Haswell system using GCC/4.9.2 toolchain

### ISSUE THREAD

**Issue by rjeschmi** [easybuilders/easybuild-easyconfigs#1605]
A couple of unusual issues. Through the logs there are references to some redefines as well.

```
symv_thread.c: In function ‘symv_kernel’:
symv_thread.c:58:23: warning: variable ‘incy’ set but not used [-Wunused-but-set-variable]
   BLASLONG lda, incx, incy;
                       ^
/tmp/eb-EUsUZe/cckGd7mU.s: Assembler messages:
/tmp/eb-EUsUZe/cckGd7mU.s:254: Error: no such instruction: `shlx %rax,0(%r13,%rbx,8),%rcx'
/tmp/eb-EUsUZe/cckGd7mU.s:255: Error: no such instruction: `shlx %rax,88(%rsp,%r14,8),%rax'
make[1]: *** [zhemv_thread_U.o] Error 1
/tmp/eb-EUsUZe/cccuIr0W.s: Assembler messages:
/tmp/eb-EUsUZe/cccuIr0W.s:254: Error: no such instruction: `shlx %rax,0(%r13,%rbx,8),%rcx'
/tmp/eb-EUsUZe/cccuIr0W.s:255: Error: no such instruction: `shlx %rax,88(%rsp,%r14,8),%rax'
make[1]: *** [zhemv_thread_V.o] Error 1
make[1]: Leaving directory `/sw/eb/build/OpenBLAS/0.2.13/GCC-4.9.2-LAPACK-3.5.0/OpenBLAS-0.2.13/driver/level2'
make: *** [libs] Error 1
 (at easybuild/tools/run.py:360 in parse_cmd_output)

```

http://filebin.ca/21pNKZvflLI5/easybuild-OpenBLAS-0.2.13-20150515.173040.VQhZX.log

**Comment by rjeschmi** [comment]
I assume it was @iotaka on IRC that reported this (just so we keep track of the issue I've put it here).

**Comment by rjeschmi** [comment]
and I've uploaded a working log that I have from a similar machine

https://gist.github.com/rjeschmi/ec9c416f3a4e4e9806c2

**Comment by rjeschmi** [comment]
Looking more into it, I'm very suspicious of an old gnu assembler being found. What OS is this ?

**Comment by boegel** [comment]
I think I've seen similar issues on OS X, which ships a broken assembler.

```eb --optarch=''` should fix it (to avoid that `eb` using `-march=native`).

**Comment by rjeschmi** [comment]
@boegel  On OS X you might find it better to use the clang provided assembler since it would allow you to still use AVX.

I remember seeing discussions about bintools before... Maybe we should give a way of safely substituting a newer gas

**Comment by iotaka** [comment]
Hi, the OS is a CentOS 6.6.
We will try what suggest @boegel

**Comment by rjeschmi** [comment]
It is a good idea to test it. I'm curious what the benchmark will look like as you will probably take a hit if you can't enable the newer extensions

**Comment by iotaka** [comment]
We will also try to compile on a node with a better CPU. Some time cheaper XEONS have missing features.

**Comment by boegel** [comment]
This is not about the CPU, but about the assembler not supporting the instructions that the compiler is producing. It's quite weird you're hitting this on CentOS 6.6...

Can you provide a full debug log (`eb --debug ...`), e.g. via http://gist.github.com?

**Comment by rjeschmi** [comment]
I'm pretty sure the debug log is what I linked to, no? Through pastebin.ca

**Comment by boegel** [comment]
@rjeschmi: sorry, missed that part...

@iotaka: https://software.intel.com/en-us/blogs/2012/06/04/write-your-first-program-with-haswell-new-instructions shows the exact same error, and mentions that you need binutils 2.22 or newer.

On Scientific Linux 6 (and CentOS 6, in a VM), where this build works, I'm seeing this though:

```
$ which as
/usr/bin/as

$ as --version
GNU assembler version 2.20.51.0.2-5.42.el6 20100205
Copyright 2009 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-redhat-linux'.

$ rpm -qa | grep binutils
binutils-2.20.51.0.2-5.42.el6.x86_64
binutils-devel-2.20.51.0.2-5.42.el6.x86_64
```

I suspect this may be an enhanced binutils 2.20 though, with stuff (like Haswell support) backported by Red Hat.

Can you check which binutils version you have?

This is a nice motivation to pick up the effort by @wpoely86 again to include our own binutils in toolchains, see https://github.com/hpcugent/easybuild-easyconfigs/pull/1346 .

**Comment by pescobar** [comment]
@iotaka if I recall correctly, the right syntax is 

``` 
eb --optarch=march=core2
```

**Comment by boegel** [comment]
Let me be more specific: I haven't seen this on Scientific Linux 6.6, but that's on Sandybridge systems.

It seems like this may be an AVX2 thing, where the standard assembler in CentOS 6 is too old to handle the instructions that a recent GCC emits.

If that's indeed the case, the only proper way out is to include a recent binutils in the toolchain, like #1346 does.

**Comment by wpoely86** [comment]
@iotaka can you try to build the HPL `HPL-2.1-foss-2015.01.eb` from #1346 ? It should fix your issue.

**Comment by rjeschmi** [comment]
@iotaka there is a --from-pr option to make this easier.

**Comment by boegel** [comment]
the people in @hpcleuven are also suffering from this problem: binutils versions included in RHEL6 is too old to handle Haswell/AVX2...

**Comment by Micket** [comment]
Long since outdated/resolved.
