### ISSUE TITLE
TINKER-8.8.1-foss-2020a.eb - TINKER version not available

### ISSUE THREAD

**Issue by MrPetkus** [easybuilders/easybuild-easyconfigs#16170]
TINKER 8.8.1 is no longer obtainable at the source:
`source_urls = ['https://dasher.wustl.edu/tinker/downloads/']`

8.8.3 is currently available

Best,
Robert

**Comment by Micket** [comment]
As foss 2020a has/is about to fall outside of support, I suspect noone will be very intersted in reviving this.
New PRs for TINKER 8.9.5 are welcome for those who use this software.
