### ISSUE TITLE
Failing test_autograd in `PyTorch/1.9.0-fosscuda-2020b` + `PyTorch-1.9.0-fosscuda-2020b-imkl.eb` on Intel Cascade Lake V100 system

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#16233]
One failing test for `PyTorch/1.9.0-fosscuda-2020b` + `PyTorch-1.9.0-fosscuda-2020b-imkl.eb` on our Intel Cascade Lake V100 system (test report coming up), perhaps this one is also flaky: `test_autograd`

```
======================================================================
FAIL: test_thread_shutdown (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_autograd.py", line 4360, in test_thread_shutdown
    self.assertRegex(s, "PYTORCH_API_USAGE torch.autograd.thread_shutdown")
AssertionError: Regex didn't match: 'PYTORCH_API_USAGE torch.autograd.thread_shutdown' not found in 'PYTORCH_API_USAGE torch.python.import\nPYTORCH_API_USAGE c10d.python.import\nPYTORCH_API_USAGE tensor.create\n'

----------------------------------------------------------------------
Ran 951 tests in 23.361s

FAILED (failures=1, skipped=312, expected failures=1)
test_autograd failed!
```

_Originally posted by @boegel in https://github.com/easybuilders/easybuild-easyconfigs/issues/15919#issuecomment-1242759805_

**Comment by Flamefire** [comment]
@boegel Did the machine on which this test was running on had any GPUs? If so how many? I'd guess 1 V100 but would like you to verify.

**Comment by boegel** [comment]
@Flamefire The failing test happens when installing that PyTorch easyconfig file in a Slurm job where 1 V100 GPU is available (system is a RHEL8 Intel Cascade Lake node with 4 V100 GPUs).
