### ISSUE TITLE
Qt5 build failed

### ISSUE THREAD

**Issue by varun082021** [easybuilders/easybuild-easyconfigs#16304]
Trying to build Qt5 5.15.2 using EasyBuild but it fails and shows below error. Can anyone help me to fix this issue?

ninja: build stopped: subcommand failed.
make[4]: *** [run_ninja] Error 1
make[4]: Leaving directory `/cm/shared/apps/easybuild/build/Qt5/5.15.2/GCCcore-11.2.0/qt-everywhere-src-5.15.2/qtwebengine/src/core'
make[3]: *** [sub-gn_run-pro-make_first] Error 2
make[3]: Leaving directory `/cm/shared/apps/easybuild/build/Qt5/5.15.2/GCCcore-11.2.0/qt-everywhere-src-5.15.2/qtwebengine/src/core'
make[2]: *** [sub-core-make_first] Error 2
make[2]: Leaving directory `/cm/shared/apps/easybuild/build/Qt5/5.15.2/GCCcore-11.2.0/qt-everywhere-src-5.15.2/qtwebengine/src'
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory `/cm/shared/apps/easybuild/build/Qt5/5.15.2/GCCcore-11.2.0/qt-everywhere-src-5.15.2/qtwebengine'
make: *** [module-qtwebengine-make_first] Error 2

**Comment by varun082021** [comment]
@jfgrimm @SebastianAchilles @boegel  Do you have any suggestion for this issue?

**Comment by SebastianAchilles** [comment]
Qt5 requires a lot of space during build time. What is your eb config (`eb --show-config`) and how much space to you have in the `buildpath` directory?

If that is not helping, would it be possible to get the full log? Maybe with `eb .. --upload-test-report` and then link the gist?

**Comment by varun082021** [comment]
@SebastianAchilles  Thanks for looking into this.
Buildpath is set to my home directory which is in NAS and there is no issue with the available space.
I'm trying to create gist with logs but seems gist is having some issue. I will retry and share the link.

**Comment by varun082021** [comment]
@SebastianAchilles 
Since log file size is too big, not able to create gist link. 
I have created a project in git and uploaded the same and invited you as collaborator.
Please let me know, whether that works for you.
https://github.com/varun082021/qt5-build-issue.git

**Comment by SebastianAchilles** [comment]
This is the failing part:
```
[3995/22428] CXX obj/third_party/crashpad/crashpad/util/util/file_io_posix.o
FAILED: obj/third_party/crashpad/crashpad/util/util/file_io_posix.o 
/cm/shared/apps/easybuild/software/GCCcore/11.2.0/bin/g++ -MMD -MF obj/third_party/crashpad/crashpad/util/util/file_io_posix.o.d -DZLIB_CONST -DCRASHPAD_USE_BORINGSSL -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DCRASHPAD_LSS_SOURCE_EXTERNAL -Igen/third_party/crashpad/crashpad -Igen -I../../3rdparty/chromium -I../../3rdparty/chromium/third_party/crashpad/crashpad -Igen -I../../3rdparty/chromium/third_party/crashpad/crashpad/compat/non_mac -I../../3rdparty/chromium/third_party/crashpad/crashpad/compat/linux -I../../3rdparty/chromium/third_party/crashpad/crashpad/compat/non_win -I../../3rdparty/chromium/third_party/zlib -I../../3rdparty/chromium/third_party/boringssl/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -m64 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-return-type -Wno-deprecated-copy -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../3rdparty/chromium/third_party/crashpad/crashpad/util/file/file_io_posix.cc -o obj/third_party/crashpad/crashpad/util/util/file_io_posix.o
In file included from ../../3rdparty/chromium/third_party/crashpad/crashpad/util/file/file_io_posix.cc:29:
../../3rdparty/chromium/third_party/crashpad/crashpad/util/file/file_io_posix.cc: In function crashpad::FileHandle crashpad::LoggingOpenMemoryFileForReadAndWrite(const base::FilePath&):
../../3rdparty/chromium/third_party/crashpad/crashpad/util/file/file_io_posix.cc:168:53: error: O_TMPFILE was not declared in this scope
  168 |   result = HANDLE_EINTR(open(tmp, O_RDWR | O_EXCL | O_TMPFILE, 0600));
      |                                                     ^~~~~~~~~
../../3rdparty/chromium/base/posix/eintr_wrapper.h:29:12: note: in definition of macro HANDLE_EINTR
   29 |   decltype(x) eintr_wrapper_result; \
      |            ^
```

Can you say what system you are working on? E.g. the output of `eb --show-system-info`.

And what type of filesystem do you use? I am asking because:
```
O_TMPFILE requires support by the underlying filesystem;
only a subset of Linux filesystems provide that support.
In the initial implementation, support was provided in the
ext2, ext3, ext4, UDF, Minix, and tmpfs filesystems.
Support for other filesystems has subsequently been added
as follows: XFS (Linux 3.15); Btrfs (Linux 3.16); F2FS
(Linux 3.16); and ubifs (Linux 4.9)
```

If you have a lot of memory, you could try `--buildpath=/dev/shm/$USER` (but iirc Qt5 needs a lot. I think it failed for me on a system with 32GB RAM). Otherwise, you could try to use `--buildpath=/tmp/$USER`.

**Comment by varun082021** [comment]
@SebastianAchilles 

Filesystem is nfs and please find the below system details.


* OS:
  -> name: RHEL
  -> type: Linux
  -> version: 7.4
  -> platform name: x86_64-unknown-linux

* CPU:
  -> vendor: Intel
  -> architecture: x86_64
  -> family: Intel
  -> arch name: UNKNOWN (archspec is not installed?)
  -> model: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
  -> speed: 2500.0
  -> cores: 40
  -> features: 3dnowprefetch,abm,acpi,adx,aes,aperfmperf,apic,arat,arch_perfmon,art,avx,avx2,avx512bw,avx512cd,avx512dq,avx512f,avx512vl,bmi1,bmi2,bts,cat_l3,cdp_l3,clflush,clflushopt,clwb,cmov,constant_tsc,cqm,cqm_llc,cqm_mbm_local,cqm_mbm_total,cqm_occup_llc,cx16,cx8,dca,de,ds_cpl,dtes64,dtherm,dts,eagerfpu,epb,ept,erms,est,f16c,flexpriority,fma,fpu,fsgsbase,fxsr,hle,ht,ida,intel_pt,invpcid,lahf_lm,lm,mca,mce,mmx,monitor,movbe,mpx,msr,mtrr,nonstop_tsc,nopl,nx,pae,pat,pbe,pcid,pclmulqdq,pdcm,pdpe1gb,pebs,pge,pln,pni,popcnt,pse,pse36,pts,rdrand,rdseed,rdt_a,rdtscp,rep_good,rtm,sep,smap,smep,smx,ss,sse,sse2,sse4_1,sse4_2,ssse3,syscall,tm,tm2,tpr_shadow,tsc,tsc_adjust,tsc_deadline_timer,vme,vmx,vnmi,vpid,x2apic,xgetbv1,xsave,xsavec,xsaveopt,xtopology,xtpr

* software:
  -> glibc version: 2.17
  -> Python binary: /usr/bin/python
  -> Python version: 2.7.5

I have around 360 GB available in /tmp. Let me try with that.

**Comment by varun082021** [comment]
@SebastianAchilles I tried with build path --buildpath=/dev/shm/$USER but issue remains same.

df -h /dev/shm/
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           189G   17G  173G   9% /dev/shm

**Comment by SebastianAchilles** [comment]
According to https://bugzilla.redhat.com/show_bug.cgi?id=1471405 `O_TMPFILE` is not supported in RHEL 7.4. So, I think only an OS update could help in this case.

**Comment by varun082021** [comment]
Thanks for you information. I will update the OS and retry.
