### ISSUE TITLE
Shall we start asking new PRs to use `SYSTEM` instead of `True`

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#16330]
Going forward, we agreed that it's a good idea to start using SYSTEM instead of True for system level dependencies. 

Discussed briefly on todays conf call, but I think it's best if we start by
1. Doing a big PR where we at least change most of the recent stuff to use this. Otherwise, it will be an never-ending stream of new contributions that copy old stuff and then get asked to change it. Very annoying and a time waste.

2. Have the CI check for this automatically.

**Comment by jfgrimm** [comment]
>     1. Doing a big PR where we at least change most of the recent stuff to use this. Otherwise, it will be an never-ending stream of new contributions that copy old stuff and then get asked to change it. Very annoying and a time waste.

done in PR #16386, and a few that were originally missed (or merged in the meantime) in #16384

>     2. Have the CI check for this automatically.

addressed  in #16384 

A PR to update the easybuild documentation was also merged in https://github.com/easybuilders/easybuild/pull/827, and instances in the framework tests updated in https://github.com/easybuilders/easybuild-framework/pull/4094

**Comment by Micket** [comment]
we do this now
