### ISSUE TITLE
OpenMPI (any Version) with SLURM - RHEL 8.6

### ISSUE THREAD

**Issue by JuergenUniVie** [easybuilders/easybuild-easyconfigs#16350]
I switched from PBS to SLURM and wanted to recompile the OpenMPI modules. Unfortunately, every version fails with the error:

checking can PMI support be built... no
configure: WARNING: PMI support requested (via --with-pmi) but neither pmi.h,
configure: WARNING: pmi2.h or pmix.h were found under locations:
configure: WARNING:     /usr/include/slurm
configure: WARNING:     /usr/include/slurm/slurm
configure: WARNING: Specified path: /usr/include/slurm
configure: WARNING: OR neither libpmi, libpmi2, or libpmix were found under:
configure: WARNING:     /usr/lib
configure: WARNING:     /usr/lib64
configure: WARNING: Specified path: /usr

BUT the File exists:

/usr/include/slurm
[root@xyz slurm]# ls -l
total 380
-rw-r--r-- 1 root root  27152 Sep 30 21:58 pmi2.h
-rw-r--r-- 1 root root  25264 Sep 30 21:58 pmi.h
-rw-r--r-- 1 root root  74860 Sep 30 21:58 slurmdb.h
-rw-r--r-- 1 root root  10767 Sep 30 21:58 slurm_errno.h
-rw-r--r-- 1 root root 211971 Sep 30 21:58 slurm.h
-rw-r--r-- 1 root root   2730 Sep 30 21:58 slurm_version.h
-rw-r--r-- 1 root root   3144 Sep 30 21:58 smd_ns.h
-rw-r--r-- 1 root root  17791 Sep 30 21:58 spank.h

[root@xyz usr]# find -name "libpmi*"
./lib64/libpmix.so.2
./lib64/pmix/lib/libpmi.so.1
./lib64/pmix/lib/libpmi.so.1.0.1
./lib64/pmix/lib/libpmi2.so.1
./lib64/pmix/lib/libpmi2.so.1.0.0
./lib64/libpmi.so.0
./lib64/libpmi.so.0.0.0
./lib64/libpmi2.so
./lib64/libpmi2.so.0
./lib64/libpmi2.so.0.0.0
./lib64/libpmix.so.2.1.25
./lib64/libpmi.so

any suggestions?

Thank you!
Juergen

PS: It's a clean install from SLURM 22.05.4

**Comment by JuergenUniVie** [comment]
it works when I set
configopts += '--with-slurm --with-pmi=/usr --with-pmi-libdir=/usr/lib64'
not good, but works....

**Comment by akesandgren** [comment]
Have you tried building it by hand? You should not need to set those at all. Also note that for newer OpenMPI versions, 4.x and later at least, you should build both Slurm and OpenMPI with an (possibly external) PMIx library
