### ISSUE TITLE
netCDF/4.9.0-gompi-2022a is missing a dependency

### ISSUE THREAD

**Issue by hrnagel** [easybuilders/easybuild-easyconfigs#16446]
Hi,

$ module load netCDF/4.9.0-gompi-2022a
$ ncgen -h
ncgen: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
$ module load bzip2/1.0.8-GCCcore-11.3.0
$ ncgen -h
Usage: ncgen [-1] [-3] [-4] [-5] [-6] [-7] [-b] [-d] [-D debuglevel] [-h] [-k kind ] [-l language=b|c|f77|java] [-M <name>] [-n] [-o outfile] [-P] [-x] [-N datasetname] [-L loglevel] [-H] [-W generate whole var upload] [file ... ]

Best regards,

Henrik

**Comment by hrnagel** [comment]
bzip2 probably comes from the CMake easyconfig file. CMake is included as a build dependency in the netCDF easyconfig file. ncgen can therefore be compiled, but not run afterwards when CMake is no longer loaded.

**Comment by branfosj** [comment]
For 4.9.0:
```
ldd $EBROOTNETCDF/bin/ncgen | grep "not found"
        libbz2.so.1.0 => not found
        libbz2.so.1.0 => not found
```

**Comment by branfosj** [comment]
I'm seeing the following extra in the log:
```
-- Found Bz2: headers at /rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/bzip2/1.0.8-GCCcore-11.3.0/include, libraries at /rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/bzip2/1.0.8-GCCcore-11.3.0/lib
--  library is /rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/bzip2/1.0.8-GCCcore-11.3.0/lib/libbz2.so
-- Found LibXml2: /rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/libxml2/2.9.13-GCCcore-11.3.0/lib/libxml2.so (found version "2.9.13")
```

**Comment by boegel** [comment]
We should also enhance the `netCDF` easyconfig with a sanity check command, we should have caught this:
```
$ ncgen --version
ncgen: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by branfosj** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16450
* https://github.com/easybuilders/easybuild-easyblocks/pull/2811
