### ISSUE TITLE
M4 1.4.18 does not build with glibc v 2.34

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#16480]
We are trying to deploy a system under Rocky Linux 9, which ships with glibc v 2.34.   It seems M4 1.4.18 can not be build against this, e.g.:

https://lore.kernel.org/all/87bla1nzu1.fsf@dell.be.48ers.dk/T/

The issues affects all toolchains that deploy 1.4.18, e.g. foss/2020b.  The issues appear fixed in M4 1.4.19.  Hacking into the the bison and flex that are used for GCC 10.2.0 and requesting M4 1.4.19 in there made me succeed in building GCC 10.2.0.   But then when trying the full foss/2020b, I got more configs that ask for M4.   Fixing (hacking into all of these) gets on the laborious side, tacking into account the number of toolchains that us M4 1.4.18.

**Comment by akesandgren** [comment]
This can be easily solved with a hook that replaces 1.4.18 with 1.4.19

See the contrib dir in the installed EB for eaxmples.

**Comment by jhein32** [comment]
> This can be easily solved with a hook that replaces 1.4.18 with 1.4.19
> 
> See the contrib dir in the installed EB for eaxmples.

Sorry this is cryptic.  Could you elaborate?

**Comment by akesandgren** [comment]
Hmmm I hadn't uploaded our latest hooks version where I actually do change versions of a specific dependencies.
For hooks in general see the documentation.

It won't be too hard to write a hook that replaces all occurances of M4 in (build)dependencies with one that has the required version.

**Comment by Micket** [comment]
We can probably just include this patch in the 1.4.18 builds?
