### ISSUE TITLE
OpenBLAS 0.3.18 LAPACK tests failed due to numerical errors 

### ISSUE THREAD

**Issue by Ezimkin** [easybuilders/easybuild-easyconfigs#16504]
Hello all,

I'm having some issues building the dependencies for `LAMMPS-23Jun2022-foss-2021b-kokkos-CUDA-11.4.1.eb`. In particular, `OpenBLAS version 0.3.18` fails due to too many numerical error occurrences during testing.

I assume there is due to some imprecise flags given to the compiler? If it is system dependent then I will mention that this is on an AMD EPYC 7713 server.

```
			-->   LAPACK TESTING SUMMARY  <--
SUMMARY             	nb test run 	numerical error   	other error  
================   	===========	=================	================  
REAL             	1294329		1233	(0.095%)	0	(0.000%)	
DOUBLE PRECISION	1302917		1195	(0.092%)	0	(0.000%)	
COMPLEX          	756180		1005	(0.133%)	0	(0.000%)	
COMPLEX16         	768848		144	(0.019%)	0	(0.000%)	

--> ALL PRECISIONS	4122274		3577	(0.087%)	0	(0.000%)	
```

Here is the full log file from the build.

[easybuild-OpenBLAS-0.3.18-20221027.182153.scXWI.log](https://github.com/easybuilders/easybuild-easyconfigs/files/9889556/easybuild-OpenBLAS-0.3.18-20221027.182153.scXWI.log)

**Comment by Ezimkin** [comment]
Ah, that may be a solution. I'm not sure what version it was from since i upgraded `eb` a few days before this but `GCC` and `GCCcore` were definitely using that older build. 

I will build it this weekend and report back if it resolves my issue.

**Comment by Ezimkin** [comment]
I got my results back a earlier than expected. I can confirm that recompilation of `GCC` and `GCCcore` resolved this issue.

Thank you @akesandgren !

**Comment by boegel** [comment]
More details on this in #16380
