### ISSUE TITLE
R-bundle-Bioconductor 3.15 foss 2022a: extension ExomeDepth not found

### ISSUE THREAD

**Issue by Ghepardo** [easybuilders/easybuild-easyconfigs#16622]
The easyconfig for R-bundle-Bioconductor-3.15-foss-2022a-R-4.2.1 specifies the extension ExomeDepth 1.1.15.  This can't be found at the given source - there is only version 1.1.16 there.  I worked around this by downloading a copy of the former version from http://download.nust.na/pub3/cran/contrib/main/.  (Thank you, Namibia.)

**Comment by boegel** [comment]
@Ghepardo `ExomeDepth` was removed from CRAN, so we removed it from the `R-bundle-Bioconductor` easyconfig, see #16492 for more information
