### ISSUE TITLE
Perl 5.36.0 GCCcore 12.2.0: extension Variable-Magic not found

### ISSUE THREAD

**Issue by Ghepardo** [easybuilders/easybuild-easyconfigs#16621]
The easyconfig for Perl-5.36.0-GCCcore-12.2.0 specifies the extension Variable-Magic 0.62.  This can't be found at the given source - there is only version 0.63 there.  I worked around this by downloading a copy of the former version from https://cpan.metacpan.org/authors/id/V/VP/VPIT/.

**Comment by boegel** [comment]
@Ghepardo Thanks for the bug report, we fixed this already in #16611, you can install the updated easyconfig easily using `eb --from-pr 16611 Perl-5.36.0-GCCcore-12.2.0`.
