### ISSUE TITLE
The latest EasyBuild easyconfig is always missing from EasyBuild-EasyConfig release.

### ISSUE THREAD

**Issue by fizwit** [easybuilders/easybuild-easyconfigs#16707]
The easyconfig for EasyBuild-4.6.2 is missing from the release of EasyBuild-Easyconfigs-4.6.2.  EasyBuild-4.6.2.eb is not found in easybuild-easyconfigs-4.6.2.tar.gz. This has been the case for every release of EasyBuild-EasyConfigs.

Why is this an issue?  When creating an EasyBuild docker container for a specific version of EB, the build fails because the specific version that is being installed can't be found in the source file.  4.6.2 is not part of the 4.6.2 release! (4.6.1 is not part of the 4.6.1 release etc...). The easyconfig for EasyBuild has to be manually injected into the container build.

**Comment by boegel** [comment]
We can't include an easyconfig file for EasyBuild v4.6.2, that's a chicken-egg problem: we need the SHA256 checksum for the `easybuild-easyconfigs` package to include in the `EasyBuild` easyconfig file
