### ISSUE TITLE
LD_LIBRARY_PATH incorrect in R 3.x module files

### ISSUE THREAD

**Issue by gjbex** [easybuilders/easybuild-easyconfigs#1684]
Dear all,

The module files generated by Easybuild for R 3.x are not quite correct.  The value '$root/lib64' is prepended to LD_LIBRARY_PATH using:
prepend-path    LD_LIBRARY_PATH         $root/lib64

However, libR.so is located in '$root/lib64/R/lib'.

Best, -gjb-

**Comment by branfosj** [comment]
We symlink `lib64` to `lib` (or vice-versa), so this is fixed.
