### ISSUE TITLE
Hello, does amber22 have a GPU version branch?

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#16868]
I have obtained the installation package of Amber22 from the official website for free
![image](https://user-images.githubusercontent.com/49931482/207578232-272b1491-c865-4b8a-8a73-e5fa24c35438.png)

**Comment by bedroge** [comment]
Hi @hezhiqiang8909, I have an open pull request (https://github.com/easybuilders/easybuild-easyconfigs/pull/16123) which adds a CUDA version of Amber 22.

**Comment by Micket** [comment]
And that PR was merged, closing this.
