### ISSUE TITLE
Feature request: easyconfig parameter for files that have to be download manually

### ISSUE THREAD

**Issue by npklein** [easybuilders/easybuild-easyconfigs#1686]
Some software can not be downloaded automatically. One example is GATK, where a license agreement has to be accepted before starting the download. In the .eb files for GATK that are currently in EasyBuild there is a comment that says to download GATK manually (and the comment doesn't link to the correct version of GATK, just the main download page). 
So when installing GATK for the first time you get an error: 
(FAILED: Installation ended unsuccessfully [...] Couldn't find file GenomeAnalysisTK-3.3-0.tar.bz2 anywhere, and downloading it didn't work either [...]). 
I think it would be handy if there is a variable, for example download_manually, so that you could put in the .eb file

download_manually = "https://www.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.0-0-g6bad1c6"

and before building dependencies there would be a message like

Can't install GATK-3.3.0. GATK-3.3.0 has to be manually downloaded from https://www.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.0-0-g6bad1c6 and put in /path/to/EasyBuild/sources/g/GATK/.

**Comment by boegel** [comment]
This makes a lot of sense, I like the idea.

Clearer error messages are certainly good.

It shouldn't be too hard to support too.

Maybe you're up for this yourself? Let us know.

**Comment by Micket** [comment]
We have download_instructions for this exact thing nowadays (it is even required if there are no source urls)
