### ISSUE TITLE
ELPA repos changed address

### ISSUE THREAD

**Issue by catalinbostan** [easybuilders/easybuild-easyconfigs#17162]
old source url:
source_urls = ['https://elpa.rzg.mpg.de/software/tarball-archive/Releases/%(version)s/'

new working source url
source_urls = ['https://elpa.mpcdf.mpg.de/software/tarball-archive/Releases/%(version)s/'

reason: New domain - Please update your bookmarks
We are now reachable at our new domain mpcdf.mpg.de. The link you used still contains our old domain and doesn't work anymore.

Please update your bookmarks replacing rzg.mpg.de with mpcdf.mpg.de

**Comment by boegel** [comment]
fixed with #17357 + #17358
