### ISSUE TITLE
libxslt-1.1.34-GCCcore-11.3.0.eb fails on RHEL9 due to missing pkgconf dependency

### ISSUE THREAD

**Issue by rungitta** [easybuilders/easybuild-easyconfigs#17202]
This happened on a RHEL9 (9.1 Plow) system for me and in a Ubuntu-focal Singularity container for @sassy-crick 

`libxslt-1.1.34-GCCcore-11.3.0.eb` fails with this output in the log:

```bash
checking for x86_64-pc-linux-gnu-xml2-config... no
checking for xml2-config... /scratch/palrosen/.local/easybuild/software/libxml2/2.9.13-GCCcore-11.3.0/bin/xml2-config
checking for LIBXML... no
./configure: line 14833: --static: command not found
configure: error: Could not find libxml2 anywhere, check ftp://xmlsoft.org/.
 (at easybuild/software/EasyBuild/4.6.0/lib/python3.9/site-packages/easybuild/tools/run.py:618 in parse_cmd_output)
```
I couldn't find any other issues about this problem here and not on the EasyBuild Slack either. The `1.1.34` version has been used since GCC 8.3.0 and is still used in the latest ebconfig.
After updating to `libxslt-1.1.37-GCCcore-11.3.0.eb` configure works again and the build finishes:

```bash
checking for x86_64-pc-linux-gnu-xml2-config... no
checking for xml2-config... /lsc/easybuild/software/libxml2/2.9.13-GCCcore-11.3.0/bin/xml2-config
checking for LIBXML... no
checking for libxml libraries >= 2.6.27... 2.9.13 found
checking whether shared libraries will be built (required for plugins)... yes
checking libxml2 module support... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
```

**Comment by rungitta** [comment]
Got some help from a colleague of mine to have a look at this issue. It turns out to be a RHEL8 vs RHEL9 issue and thus might affect other ebconfigs as well.

On RHEL8 /usr/sbin/pkg-config is a symlink to a binary that gets called directly.  On RHEL9 it is a wrapper shellscript that first calls rpm to determine the architecture it is running on and then run the appropriate pkg-config binary.  Due to the XZ module being loaded, rpm does not run.  Thus pkg-config does not get detected reliably and in the end the PKG_CONFIG variable is empty and calling $PKG_CONFIG --static ... fails.  For RHEL9 the dependency on a pkgconf module is *needed* to get it working, but even on other operating systems/OS versions, xslt should not use the OS wide pkg-config but one provided by easybuild.

So a solution here is to just add this dep to the ebconfig:
```bash
    ('pkgconf', '1.8.0'),
```

**Comment by Micket** [comment]
Yes everywhere when pkg-config is called (except for SYSTEM level stuff) we should have a builddepedency on pkgconf.
