### ISSUE TITLE
slamdunk-0.4.3-foss-2021b.eb and SlamDunk-0.4.3-foss-2021b.eb

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#17300]
There are easyconfigs for slamdunk-0.4.3-foss-2021b.eb and SlamDunk-0.4.3-foss-2021b.eb  

This creates issues on filesystems that are configured as "case insensitive", e.g. the Mac I am using for writing easyconfigs.

**Comment by Micket** [comment]
Yes this is just wrong. slamdunk-0.4.3-foss-2021b.eb shouldn't have been merged. We need to enhance the test suite to ensure things like this doesn't get merged.
