### ISSUE TITLE
No LD_LIBRARY_PATH in Java module files

### ISSUE THREAD

**Issue by gjbex** [easybuilders/easybuild-easyconfigs#1740]
Dear all,

LD_LIBRARY_PATH is not modified in the module files generated for Java.  This is an issue when installing software that tries to link in any of the libraries in, e.g., jre/lib/...

Best, -gjb-

**Comment by boegel** [comment]
This should be an easy fix via `modextrapaths` in the Java easyconfigs...

@gjbex: do you have a full list of directories that should be included in `LD_LIBRARY_PATH`? Up for tackling this for one Java easyconfig yourself?

**Comment by Micket** [comment]
We have this nowadays.
