### ISSUE TITLE
Can you add the template of PhyloSift software, link https://github.com/gjospin/PhyloSift

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#17650]
Can you add the template of PhyloSift software, link https://github.com/gjospin/PhyloSift

**Comment by Micket** [comment]
As with basically all new software, please do the work and open a pull request with the new easyconfig yourself. I don't think anyone will volunteer to do it for you, as essentially all contributions are from HPC administrators that make contributions based on their users requests only.
