### ISSUE TITLE
wrong NWChem homepage

### ISSUE THREAD

**Issue by edoapra** [easybuilders/easybuild-easyconfigs#17964]
The URL used for the NWChem homepage currently used in this repository has been bought by cybersquatters 2 years ago. https://github.com/easybuilders/easybuild-easyconfigs/blob/75dd36389810e0e38026ef53d10ea1f6b85651d5/easybuild/easyconfigs/n/NWChem/NWChem-7.0.2-intel-2022a.eb#L6
Please use the current website
https://nwchemgit.github.io

https://github.com/easybuilders/easybuild-easyconfigs/commit/79e0cc97cdf70b8044d7e8f8aa61f3967e839c18

**Comment by boegel** [comment]
see also https://github.com/nwchemgit/nwchem/pull/204

**Comment by boegel** [comment]
The most recent easyconfig that still uses `https://www.nwchem-sw.org` is `NWChem-6.8.revision47-intel-2018a-2017-12-14-Python-2.7.14.eb`, which has been archived for the upcoming EasyBuild v5.0.0 release, so I'll close this.

For recent NWChem easyconfigs, this is fixed by:
* #18184
