### ISSUE TITLE
what is checksum algorithm used by easybuild?

### ISSUE THREAD

**Issue by yanchenmochen** [easybuilders/easybuild-easyconfigs#18000]
![image](https://github.com/easybuilders/easybuild-easyconfigs/assets/16216088/3f29a8ba-358d-400b-b4d7-0b600095e029)

**Comment by boegel** [comment]
These are SHA-256 checksums, see also https://docs.easybuild.io/writing-easyconfig-files/#common_easyconfig_param_sources_checksums

On Linux, you can compute these checksums using the `sha256sum` command, see also https://help.ubuntu.com/community/HowToSHA256SUM

**Comment by yanchenmochen** [comment]
Hi @boegel, That is a very concrete answer, solves the problem, Thank you very much
