### ISSUE TITLE
Qt5-5.15.7-GCCcore-12.2.0.eb fails with glibc 2.34 on Rocky 9

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#18209]
I think we are hitting the issues in https://github.com/easybuilders/easybuild-easyconfigs/commit/b2402aacc4132228b4bb277eaabeb2c85c1b8c46 with Qt5-5.15.7-GCCcore-12.2.0.eb

We use rocky 9 with glibc 2.34

**Comment by zao** [comment]
This easyconfig still appear to need both the glibc-related patches.
`Qt5-5.15.2_fix-qtwebengine-breakpad-glibc-2.34.patch` applies as-is.
`Qt5-5.15.7_fix-qtwebengine-abseil-cpp-glibc-2.34.patch` needs to be re-done as some of the surrounding context has changed, preventing a clean application.
