### ISSUE TITLE
Torchvision CUDA backend

### ISSUE THREAD

**Issue by boesr** [easybuilders/easybuild-easyconfigs#18391]
Hey everybody, 

I installed torchvision/0.13.1-foss-2022a-CUDA-11.7.0 and tried to run the following example script:

```python
import torch
import torchvision
import sys

print(sys.version)
print(torch.cuda.is_available())
print(torch.__version__)
print(torchvision.__version__)

device = 'cuda'
boxes = torch.tensor([[0., 1., 2., 3.]]).to(device)
scores = torch.randn(1).to(device)
iou_thresholds = 0.5

print(torchvision.ops.nms(boxes, scores, iou_thresholds))
```

This throws the following error:  `NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.`

Cuda is detected since the script prints:

```bash
3.10.4 (main, Sep 26 2022, 19:49:57) [GCC 11.3.0]
True
1.12.0
0.13.1
```

The error is the same if I run the script with a non-compatible (non-cuda) version. I already tried to create a custom easyconfig with `preinstallopts: "FORCE_CUDA=1"` but that didn't work either. 

Does someone else have the same problem or is there a fix for that?

PyTorch and Torchvision were built on a GPU node. 

Thanks in advance.

**Comment by boesr** [comment]
Will close that. Turns out it worked for some cpu architecture / generation. Probably a copying error during the build process.

**Comment by boegel** [comment]
@boesr May be related to a fix we implemented recently in the `torchvision` easyblock, see https://github.com/easybuilders/easybuild-easyblocks/pull/2931
