### ISSUE TITLE
Util-linux-2.39-GCCcore-12.3.0 fails to build on CentOS 7 (PER_LINUX_FDPIC undeclared)

### ISSUE THREAD

**Issue by casparvl** [easybuilders/easybuild-easyconfigs#18519]
```
  CC       lib/eject-monotonic.o
sys-utils/setarch.c:90:7: error: PER_LINUX_FDPIC undeclared here (not in a function); did you mean PER_LINUX_32BIT?
   90 |     X(PER_LINUX_FDPIC) \
      |       ^~~~~~~~~~~~~~~
sys-utils/setarch.c:345:27: note: in definition of macro X
  345 | #define X(opt) { .value = opt, .name = #opt },
      |                           ^~~
sys-utils/setarch.c:346:9: note: in expansion of macro ALL_PERSONALITIES
  346 |         ALL_PERSONALITIES
      |         ^~~~~~~~~~~~~~~~~
make[2]: *** [sys-utils/setarch.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/dev/shm/utillinux/2.39/GCCcore-12.3.0/util-linux-2.39'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/dev/shm/utillinux/2.39/GCCcore-12.3.0/util-linux-2.39'
make: *** [all] Error 2
```
Observed by @verdurin when testing another PR https://github.com/easybuilders/easybuild-easyconfigs/pull/18495#issuecomment-1671563570

Seems it should be provided by the kernel? https://docs.huihoo.com/doxygen/linux/kernel/3.7/uapi_2linux_2personality_8h.html

I created this issue for reference, as we didn't want it to block that (unrelated) PR.

**Comment by verdurin** [comment]
The build node is still running CentOS 7.

**Comment by verdurin** [comment]
I've reported this upstream at:

https://github.com/util-linux/util-linux/issues/2436

**Comment by verdurin** [comment]
I ran a test build of current git and that worked without error on CentOS 7. 
Had to disable the patch, which didn't apply.

**Comment by verdurin** [comment]
https://github.com/util-linux/util-linux/commit/2756f00407d3bc7dca3f5be0a0d101ef97e8eb5e

**Comment by schiotz** [comment]
I am seeing the same problem, could we perhaps add that patch to EasyBuild?

**Comment by SebastianAchilles** [comment]
Thanks @schiotz for adding the patch in #18855
