### ISSUE TITLE
EasyConfig build fails - OpenMM 7.5.1 and 7.7.0 with CUDA

### ISSUE THREAD

**Issue by fizwit** [easybuilders/easybuild-easyconfigs#18702]
EasyBuild log for [OpenMM-7.7.0-foss-2021a-CUDA-11.3.1.eb](https://gist.github.com/fizwit/b7ffb54884aff557347ebdd56edd27f3)

Issue: Build fails during Sanity Test,
exception: Error initializing context: clGetPlatformIDs (-1001)

Many of the tests want to use OpenCL
My build environment does not have OpenCL installed
The same build issue also happens with EasyConfig OpenMM-7.5.1-foss-2021b-CUDA-11.4.1-DeepMind-patch.eb

OpenMM-7.5.1 does not build the Python wrapper correctly. Only the EGG file is put into site-packages. (the CPU-only version for  7.5.1-foss-2020b does.)

**Comment by nd996** [comment]
To stop the OpenCL test being built, you could try setting `configopts = ' -DOPENMM_BUILD_OPENCL_TESTS=FALSE '` in the EasyConfig.

**Comment by fizwit** [comment]
Issue solved. The problem is not about missing OpenCL libraries. OpenMM creates the OpenCL libs needed to pass the OpenCL tests.  This is the actual error. 

```
/OpenMM/7.7.0/foss-2021a-CUDA-11.3.1/easybuild_obj$ ./TestOpenCLSettle
exception: Error initializing context: clGetPlatformIDs (-1001)
```

My build environment runs in a container that has access to GPUs.  nvidia-smi does work, and the build environment has access to the GPU. However, the container does not have this file, which is available on the Docker host system;  `/etc/OpenCL/vendors/nvidia.icd` Adding this file to the container fixes the OpenCL failed tests. Add the following to the Easybuild build container.

```
RUN mkdir -p /etc/OpenCL/vendors
COPY etc/nvidia.icd /etc/OpenCL/vendors/nvidia.icd
```
