### ISSUE TITLE
Perl problem with VCFtools

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#1878]
I've tried building VCFtools and it fails during the compilation of Perl:

== 2015-08-18 08:41:38,921 main.filetools DEBUG Possible new dir /home/operations/.local/easybuild/build/Perl/5.16.3/goolf-1.4.10/DB_File/DB_File-1.827 found
== 2015-08-18 08:41:38,921 main.run DEBUG run_cmd: running cmd  perl Makefile.PL PREFIX=/srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10  (in /home/operations/.local/easybuild/build/Perl/5.16.3/goolf-1.4.10/DB_File/DB_File-1.827)
== 2015-08-18 08:41:39,196 main.run DEBUG cmd " perl Makefile.PL PREFIX=/srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10 " exited with exitcode 0 and output:
Parsing config.in...
Looks Good.
Checking if your kit is complete...
Looks good
Note (probably harmless): No library found for -ldb
Writing Makefile for DB_File
Writing MYMETA.yml and MYMETA.json

== 2015-08-18 08:41:39,196 main.run DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|.?\w)
== 2015-08-18 08:41:39,197 main.run DEBUG run_cmd: running cmd  make -j 8  (in /home/operations/.local/easybuild/build/Perl/5.16.3/goolf-1.4.10/DB_File/DB_File-1.827)
== 2015-08-18 08:41:39,346 main.run DEBUG cmd " make -j 8 " exited with exitcode 2 and output:
gcc -c  -I/usr/local/BerkeleyDB/include -D_REENTRANT -D_GNU_SOURCE -fPIC -O2 -march=native -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"1.827\" -DXS_VERSION=\"1.827\" -fPIC "-I/srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10/lib/perl5/5.16.3/x86_64-linux-thread-multi/CORE"  -D_NOT_CORE  -DmDB_Prefix_t=size_t -DmDB_Hash_t=u_int32_t   version.c
/srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10/bin/perl /srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10/lib/perl5/5.16.3/ExtUtils/xsubpp -noprototypes -typemap /srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10/lib/perl5/5.16.3/ExtUtils/typemap -typemap typemap  DB_File.xs > DB_File.xsc && mv DB_File.xsc DB_File.c
Running Mkbootstrap for DB_File ()
chmod 644 DB_File.bs
cp DB_File.bs blib/arch/auto/DB_File/DB_File.bs
chmod 644 blib/arch/auto/DB_File/DB_File.bs
cp DB_File.pm blib/lib/DB_File.pm
AutoSplitting blib/lib/DB_File.pm (blib/lib/auto/DB_File)
version.c:30:16: fatal error: db.h: No such file or directory
compilation terminated.
make: **\* [version.o] Error 1
make: **\* Waiting for unfinished jobs....

== 2015-08-18 08:41:39,383 main ERROR cmd " make -j 8 " exited with exitcode 2 and output:
gcc -c  -I/usr/local/BerkeleyDB/include -D_REENTRANT -D_GNU_SOURCE -fPIC -O2 -march=native -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"1.827\" -DXS_VERSION=\"1.827\" -fPIC "-I/srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10/lib/perl5/5.16.3/x86_64-linux-thread-multi/CORE"  -D_NOT_CORE  -DmDB_Prefix_t=size_t -DmDB_Hash_t=u_int32_t   version.c
/srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10/bin/perl /srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10/lib/perl5/5.16.3/ExtUtils/xsubpp -noprototypes -typemap /srv/data/sw/eb/software/Perl/5.16.3-goolf-1.4.10/lib/perl5/5.16.3/ExtUtils/typemap -typemap typemap  DB_File.xs > DB_File.xsc && mv DB_File.xsc DB_File.c
Running Mkbootstrap for DB_File ()
chmod 644 DB_File.bs
cp DB_File.bs blib/arch/auto/DB_File/DB_File.bs
chmod 644 blib/arch/auto/DB_File/DB_File.bs
cp DB_File.pm blib/lib/DB_File.pm
AutoSplitting blib/lib/DB_File.pm (blib/lib/auto/DB_File)
version.c:30:16: fatal error: db.h: No such file or directory
compilation terminated.
make: **\* [version.o] Error 1
make: **\* Waiting for unfinished jobs....
 (at easybuild/tools/run.py:360 in parse_cmd_output)
== 2015-08-18 08:41:39,384 main.easyblock WARNING build failed (first 300 chars): cmd " make -j 8 " exited with exitcode 2 and output:
gcc -c  -I/usr/local/BerkeleyDB/include -D_REENTRANT -D_GNU_SOURCE -fPIC -O2 -march=native -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"1.827\" -DXS_VERSION=\"1.827\
== 2015-08-18 08:41:39,384 main.EB_Perl INFO Closing log for application name Perl version 5.16.3

Again this is on a CentOS 7.1. VM, using 2.2.0.

**Comment by boegel** [comment]
@verdurin: known (yet unresolved) issue, see https://github.com/hpcugent/easybuild-easyconfigs/issues/342

**Comment by boegel** [comment]
#913 may help in fixing this (i.e., either add `DB` as a dep to `Perl`, or flesh out `DB_File` form the `Perl` easyconfig)

**Comment by verdurin** [comment]
Thanks for the pointers. In the short term, I'm trying out the newer versions at:

http://www.molgenis.org/wiki/ComputeVM

I'll start work on a newer VCFtools .eb for the first GitHub release, too.

**Comment by Micket** [comment]
DB_File issues should be a thing of the past since we've had this for so long now. Closing.
