### ISSUE TITLE
SciPy-bundle-2023.07-gfbf-2023a.eb fails to build (self test crashes)

### ISSUE THREAD

**Issue by schiotz** [easybuilders/easybuild-easyconfigs#18859]
I am trying to build `SciPy-bundle-2023.07-gfbf-2023a.eb`, it works on the `Intel Cascade_Lake Xeon_Gold_6242R` but fails on the `IceLake Xeon_Gold_6348` with this error in the self-test:

```
scipy/integrate/tests/test__quad_vec.py::test_quad_vec_pool_args[1-extra_args1] PASSED                                           [ 11%]
scipy/integrate/tests/test__quad_vec.py::test_quad_vec_pool_args[10-2] Fatal Python error: Aborted
```

**Comment by boegel** [comment]
Hmm, this seems similar to the hard crash in #17539, but it's not a segmentation fault.

Maybe the test suite is consuming a significant amount of memory, and that's triggering the kernel to abort the process because it's running in a Slurm job where only a specific amount of memory is available?

**Comment by schiotz** [comment]
I am compiling on a login node, where memory is limited to 50GB per process.  Total memory is 500 GB. I really hope that is not too little to build SciPy-bundle. :-)

**Comment by schiotz** [comment]
Follow-up: It could very well be related to ressources - building on a compute node in a slurm job worked.  Thank you very much, indeed, for pointing me in the right direction.
