### ISSUE TITLE
MPI hanging if `MPI_Init_thread` used on generoso with foss/2023a (OpenMPI 4.1.5 / libfabric 1.18.0)

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-easyconfigs#18925]
It is hanging in the PSM3 provider in `libfabric`. We are seeing this when testing on generoso in #18443, #18444, #18731.

Error:
```
$ mpirun -n 2 ./a.out
login1:rank0.a.out: Failed to get eth0 (unit 0) cpu set
login1:rank0: PSM3 can't open nic unit: 0 (err=23)
login1:rank0: PSM3 can't open nic unit: 0 (err=23)
login1:rank0.a.out: Failed to get eth0 (unit 0) cpu set
login1:rank1: PSM3 can't open nic unit: 0 (err=23)
login1:rank1.a.out: Failed to get eth0 (unit 0) cpu set
login1:rank1.a.out: Failed to get eth0 (unit 0) cpu set
login1:rank1: PSM3 can't open nic unit: 0 (err=23)
```

If we control `libfabric` with `FI_PROVIDER` (such as `FI_PROVIDER="udp,tcp"` or `FI_PROVIDER="psm2"`) then the example completes. It fails if we set `FI_PROVIDER="psm3"`.

Running with FI_LOG_LEVEL=debug mpirun -n 2 ./a.out gives lots of output. I think the relevant line is
```
libfabric:3915417:1696406953::psm3:core:psmx3_trx_ctxt_alloc():320<warn> login1:rank1: psm3_ep_open returns 23, errno=2
```

From the code:
```
libfabric-1.18.0/prov/psm3/src/psmx3_util.c:    -FI_EIO,        /* PSM2_EP_DEVICE_FAILURE = 23 */
```

**Comment by boegel** [comment]
Also worth mentioning is that we're not seeing this with `OpenMPI/4.1.6-GCC-13.2.0` (libfabric 1.9.0)

**Comment by branfosj** [comment]
Also solve the issue:
* `PSM3_HAL=loopback`
* `PSM3_DEVICES=self`
* `FI_PROVIDER="^psm3"`

**Comment by boegel** [comment]
So, which option is the safest (in particular for `generoso`)?

**Comment by boegel** [comment]
workaround for `generoso`: https://github.com/boegel/boegelbot/pull/28

**Comment by boegel** [comment]
@branfosj We can close this one now, right?

**Comment by branfosj** [comment]
> @branfosj We can close this one now, right?

Yes.

For reference, we're decided on
```
PSM3_DEVICES='self,shm' 
```
as this fixed the issue we settee seeing and looked to be a change least likely to break anything else.

**Comment by branfosj** [comment]
Based on the issues in #17561, we'll change option https://github.com/boegel/boegelbot/pull/37
