### ISSUE TITLE
OpenBLAS build fails on Sapphire Rapids due to "Too many LAPACK tests failed"

### ISSUE THREAD

**Issue by robert-mijakovic** [easybuilders/easybuild-easyconfigs#19021]
Hi guys,

while building OpenBLAS on Sapphire Rapids running Ubuntu 22.04LTS, I faced "Too many LAPACK tests failed due to non-numerical errors: 55 (> 0)".

```
                        -->   LAPACK TESTING SUMMARY  <--
SUMMARY                 nb test run     numerical error         other error
================        ===========     =================       ================
REAL                    1328283         0       (0.000%)        0       (0.000%)
DOUBLE PRECISION        1325997         11      (0.001%)        0       (0.000%)
COMPLEX                 760371          160     (0.021%)        55      (0.007%)
COMPLEX16               771518          48      (0.006%)        0       (0.000%)

--> ALL PRECISIONS      4186169         219     (0.005%)        55      (0.001%)
```

Are we too restrictive on tolerance?
I will look further to see whether I can find a trace of recent patches in OpenBLAS. So far, I haven't seen anything.
For the moment, I will stick to `--ignore-test-fail` when installing OpenBLAS 0.3.24 on Sapphire Rapids.

Best regards,
Robert

**Comment by Flamefire** [comment]
I'm seeing the same issue with
- OpenBLAS/0.3.20-GCC-11.2.0
- OpenBLAS/0.3.20-GCC-11.3.0
- OpenBLAS/0.3.21-GCC-12.2.0
- OpenBLAS/0.3.23-GCC-12.3.0

after patching OpenBLAS to detect the Rapids (https://github.com/easybuilders/easybuild-easyconfigs/pull/19141)
