### ISSUE TITLE
ASE is on wrong toolchain level in foss/2023 (should be gfbf/2023a)

### ISSUE THREAD

**Issue by schiotz** [easybuilders/easybuild-easyconfigs#19039]
I was asked to move the ASE package was from the foss level to the gfbf level with the 2022b toolchains.  

Unfortunately, somebody beat me to adding it to the 2023a toolchain, and it is back at the foss level, forcing packages that depend on ASE to be at that level too.  It has not yet been released, so it is not too late to move it to gfbf/2023a.

I'll submit a PR doing that.

**Comment by boegel** [comment]
fixed in #19040
