### ISSUE TITLE
JupyterLab paths are wrong

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#19097]
Loading our jupyter labs modules and checking paths shows we currently end up with something like:

```bash
$ jupyter --paths
config:
    /apps/Arch/software/JupyterLab/3.5.0-GCCcore-11.3.0/etc/jupyter
    /apps/Arch/software/IPython/8.5.0-GCCcore-11.3.0/etc/jupyter
    /cephyr/users/ohmanm/Vera/.jupyter
    /cephyr/users/ohmanm/Vera/.local/etc/jupyter
    /apps/Arch/software/Python/3.10.4-GCCcore-11.3.0/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /apps/Arch/software/JupyterLab/3.5.0-GCCcore-11.3.0/share/jupyter
    /apps/Arch/software/IPython/8.5.0-GCCcore-11.3.0/share/jupyter
    /cephyr/users/ohmanm/Vera/.local/share/jupyter
    /apps/Arch/software/Python/3.10.4-GCCcore-11.3.0/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /cephyr/users/ohmanm/Vera/.local/share/jupyter/runtime
```

The issues are:
1. Installation directories end up first. This means this  is the path that jupyter lab will try to save it's settings. Obviously won't work, so, it's basically broken from the user perspective.
2. It's adding a pointless python sysroot path `/apps/Arch/software/Python/3.10.4-GCCcore-11.3.0/etc/jupyter` which wouldn't even exist. 

The goal should be to obtain this:
```bash
$ jupyter --paths
config:
    /cephyr/users/ohmanm/Vera/.jupyter
    /cephyr/users/ohmanm/Vera/.local/etc/jupyter
    /apps/Arch/software/JupyterLab/3.5.0-GCCcore-11.3.0/etc/jupyter
    /apps/Arch/software/IPython/8.5.0-GCCcore-11.3.0/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /cephyr/users/ohmanm/Vera/.local/share/jupyter
    /apps/Arch/software/JupyterLab/3.5.0-GCCcore-11.3.0/share/jupyter
    /apps/Arch/software/IPython/8.5.0-GCCcore-11.3.0/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /cephyr/users/ohmanm/Vera/.local/share/jupyter/runtime
```

which I think we achieve by **not** touching `JUPYTER_CONFIG_PATH`  (like we incorrectly do today), but i'm not 100% sure what we should do to achieve this. 
The logic for these paths are here:
https://github.com/jupyter/jupyter_core/blob/aa7b722e957e07e1979c03a6000f06c125fe4932/jupyter_core/paths.py#L230

What we really want is to put IPytyon and JupyterLab into `SYSTEM_JUPYTER_PATH` only, but I'm not sure this can be achieved with just environment variables.

This is primarily a problem with `config` paths, but maybe could also cause similar issues with `data`.

**Comment by Micket** [comment]
I guess we should have our JupyterLab path should show up in platformdirs.site_config_dir(...), then just drop the extra envrionment variables we set.

https://github.com/jupyter/jupyter_core/blob/aa7b722e957e07e1979c03a6000f06c125fe4932/jupyter_core/paths.py#L290C39-L290C54

**Comment by Micket** [comment]
Unfortunattely, the part where I would have loked to add the IPython and JupyterLab paths is hardcoded to be only the sys.prefix.

```
ENV_JUPYTER_PATH = [os.path.join(sys.prefix, "share", "jupyter")]
...
ENV_CONFIG_PATH = [os.path.join(sys.prefix, "etc", "jupyter")]
```

and `SYSTEM_CONFIG_PATH` is also hardcoded only. 

Don't think there is a way out of this without a patch to allow us to interject into `ENV_{JUPYTER/CONFIG}_PATH`.

**Comment by Flamefire** [comment]
> Yes. I included the goal output in my previous message which I think is the desired output. I think the core issue is relatively simple: Our modules JupyterLab and IPython should be considered "system" installations that should go into SYSTEM_CONFIG_PATH's, and we should not touch JUPYTER_CONFIG_PATH or try to change any other default behavior.
> 
> The problem is that Jupyter assumes that there is just 1 system level path and it has to be under `sys.prefix`, thus they use exatcly 1 path and it's `os.path.join(sys.prefix, "etc", "jupyter")`, but our modules are spread out so we couldn't use that (without patching).
> 
> The (nonexistent) `/apps/Arch/software/Python/3.10.4-GCCcore-11.3.0/etc/jupyter` path should be replaced by `/apps/Arch/software/JupyterLab/3.5.0-GCCcore-11.3.0/etc/jupyter` and `/apps/Arch/software/IPython/8.5.0-GCCcore-11.3.0/etc/jupyter`. I think we want a patch and a custom environment variable set in IPython and JupyterLab.

Indeed as we have a custom use case we need a custom patch and can't reasonably expect this to be changed upstream.    

I checked JupyterLab-1.2.5-fosscuda-2019b-Python-3.7.4 and there it looks alright:
```
config:
    /home/h3/s3248973/.jupyter
    /sw/installed/Python/3.7.4-GCCcore-8.3.0/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/h3/s3248973/.local/share/jupyter
    /sw/installed/Python/3.7.4-GCCcore-8.3.0/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/h3/s3248973/.local/share/jupyter/runtime
```

However in JupyterLab-3.5.0-GCCcore-11.3.0.eb we additionally have 
```
modextrapaths = {
    'JUPYTER_PATH': 'share/jupyter',
    'JUPYTER_CONFIG_PATH': 'etc/jupyter',
}
modextravars = {
    # only one path allowed as JUPYTERLAB_DIR
    'JUPYTERLAB_DIR': '%(installdir)s/share/jupyter/lab',
}

# keep user's configuration in their home directory
# note: '~' is not expanded by JupyterLab
modluafooter = """
setenv("JUPYTERLAB_SETTINGS_DIR", pathJoin(os.getenv("HOME"), ".jupyter", "lab", "user-settings"))
setenv("JUPYTERLAB_WORKSPACES_DIR", pathJoin(os.getenv("HOME"), ".jupyter", "lab", "workspaces"))
"""
modtclfooter = """
setenv JUPYTERLAB_SETTINGS_DIR "$::env(HOME)/.jupyter/lab/user-settings"
setenv JUPYTERLAB_WORKSPACES_DIR "$::env(HOME)/.jupyter/lab/workspaces"
"""
```

Checking further I have `$JUPYTER_CONFIG_PATH` set by `JupyterLab`, `jupyter-server` and `IPython` and as metnioned before that variable takes precedence. However I assume we do need it such that those modules work.

So:

> The issues are:
> 
> -    Installation directories end up first. This means this is the path that jupyter lab will try to save it's settings. Obviously won't work, so, it's basically broken from the user perspective.

Are you sure this is the case? Because there is [`jupyter_config_dir()`](https://github.com/jupyter/jupyter_core/blob/aa7b722e957e07e1979c03a6000f06c125fe4932/jupyter_core/paths.py#L133C5-L133C23) which I guess is used for that and that uses the home directory. Have you found this to be an actual issue and have a traceback where `jupyter_config_path()[0]` is actually used? I'd assume it uses `jupyter_config_dir()`

> -    It's adding a pointless python sysroot path /apps/Arch/software/Python/3.10.4-GCCcore-11.3.0/etc/jupyter which wouldn't even exist.

So `ENV_JUPYTER_PATH`. We could patch this such that it retains only existing paths.

Or as a larger change: Instead of modules adding to `JUPYTER_CONFIG_PATH` they add to something we patch to go into `ENV_JUPYTER_PATH`, e.g. `$EB_ENV_JUPYTER_PATH` and use that instead (requires changing all modules...)
Or we change `jupyter_path` to add `$JUPYTER_PATH` to `env`, i.e. https://github.com/jupyter/jupyter_core/blob/aa7b722e957e07e1979c03a6000f06c125fe4932/jupyter_core/paths.py#L254-L256 goes after https://github.com/jupyter/jupyter_core/blob/aa7b722e957e07e1979c03a6000f06c125fe4932/jupyter_core/paths.py#L271 replacing `paths.extend` by `env.extend` but that may break user assumption about `$JUPYTHER_PATH` taking highest priority.

**Comment by Micket** [comment]
> I checked JupyterLab-1.2.5-fosscuda-2019b-Python-3.7.4 and there it looks alright:

yes though that was missing the config path that we do want to add (`/apps/Arch/software/JupyterLab/3.5.0-GCCcore-11.3.0/etc/jupyter`).

> Are you sure this is the case? Because there is [jupyter_config_dir()](https://github.com/jupyter/jupyter_core/blob/aa7b722e957e07e1979c03a6000f06c125fe4932/jupyter_core/paths.py#L133C5-L133C23) which I guess is used for that and that uses the home directory.

Ah, apparently I had an older build of JupyterLab, before that extra modluafooter was added (surely to work around this problem).
Without that, trying to e.g. change a theme you end up with
```
[W 2023-11-07 18:19:13.515 ServerApp] 500 PUT /lab/api/settings/@jupyterlab/apputils-extension:themes?1699377553506 (127.0.0.1): Failed writing settings (@jupyterlab/apputils-extension:themes): [Errno 30] Read-only file system: '/apps/Arch/software/JupyterLab/3.5.0-GCCcore-11.3.0/etc/jupyter/lab'
[W 2023-11-07 18:19:13.516 LabApp] wrote error: "Failed writing settings (@jupyterlab/apputils-extension:themes): [Errno 30] Read-only file system: '/apps/Arch/software/JupyterLab/3.5.0-GCCcore-11.3.0/etc/jupyter/lab'"
```
due to JUPYTER_CONFIG_PATH being set.

Still, I think we shouldn't do this and have this workaround; user should be able to override jupyter_server_config.d and all that other stuff if they want, and I bet there are other corner cases as well (e.g. we should still have our configs (as lower priority) even if the user chooses to set their own JUPYTER_CONFIG_PATH)

> Or as a larger change: Instead of modules adding to JUPYTER_CONFIG_PATH they add to something we patch to go into ENV_JUPYTER_PATH, e.g. $EB_ENV_JUPYTER_PATH and use that instead (requires changing all modules...)

This is what I was thinking yes. That is where the main Python module currently gets added (as a side effect of being the sys.prefix and Jupyter assuming that's where jupyter was installed) so it seems right to me that the other modules go there as well.
Apart from that there shouldn't be any need to mess with any other environment variables or use any footers.
