### ISSUE TITLE
Is the SYSTEM toolchain for Catch2 the reasonable choice?

### ISSUE THREAD

**Issue by HPC-UniOldenburg** [easybuilders/easybuild-easyconfigs#19188]
I was recently confused by Catch2 appearing in a list of dependencies to be installed. The confusion was that Catch2 itself required a lot of additional dependencies, in particular the complete GCCcore 10.x with matching binutils. This seems wrong to me, it should either be SYSTEM and use the system compiler (and a system CMake or a CMake build with SYSTEM) or it should be built with the GCCcore toolchain. 

It seems to be mostly needed as dependency for pybind11-2.10.3-GCCcore-12.2.0.eb and pybind11-2.11.1-GCCcore-12.3.0.eb which means that in the current setup you install GCCcore 12.x and GCCcore 10.x if you install one of the two pybind11 modules.

**Comment by boegel** [comment]
Very good point, I ran into this myself recently, and fixed it, see PR #19270
