### ISSUE TITLE
Ensuring Fortran modules do not end up at `GCCcore`

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyconfigs#19287]
There's currently no check to ensure that Fortran modules do not end up at `GCCcore` level. It's a tricky one to catch as the builds have no problem. Can we implement something in CI to help with this?

Fixes are tedious and quite intrusive: see https://github.com/easybuilders/easybuild-easyconfigs/pull/19283

**Comment by branfosj** [comment]
See my (limited) notes in https://github.com/easybuilders/easybuild-framework/issues/4203

**Comment by ocaisa** [comment]
Perhaps this is something we can fix at a framework level by shadowing `gfortran` with something that prints something useful and exits with an error.

**Comment by ocaisa** [comment]
Wrapping the compiler is perhaps too aggressive, I think I probably agree with @branfosj that we should search for .mod files.

**Comment by branfosj** [comment]
See https://github.com/easybuilders/easybuild-framework/pull/4389

**Comment by ocaisa** [comment]
Fix is in for 5.0
