### ISSUE TITLE
CUDA/10.0.130 builds on Skylake GPU nodes, but not on Cascadelake GPU nodes

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#19345]
I am repeating the installation of `CUDA/10.0.130` module under the 2019b toolchain on our Cascadelake GPU servers (on VSC Genius cluster). I get the following error during the copy step:
```
ERROR: Build of /apps/leuven/rocky8/skylake/2019b/software/CUDA/10.0.130/easybuild/CUDA-10.0.130.eb failed (err: "build failed (first 300 chars): Failed to copy directory /apps/leuven/rocky8/cascadelake/2019b/software/CUDA/10.0.130/lib64/stubs to /apps/leuven/rocky8/cascadelake/2019b/software/CUDA/10.0.130/stubs/lib64: [Errno 2] No such file or directory: '/apps/leuven/rocky8/cascadelake/2019b/software/CUDA/10.0.130/lib64/stubs'"
```
The full debug log is attached.

Around the same copy step, I see the following logline after the successful (re)build for the Skylake GPU servers.
```
== 2023-07-28 11:35:15,802 run.py:233 INFO running cmd: /sbin/ldconfig -N /apps/leuven/rocky8/skylake/2019b/software/CUDA/10.0.130/lib64/stubs
== 2023-07-28 11:35:16,061 filetools.py:2538 INFO /apps/leuven/rocky8/skylake/2019b/software/CUDA/10.0.130/lib64/stubs copied to /apps/leuven/rocky8/skylake/2019b/software/CUDA/10.0.130/stubs/lib64
== 2023-07-28 11:35:16,062 filetools.py:337 INFO Symlinked lib64 to /apps/leuven/rocky8/skylake/2019b/software/CUDA/10.0.130/stubs/lib
```
This surprises me because using the same easyconfig file ends up creating the module seamlessly on a Skylake node! Both node architectures run under an identical OS image (Rocky Linux 8.8). 

Any idea why in this case, the simple copy fails?

[easybuild-CUDA-10.0.130-20231201.234317.FPopu.log](https://github.com/easybuilders/easybuild-easyconfigs/files/13544994/easybuild-CUDA-10.0.130-20231201.234317.FPopu.log)

**Comment by MaximeVdB** [comment]
The `easybuild-...-test_report.md` file of the Skylake installation indicates that a modified `cuda.py` easyblock was used (which shows the addition of an `--override` install option). When using the same easyblock the installation (for Cascadelake) does go to completion. More recent CUDA releases don't seem to need this extra install option.

**Comment by moravveji** [comment]
Thanks @MaximeVdB for the tip. Indeed, I could reproduce the build with that.
Closing this issue now.
