### ISSUE TITLE
PAPI-7.0.1-GCCcore-12.2.0.eb gets stuck in testing

### ISSUE THREAD

**Issue by dirkpetersen** [easybuilders/easybuild-easyconfigs#19437]
PAPI-7.0.1-GCCcore-12.2.0.eb ran for many hours and got stuck in testing with no cpu utilization, so i needed to kill it.

[PAPI-7.0.1-GCCcore-12.2.0.eb-easybuild-PAPI-7.0.1-20231216.192244.HMeUz.log](https://github.com/easybuilders/easybuild-easyconfigs/files/13697238/PAPI-7.0.1-GCCcore-12.2.0.eb-easybuild-PAPI-7.0.1-20231216.192244.HMeUz.log)

```
 Installing PAPI-7.0.1-GCCcore-12.2.0.eb ... 

WARNING: signal received (15), cleaning up locks (_opt_eb_software_PAPI_7.0.1-GCCcore-12.2.0)...

== Temporary log file in case of crash /tmp/eb-321gwg1s/easybuild-2p4hvtuf.log
== found valid index for /home/ec2-user/.local/easybuild/easyconfigs, so using it...
== found valid index for /home/ec2-user/.local/easybuild/easyconfigs, so using it...
== resolving dependencies ...
== processing EasyBuild easyconfig /home/ec2-user/.local/easybuild/easyconfigs/p/PAPI/PAPI-7.0.1-GCCcore-12.2.0.eb
== building and installing PAPI/7.0.1-GCCcore-12.2.0...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== ... (took 5 secs)
== building...
== ... (took 14 secs)
== testing...
== ... (took 13 hours 28 mins 54 secs)
*** EASYBUILD RETURNCODE: 15
```

**Comment by branfosj** [comment]
Does the change in  #19372 fix this for you?

**Comment by dirkpetersen** [comment]
Ah, I did check issues but not PR. Good that it is being addressed, I have no idea what PAPI does. it am just doing some automated  builds and when somethings gets stuck like that the pipeline never finishes. You can close this one
