### ISSUE TITLE
Problem installing GCC version 13 with EasyBuild using Slurm

### ISSUE THREAD

**Issue by AnDreW-21** [easybuilders/easybuild-easyconfigs#19544]
# Description:
I am attempting to install GCC version 13 using EasyBuild with Slurm as the job manager. However, I am encountering the following error:

### EasyBuild crashed with an error (at easybuild/software/EasyBuild/4.8.2/lib/python3.6/site-packages/easybuil/base/exceptions.py:126 in __init__)   
configure: error: cannot run C compiled programs.
 -----------------------------------------------------------------------------------------------------------------------------

### I try to install it using the following command:
``` eb GCC-13.2.0.eb --job --job-cores 8 --tmp-logdir $HOME/eb_tmplogs  ```

### Environment:

1. EasyBuild Version:  4.8.2
2. GCC Version:  8.5.0
3.  Slurm Version:  23.11.1

Additional Information:

# config.log
```
cc version 8.5.0 20210514 (Red Hat 8.5.0-18) (GCC)
configure:4407: $? = 0
configure:4396: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4407: $? = 1
configure:4396: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:4407: $? = 1
configure:4427: checking whether the C compiler works
configure:4449: gcc    conftest.c  >&5
configure:4453: $? = 0
configure:4501: result: yes
configure:4504: checking for C compiler default output file name
configure:4506: result: a.out
configure:4512: checking for suffix of executables
configure:4519: gcc -o conftest    conftest.c  >&5
configure:4523: $? = 0
configure:4545: result:
configure:4567: checking whether we are cross compiling
configure:4575: gcc -o conftest    conftest.c  >&5
conftest.c:9:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
configure:4579: $? = 1
configure:4586: ./conftest
../configure: line 4588: ./conftest: No such file or directory
configure:4590: $? = 127
configure:4597: error: in "/GCCcore/13.2.0/system-system/gcc-13.2.0/stage1_obj':
configure:4599: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```

**Comment by Micket** [comment]
This looks like your OS compiler doesn't have stdio.h?
I strongly believe you simply are missing glibc-headers, without which you won't be able to bootstrap the compilers
