### ISSUE TITLE
Affymetrix Power Tools

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#1957]
One of our users needs to run this suite, so I'll be creating an easyconfig, unless someone else already has one...

**Comment by rjeschmi** [comment]
I don't think there is. I tried for a bit, but settled for the binary version since it wasn't really that useful to our users.

I'll test it if you make it though.

**Comment by Micket** [comment]
I don't think we need to have an issue for software, i'm sure if someone needs this, they will just create a Tarball package system level binary installs and be happy with this. PR's welcome.
