### ISSUE TITLE
toolchain system

### ISSUE THREAD

**Issue by gcpmendez** [easybuilders/easybuild-easyconfigs#19680]
Is it normal for an easybuild file with system toolchain to have gcc/10.2.0 as a dependency? shouldn't it get GCC from the system itself?

[https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/c/Catch2/Catch2-2.13.9.eb
](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/c/Catch2/Catch2-2.13.9.eb
)
```
easyblock = 'CMakeMake'

name = 'Catch2'
version = '2.13.9'

homepage = 'https://github.com/catchorg/Catch2'
description = """A modern, C++-native, header-only,
 test framework for unit-tests, TDD and BDD
 - using C++11, C++14, C++17 and later
"""

toolchain = SYSTEM

source_urls = ['https://github.com/catchorg/Catch2/archive/']
sources = ['v%(version)s.tar.gz']
checksums = ['06dbc7620e3b96c2b69d57bf337028bf245a211b3cddb843835bfe258f427a52']

# using CMake built with GCCcore to avoid relying on the system compiler to build it
builddependencies = [
    ('GCCcore', '10.2.0'),  # required to a access CMake when using hierarchical module naming scheme
    ('binutils', '2.35', '', ('GCCcore', '10.2.0')),  # to make CMake compiler health check pass on old systems
    ('CMake', '3.18.4', '', ('GCCcore', '10.2.0')),
]

separate_build_dir = True

sanity_check_paths = {
    'files': [],
    'dirs':  ['include/catch2', 'lib64/cmake'],
}

moduleclass = 'lib'
```

**Comment by cishard** [comment]
As far as I unsterstand Easybuild try to build the software very consistent. Therefore it makes a difference if software was built with GCC 5.2.3 or with GCC 10.2.0 or your system GCC Compiler. Therefore it makes sense to mark compiler as dependencies. I hope my answer helpd you.

**Comment by gcpmendez** [comment]
thanks for your reply,

In this case I think it is appropriate to clarify the toolchain in the name of the file, Catch2/2.13.9-GCCcore-10.2.0.

I had a problem compiling a software and I had to go down through the dependencies until I found this one where the dependency is gcc and it is not defined inside the corresponding toolchain.

Regards,
Germán.

**Comment by cishard** [comment]
Partially it is. But i don't understand the inconsistency in the Catch2 naming.

**Comment by gcpmendez** [comment]
![image](https://github.com/easybuilders/easybuild-easyconfigs/assets/10725162/b49a47f0-69ad-4abb-a673-17a824a8058a)

The inconsistency is that dependencies have been added with gcc/10.2.0 when trying to compile other software which in turn pulls from it, which is illogical as it belongs to foss/2022b which in turn pulls from gcc/12.2.0.

But I suppose this is somewhat possible and that in some cases, even with the SYSTEM toolchain, you can specify the compiler version as GCC which appears in the dependencies. Maybe to avoid problems with the system compiler.

**Comment by gcpmendez** [comment]
I mean we are mixing GCC versions. I understand that we can but it can lead to some confusion.

**Comment by cishard** [comment]
Yeah, probably someone was lazy there and didn't want to adapt to compile the software with gcc12 or there were special requirements which only fullfils the gcc 10.2.0 compiler.
