### ISSUE TITLE
Arpack-ng 3.8.0 and 3.9.0 easyconfigs quietly fail to install any of the .f files

### ISSUE THREAD

**Issue by rlpitts** [easybuilders/easybuild-easyconfigs#19930]
I've tried installing both Arpack-ng/3.8.0 and 3.9.0. In both cases, the .so, .h, make files, etc are all there, but not a single .f file has been installed, let alone SRC, UTIL, and other directories visible on the Arpack-ng github page. What happened?

**Comment by branfosj** [comment]
We use a standard `configure` / `make` / `make install` process to build `arpack-ng`. This matches one of the methods documented in the `arpack-ng` [README](https://github.com/opencollab/arpack-ng/blob/master/README.md). This process compiles the `.f` files into the libraries that get installed. I've also checked with the other documented build option, which uses `CMake`, and the install is similar.

For software built in this way I'd not expect the `.f` to be in the installed items.

**Comment by rlpitts** [comment]
It was explained to me by my superior. The problem is with the package calling it, not this distribution. For some reason the other software cannot find the compiled functions, only the .f versions.
