### ISSUE TITLE
Look into failed tests in PyTorch 2.1.2 w/ foss 2023a + CUDA

### ISSUE THREAD

**Issue by jfgrimm** [easybuilders/easybuild-easyconfigs#19946]
Saw:

- `1x H100, AMD EPYC 7413` :`22 test failures, 0 test errors (out of 210827)`
- `1x  A40, AMD EPYC 7643`: `42 test failures, 0 test errors (out of 210875)`

I'll plan to take a closer look at failures, so we can decrease the `max_failed_tests` again

**Comment by Flamefire** [comment]
8x A100, AMD EPYC 7352: `7 test failures, 0 test errors (out of 211121):`
- distributed/checkpoint/test_fsdp_optim_state
- distributed/fsdp/test_fsdp_tp_integration
- distributed/fsdp/test_shard_utils
- distributed/tensor/parallel/test_tp_random_state
- test_nn
- test_torch --> Completely fails with some
    > UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 96: ordinal not in range(128)
