### ISSUE TITLE
Building VSCode-1.85.0.eb fails because the checksum has changed

### ISSUE THREAD

**Issue by cjroberts** [easybuilders/easybuild-easyconfigs#19950]
Hello, I am trying to build VSCode-1.85.0.eb. It fails because the checksum for the code from https://code.visualstudio.com/sha/download?build=stable&os=linux-x64&code-stable-x64-1701901635.tar.gz has changed to `cf3d4ac7ebbd4161284c7fa3ff9132c94b69052ad8a23761243d9e4b08c6df9d`. Please could this be fixed?

**Comment by Micket** [comment]
Seems like checksums aren't stable for this source. Dropped the checksum in #19995
