### ISSUE TITLE
failing rpath sanity checks for OCaml 4.14.0

### ISSUE THREAD

**Issue by jfgrimm** [easybuilders/easybuild-easyconfigs#20021]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/19997

rpath checks fail for `bin/{opam,opam-installer}`

**Comment by boegel** [comment]
@jfgrimm duplicate of https://github.com/easybuilders/easybuild-easyblocks/issues/3247, which has more details ;)

**Comment by jfgrimm** [comment]
oops
