### ISSUE TITLE
Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb bogus atime tests, failed on NFS

### ISSUE THREAD

**Issue by spacelama** [easybuilders/easybuild-easyconfigs#20145]
atime tests are almost entirely useless these days, and there's little point in perl installation trying to police optional operating system functionality anymore, given operating systems don't honour the atime promises they once made. Also, we're not just trying to install on ext4 filesystems.  NFS is particularly prone to file modification/creation/access time issues.

```
== 2024-03-19 14:19:17,857 run.py:247 INFO running cmd: make test 
"/usr/local/easybuild/4.6.0/software/Perl/5.36.1-GCCcore-12.3.0/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- HiRes.bs blib/arch/auto/Time/HiRes/HiRes.bs 644
PERL_DL_NONLAZY=1 "/usr/local/easybuild/4.6.0/software/Perl/5.36.1-GCCcore-12.3.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/alarm.t ......... ok
t/clock.t ......... ok
t/gettimeofday.t .. ok
t/itimer.t ........ ok
t/nanosleep.t ..... ok
t/sleep.t ......... ok
t/stat.t .......... ok
t/time.t .......... ok
t/tv_interval.t ... ok
t/ualarm.t ........ ok
t/usleep.t ........ ok

#   Failed test 'atime set correctly'
#   at t/utime.t line 150.
#          got: '2.222222222'
#     expected: '1.111111111'

#   Failed test 'atime set correctly'
#   at t/utime.t line 162.
#          got: '2.222222222'
#     expected: '1.111111111'

#   Failed test 'File 1 atime set correctly'
#   at t/utime.t line 189.
#          got: '2.222222222'
#     expected: '1.111111111'

#   Failed test 'File 2 atime set correctly'
#   at t/utime.t line 197.
#          got: '2.222222222'
#     expected: '1.111111111'
# Looks like you failed 4 tests of 22.
t/utime.t ......... 
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/22 subtests 

Test Summary Report
-------------------
t/utime.t       (Wstat: 1024 (exited 4) Tests: 22 Failed: 4)
  Failed tests:  2, 5, 12, 14
  Non-zero exit status: 4
Files=12, Tests=118, 30 wallclock secs ( 0.05 usr  0.02 sys + 14.49 cusr  0.17 csys = 14.73 CPU)
Result: FAIL
Failed 1/12 test programs. 4/118 subtests failed.
make: *** [Makefile:1070: test_dynamic] Error 4
```

This is an ancient Perl bug finally acknowledged here: https://github.com/Perl/perl5/issues/19737
https://rt.cpan.org/Public/Bug/Display.html?id=116127
Various other bugs exist which point out timelines such as this:
https://github.com/arsv/perl-cross/issues/36

Supposedly it's fixed in 1.9740, but Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb is trying to install Time::HiRes 1.9764.

Suspect given how long it's remained in upstream (I think I found bugs where they said it was closed circa ~5.26, and then reading the comments it was clear the author had no idea why and when they were testing, and it's clearly still there for other filesystem types), I suspect it's more prudent to apply an extra patch in EB completely disabling that test.

Annoyingly, these tests don't get skipped if you try to supply any of the --skip-test-step --ignore-test-failure --skipo-test-cases etc.

**Comment by casparvl** [comment]
Hm, my guess is the reason `--skip-test-step` and friends do not work because this is a bundle. I.e. the `test-step` of the bundle would be skipped, but the test step of each of the extensions isn't. But it should be quite clear from the EasyBuild logs if you are already in the 'extensions'  step.

You could try setting `runtest` to `False` for this particular extension. I'm not 100% sure if that'll work, but from looking at the `PerlModule` EasyBlock, particularly [this line](https://github.com/easybuilders/easybuild-easyblocks/blob/99173c4ad927595100d0124228b2e1007bce7413/easybuild/easyblocks/generic/perlmodule.py#L106) I think that should do the trick and skip the tests for that extension.
