### ISSUE TITLE
Python version within toolchains

### ISSUE THREAD

**Issue by hajgato** [easybuilders/easybuild-easyconfigs#2020]
I would like to open a discussion about different version of Python within a toolchain. I think we should stick to one version of python (and maybe one perl) version for each toolchain, especially for the fast changing ones. Opinions? (see for example the compications PR #1627

**Comment by fgeorgatos** [comment]
IMHO, the choice of version is more often than not successful within a scientific domain's context, given that groups of scientists tend to cluster together around specific versions (yeah, sad but true).

In the past it has been the case that certain versions were more popular than others (fi. python/2.7.3), yet this is merely a coincidence and it is difficult to know in advance which version of a tool will become successful (often a bug-free longstanding release). For a related discussion, check also #1689 .

**Comment by Micket** [comment]
We do this nowadays.
