### ISSUE TITLE
Overlap between UCSC-tools and BLAT?

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#2021]
(Raising this here so it can be discussed before submission)

I'm working on an easyconfig for the UCSC tools (sometimes known as the Jim Kent tools). BLAT is one of those tools, and also includes a very small subset of the very large tool collection.

In case that my version is more up to date, is the preferred approach for me to exclude what's in BLAT from UCSC-tools, then submit a separate PR to update BLAT?

**Comment by boegel** [comment]
@verdurin: I think it's OK to have an easyconfig for the whole 'suite' of UCSC tools, even if we already have easyconfigs for BLAT separately.

An update for BLAT is also welcome, of course. :)

**Comment by Micket** [comment]
The need for this seems to have not been so great. Closing.
