### ISSUE TITLE
XZ uninstallable due to URL being down (security backdoor etc).

### ISSUE THREAD

**Issue by hattom** [easybuilders/easybuild-easyconfigs#20266]
I think many of us have probably heard of the XZ situation.

the URL in the easyconfig files points to `https://tukaani.org/xz`, and `https://tukaani.org/xz/xz-5.4.4.tar.bz2` redirects to `https://github.com/tukaani-project/xz/releases/download/v5.4.4/xz-5.4.4.tar.bz2`.
The github repo has been suspended, so the package cannot be installed.

Looks like there were not any EB configs for the affected versions (5.6.0 & 5.6.1 were backdoored), but also the older versions can't be installed at present for the reason able.

**Comment by branfosj** [comment]
The XZ GitHub has been restored, so these downloads are available again.
