### ISSUE TITLE
CuPy requires --cuda-compute-capabilities flag to install on some systems

### ISSUE THREAD

**Issue by stevecdavis** [easybuilders/easybuild-easyconfigs#20305]
Installing CuPy on a system that does not have cuda_cc_cmake variable set throws an error requiring the flag --cuda-compute-capabilities flag to be set. 

It'd be beneficial if there are no cuda compute capabilities specified it'd throw an error and not crash hard. 
It might also be helpful if the error gave a little direction i.e. - 
"Look here to confirm your compute capabilities - https://en.wikipedia.org/wiki/CUDA#GPUs_supported"

**Comment by Micket** [comment]
This will error out in 5.0.x as we have made unresolved template arguments hard errors (i.e. "%(cuda_cc_cmake)s"  would become an error. 

This flag should always be set, as part of the main configuration for the software stack one is building, when dealing with any CUDA software, so it's not specific to CuPy. One should always set cuda_compute_capabilities.
