### ISSUE TITLE
GROMACS 2024.1 test fails due to time outs on AMD-ZEN2 .

### ISSUE THREAD

**Issue by satishskamath** [easybuilders/easybuild-easyconfigs#20323]
A link to the issue: https://gitlab.com/gromacs/gromacs/-/issues/5062

**Comment by ocaisa** [comment]
Are you using OpenMPI with the patch that appeared in 4.9.1?

**Comment by ocaisa** [comment]
And/or are you disabling libfabric? Not sure which, but one or both of these seemed to have resolved similar issues for EESSI

**Comment by boegel** [comment]
@satishskamath Any updates on this?

**Comment by satishskamath** [comment]
I have the run going with twice the timeout limit. I will update once it finishes here.

**Comment by satishskamath** [comment]
I ran it with 4 times the default tolerance but still 1 test fails due to time out. 
```
The following tests FAILED:
	 65 - MdrunIOTests (Timeout)
```
So I presume there is more going on. Now I will try to turn the OFI provider completely off. 
@boegel Is there a way to pass an environment variable into easybuild build and test environment via the easyconfig ?

**Comment by satishskamath** [comment]
So all these tests are passing right now. But it is taking quite some time for the `gmxapi` to build that could be related to the file system race. I have included the patch from your earlier PR and now am building it again on Snellius. If that works out this ticket can be closed.

The timeouts also seem to be a local system problem which needs to diagnosed.

**Comment by satishskamath** [comment]
Issue resolved. Thanks @ocaisa and @boegel .
