### ISSUE TITLE
OpenSSL/1.1 fails the sanity test when using a proxy with authentication on Rocky 9

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#20337]
I found that when building `OpenSSL/1.1` on Rocky 9 we cannot use the wrapper because the OS does not provide compatibility headers.

In this case, the system is air gapped, and we need to use an authenticated proxy for external connections.

Unfortunately, the sanity test involves a connection to Github and it doesn't format the proxy settings properly.
It adds the whole string from the `https_proxy` environment variable to the `-proxy` parameter, instead of using `-proxy_user` and `-proxy_pass`. As a result the sanity test fails because `s_client` rejects the badly formatted `-proxy` value and does not use the authenticated proxy.

The workaround is to add:

`skipsteps = ['sanitycheck']`

to the `OpenSSL` easyconfig.

**Comment by Micket** [comment]
I believe such customizations should be expected to be dealt with via a hook (at the parse stage) where you can include such modificaitons. Rocky 9 system should in general just avoid OpenSSL 1.1 and use a hook to OpenSSL 3 instead.
