### ISSUE TITLE
[Bug] ncurses-6.0.eb cannot install on an EL9 (Rocky 9) OS.

### ISSUE THREAD

**Issue by jkwmoore** [easybuilders/easybuild-easyconfigs#20558]
When attempting to install `ncurses-6.0.eb` it errors out. Not had time to test this on other EL9 flavours but I expect the same outcome.

```bash
 cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.3 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.3 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```

Installation log: [easybuild-ncurses-6.0-20240520.163216.wjMrt.log](https://github.com/easybuilders/easybuild-easyconfigs/files/15378967/easybuild-ncurses-6.0-20240520.163216.wjMrt.log)

I noted that this may relate to https://github.com/spack/spack/issues/41981 but I didn't get into any deep level of debugging to confirm.

See also: https://github.com/spack/spack/pull/41982

TIL of `eb-live --show-system-info`

```bash
eb-live --show-system-info
System information (node028):

* OS:
  -> name: Rocky Linux
  -> type: Linux
  -> version: 9.3
  -> platform name: x86_64-unknown-linux

* CPU:
  -> vendor: Intel
  -> architecture: x86_64
  -> family: Intel
  -> arch name: UNKNOWN (archspec is not installed?)
  -> model: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
  -> speed: 3400.0
  -> cores: 64
  -> features: 3dnowprefetch,abm,acpi,adx,aes,aperfmperf,apic,arat,arch_capabilities,arch_perfmon,art,avx,avx2,avx512_bitalg,avx512_vbmi2,avx512_vnni,avx512_vpopcntdq,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vl,bmi1,bmi2,bts,cat_l3,clflush,clflushopt,clwb,cmov,constant_tsc,cpuid,cpuid_fault,cqm,cqm_llc,cqm_mbm_local,cqm_mbm_total,cqm_occup_llc,cx16,cx8,dca,de,ds_cpl,dtes64,dtherm,dts,epb,ept,ept_ad,erms,est,f16c,flexpriority,flush_l1d,fma,fpu,fsgsbase,fsrm,fxsr,gfni,ht,ibpb,ibrs,ibrs_enhanced,ida,intel_ppin,intel_pt,invpcid,invpcid_single,la57,lahf_lm,lm,mba,mca,mce,md_clear,mmx,monitor,movbe,msr,mtrr,nonstop_tsc,nopl,nx,ospke,pae,pat,pbe,pcid,pclmulqdq,pconfig,pdcm,pdpe1gb,pebs,pge,pku,pln,pni,popcnt,pse,pse36,pts,rdpid,rdrand,rdseed,rdt_a,rdtscp,rep_good,sdbg,sep,sha_ni,smap,smep,smx,split_lock_detect,ss,ssbd,sse,sse2,sse4_1,sse4_2,ssse3,stibp,syscall,tm,tm2,tme,tpr_shadow,tsc,tsc_adjust,tsc_deadline_timer,umip,vaes,vme,vmx,vnmi,vpclmulqdq,vpid,wbnoinvd,x2apic,xgetbv1,xsave,xsavec,xsaveopt,xsaves,xtopology,xtpr

* software:
  -> glibc version: 2.34
  -> Python binary: /usr/bin/python3
  -> Python version: 3.9.18
 
```

**Comment by boegel** [comment]
@SebastianAchilles Any idea why we haven't seen this on `jsc-zen3`?

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles Any idea why we haven't seen this on `jsc-zen3`?

`ncurses-6.0.eb` was used in `GCCcore/6.4.0` and earlier. As far as I see on `jsc-zen3` we only build the [Supported Toolchain Generations](https://docs.easybuild.io/policies/toolchains/#current-situation)

`ncurses-6.0.eb` fails indeed on `jsc-zen3` with RockyLinux 9.4: https://gist.github.com/SebastianAchilles/c5542ff25a570a6803418ae0096363e9

**Comment by Micket** [comment]
As this is just way to old to work on any modern OS, and we have already removed this (any many other extremely outdated easyconfigs) from the repo for 5.0.x, there really isn't anything to do here.
(even with the easyconfigs we keep as "supported" they are never expected to continue working indefinitely into newer OS releases).
