### ISSUE TITLE
GAMESS - GCC Checksum verification failed

### ISSUE THREAD

**Issue by DetlevCM** [easybuilders/easybuild-easyconfigs#20584]
Looking around for (potentially useful) chemistry (related) software, I found an issue with GAMESS:

`eb GAMESS-US-20180214-R1-foss-2016b.eb -r `

runs until it encountered

```
== ... (took 5 mins 21 secs)
== FAILED: Installation ended unsuccessfully (build directory: /software/tmp/eb-build/GCCcore/5.4.0/system-system): build failed (first 300 chars): Unexpected error occurred when trying to download http://ftpmirror.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2 to /software/src/eb-src/g/GCCcore/gcc-5.4.0.tar.bz2: 'Failed to write to /software/src/eb-src/g/GCCcore/gcc-5.4.0.tar.bz2: timed out' (took 5 mins 21 secs)
== Results of the build can be found in the log file(s) /tmp/eb-2bfqs8iq/easybuild-GCCcore-5.4.0-20240522.112816.uEJWD.log
ERROR: Build of /home/hpc-software/easybuild/easybuild/easyconfigs/g/GCCcore/GCCcore-5.4.0.eb failed (err: "build failed (first 300 chars): Unexpected error occurred when trying to download http://ftpmirror.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2 to /software/src/eb-src/g/GCCcore/gcc-5.4.0.tar.bz2: 'Failed to write to /software/src/eb-src/g/GCCcore/gcc-5.4.0.tar.bz2: timed out'")
```

rerunning yields

```
== FAILED: Installation ended unsuccessfully (build directory: /software/tmp/eb-build/GCCcore/5.4.0/system-system): build failed (first 300 chars): Unexpected error occurred when trying to download http://ftpmirror.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2 to /software/src/eb-src/g/GCCcore/gcc-5.4.0.tar.bz2: 'Failed to write to /software/src/eb-src/g/GCCcore/gcc-5.4.0.tar.bz2: timed out' (took 5 mins 21 secs)
== Results of the build can be found in the log file(s) /tmp/eb-2bfqs8iq/easybuild-GCCcore-5.4.0-20240522.112816.uEJWD.log
ERROR: Build of /home/hpc-software/easybuild/easybuild/easyconfigs/g/GCCcore/GCCcore-5.4.0.eb failed (err: "build failed (first 300 chars): Unexpected error occurred when trying to download http://ftpmirror.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2 to /software/src/eb-src/g/GCCcore/gcc-5.4.0.tar.bz2: 'Failed to write to /software/src/eb-src/g/GCCcore/gcc-5.4.0.tar.bz2: timed out'")
```

[easybuild-GCCcore-5.4.0-20240522.121221.hNnhA.log](https://github.com/easybuilders/easybuild-easyconfigs/files/15401733/easybuild-GCCcore-5.4.0-20240522.121221.hNnhA.log)

The file does download manually - rerunning again gives the same error and a shorter log file.

[easybuild-GCCcore-5.4.0-20240522.121740.sidQy.log](https://github.com/easybuilders/easybuild-easyconfigs/files/15401719/easybuild-GCCcore-5.4.0-20240522.121740.sidQy.log)

**Comment by Micket** [comment]
This is to way way way old to have any hope in working at all, and these are all deprecated and is archived for the next 5.0 release as well. 

Failed to write indicates that maybe your software src dir is running out of space?

**Comment by DetlevCM** [comment]
I don't think the drive was running out of space as other builds worked fine.
It is indeed old code and was part of the the tool suite I wanted to set up and make available to the chemists. Not building it, does not create an immediate problem.

On a side note though, it does bring up an interesting question about the longterm viability of software used in research.
Historically one would have always expected to be be able to build software again if the source code is available, but even this starts to become less well guaranteed...
(This was my experience with OpenFOAM where the newest compiler won't build older OpenFOAM...)

**Comment by Micket** [comment]
> Historically one would have always expected to be be able to build software again if the source code is available, but even this starts to become less well guaranteed...

No i don't think this was ever even remotely true, older codes and programming languages were even way worse w.r.t. being standard compliant and such, with most more drastic changes in OS'es and whatnot.

> longterm viability of software

No such thing. Everything will bitrot, hardware changes, support is dropped, sources are lost, whole programming languages will stop being supported due to falling into obscurity.

> This was my experience

it will be the experience with basically all software at slightly different time scales.
