### ISSUE TITLE
Failed to find required EasyBuild package easybuild-framework

### ISSUE THREAD

**Issue by marctormo** [easybuilders/easybuild-easyconfigs#20815]
Hi there!

I'm trying to update the eb version in our cluster, but I'm getting the following error:

```{bash}
$ eb --install-latest-eb-release
== Temporary log file in case of crash /homes/aplic/tmp/easybuild-SvJ2Bd.log


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Running EasyBuild with Python v2.x is deprecated, found Python v2.7.5.                      !!!
!!! Support for running EasyBuild with Python v2.x will be removed in EasyBuild v5.0.           !!!
!!!                                                                                             !!!
!!! It is strongly recommended to start using Python v3.x for running EasyBuild,                !!!
!!! see https://docs.easybuild.io/en/latest/Python-2-3-compatibility.html for more information. !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


== found valid index for /homes/aplic/noarch/software/EasyBuild/4.9.1/easybuild/easyconfigs, so using it...
== processing EasyBuild easyconfig /tmp/eb-BRm_f_/tmp9LqLnp/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.9.2.eb
== building and installing EasyBuild/4.9.2...
== fetching files...
== creating build dir, resetting environment...
== ... (took 51 secs)
== unpacking...
== ... (took 22 secs)
== patching...
== preparing...
== ... (took 2 secs)
== configuring...
== building...
== testing...
== installing...
== FAILED: Installation ended unsuccessfully (build directory: /homes/aplic/noarch/build/EasyBuild/4.9.2/system-system): build failed (first 300 chars): Failed to find required EasyBuild package easybuild-framework (subdirs: ['easybuild_framework-4.9.2', 'easybuild_easyblocks-4.9.2', 'easybuild_easyconfigs-4.9.2'], seldirs: []) (took 1 min 17 secs)
== Results of the build can be found in the log file(s) /homes/aplic/tmp/easybuild-EasyBuild-4.9.2-20240613.120927.HyQZT.log
ERROR: Build of /tmp/eb-BRm_f_/tmp9LqLnp/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.9.2.eb failed (err: "build failed (first 300 chars): Failed to find required EasyBuild package easybuild-framework (subdirs: ['easybuild_framework-4.9.2', 'easybuild_easyblocks-4.9.2', 'easybuild_easyconfigs-4.9.2'], seldirs: [])")

```

Do you have any clues on what's happening?

Thank you very much,
Marc

**Comment by bedroge** [comment]
Hi Marc,

It was a known issue, and some more details and a fix were provided in https://github.com/easybuilders/easybuild-easyblocks/pull/3358, but that requires you to do `eb --install-latest-eb-release --include-easyblocks-from-pr 3358`.

However, a better fix was just merged in https://github.com/easybuilders/easybuild-easyconfigs/pull/20818, and this should allow you to just use `eb --install-latest-eb-release` again. Please give it a try, the `--install-latest-eb-release` option should make sure that it automatically pulls in this updated easyconfig for version 4.9.2.

**Comment by alvarofazenda** [comment]
Hi!
Thanks for the clues, but I try to do:
eb --install-latest-eb-release --include-easyblocks-from-pr 3358

And receive the following error message:

ERROR: Framework (4.9.2) is a different major version than used in easybuilders/easybuild-easyblocks PR #3358 (5.0.1.dev0)

Do you have any clues about this new issue?

Many thanks for considering my request.

Alvaro

**Comment by bedroge** [comment]
> Hi! Thanks for the clues, but I try to do: eb --install-latest-eb-release --include-easyblocks-from-pr 3358
> 
> And receive the following error message:
> 
> ERROR: Framework (4.9.2) is a different major version than used in easybuilders/easybuild-easyblocks PR [#3358](https://github.com/easybuilders/easybuild-easyconfigs/pull/3358) (5.0.1.dev0)
> 
> Do you have any clues about this new issue?
> 
> Many thanks for considering my request.
> 
> Alvaro

@alvarofazenda the problem described in this issue was specific to installing EasyBuild 4.9.2 with an older version. It should not be relevant anymore for newer versions. So, assuming you want to install 5.0.0 (the latest version), could you please try it without `--include-easyblocks-from-pr 3358`?

**Comment by alvarofazenda** [comment]
Hi!
Thank you so much for your attention.
I'm trying to update my EasyBuild version 4.9.2 to 5.0.0.
After execute, as your question: eb --install-latest-eb-release
The EB returns firstly the warning message:

Running EasyBuild with Python v2.x is deprecated, found Python v2.7.5.
Support for running EasyBuild with Python v2.x will be removed in EasyBuild v5.0.

However, the default python version installed is: 

 python --version
Python 3.8.1

After this warning the final error is:

...
== installing...
== FAILED: Installation ended unsuccessfully (build directory: /home/eb/eb-install/build/EasyBuild/5.0.0/system-system): build failed (first 300 chars): cmd " /bin/python2 setup.py install --prefix=/home/eb/eb-install/software/EasyBuild/5.0.0 " exited with exit code 1 and output:
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
...
ERROR: Build of /tmp/eb-Sk2Fxw/tmpTte68S/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-5.0.0.eb failed (err: 'build failed (first 300 chars): cmd " /bin/python2 setup.py install --prefix=/home/eb/eb-install/software/EasyBuild/5.0.0 " exited with exit code 1 and output:\nTraceback (most recent call last):\n  File "setup.py", line 39, in <module>\n    from easybuild.tools.version import VERSION\n  File "/home/eb/eb-install/build/EasyBuild/5.0.0')

I appreciate any clue to solve it. 
Thanks!!
