### ISSUE TITLE
[GCCcore/13.2.0] HDF v4.2.16-2 - download link broken

### ISSUE THREAD

**Issue by sdx23** [easybuilders/easybuild-easyconfigs#21105]
The previous link
http://www.hdfgroup.org/ftp/HDF/releases/HDF4.2.16-2/src/hdf-4.2.16-2.tar.gz
does not work anymore. The download website refers now to
https://hdf-wordpress-1.s3.amazonaws.com/wp-content/uploads/manual/HDF4/HDF4.2.16-2/src/hdf-4.2.16-2.tar.gz

(I currently lack time to look into this further but might PR on this next week)

**Comment by hattom** [comment]
Changing "www" -> "support" works.
https://support.hdfgroup.org/ftp/HDF/releases/HDF4.2.16-2/src/hdf-4.2.16-2.tar.gz

**Comment by sdx23** [comment]
That's better than this wordpress aws url. Thank you!
