### ISSUE TITLE
intel compiler 2021.2.0 can't be downloaded

### ISSUE THREAD

**Issue by hediinn** [easybuilders/easybuild-easyconfigs#21104]
i tried to install intel-compilers-2021.2.0.eb 
and it didn't download any thing.
Then i tried following the link
https://registrationcenter-download.intel.com/akdlm/irc_nas/17749/l_dpcpp-cpp-compiler_p_2021.2.0.118_offline.sh
and it seems to give an error 
same issue with 2021.3.0 
https://registrationcenter-download.intel.com/akdlm/irc_nas/17928/l_dpcpp-cpp-compiler_p_2021.3.0.3168_offline.sh

**Comment by bartoldeman** [comment]
This is normal, since Intel doesn't provide older downloads for free. These still may be available if you bought priority support.
https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-supported-product-versions.html

**Comment by hediinn** [comment]
> This is normal, since Intel doesn't provide older downloads for free. These still may be available if you bought priority support. https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-supported-product-versions.html

so they should be set to deprecated, since the download links don't do anything

**Comment by hediinn** [comment]
2021.4.0 seems to still be there
https://registrationcenter-download.intel.com/akdlm/irc_nas/18209/l_dpcpp-cpp-compiler_p_2021.4.0.3201_offline.sh

**Comment by bartoldeman** [comment]
The URLs are broken, but otherwise the easyconfigs still work if you had already downloaded the software earlier, or if you can download it via premium support.

Not sure what the right way is here.
