### ISSUE TITLE
Couldn't determine CPU architecture, you need to set 'kokkos_arch' manually

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#21158]
When I install LAMMPS-2Aug2023_update2-foss-2023a-kokkos-CUDA-12.1.1.eb, it prompts an error that the CPU architecture cannot be determined and "kokkos_arch" needs to be set manually. How should I set the parameters? I tried to set configopts = '--kokkos-arch=SKX' in the .eb file, but it doesn't seem to work.
![image](https://github.com/user-attachments/assets/9a5c7569-6654-44a8-a8dd-fbfdaa0e7385)

**Comment by Thyre** [comment]
Looking at the EasyBlock, there is an option to set the Kokkos architecture:

https://github.com/easybuilders/easybuild-easyblocks/blob/1ca6dc32f89842d33bd6599d1ca0e795c12fbf75/easybuild/easyblocks/l/lammps.py#L222
```python
'kokkos_arch': [None, "Set kokkos processor arch manually, if auto-detection doesn't work.", CUSTOM],
```

Since the error message is produced by the EasyBlock, setting `--kokkos-arch=[x]` will probably not work.

**Comment by hezhiqiang8909** [comment]
> 查看 EasyBlock，有一个设置 Kokkos 架构的选项：
> 
> https://github.com/easybuilders/easybuild-easyblocks/blob/1ca6dc32f89842d33bd6599d1ca0e795c12fbf75/easybuild/easyblocks/l/lammps.py#L222
> 
> ```python
> 'kokkos_arch': [None, "Set kokkos processor arch manually, if auto-detection doesn't work.", CUSTOM],
> ```
> 
> 由于[错误消息是由 EasyBlock 产生的](https://github.com/easybuilders/easybuild-easyblocks/blob/1ca6dc32f89842d33bd6599d1ca0e795c12fbf75/easybuild/easyblocks/l/lammps.py#L597)，设置`--kokkos-arch=[x]`可能不起作用。
With your help, I modified it and compiled it successfully. Thank you very much @Thyre
