### ISSUE TITLE
build of xtb 6.7.0 with `gfbf/2023a` not working

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#21243]
```
[528/898] Compiling Fortran object libxtb.so.6.7.0.p/src_dipro_xtb.F90.o
FAILED: libxtb.so.6.7.0.p/src_dipro_xtb.F90.o libxtb.so.6.7.0.p/xtb_dipro_xtb.mod
gfortran -Ilibxtb.so.6.7.0.p -I. -I../xtb-6.7.0 -I../xtb-6.7.0/include -Isubprojects/mctc-lib/libmctc-lib.a.p -Isubprojects/json-fortran-8.2.5/libjsonfortran.a.p -I../xtb-6.7.0/subprojects/tblite/include -Isubprojects/tblite/libtblite.a.p -Isubprojects/dftd4/libdftd4.a.p -I../xtb-6.7.0/subprojects/dftd4/include -Isubprojects/multicharge/libmulticharge.a.p -Isubprojects/s-dftd3/libs-dftd3.a.p -I../xtb-6.7.0/subprojects/s-dftd3/include -Isubprojects/toml-f/libtoml-f.a.p -Isubprojects/numsa/libnumsa.a.p -Isubprojects/cpx/libcpx.a.p -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -O2 -fdefault-real-8 -fdefault-double-8 -ffree-line-length-none -fbacktrace -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -fopenmp -pthread -fopenmp -DWITH_TBLITE=1 -DWITH_CPCMX=1 -Jlibxtb.so.6.7.0.p -o libxtb.so.6.7.0.p/src_dipro_xtb.F90.o -c ../xtb-6.7.0/src/dipro/xtb.F90
../xtb-6.7.0/src/dipro/xtb.F90:53:42:

   53 |       call new_gfn2_calculator(xcalc, mol)
      |                                          1
Error: Missing actual argument for argument error at (1)
../xtb-6.7.0/src/dipro/xtb.F90:55:42:

   55 |       call new_gfn1_calculator(xcalc, mol)
      |                                          1
Error: Missing actual argument for argument error at (1)
../xtb-6.7.0/src/dipro/xtb.F90:57:43:

   57 |       call new_ipea1_calculator(xcalc, mol)
      |                                           1
Error: Missing actual argument for argument error at (1)
ninja: build stopped: subcommand failed.
```

I'm a bit confused why this error didn't pop up in #20288...

@WilleBell Can you check if a test install of `xtb-6.7.0-gfbf-2023a.eb` is still working for you?

**Comment by boegel** [comment]
Right, so we need a way to make sure that `xtb` doesn't pull in random external stuff during the build... *sigh*

**Comment by boegel** [comment]
Reported upstream: https://github.com/grimme-lab/xtb/issues/1091

It seems like https://github.com/grimme-lab/xtb/pull/1072 probably fixes this problem (to be confirmed), but that's only temporary, it's bound to happen again as long as we pull in random code at build time from a bunch of other repos...

**Comment by boegel** [comment]
Patch corresponding to https://github.com/grimme-lab/xtb/pull/1072 is working to fix build of `xtb` 6.7.1 with `gfbf/2023a`

**Comment by boegel** [comment]
See also:
* #21245

**Comment by WilleBell** [comment]
> ```
> [528/898] Compiling Fortran object libxtb.so.6.7.0.p/src_dipro_xtb.F90.o
> FAILED: libxtb.so.6.7.0.p/src_dipro_xtb.F90.o libxtb.so.6.7.0.p/xtb_dipro_xtb.mod
> gfortran -Ilibxtb.so.6.7.0.p -I. -I../xtb-6.7.0 -I../xtb-6.7.0/include -Isubprojects/mctc-lib/libmctc-lib.a.p -Isubprojects/json-fortran-8.2.5/libjsonfortran.a.p -I../xtb-6.7.0/subprojects/tblite/include -Isubprojects/tblite/libtblite.a.p -Isubprojects/dftd4/libdftd4.a.p -I../xtb-6.7.0/subprojects/dftd4/include -Isubprojects/multicharge/libmulticharge.a.p -Isubprojects/s-dftd3/libs-dftd3.a.p -I../xtb-6.7.0/subprojects/s-dftd3/include -Isubprojects/toml-f/libtoml-f.a.p -Isubprojects/numsa/libnumsa.a.p -Isubprojects/cpx/libcpx.a.p -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -O2 -fdefault-real-8 -fdefault-double-8 -ffree-line-length-none -fbacktrace -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -fopenmp -pthread -fopenmp -DWITH_TBLITE=1 -DWITH_CPCMX=1 -Jlibxtb.so.6.7.0.p -o libxtb.so.6.7.0.p/src_dipro_xtb.F90.o -c ../xtb-6.7.0/src/dipro/xtb.F90
> ../xtb-6.7.0/src/dipro/xtb.F90:53:42:
> 
>    53 |       call new_gfn2_calculator(xcalc, mol)
>       |                                          1
> Error: Missing actual argument for argument error at (1)
> ../xtb-6.7.0/src/dipro/xtb.F90:55:42:
> 
>    55 |       call new_gfn1_calculator(xcalc, mol)
>       |                                          1
> Error: Missing actual argument for argument error at (1)
> ../xtb-6.7.0/src/dipro/xtb.F90:57:43:
> 
>    57 |       call new_ipea1_calculator(xcalc, mol)
>       |                                           1
> Error: Missing actual argument for argument error at (1)
> ninja: build stopped: subcommand failed.
> ```
> 
> I'm a bit confused why this error didn't pop up in #20288...
> 
> @WilleBell Can you check if a test install of `xtb-6.7.0-gfbf-2023a.eb` is still working for you?

Indeed, it is not working for me anymore ..

**Comment by WilleBell** [comment]
I made a PR with the same (temporary) solution in #21255 to build xtb-6.7.0
