### ISSUE TITLE
Python 2.5 build fails linux 3.x

### ISSUE THREAD

**Issue by tvandera** [easybuilders/easybuild-easyconfigs#2134]
Python 2.5 (e.g. 2.5.6-gompi-1.4.12-no-OFED-bare) fails to build on Linux systems with a kernel version >= 3.0. The reason seems to that it fails to generate .py files from system headers:

From the build log:

> python$EXE ../../Tools/scripts/h2py.py -i '(u_long)' /usr/include/netinet/in.h
> python: error while loading shared libraries: libpython2.5.so.1.0: cannot open shared object file: No such file or directory

This step does not happen on Linux 2.x systems. The files have been pre-generated.

**Comment by tvandera** [comment]
Attached full log

[easybuild-Python-2.5.6-20151002.154331.dQKOL.log.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/32359/easybuild-Python-2.5.6-20151002.154331.dQKOL.log.txt)

**Comment by boegel** [comment]
@tvandera: thanks for logging this, I think @geimer ran into a similar issue a while ago

Not sure if this is easily fixed tough... Why do you need an old Python on a recent system? You're bound to run into problems in that case...

**Comment by boegel** [comment]
@tvandera ping? How important is it to really fix this?

**Comment by Micket** [comment]
Not very important I'm guessing.
