### ISSUE TITLE
QT foss-2015a missing dependencies on CentOS6

### ISSUE THREAD

**Issue by iotaka** [easybuilders/easybuild-easyconfigs#2176]
`eb PyQt-4.11.4-foss-2015a-Python-2.7.9.eb --robot`

it fails when compiling QT with the error

`Project ERROR: Package gstreamer-app-0.10 not found`

if is not installed the following package on a CentOS 6:

`yum install gstreamer-plugins-base-devel`

**Comment by Micket** [comment]
Long since outdated (nowdays we have easyconfigs for gstreamer plugins)
