### ISSUE TITLE
Why is this file written to the public_databases directory, and not to the output file of the mapping? I am running on an HPC cluster, and the administrator has set the database permissions to read-only.

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#21936]
PermissionError: [Errno 13] Permission denied: '/root/public_databases/mmcif_files/2pv7.cif
![image](https://github.com/user-attachments/assets/7ff76593-eb42-48fc-b582-74bdb99d353e)

**Comment by Micket** [comment]
Why are you posting this question here? It clearly has nothing to do with easybuild, it's a picture of text with multiple horrendous installation paths, and an error that of course has nothing to do with easybuild or even how the software was installed.
