### ISSUE TITLE
Failure due to templating in checksums of extension

### ISSUE THREAD

**Issue by lexming** [easybuilders/easybuild-easyconfigs#22090]
Test are failing in #22088 for `Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb` due to the usage of a `%(version)s` template in the checksum specification of an extension:

```
== 2024-12-21 00:31:11,868 easyblock.py:871 INFO Found file Sys-Info-Driver-Linux-0.7905.tar.gz at /project/def-maintainers/boegelbot/sources/p/Perl-bundle-CPAN/extensions/Sys-Info-Driver-Linux-0.7905.tar.gz
== 2024-12-21 00:31:11,868 filetools.py:1265 DEBUG Using blocksize 16777216 for calculating the checksum
== 2024-12-21 00:31:11,869 easyblock.py:692 INFO sha256 checksum for /project/def-maintainers/boegelbot/sources/p/Perl-bundle-CPAN/extensions/Sys-Info-Driver-Linux-0.7905.tar.gz: 899c329bd3508ec5849ad0e5dadfa7c3679bbacaea9dda12404a7893032e8b7b
== 2024-12-21 00:31:11,869 easyblock.py:695 DEBUG Verifying checksums for extension source...
== 2024-12-21 00:31:12,039 build_log.py:226 ERROR EasyBuild encountered an error (at easybuild/5.0.x/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Missing checksum for Sys-Info-Driver-Linux-0.7905.tar.gz in {'Sys-Info-Driver-Linux-%(version)s.tar.gz': '899c329bd3508ec5849ad0e5dadfa7c3679bbacaea9dda12404a7893032e8b7b'} (at easybuild/5.0.x/easybuild-framework/easybuild/tools/filetools.py:1307 in verify_checksum)
```

This is the easyconfig code related to this error:
https://github.com/easybuilders/easybuild-easyconfigs/blob/ef644ae1e1edeab766f0c9632bdd8a210186737e/easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb#L2120-L2135

**Comment by Micket** [comment]
Is that checksum even right? We normally don't use templates in the checksum dicts. This must have been incorrectly written out by hand in that commit 4dab87b7855

I'm not sure checksum dicts are even expanded with templates, so i'm surprised this isn't an error when building, but maybe the actual string format. It doesn't make sense dictionary keys to have templates, so the CI is correct to complain.
So i think you should just fix that mistake in 5.36.1 (you wrote 5.38.0 but linked 5.36.1)

**Comment by lexming** [comment]
Indeed, I agree that checksum keys should not use templating. Then the issue is that this template went through our CI in the first place. Not sure how this managed to pass the test originally.

I'll fix this easyconfig then and see if we can have a test for templates in checksums.

**Comment by boegel** [comment]
This is fallout from https://github.com/easybuilders/easybuild-framework/pull/4516, which only got merged recently.

That explains why CI hasn't caught this, because some checks are only run for easyconfigs touched in PRs...

**Comment by boegel** [comment]
fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/22091
