### ISSUE TITLE
Building a tool using Go

### ISSUE THREAD

**Issue by nathanhaigh** [easybuilders/easybuild-easyconfigs#2251]
I've written an easyconfig for the binary version of `hub` (#2249) and am trying to write another easyconfig to build `hub` from source. The build depends on `Go` and I need to run the following build command to generate the executable `hub`:

``` bash
script/build
```

I'm using the `CmdCp` easyblock, but I'm confused what to set, if anything, as the toolchain. I had thought to specify `Go`, but that isn't a toolchain in EasyBuild. I then thought I'd set the toolchain to `GCC` (version to sync with that used to build `Go`) and set `Go` as a build dependency. However, strictly speaking, building `hub` doesn't require `GCC`, I'm just specifying this so that auto-dependency installation will work using `--robot`.

This seems a bit hacky, I'm I on the right tracks or going off on one!?

**Comment by boegel** [comment]
The toolchain indicates using which set of C/C++/Fortran compilers the whole software stack is built, so using `GCC` in this case as toolchain, and then including `Go` as a dependency makes sense.

In theory, we can look into defining a Go-based toolchain, but it's probably not worth the effort. The largest reason for the whole toolchain mechanism is to set up the build environment, which is probably largely irrelevant for Go.

This is the same approach we take for Python, Perl, R 'extensions', see for example https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/n/numpy/numpy-1.9.2-intel-2015b-Python-2.7.10.eb.

**Comment by boegel** [comment]
@nathanhaigh ok to close?

**Comment by Micket** [comment]
We've had `GoPackage` easyblock since 2020.
