### ISSUE TITLE
deap-0.9.1: detected (once more) an upstream change without version update; whatever

### ISSUE THREAD

**Issue by fgeorgatos** [easybuilders/easybuild-easyconfigs#2479]
However, a fraction of the changes are not typos and seem as strong indications of potential trouble;
N.B. **deap is an extension used across several popular Python builds**.

Feel free to close this issue as soon as you see it, I just raise it here for documenting one such case;
(this is not really an EasyBuild problem per se; such issues should be handled via Binary Repos)

somewhere in the middle of this, you will spot some candidate hashes, if anyone is up to the task:

```
64ea1578b364914fe42ea9bead8da43a  ./deap-0.9.1/deap/creator.py
10dfab98e5a2fae4f5520e78137f1a15  ./deap-0.9.1/doc/api/benchmarks.rst
e21a5116967652e4e829976d8696d47c  ./deap-0.9.1/doc/tutorials/gp.rst
8137d221f29d9d1e267fd5e7d320c550  ./deap-0.9.1/doc/tutorials/next_step.rst
54bdc7c876c67994b2cc00e9de8aa05b  ./deap-0.9.1/doc/tutorials/start.rst
0795f38aed51dfe91be7f562b602fdd7  ./deap-0.9.1/doc/tutorials/types.rst
d52d48d46f07ce54e0d27dfd5df5baa2  ./deap-0.9.1.recent/deap/benchmarks/gp.py
3eebe1ea456f17994caf5e440a062473  ./deap-0.9.1.recent/deap/creator.py
dff3b46103b1efc7d5087251b0d4b49c  ./deap-0.9.1.recent/doc/api/benchmarks.rst
a11edcc5b80032d70fb24549ee304dfb  ./deap-0.9.1.recent/doc/code/examples/speed.txt
2ba21889d6deb7d68c2d04a84171963e  ./deap-0.9.1.recent/doc/tutorials/gp.rst
7594090778c7231d41f302c729ed304d  ./deap-0.9.1.recent/doc/tutorials/next_step.rst
ddd1982165251c6b9b8c826c78caa9c7  ./deap-0.9.1.recent/doc/tutorials/start.rst
053ebfb7abebf4e64c1fb9a64e6a6b5c  ./deap-0.9.1.recent/doc/tutorials/types.rst
$ md5sum ../deap-0.9.1.tar.gz*
96c5bba951249ae98768165f027ccbbb  ../deap-0.9.1.tar.gz
d844135eb93573c45e45f6dd8b15e2dc  ../deap-0.9.1.tar.gz.recent
$ diff ./deap-0.9.1/deap/creator.py ./deap-0.9.1.recent/deap/creator.py
174c174
<     objtype = type(name, (base,), dict_cls)

---
>     objtype = type(str(name), (base,), dict_cls)
$ cat ./deap-0.9.1.recent/deap/benchmarks/gp.py
[...]
```

Interestingly, I do not see in the github release of this version the named change:
https://github.com/DEAP/deap/blob/0.9.1/deap/creator.py
but somewhere along the distribution path things get messy:
https://github.com/DEAP/deap/blob/master/deap/creator.py#L169

enough for this week! (and month, and year...)

**Comment by fgeorgatos** [comment]
btw. this would not be so important, if it wasn't part of Python-2.7.3-goolf-1.4.10.eb and so many other things; it makes me wish to ban such packages from default Python builds...

**Comment by boegel** [comment]
Wait, are you saying they're changing the source tarball for an *old* version?!

**Comment by boegel** [comment]
https://pypi.python.org/pypi/deap/0.9.1 says the tarball was uploaded Feb'14 (and PyPI doesn't easily let you replace a tarball 'in place' without bumping the version)

**Comment by fgeorgatos** [comment]
@boegel: that's exactly why I report it, and it would be nice to hear your opinions if you confirm the same experience.

Note that this is not the first time we see such change by upstream, it IS hard to keep track of this:
https://github.com/dzerbino/velvet/commit/d7996318a613d6431190f67d5357faba900c96ac#commitcomment-4622066

**Comment by Micket** [comment]
This doesn't ring a bell in the past couple of years, so if they did re-release stuff in the past it doesn't seem to be happening anymore at least. Closing.
