### ISSUE TITLE
Plotting for R

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#2742]
At the moment, I have to use a local fork of the `R` EB to include `Cairo` during build, in order for plotting tools to work. I think some sites use `libpng` instead.

I don't really mind which is used - could we agree on one method and include that in the default EB?

This came up on IRC but I can't remember what the conclusion was.

**Comment by boegel** [comment]
We should revisit this with the upcoming refresh of R for the `2017a` toolchains...

So, basically the choice is to include either `libpng` or `Cairo` as an additional dep?

**Comment by verdurin** [comment]
Some of the `configopts` also need to be changed.

Another related requirement that's come up for us is people wanting to run `R` interactively, which means `libX11` is required.

**Comment by JackPerdue** [comment]
FWIW, I put our latest copy here:   https://github.com/hpcugent/easybuild-easyconfigs/pull/4234

Includes plotting/X11/cairo/etc.... no extensions though (we manage those seperately).

**Comment by JackPerdue** [comment]
Enabling ['rpath': True] in toolchainopts would help with Python-bare.   At the moment it requires the command line to get right (and an objdump to check).  As a Fedora fan (and adherent to their guidelines) I'm not really into RPATH.   But in the case of Python-bare (with minimal toolchain) it makes sense if one wants to use it as a builddependencie.

**Comment by boegel** [comment]
We include `--with-cairo` & `--with-libpng` & co in recent R easyconfigs + the required dependencies (incl. X11), so this can be closed imho.
