### ISSUE TITLE
Python 2.7.11 missing `unzip`?

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#2951]
I'm trying to build `Python 2.7.11` for `foss-2016a`, based on the `intel-2016a` easyconfig.

It's complaining that `unzip` isn't available.

[easybuild-Python-2.7.11-20160425.230755.POoHd.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/236003/easybuild-Python-2.7.11-20160425.230755.POoHd.txt)

**Comment by verdurin** [comment]
This is with an Ubuntu `14.04` VM, based on the official cloud image.

**Comment by boegel** [comment]
@verdurin that probably occurs more often, since `unzip` is commonly available on the OS...

Just includes a (build) dep may not work here though, see also https://github.com/hpcugent/easybuild-framework/issues/1376...

**Comment by Micket** [comment]
We have UnZip as a builddep for Python these days.
