### ISSUE TITLE
avoid draft easyconfigs to end up in released version

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#30]
Adjust setup.py (or release procedure) to make sure no files that are not committed and pushed to master end up in released version of easybuild-easyconfigs.

**Comment by migueldiascosta** [comment]
the release procedure (https://github.com/easybuilders/easybuild/wiki/Release-management) and, more recently, the `create_source_tarball.sh` script (https://github.com/easybuilders/easybuild/pull/612) have addressed this and similar issues
