### ISSUE TITLE
Possible linker problem with foss-2016a

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#3011]
I'm working on an easyconfig for fastq-tools (http://homes.cs.washington.edu/~dcjones/fastq-tools/).

It compiles fine on my build system on Fedora 23, but fails on the same system using `foss-2016a`.

I've reported this upstream at https://github.com/dcjones/fastq-tools/issues/17 because I'm not sure yet whether it's a problem there or with EB.

The actual problem is that during the configure step a spurious linker value is added. Here's a comparison between the `config.log` output of the broken and working attempts (respectively):

```
-LIBS='-lm -lpthread-lm'
+LIBS='-lm'
```

Other than the GCC versions (4.9.3 vs. 5.3), the main difference between the two that I can see is the use of gold rather than GNU ld. 

Just thought I'd mention it here in case it's a toolchain rather than an upstream issue.

**Comment by boegel** [comment]
@verdurin so, with the broken build you're seeing `-lpthread-lm` in `$LIBS`?

Using `eb -x`, you can figure how EasyBuild defines `$LIBS` in the build environment, which may help.

This looks a lot like a missing space somewhere though; should be `-lpthread -lm`?

**Comment by verdurin** [comment]
@boegel - thanks for looking.

It does look like a missing space, or perhaps a failure to check for an empty value somewhere. 

What was puzzling me was why `-lpthread` was being added at all.

Anyway, `$LIBS` is set to `-lm -lpthread` in the dry run, so it doesn't look like the problem is at the EasyBuild end.

**Comment by boegel** [comment]
@verdurin: OK, that seems to confirm that fastq-tools somewhere consumes `$LIBS` and assumes it'll include a trailing space?

Please close this issue if there's not else to do on the EB side.

**Comment by verdurin** [comment]
Thanks to @SethosII for keeping an eye on this one. He's made a new upstream report, as linked above.
