### ISSUE TITLE
Difficult to compile against PETSc?

### ISSUE THREAD

**Issue by spikebike** [easybuilders/easybuild-easyconfigs#306]
Using easybuild-1.5 on ubuntu 13.04 I got Petsc to compile, this is all the version info for it and it's dependencies:
Currently Loaded Modulefiles:
  1) build/1.5
  2) GCC/4.7.2
  3) hwloc/1.6.2-GCC-4.7.2
  4) OpenMPI/1.6.4-GCC-4.7.2
  5) gompi/1.4.10
  6) OpenBLAS/0.2.6-gompi-1.4.10-LAPACK-3.4.2
  7) FFTW/3.3.3-gompi-1.4.10
  8) ScaLAPACK/2.0.2-gompi-1.4.10-OpenBLAS-0.2.6-LAPACK-3.4.2
  9) goolf/1.4.10
 10) bzip2/1.0.6-goolf-1.4.10
 11) zlib/1.2.7-goolf-1.4.10
 12) libreadline/6.2-goolf-1.4.10
 13) ncurses/5.9-goolf-1.4.10
 14) Python/2.7.3-goolf-1.4.10
 15) Boost/1.51.0-goolf-1.4.10-Python-2.7.3
 16) ScientificPython/2.8-goolf-1.4.10-Python-2.7.3
 17) FIAT/1.0.0-goolf-1.4.10-Python-2.7.3
 18) CMake/2.8.4-goolf-1.4.10
 19) METIS/5.0.2-goolf-1.4.10
 20) ParMETIS/4.0.2-goolf-1.4.10
 21) SCOTCH/5.1.12b_esmumps-goolf-1.4.10
 22) SuiteSparse/3.7.0-goolf-1.4.10-withparmetis
 23) Hypre/2.8.0b-goolf-1.4.10
 24) PETSc/3.3-p2-goolf-1.4.10-Python-2.7.3

I think that's mostly stock, but I used boost 1.51 instead of 1.49 that had a problem previously mentioned.

Looks like almost all libraries are static, is that by choice?  Seems rather awkward to compile against and leaves significant state in random user Makefiles that will change/break over time.  Mostly removing all the advantages of the module based environment.  Am I missing something.  I ended up with something like:

$ mpiCC -fPIC -O3 -L../../base/lib -L/share/apps/build-1.5/.local/easybuild/software/PETSc/3.3-p2-goolf-1.4.10-Python-2.7.3/lib -L/usr/lib/X11 -o main build/main.o build/OutputManager.o build/SystemState.o build/SystemDataElement.o build/Geometry.o build/CartesianGeometry.o build/ProjectionScheme.o build/ProjectionScheme_Tracers.o build/BlockNeighborData.o build/TestCase.o build/TestCase2.o build/TestCase3.o -lrt -ltempestbase -lX11 -lpetsc -L/share/apps/build-1.5/.local/easybuild/software/ParMETIS/3.1.1-goolf-1.4.10/lib -lparmetis -lmetis -L/share/apps/build-1.5/.local/easybuild/software/FFTW/3.3.3-gompi-1.4.10/lib -lfftw3_mpi -lfftw3 -L/share/apps/build-1.5/.local/easybuild/software/Hypre/2.8.0b-goolf-1.4.10/lib -lHYPRE -lumfpack -lamd -lfftw3  -lpthread -llapack -lblas

Normally it would be something like:
<modules setup LD_LIBRARY_PATH>
mpiCC -fPIC -O3 -L../../base/lib -L/share/apps/build-1.5/.local/easybuild/software/PETSc/3.3-p2-goolf-1.4.10-Python-2.7.3/lib -L/usr/lib/X11 -o main build/main.o build/OutputManager.o build/SystemState.o build/SystemDataElement.o build/Geometry.o build/CartesianGeometry.o build/ProjectionScheme.o build/ProjectionScheme_Tracers.o build/BlockNeighborData.o build/TestCase.o build/TestCase2.o build/TestCase3.o -lrt -ltempestbase -lX11 -lpetsc
-lparmetis -lmetis -lHYPRE -lumfpack -lamd -lfftw3  -lpthread -llapack -lblas

Am I doing it wrong?

**Comment by boegel** [comment]
no replies for ages, so closing this...
