### ISSUE TITLE
apply libreadline 6.3 patches

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#3085]
There are a bunch of patches available for libreadline 6.3, we should probably apply them: http://ftp.gnu.org/gnu/readline/readline-6.3-patches

One of these (002) fixes a segfault issue that your can trigger easily with IPython 3.x, cfr https://gist.github.com/boegel/87495470c65c8b9372c604941b98e30d and https://github.com/hpcugent/easybuild-easyconfigs/pull/2457#issuecomment-220347366

**Comment by boegel** [comment]
segfault patch is applied in #3086

**Comment by boegel** [comment]
@wpoely86 we should also apply the other patches?

**Comment by Micket** [comment]
libreadline-6.3 is already oudated/archived now. I hope it got all the patches it deserved.
