### ISSUE TITLE
ncurses 6.0 fails to build with foss-2016b toolchain when old ada support is picked up from OS

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-easyconfigs#3339]
Adding `--without-ada` to the easyconfig from #3299 works.

**Comment by boegel** [comment]
How does this relate to #3335?

I wonder why we haven't seen this problem...

**Comment by migueldiascosta** [comment]
I don't think it's related... this seems to only happen because gcc-gnat is detected (from OS, RedHat 6.6) but is much older (4.4.7), if either it is not installed or is more recent there probably isn't an issue.

I suppose another way this would not happen is if the easybuild installed GCCcore included ada support, but at least in this case it didn't (should it?).

This is in a system I don't have root access to, I also didn't see this problem in my systems, will try to reproduce.

**Comment by migueldiascosta** [comment]
I can't reproduce the error on my systems, even installing old gcc-gnat and binutils. If this is too system specific, do close this issue.

**Comment by boegel** [comment]
@migueldiascosta it sounds like this is quite specific to the system where you were hitting this problem, indeed

Let's indeed close this, and reconsider in the future if this pops up again.

**Comment by boegel** [comment]
@crphilipp You mentioned you ran into this too? Can you give us some more context, with the above in mind?

**Comment by crphilipp** [comment]
I have added "--without-ada" to configopts in ncurses-6.0-GCCcore-6.4.0.eb and it built without issues.

**Comment by boegel** [comment]
So, should we add `--without-ada` to `configopts` in all (recent) `ncurses` easyconfigs?

**Comment by boegel** [comment]
done in #6228
