### ISSUE TITLE
Cannot install EasyBuild 2.8.2 via EasyBuild 2.7.0

### ISSUE THREAD

**Issue by andreas-h** [easybuilders/easybuild-easyconfigs#3362]
I have a working installation of EasyBuild 2.7.0. I wanted to "update" to 2.8.2, so I downloaded the easyconfig for 2.8.2 from github master, and tried to build it with `eb EasyBuild-2.8.2.eb`.  This doesn't work on my machine due to some setuptools problem, see the log at https://gist.github.com/andreas-h/8e73d5d34b83c8b6618b7a3ccec85f14.

Is this some problem with EasyBuild, or is it a problem with my machine/setup?

**Comment by verdurin** [comment]
Does it work if you use this method?:

```
eb --from-pr 3341

```
?

**Comment by andreas-h** [comment]
Thanks, but no, it doesn't:

The command `eb --from-pr 3341 EasyBuild-2.8.2.eb` still produces the
same `ImportError: No module named setuptools.command.test` as before.

**Comment by verdurin** [comment]
Please try the exact command I pasted - adding the EB to the end of that command is incorrect.

The PR includes the necessary EB automatically.

**Comment by andreas-h** [comment]
Sorry, I wasn't aware of that. Tried again, this time with the command

    eb --from-pr 3341

and the error is still the same

    2016-07-17 21:38:10,974 build_log.py:152 ERROR cmd " /usr/bin/python setup.py install --prefix=/home/hilboll/eb/software/EasyBuild/2.8.2 " exited with exitcode 1 and output:                                                                                                                                              Traceback (most recent call last):
      File "setup.py", line 43, in <module>
        import shared_setup_dist_only as shared_setup
      File "external_dist_only/shared_setup_dist_only.py", line 41, in <module>
        import setuptools.command.test
    ImportError: No module named setuptools.command.test
     (at easybuild/tools/run.py:397 in parse_cmd_output)

**Comment by verdurin** [comment]
Do you have `setuptools` installed locally?

Does re-running the latest version of the `bootstrap` script work?

**Comment by andreas-h** [comment]
> Do you have `setuptools` installed locally?

Yes:

    $ python
    Python 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import setuptools
    >>> setuptools.__version__
    '20.9.0'
    >>> import setuptools.command.test
    >>> 

> Does re-running the latest version of the `bootstrap` script work?

Yes.  re-running the latest version of `bootstrap` script works fine.

Can I just do that, providing the same `$EASYBUILD_PREFIX` I'm already
using for my 2.7.0 installation?  Or will this break things?

**Comment by verdurin** [comment]
@andreas-h - no, that shouldn't break anything. I know some sites use that method to upgrade.

**Comment by andreas-h** [comment]
Bootstrapping also didn't work; I created a seperate issue for that: https://github.com/hpcugent/easybuild-framework/issues/1854

**Comment by boegel** [comment]
Hmm, this is quite strange... Any updates on this @andreas-h?

**Comment by boegel** [comment]
@andreas-h This is a very weird problem as well.

Since the bootstrap problem you reported at https://github.com/hpcugent/easybuild-framework/issues/1854 *seems* to be related with a `setuptools` problem as well, can you check now whether this is currently still a problem?

Google tells me nobody has run into this `ImportError` before, which seems *very* fishy to me...

**Comment by andreas-h** [comment]
Running

    module load EasyBuild/2.7.0
    eb --from-pr 3341 -f

produces the following error:

    == 2016-09-06 12:24:41,522 build_log.py:152 ERROR cmd " /usr/bin/python setup.py install --prefix=/home/hilboll/eb/software/EasyBuild/2.8.2 " exited with exit
    Traceback (most recent call last):
      File "setup.py", line 43, in <module>
        import shared_setup_dist_only as shared_setup
      File "external_dist_only/shared_setup_dist_only.py", line 41, in <module>
        import setuptools.command.test
    ImportError: No module named setuptools.command.test
     (at easybuild/tools/run.py:397 in parse_cmd_output)

On the other hand, importing that module from the Python shell works:

    python -c 'import setuptools; print(setuptools.__version__); import setuptools.command.test'
    20.9.0

**Comment by boegel** [comment]
@andreas-h is this still relevant, since you mentioned in https://github.com/hpcugent/easybuild-framework/issues/1854 that the problem got fixed?

**Comment by Micket** [comment]
Long since outdated/resolved (and there are multiple ways of installing EB)
