### ISSUE TITLE
Binutils problem

### ISSUE THREAD

**Issue by sametd** [easybuilders/easybuild-easyconfigs#3405]
I was trying to compile intel packages (with a fresh easybuild) but easybuild fails at the GCCcore/4.9.3 state with the error below:

> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether ln works... yes
> checking whether ln -s works... yes
> checking for a sed that does not truncate output... /bin/sed
> checking for gawk... no
> checking for mawk... mawk
> checking for libatomic support... yes
> checking for libcilkrts support... yes
> checking for libitm support... yes
> checking for libsanitizer support... yes
> checking for libvtv support... yes
> checking for gcc... gcc
> checking for C compiler default output file name...
> configure: error: in /dev/shm/GCCcore/4.9.3/dummy-/gcc-4.9.3/obj:
> configure: error: C compiler cannot create executables

i know this is a common problem but somehow this is different. Also config.log can be seen below.

> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.1)
> 
> configure:4249: $? = 0
> configure:4238: gcc -V >&5
> gcc: error: unrecognized command line option '-V'
> gcc: fatal error: no input files
> compilation terminated.
> configure:4249: $? = 1
> configure:4238: gcc -qversion >&5
> gcc: error: unrecognized command line option '-qversion'
> gcc: fatal error: no input files
> compilation terminated.
> configure:4249: $? = 1
> configure:4269: checking for C compiler default output file name
> configure:4291: gcc    conftest.c  >&5
> /opt/programs/binutils/2.25/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o: unrecognized relocation (0x2a) in section `.init'
> /opt/programs/binutils/2.25/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> configure:4295: $? = 1
> configure:4332: result:
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME ""
> | #define PACKAGE_TARNAME ""
> | #define PACKAGE_VERSION ""
> | #define PACKAGE_STRING ""
> | #define PACKAGE_BUGREPORT ""
> | #define PACKAGE_URL ""
> | /* end confdefs.h.  */
> |
> | int
> | main ()
> | {
> |
> |   ;
> |   return 0;
> | }
> configure:4338: error: in`/dev/shm/GCCcore/4.9.3/dummy-/gcc-4.9.3/obj':
> configure:4342: error: C compiler cannot create executables

To check this error i used two seperated distrubutions, Ubuntu 16.04 and Arch linux (both amd64) with the all latest updates. Both gave me the same error. Ubuntu has build-essential etc. 

When i remove binutils from dependencies of GCCcore it builds just fine.
I also used custom binutils config files from the other related issues but it also didn't solve my issue.

**Comment by boegel** [comment]
@sametd What version is the system binutils? It's possible that using an older binutils version than the one the system has is going to cause problems like this (but I'm not sure)...

@wpoely86: any ideas?

**Comment by sametd** [comment]
System has binutils 2.26.1, i will try to downgrade it right now and report the result

**Comment by sametd** [comment]
I downgraded system gcc to 4.9.2 and binutils 2.24 but it didn't solve the issue

**Comment by sametd** [comment]
Full config.log can be seen from the link below
http://pastebin.com/avDvd4wQ

**Comment by akesandgren** [comment]
A quick google of "gcc 6 binutils" indicates that you probably need binutils 2.27 or later.
And it is the crti.o from the system compiler (gcc 6.1.1) that is causing problems for the 2.25 binutils.
At the very least, try to build that with a 2.26 binutils instead.

I.e., it is the easybuild built 2.25 binutils that is failing.

**Comment by wpoely86** [comment]
Yes, I agree with @akesandgren. Using a `crti.o` from a newer binutils with a older version is not something that is supported (as far as I know).

**Comment by boegel** [comment]
@sametd did the answers above help you? It seems like using an older binutils than the one provided by the system isn't going to work?

**Comment by Micket** [comment]
For anyone who happen to find this issue:
Building older binutils that the OS is a known problem, and the only feasible way to resolve it is to 
1. filter out old binutils packages (meaning your modules would rely on the OS provided binutils instead
2. or write a hook to replace the dependency with a newer one
3. just using a newer toolchain instead.
