### ISSUE TITLE
Perl module DB_File requires DB dep

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#342]
The Perl module `DB_File`, which is included in the list of extensions in the non-bare Perl easyconfig (because it's a dependency for other modules, e.g. BioPerl), depends on `DB` (i.e. requires `db4-devel` to be installed for `db.h`).

Building `DB` itself is not a big issue, but making `DB_File` correctly use the DB installation in a non-default path is proving to be tremendously difficult. Although the configure and build steps work, the `make test` fails with errors like

```
Can't load '/path/to/DB_File-1.827/blib/arch/auto/DB_File/DB_File.bundle' for module DB_File:
dlopen(/path/to/DB_File-1.827/blib/arch/auto/DB_File/DB_File.bundle, 2): Symbol not found: _db_create
```

For now, I'll assume the required deps for `DB_File` are provided by the OS; it usually is in this case, because `db4` is a common dependency.

**Comment by boegel** [comment]
This issue only occurs with the Perl 5.16.3 easyconfigs we have; for the more recent Perl 5.20.x and 5.22.x easyconfigs, `DB_File` has been fleshed out in a separate easyconfig, that includes `DB`

**Comment by Micket** [comment]
Closing this issue as it's long since resolved.
