### ISSUE TITLE
FreeType circular deps for extended capabilities (with HarfBuzz)

### ISSUE THREAD

**Issue by hajgato** [easybuilders/easybuild-easyconfigs#3441]
We might have to put in order `FreeType` (its with a circular dep for extended capabilities):
`FreeType` recommends `HarfBuzz`
`HarfBuzz` recommends `FreeType`
Solution would be:
1) install `FreeType` without `HarfBuzz`
2) install `HarfBuzz` (with `FreeType` without `HarfBuzz`)
3) reinstall `FreeType` (with `HarfBuzz`)

We could use the new easyblock https://github.com/hpcugent/easybuild-easyblocks/pull/979
see https://github.com/hpcugent/easybuild-easyconfigs/pull/3440
Putting the installation order to
`FreeType`
`HarfBuzz`
`FreeType`
then we would have a FreeType-HarfBuzz bundle.
Thoughts?

**Comment by boegel** [comment]
@hajgato not sure the enhanced `ConfigureMake` is a good approach here, and not a big fan of listing the same thing twice either (for normal extensions, this would mean the 2nd one is just skipped)

**Comment by hajgato** [comment]
@boegel: well, this is one more reason to extend the `Bundle` and not to use enhanced `ConfigureMake`. Plus implement "force reinstall" for (this kind of) circular deps. I am sure there are a couple of similar, just I bumped this one recently. Alternatively, this could be solved using an `EasyBlock`  for `FreeType-HarfBuzz` (or `HarfBuzz-FreeType`?) , but maybe a general solution would be better?

**Comment by boegel** [comment]
@hajgato how about simply including the Freetype without Harfbuzz as build dep when installing Harfbuzz? Would that work?

**Comment by hajgato** [comment]
@boegel: I was thinking about it, but its a circular dep. 
This might work:
1) install `FreeType` (dep none)
2) install `HarfBuzz` (buildep FreeType)
3) install `FreeType` (dep HarfBuzz-Freetype [from 2])
Here we have `FreeType` with`HarfBuzz`, but no `HarfBuzz` with `Freetype` as a dep
So then we have to make a `HarfBuzz` with dep [from 3]. 
4) install `HarfBuzz` (dep `FreeType` from[3]) will give us 2 `HarfBuzz`, the installed one and `HarfBuzz` [from 2]. 
How would you name those modules? What would you do with the double `HarfBuzz`?

**Comment by hajgato** [comment]
@boegel: plus you have to load [from4], if you need `FreeType`

**Comment by boegel** [comment]
Urgh, what a mess... Is that how it is also done by other projects, e.g. RPMs?

Also, does the installation of both `HarfBuzz` and `FreeType` actually differ with the dependencies included? Or is the recommendation just to *use* them together?

**Comment by hajgato** [comment]
@boegel: `HafBuzz` extends the functionality of `FreeType`. I guess, For `HarfBuzz` a non extended functionaluity `FreeType` would be enough, but never checked. But then in this case, we would have two `FreeType` if we load `HarfBuzz`, one standard and one extended. Anyway, this is needed for __extended__ capability `FreeType` only.

**Comment by Micket** [comment]
I think it's safe to say by now that we haven't been hurt to much by missing out on whatever the extended functionality in freetype might have been (and circular deps would be a massive problem to deal with)
