### ISSUE TITLE
create an easyblock for scipy stack

### ISSUE THREAD

**Issue by JensTimmerman** [easybuilders/easybuild-easyconfigs#35]
http://www.scipy.org/stackspec.html
We should have support for the SciPy stack

**Comment by migueldiascosta** [comment]
"The SciPy Stack specification was developed in 2012. As of 2017, the SciPy Stack concept is obsolete given improvements in package management and distribution."

In any case, the SciPy-bundle easyconfigs (https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/s/SciPy-bundle) follow the same spirit, even if not exactly the same components
