### ISSUE TITLE
Question/Request - Official docker image for easybuild?

### ISSUE THREAD

**Issue by jerowe** [easybuilders/easybuild-easyconfigs#3514]
Hello,

I'm wondering if there is an official docker image for easybuild. I would like one for testing my easybuild-configs. I have a lot. ;-) I see the CI seems to be using the travis VM's. I'll don't mind building one to fit my needs, just wondering.

Thanks for the great project!

Best,
Jillian

**Comment by wpoely86** [comment]
We don't have an official docker image (yet). @rjeschmi was playing with it. Any news on that front?

**Comment by boegel** [comment]
There are several Docker images available on Docker Hub, see for example https://hub.docker.com/r/rjeschmi/easybuild-centos6/

I'm not sure how up-to-date they are, but maybe we should indeed have 'official' EasyBuild images, and consistently update them as new EasyBuild versions are released.

Now that Docker is properly supported on OS X, these may be of use to me as well for testing contributions, etc.

**Comment by boegel** [comment]
Maybe we should redirect this discussion to https://github.com/hpcugent/easybuild/issues, since this is not specific to easyconfigs at all?

**Comment by jerowe** [comment]
I'm not sure if there is an official image - but my organization put one up here - https://quay.io/repository/nyuad_cgsb/easybuild. `docker pull quay.io/nyuad_cgsb/easybuild`
