### ISSUE TITLE
R-3.3.1-intel-2016b.eb requires additional openssl dependency on SLE 11 SP1-3

### ISSUE THREAD

**Issue by dominikborkowski** [easybuilders/easybuild-easyconfigs#3560]
R-3.3.1-intel-2016b.eb introduces new R package: openssl. That package has a hard requirement for OpenSSL greater than 1.0:

Excerpt from its `configure` script:

```
pkg-config ${PKG_CONFIG_NAME} --atleast-version=1.0  2>/dev/null
```

And a link to its page: https://cran.r-project.org/web/packages/openssl/index.html

Unfortunately, SUSE Linux Enterprise hasn't introduced OpenSSL 1.0 until SLE 11 SP4, and that comes as a separate package, while everything else remains on OpenSSL 0.9.8. One possible way of getting it to compile on SLE 11 SP1-3 is to add explicit dependency EasyBuild provided OpenSSL, eg:

```
dependencies = [
    ('OpenSSL', '1.0.1s')
]
```

Hope others may find this useful.

**Comment by boegel** [comment]
@dominikborkowski can you include the error messages you were getting, so others running into this problem can find this issue easily?

Also, this issue should be closed since you've figured out a workaround, and there's nothing much we should do/change? Or is there?

**Comment by boegel** [comment]
closing as there's little we can do about this, workaround (including OpenSSL as dep via EB) is documented
