### ISSUE TITLE
Build all of EPD (Enthought Python Distribution) from source

### ISSUE THREAD

**Issue by JensTimmerman** [easybuilders/easybuild-easyconfigs#36]
- [ ] appinst  2.1.2   OS abstraction for installing application menus, links and icons
- [ ] apptools 4.1.0   application building block technologies
- [x] basemap  1.0.2   plots data on map projections with matplotlib
- [ ] biopython    1.59    tools for biological computation
- [ ] bitarray 0.8.0   efficient representation of arrays of booleans
- [ ] blist    1.3.4   list-like type with better asymptotic performance
- [ ] blockcanvas  4.0.1   visual environment for creating simulation experiments
- [ ] bsdiff4  1.1.1   binary diff and patch using the BSDIFF4-format
- [ ] casuarius    1.0 python-wrap of Cassowary linear constraint solver
- [ ] chaco    4.2.0   interactive 2D plotting
- [ ] cloud    2.4.6   access to PiCloud's cloud-computing platform
- [ ] codetools    4.0.0   code analysis and execution tools
- [ ] configobj    4.7.2   simple but powerful configuration file reader and writer
- [ ] coverage 3.5.2   Code coverage measurement for Python
- [x] curl 7.25.0  transferring data specified with URL syntax (C library, OSX and Linux only)
- [ ] Cython   0.16    language for writing C extensions for Python
- [x] distribute   0.6.26  download, build, install, upgrade, and uninstall Python packages
- [ ] docutils 0.8.1   Documentation Utilities
- [ ] enable   4.2.0   low-level drawing and interaction
- [ ] enaml    0.2.0   language for building dynamic user interfaces
- [ ] encore   0.2 low-level core modules for building applications
- [ ] enstaller    4.5.6   managing and install tool for egg distributions
- [ ] envisage 4.2.0   Extensible Application Framework
- [ ] epydoc   3.0.1   generates API documentation for Python modules from docstrings
- [ ] ets  4.2.0   components to construct custom scientific applications
- [ ] etsdevtools  4.0.0   tools to support Python development
- [ ] etsproxy 0.1.1   proxy modules for backwards compatibility  
- [ ] feedparser   5.1.1   handles RSS and Atom feeds
- [ ] foolscap 0.6.3   new version of Twisted's native RPC protocol
- [x] freetype 2.4.4   high-quality portable font engine
- [ ] fwrap    0.1.1   Tool to wrap Fortran 77/90/95 code in C, Cython and Python
- [x] GDAL 1.8.1   Geospatial Data Abstraction Library
- [ ] graphcanvas  4.0.0   Interactive Graph (network) Visualization
- [ ] grin 1.2.1   searches directories of source code better than grep or find
- [x] h5py 2.0.0   Python interface to the HDF library
- [x] hdf5 1.8.9   general purpose file format library for scientific data
- [ ] html5lib 0.95    HTML parser designed to follow the WHATWG HTML5 specification
- [ ] idle 2.7.3   interactive Python shell
- [ ] ipython  0.13.1  advanced shell for interactive and exploratory computing
- [ ] Jinja2   2.6 template engine
- [ ] jsonpickle   0.4.0   serializing any arbitrary object graph into JSON
- [ ] keyring  0.9.2   store and access your passwords safely
- [x] lib_netcdf4  4.2 NetCDF (network Common Data Form) library for array-oriented data
- [x] libgdal  1.8.1   Geospatial Data Abstraction Library
- [x] libjpeg  7.0 JPEG library
- [x] libpng   1.2.40  reference library for Portable Network Graphics
- [ ] libpython    1.2 mingw import library
- [x] libxml2  2.7.8   XML parser and toolkit
- [ ] libxslt  1.1.26  XSLT library with XPath support
- [ ] libYAML  0.1.4   YAML 1.1 parser and emitter (C library)
- [ ] lxml 2.3.4   XML/XSLT library with bindings to libxml2/libxslt
- [x] matplotlib   1.2.0   interactive 2D plotting library
- [ ] mayavi   4.2.0   interactive 3D visualization
- [x] MDP  3.2 Modular toolkit for Data Processing (MDP)
- [ ] mingw    4.5.2   native Windows port of GCC
- [x] MKL  10.3    Intel Math Kernel Library (runtime)
- [x] netCDF4  1.0 interact with in both the new netCDF 4 and 3 formats
- [ ] networkx 1.6 creating and manipulating graphs and networks
- [x] nose 1.1.2   extends the test loading and running features of unittest
- [ ] numexpr  2.0.1   fast evaluation of array expressions
- [x] numpy    1.6.1   general-purpose array-processing and math library
- [ ] openpyxl 1.5.8   reader and writer of Excel OpenXML files
- [x] pandas   0.10.0  data analysis library
- [x] paramiko 1.7.7.1 SSH2 protocol for secure connections to remote machines
- [ ] pep8 1.0.1   Python style guide checker
- [ ] PIL  1.1.7   image processing library
- [ ] ply  3.4 Python implementation of lex and yacc
- [ ] pyaudio  0.2.4   bindings for PortAudio
- [ ] Pycluster    1.50    clustering software for gene expression data analysis
- [ ] pycrypto 2.4.1   collection of cryptographic algorithms and protocols
- [ ] pydot    1.0.28  interface to Graphviz's Dot language
- [ ] pyface   4.2.0   GUI abstraction layer
- [ ] pyfits   3.0.6
- [ ] pyflakes 0.5.0   analyze Python programs and detect error
- [ ] pygarrayimage    0.0.7   allows NumPy arrays as source of texture
- [ ] pyglet   1.1.4   interface for developing visually-r
- [ ] Pygments 1.4 code syntax highlighting package written in Pytho
- [x] pyhdf    0.8.3   interface to the NCSA HDF4 library
- [ ] pyodbc   3.0.6   d
- [ ] PyOpenGL 3.0.1   python binding to OpenGL and related APIs
- [ ] pyOpenSSL    0.13
- [ ] pyparsing    1.5.6   module for creating parsers with a simple gra
- [ ] pyproj   1.9.0   cartographic transformations and geodetic computati
- [ ] pyserial 2.6 encapsulation the acces
- [ ] PySide   1.1.1   bindings for Qt
- [x] pytables 2.3.1   hierarchical
- [x] Python   2.7.3   general-purpose, high-level programming
- [ ] python_dateutil  1.5 extensions to the standard datetime module
- [ ] PythonDoc
- [ ] pytz 2011n   world timezone definitions, modern and hi
- [ ] pywin32  214 Python extensions for Windows
- [x] PyYAML   3.10    YAML parser and emitter 
- [ ] pyzmq    2.
- [ ] Qt   4.7.3   cross-platform application and UI framework
- [ ] Rep
- [x] scikit_learn 0.11    set of python modules for machine learning and data mining
- [ ] scikit
- [ ] scikits.timeseries   0.91.3  manipulating
- [ ] scimath  4.1.0   support for scientific
- [x] scipy    0.10.1  libraries for mathematics, science, and engin
- [ ] scite    1.74    Text editor based on Scintilla
- [ ] scons    2.0.1   Python
- [ ] Shapely  1.2.14  Geometric objects, predicates, and operations
- [ ] Si
- [ ] Sphinx   1.1.2   creates intelligent and beautiful
- [ ] SQLAlchemy   0.7.6   SQL toolkit and Object Relational Mapper
- [ ] statsmodels  0
- [ ] swig 1.3.40  C and C++ wrapper and interface generator
- [ ] sympy    0.7.1   library
- [ ] tornado  2.2 non-blocking web server
- [ ] traits   4.2.0   object attribut
- [ ] traitsui 4.2.0   traits-capable windowing framework
- [ ] Twi
- [x] VTK  5.6.0   3-D computer graphics, image processing
- [ ] wxPython 2.9.2.4 wrapper around the wxWidget
- [ ] xlrd 0.7.6   extract data from Microsoft Excel (tm)
- [ ] xlwt 0.7.4   create spreadsheet files compatible wi
- [x] zlib 1.2.6   cross-platform lossless data-compression library
- [ ] zope.inter

**Comment by migueldiascosta** [comment]
both EPD and it's successor Canopy are gone, there's EDM but even just listing the packages seems to require a commercial subscription (tried with their docker image). 

This issue as it is doesn't seem to make sense anymore, so closing
