### ISSUE TITLE
MariaDB built with intel/2016b is broken because of bug in binutils 2.26

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#3618]
The `libmysqlclient.so.18` (part of MariaDB) built with `intel/2016b` is broken because of a bug in `binutils` 2.26 (which is part of `intel/2016b`), cfr. https://sourceware.org/bugzilla/show_bug.cgi?id=19698

It manifests when trying to install the `mysqlclient` Python wrappers, as follows:

```
== 2016-09-26 17:32:11,234 build_log.py:163 ERROR Sanity check failed: mysqlclient failed to install, cmd '/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/2.7.12-intel-2016b/bin/python -c "import MySQLdb"' (stdin: None) output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/MySQLdb/__init__.py", line 19, in <module>
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 6, in __bootstrap__
ImportError: /user/home/gent/vsc400/vsc40023/.python-eggs/mysqlclient-1.3.7-py2.7-linux-x86_64.egg-tmp/_mysql.so: symbol THR_KEY_mysys, version libmysqlclient_16 not defined in file libmysqlclient.so.18 with link time reference
 (at easybuild/framework/easyblock.py:1954 in _sanity_check_step)
```

As far as I can tell, the only way to fix this is to use a different version of `binutils` when building `MariaDB`, but since `binutils` is a part of the toolchain being used there's no (easy) way of doing this currently...

**Comment by boegel** [comment]
@wpoely86 thoughts on this one?

**Comment by boegel** [comment]
see also test report in #3617

**Comment by wpoely86** [comment]
force the system linker?

**Comment by boegel** [comment]
@wpoely86 but then we're at the mercy of the OS again (which may be using `binutils` 2.26 too, for all we know)...

I was more thinking along the lines of adding support for (build?) dependencies that override other versions that get loaded indirectly.
That does imply a whole bunch of things though, like support for swapping rather than simply loading dependencies, and also (potentially) for using `module swap` rather than `module load` in the generated module file when appropriate...

For now, we can get away with only allowing this for build dependencies...

**Comment by boegel** [comment]
No longer relevant imho...
