### ISSUE TITLE
ncurses should be built with --enable-termcap to satisfy libreadline dependencies

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyconfigs#3807]
The easyconfig for libreadline says:

```
\# for the termcap symbols, use EB ncurses
preconfigopts = "env LDFLAGS='-lncurses'"
```

But the easybuilt ncurses does not contain, for instance, this termcap symbol, `tgetflag`, which libreadline uses.

ncurses needs to be built with `--enable-termcap` to contain the required symbols.
And to work for  libreadline, `--with-termlib` can not be used (like it currently is for ncurses-6.0.eb) becuse then those symbols end up in `libtinfo`

**Comment by boegel** [comment]
@wpoely86 I think you've looked into this before, thoughts?

I'm not sure if switching to not using `--with-termlib` is an option now though, unless that's a pure bug fix and doesn't cause any other fallout...

**Comment by wpoely86** [comment]
Weird, our `ncurses` do have this symbol. I checked and we don't use `libtinfo` anywhere in ncurses (or libreadline).

You seem to have an interesting build system @akesandgren What OS are you using to trigger this?

**Comment by geimer** [comment]
Maybe kind of related: Even though `ncurses` is listed as a build dependency for `LLVM`, it seems to pick up `libtinfo.so` from the system, as `--with-termlib` is not given for the non-dummy `ncurses` builds. So, if `--with-termlib` can't be used  for `libreadline`, but may be needed for `LLVM`, we are in a catch-22 situation, no?

**Comment by wpoely86** [comment]
Not really I think.
We need to enable `--with-termlib` but that means we can drop '-lncurses` and replace it by `-ltinfo` in a lot of cases (including libreadline). At least, that's how I understand it.

**Comment by akesandgren** [comment]
@wpoely86 Ubuntu xenial, I had no changes to the ncurses easyconfigs at the time.

**Comment by boegel** [comment]
@akesandgren Is this still relevant after the changes in #5067 and #5074?

**Comment by akesandgren** [comment]
Hopefully not, but I don't remember what chain was actually hit by the problem.
Let's close this one as not needed due to the above and go on with life.
