### ISSUE TITLE
Add extra bioinformatics packages according to popular demand & refresh versions.

### ISSUE THREAD

**Issue by fgeorgatos** [easybuilders/easybuild-easyconfigs#383]
Hi,

Some applications from the following lists may become important/critical for folks,
it would be good to know which ones they are, to join forces together:
- http://hpcbios.readthedocs.org/en/latest/HPCBIOS_2012-94.html
- http://www.eaglegenomics.com/2012/04/the-elements-of-bioinformatics/

Furthermore, near end-of-year, the versions mentioned in this one have to be promoted to latest and greatest (ie. providing a 2nd refreshed working environment for bioinformaticians):
https://github.com/fgeorgatos/easybuild.experimental/blob/master/users/fgeorgatos/HPCBIOS/HPCBIOS_Bioinfo-goolf-1.4.10.eb

This is a long-term request, please supply feedback until end-of-October,
so that we can react on it thereafter, in the optimal way.

**Comment by Micket** [comment]
Adding extra packages or according to popular demand and refreshing versions (regardless of research domain) is something we already do to the maximum of our capacity.
