### ISSUE TITLE
Tk should have libX11-devel as os dependency

### ISSUE THREAD

**Issue by andreas-h** [easybuilders/easybuild-easyconfigs#3864]
I was just trying to install `Tk-8.6.5-foss-2016b.eb` with EasyBuild 3.0.0, and got the error that `X11/Xlib.h` was not found.  This was on CentOS7.2, so I installed `sudo yum install libX11-devel`, and everything works fine.

It seems to me that Tk should have the X11 headers as OS dependency.

**Comment by boegel** [comment]
@andreas-h No longer relevant now that we include `X11` as a dep in `Tk` easyconfigs?

**Comment by andreas-h** [comment]
We switched to Python-3.6.1-intel-2017a, which doesn't depend on Tk at all any more. I was never interested in having Tk on my nodes, this was just needed to satisfy the Python dependency on Tk. So yes, no longer relevant for me.

**Comment by verdurin** [comment]
@boegel - what about fixing older versions of this? Just encountered trying to test a PR from `foss-2016b`.

**Comment by Micket** [comment]
Tk has a X11 (not os) dependency these days.
