### ISSUE TITLE
ncview Intel compiler issue EB 2.X/3.X

### ISSUE THREAD

**Issue by hajgato** [easybuilders/easybuild-easyconfigs#3880]
`ncview` must be compiled with exactly the same compiler (As far as I understand the same _path_ as well) then `netCDF`. If your `netCDF` was previously compiled with EB 2.X, and you compile `ncview`  with EB 3.X, then your build will fail, because `Intel` toolchain MPI C compiler is changed from `mpicc` to `mpiicc`, and `ncview` is not intelligent enough to recognize that the two compilers are the same. Solution: you have to recompile `netCDF` with EB 3.X.

**Comment by boegel** [comment]
Thanks for reporting this @hajgato.

This is indeed some (minor) fallout of https://github.com/hpcugent/easybuild-framework/pull/2005, but I blame `ncview` here...

Can you share the exact error you were getting, for future reference?

**Comment by hajgato** [comment]
You would get an error message at `configure_step`:

```
======================================================================
Configuration error: You specified that the "/apps/brussel/ivybridge/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/bin64/mpiicc" C compiler should be
used to build ncview, but the netcdf library was compiled with the "/apps/brussel/ivybridge/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/bin64/mpicc"
compiler.  Here is the path where I found the netcdf library:
     -L/apps/brussel/ivybridge/software/netCDF/4.4.1-intel-2016b/lib64 -lnetcdf -lhdf5_hl -lhdf5 -lsz -lz -ldl -lm -liomp5 -lpthread -lcurl
You must use the same compiler for ncview as was used to build the netcdf library!

There are two possible ways to fix this.

1) Download the netcdf library and compile it with the /apps/brussel/ivybridge/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/bin64/mpiicc compiler,
install it, and try again to build ncview.  NOTE that if you do this,
you might have more than one version of the netcdf library on your system,
built with differnt compilers, which can get confusing.  If you do this,
you will have to specify the path to the (new) version of nc-config
that was compiled using the /apps/brussel/ivybridge/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/bin64/mpiicc compiler by configuring ncview in a
way similar to this:

   ./configure --with-nc-config=/path/to/newly/compiled/nc-config

2) Configure ncview to use the /apps/brussel/ivybridge/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/bin64/mpicc compiler.
To do this, set environmental variable CC to /apps/brussel/ivybridge/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/bin64/mpicc
and run ./configure again
===================================================================
```

**Comment by boegel** [comment]
@hajgato OK, thanks.

I don't think there's much we can do about this, other than rebuilding netCDF?

**Comment by hajgato** [comment]
@boegel we could patch `ncview`, but I think its not the way to go.

**Comment by boegel** [comment]
@hajgato patch it to ignore a mismatch in compiler name/path? I guess that's an option, but probably not worth the trouble.

**Comment by Micket** [comment]
This hasn't been an issue for some time now and noone will hopefully spend their time patching a 2016 release.
