### ISSUE TITLE
MATLAB R2016b RPM issue

### ISSUE THREAD

**Issue by shahzebsiddiqui** [easybuilders/easybuild-easyconfigs#3945]
I am having an issue with RPMing Matlab.

I recall having to rpm matlab myself and it requires multiple RPMs because it is too large to fit inside one. Does Easybuild take care of this.

I can't tell what the error is from the log. Please take a look at this.

Here is my output and log is attached at bottom

Building remotely on hpcswadm+hpcv18.pfizer in workspace /hpc/grid/scratch/jenkins/workspace/hpc-software/MATLAB-2016b
Cloning the remote Git repository
Cloning repository ssh://srvgbl-hpcbuild@pfizer.collab.net:29418/easybuild
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git init /hpc/grid/scratch/jenkins/workspace/hpc-software/MATLAB-2016b # timeout=10
Fetching upstream changes from ssh://srvgbl-hpcbuild@pfizer.collab.net:29418/easybuild
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git --version # timeout=10
using GIT_SSH to set credentials id_rsa_hpcbuild
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git -c core.askpass=true fetch --tags --progress ssh://srvgbl-hpcbuild@pfizer.collab.net:29418/easybuild +refs/heads/*:refs/remotes/origin/*
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git config remote.origin.url ssh://srvgbl-hpcbuild@pfizer.collab.net:29418/easybuild # timeout=10
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git config remote.origin.url ssh://srvgbl-hpcbuild@pfizer.collab.net:29418/easybuild # timeout=10
Fetching upstream changes from ssh://srvgbl-hpcbuild@pfizer.collab.net:29418/easybuild
using GIT_SSH to set credentials id_rsa_hpcbuild
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git -c core.askpass=true fetch --tags --progress ssh://srvgbl-hpcbuild@pfizer.collab.net:29418/easybuild +refs/heads/*:refs/remotes/origin/*
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 3df05d72e26681d4b8f1d09b91624b2636e7a4ac (refs/remotes/origin/master)
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git config core.sparsecheckout # timeout=10
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git checkout -f 3df05d72e26681d4b8f1d09b91624b2636e7a4ac
 > /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/git/2.4.6/bin/git rev-list 73bf776c4a14b77751d94e0c26c43cd79c6b68f6 # timeout=10
First time build. Skipping changelog.
[MATLAB-2016b] $ /bin/bash --login /tmp/hudson7119201660382167186.sh
ERROR: Build of /hpc/grid/scratch/jenkins/workspace/hpc-software/MATLAB-2016b/MATLAB/MATLAB-2016b.eb failed (err: 'build failed (first 300 chars): cmd "fpm --workdir /hpc/grid/scratch/tmp/eb-bxPBPj/eb-pkgs-6Db2jt --name "MATLAB-2016b" --provides "MATLAB-2016b" -t rpm -s dir --version eb-3.0.1 --iteration 1 --description "MATLAB is a high-level language and interactive environment\nthat enables you to perform computationally intensive tasks fast')
== temporary log file in case of crash /hpc/grid/scratch/tmp/eb-bxPBPj/easybuild-KiCRKB.log
== processing EasyBuild easyconfig /hpc/grid/scratch/jenkins/workspace/hpc-software/MATLAB-2016b/MATLAB/MATLAB-2016b.eb
== building and installing MATLAB/2016b...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== FAILED: Installation ended unsuccessfully (build directory: /nfs/grid/software/RHEL7-BUILD/easybuild/build/MATLAB/2016b/dummy-): build failed (first 300 chars): cmd "fpm --workdir /hpc/grid/scratch/tmp/eb-bxPBPj/eb-pkgs-6Db2jt --name "MATLAB-2016b" --provides "MATLAB-2016b" -t rpm -s dir --version eb-3.0.1 --iteration 1 --description "MATLAB is a high-level language and interactive environment
that enables you to perform computationally intensive tasks fast
== Results of the build can be found in the log file(s) /hpc/grid/scratch/tmp/eb-bxPBPj/easybuild-MATLAB-2016b-20161216.152320.sIGQy.log
Build step 'Execute shell' marked build as failure
CollabNet Tracker: Build is continuing to fail; updating issue.
CollabNet Tracker: Successfully uploaded build log.
CollabNet Tracker: updateFailingBuild failed due to org.apache.axis.AxisFault: Setting field status in folder projects.hpc/tracker.software_stack to value 'Open' violates status transition constraints.[exid198c42eda1ab7fa4f05b7aea]
Finished: FAILURE

[easybuild-NWChem-6.1.1-20161208.104055.yjdlB.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/661419/easybuild-NWChem-6.1.1-20161208.104055.yjdlB.txt)

**Comment by Minerva411** [comment]
Maybe you wanna check: [https://github.com/hpcugent/easybuild-easyconfigs/issues/3867], Good Luck

**Comment by boegel** [comment]
@shahzebsiddiqui the log you provide is for NWChem, not for MATLAB?

Also, EasyBuild currently does not take care of splitting up an RPM in case it gets too big, no.
I doubt that will happen soon, I'm afraid...

**Comment by rjeschmi** [comment]
I don't think the size of the RPM is an issue here. Anything beyond RHEL or Centos 6 should be fine with large RPMs.

https://stackoverflow.com/questions/10313873/how-to-get-around-rpm-size-limit

**Comment by Micket** [comment]
As there was never any follow up, and this is far outdated already, i'll just close this.
