### ISSUE TITLE
NCL file out of date?  Dependencies missing?

### ISSUE THREAD

**Issue by spikebike** [easybuilders/easybuild-easyconfigs#395]
I'm a big confused.

NCL-6.0.0-goolf-1.4.10.eb mentions a bunch of dependencies.

Yet when I look at the manual for NCL:
http://www.ncl.ucar.edu/Download/build_from_src.shtml

It doesn't mention ESMF, but it does mention PROJ.4, HDF-EOS2, and GDAL.  None of which exist for goolf.

**Comment by Micket** [comment]
Looking at recent NCLs, it all looks fine to me, so I guess this got solved quite some years ago.
