### ISSUE TITLE
Missing perl-Thread-Queue dep for xorg-macros

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#4025]
In building updated R easyconfigs with `X11` support, I found that I had to install `perl-Thread-Queue` on build nodes, and this wasn't specified as an OS dep in the `xorg-macros` easyconfig.

**Comment by boegel** [comment]
This has come up before, cfr. #1822.

Should we look into an easyconfig for `perl-Thread-Queue` (that used the system Perl) so we can include that as a build(?) dep?

**Comment by verdurin** [comment]
You mean to get around the fact that we can't have system build deps? (Or can we?)

Not sure what the advantage is of doing it this way?

**Comment by boegel** [comment]
follow-up in #5174, seems like it's not really needed after all?
