### ISSUE TITLE
remove (archive) OpenSSL and zlib easyconfigs

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild-easyconfigs#4058]
I think, in general, that it is the opinion of the group (EB community), that one should use the distribution provided OpenSSL so that one doesn't have to rebuild things as updates are issued from the upstream vendor/provider (for timely security updates).   Similarly, I believe on most Linux distributions, that openssl-devel relies upon a zlib-devel package (.rpm or .deb).

I propose we:

1) move all OpenSSL and zlib easyconfigs to archive
2) for every easyconfig that references them, replace with the appropriate "osdependencies".

zlib is tricky and leads to things like fseek64 linkage errors if one isn't careful.  Let's take it out of the equation (like we've done with OpenSSL).

Anyway... rebuilding all my toolchains from the ground up after upgrading from RH7.2 to 7.3 (the glibc upgrade causes all my shit to segfault now.... 7.2's glibc is fine.... the new one falls on its face all over the place [much like me in my drunken state Friday as we swore in a new president]).   Trying to narrow the window of possibilities.

I think given the decision to use the system OpenSSL implies/dictates that we should use the system zlib too.   But that's just me (dumb American who somehow allowed a moron to be elected president).

**Comment by vanzod** [comment]
Jack,
In my case I am building everything (e.g. Python) against OpenSSL 1.0.2h since on the system (RHEL 6) we have OpenSSL 1.0.1e so it seemed an appropriate thing to rely on a newer version via EB than the one available on the system.
But that's just me (a green card holder that does not know if it is wise to take a vacation abroad)

**Comment by JackPerdue** [comment]
First and foremost (more important than any code).... if you are in the states I wouldn't move at the moment.

I'm good... I think... for the moment... as a US citizen I have a  US passport  But its a new day so who knows and might just be safe to stay where you are. (I got no clue what's going on either)

That said, although RHEL's versioning numbers run behind the latest and greatest OpenSSL, they do backport any/all security/bug fixes to the version they support.  And you won't have to worry about updating your 1.2.x to 1.2.y (and rebuilding everything) if 1.2x has a security problem.  I think the general consensus is that using the system/distro version (with timely updates) is the most secure solution .

**Comment by henkela** [comment]
Hi Jack, 
Has there been a decision on zlib? I'm on CentOS 7.3 and built everything using zlib 1.2.11...

(Still wondering if it's moron or comedian beyond our understanding...)

**Comment by Micket** [comment]
I don't believe we have really seen any issues with zlib like this. Noone has complained about it at least, and it would be a biiig can of worms to try and change this now. Until further notice, I saw we will continue to build like this, zlib in easybuild, openssl as a OS wrapper.
