### ISSUE TITLE
Installation of additional toolboxes along with Octave.

### ISSUE THREAD

**Issue by lekshmideepu** [easybuilders/easybuild-easyconfigs#4108]
Basic Octave installation doesn't include the additional toolboxes given in the following link: https://octave.sourceforge.io/packages.php

Would it be possible to have a kind of Octave forge bundle like the Python bundle (PYPI packages)?

Octave forge link of individual packages: https://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/

**Comment by boegel** [comment]
update on this: @lekshmideepu was working on this during the EasyBuild User Meeting last week, and more or less got it working; hopefully this will make it into EasyBuild soon

**Comment by boegel** [comment]
@lekshmideepu Did you ever get to finish this? Is the work-in-progress support that you had during the EasyBuild User Meeting at JSC available somewhere?

I need to install the `signal` package in Octave, and I was hoping to leverage your work rather than starting from scratch to add support for installing Octave packages...

**Comment by boegel** [comment]
@damianam @ocaisa ping on this, do you have access to @lekshmideepu's WIP support for this?

**Comment by lekshmideepu** [comment]
@boegel Sorry for the late response. I was on vacation since mid of August and back to office only today. I have the already worked files on our local system. As our users requirement changed, I postponed this work for some time and got busy with other stuff.

**Comment by boegel** [comment]
@lekshmideepu Could you provide what you have? I would like to continue where you left off, we have a need for support for installing Octave packages as extensions since recently...

**Comment by lekshmideepu** [comment]
@boegel : sent you the files by mail.

**Comment by boegel** [comment]
Excellent, thank you @lekshmideepu!

**Comment by boegel** [comment]
Support for installing Octave packages as extensions is implemented in https://github.com/easybuilders/easybuild-easyblocks/pull/1304, on top of the work @lekshmideepu sent me.

Thanks for your work on this @lekshmideepu!
