### ISSUE TITLE
Naming Structures

### ISSUE THREAD

**Issue by jerowe** [easybuilders/easybuild-easyconfigs#4120]
Hi all,

What does everyone think about having a different naming structure for perl/python/R/whatever I am missing packages?

Instead of 

```
gsl-1.9-10-intel-2014b-R-3.1.1.eb
```

```
r-gsl-1.9-10-intel-2014b-R-3.1.1.eb`
```
I see that for this one it is appended with the R version. I'm not sure if this is the case for everything, but I like it! For bioinformatics packages in particular it would be helpful to 'pin' boost, perl, python, R and possibly samtools. 

This would also relieve the issue of case insensitive file systems. I think the default OSX is case insensitive. Dropbox is case insensitive, although that is not an easybuild problem.

**Comment by boegel** [comment]
@jerowe I noticed you never got a reply to this...

Doesn't this lead to duplication, since you already have `-R-` (or `-Python-`, etc.) in the easyconfig file name? We're pretty consistent with that...

**Comment by jerowe** [comment]
Since I've gotten more familiar with the robot and the naming schema this isn't such a big deal, and you are probably right that it would lead to duplication.

Also, hi! I've been traveling on vacation for most of the summer, but now I am back and have a few easybuild related projects I would like to work on. ;-)
