### ISSUE TITLE
Changing of GROMACS easyconfigs/module version suffix

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyconfigs#4129]
The current versionsuffix for GROMACS (-mt and -hybrid) is not very obvious for users.
Several of our users have thought that -hybrid is a GPU/CPU version (since we have lots of GPUs)

I suggest that the GROMACS build is either redone so that both the current -mt and -hybrid builds is merged into one, as would be the normal case for out-side EB builds, and using a -gpu version suffix for the cuda build.

Or renaming them to be -threadmpi, -mpi, -gpu. Where the -mpi is the current hybrid.

Or if someone can come up with a better naming scheme...

**Comment by verdurin** [comment]
I'm preparing an update to `2016.2` - happy to name them however you like.

**Comment by akesandgren** [comment]
I was more seeking comments on how to name things.

Reworking the easyblock so it builds both versions at the same time, like most normal manual builds is the one i personally prefer.
But if keeping them separate is what people think is best, then removing the versionsuffix for the normal mpi build, having -tmpi or -threadmpi for the current -mt build, and having -gpu or -cuda for that build is what i would go with.

As for the 2016.2 i no longer think boost is needed from what i could see. Haven't asked the maintainers yet though.

**Comment by vanzod** [comment]
As far as I am concerned, I agree with @akesandgren. I would prefer a single GROMACS build that contains both mpi and treadmpi versions. Then the GPU version will be in a separate toolchain that supports CUDA.

**Comment by akesandgren** [comment]
I have finally had time to look at this a bit more.

The gromacs.py does indeed build both ntmpi and mpi versions, both gmx and gmx_mpi exists, if usempi=true.

This means that there is no need to do very much. Just dropping the suffixes should be enough.

@verdurin @vanzod comments on this?

If there are no objections i can start by pushing my new PLUMED enabled gromacs easyblock, and some corresponding easyconfigs....

It's still a bit of an overkill though, since for MPI you only need to build mdrun_mpi, but having to use
mpirun gmx_mpi mdrun
is similar enough for users not to get too confused.

**Comment by vanzod** [comment]
Sounds good to me.

**Comment by verdurin** [comment]
@akesandgren - fine by me, as long as this is mentioned in the description, preferably at the end.

PLUMED-enabled easyblock will be very welcome here...

**Comment by boegel** [comment]
@akesandgren Recent `GROMACS` easyconfigs no longer have a `versionsuffix`, so this can be closed?

**Comment by akesandgren** [comment]
Yes, closing.
