### ISSUE TITLE
Provide symlink to shorten path lengths in `eb --search` output

### ISSUE THREAD

**Issue by fgeorgatos** [easybuilders/easybuild-easyconfigs#416]
I had a couple new users complaining about the long names:
`/opt/apps/HPCBIOS.20130715/software/EasyBuild/1.6.0/lib/python2.6/site-packages/easybuild_easyconfigs-1.6.0.0-py2.6.egg/easybuild/easyconfigs/p/Python/Python-2.7.5-goolf-1.4.10.eb`

Could we make instead a symlink for everyday use???, something like:
`/opt/apps/HPCBIOS.20130715/software/EasyBuild/1.6.0/easybuild/easyconfigs/p/Python/Python-2.7.5-goolf-1.4.10.eb`

eg. try `eb --search /Python-` and you will understand!

**Comment by Micket** [comment]
Search uses robot path variable to shorten things for as long as ivd used easybuild already.
