### ISSUE TITLE
CMake: ncurses dependency not found during build

### ISSUE THREAD

**Issue by geimer** [easybuilders/easybuild-easyconfigs#4171]
Building `CMake` on a Debian 8.7 (jessie) box without the `libncurses5-dev` OS package installed resulted in an installation lacking the `ccmake` utility, even though `ncurses/6.0` is listed as a dependency in the easyconfig file.  The only diagnostic output of the `configure_step` regarding this is
```
Curses libraries were not found. Curses GUI for CMake will not be built.
```

I was able to convince `CMake` to find the `ncurses` stuff and to build `ccmake` by adding
```
configopts += '-DCURSES_INCLUDE_PATH=$EBROOTNCURSES/include '
configopts += '-DCURSES_LIBRARY=$EBROOTNCURSES/lib/libcurses.so '
configopts += '-DCURSES_NCURSES_LIBRARY=/lib/libncurses.so'
```
to the `CMake` easyconfig file, though I'm not yet convinced that this is the way to go. (`CMake` should just do its job properly and find the `ncurses` installation!)  Also, even with this "fix", the log file shows some weirdness:
```
-- Looking for cbreak in /lib/libncurses.so
-- Looking for cbreak in /lib/libncurses.so - not found
```

**Comment by boegel** [comment]
@geimer Which CMake version was being used here? Did you try using a different CMake version? Cfr. #4170

**Comment by geimer** [comment]
@boegel I was installing CMake 3.7.2, but 3.7.1 shows the same behavior.  I did not test older versions yet.

**Comment by geimer** [comment]
@boegel It's the same for CMake 3.6.2 and trying with ncurses 5.9 didn't help either...

**Comment by geimer** [comment]
@boegel Maybe this issue is also an incentive to add `ccmake` to the sanity check (once it is resolved)? :wink:

**Comment by geimer** [comment]
Hmm... Alright, it looks like the right way to do it is to set `CMAKE_PREFIX_PATH=$EBROOTNCURSES` (see https://cmake.org/cmake/help/v3.7/variable/CMAKE_PREFIX_PATH.html#variable:CMAKE_PREFIX_PATH).  Then the `FindCurses` command will correctly pick up `ncurses` from the EasyBuild install.  Now I'm wondering whether EB-generated modulefiles for libraries should prepend to this environment variable automatically?  Though it looks to me like CMake is pretty much borked...

**Comment by boegel** [comment]
@geimer Good to hear that using `CMAKE_PREFIX_PATH` fixes the issue, but doing this consistently has bitten us in the past, cfr. https://github.com/hpcugent/easybuild-easyblocks/commit/6c4a3dfb5035f79aad396cb04f7c718a1cfe1b7f and remark in https://github.com/hpcugent/easybuild-easyblocks/pull/360#issuecomment-35163577

**Comment by geimer** [comment]
@boegel Too bad... It would be interesting to know how many build issues go by unnoticed because of this.  I mean, the CMake built itself was successful, but incomplete.

**Comment by boegel** [comment]
@geimer Well, that's certainly a reason to extend the sanity check for CMake to also check for `ccmake`, although admittedly that's not enough in this case since that doesn't check whether the `ncurses` that is picked up is the correct one.

**Comment by geimer** [comment]
@boegel Agreed.  But checking the build logs automatically isn't that easy (I believe).  And as we noticed on IRC yesterday, it may actually be sufficient to have a `libncurses5-dev` OS package installed for CMake to pick up the EB-built ncurses (which is something I still don't get)...

Do you want me to open a PR adding `ccmake` to the sanity check as well as `-DCMAKE_PREFIX_PATH=$EBROOTNCURSES` to `configopts`?  Though I will probably only touch the CMake easyconfigs for 2016 toolchains...

**Comment by boegel** [comment]
@geimer This can be closed?

**Comment by geimer** [comment]
@boegel I intentionally left this open since #4196 fixes this issue for "only" 37 configurations out of >90.  If you think this is good enough, I can close it.

**Comment by boegel** [comment]
closing this as this is fixed in all recent CMake easyconfigs...
