### ISSUE TITLE
build error: NWChem-6.5.revision26243-intel-2015b-2014-09-10-Python-2.7.10.eb

### ISSUE THREAD

**Issue by fedepad** [easybuilders/easybuild-easyconfigs#4201]
Hi,

NWChem 6.5. build seems to fail for some reason.

To build everything I use the line:
`eb --module-syntax=Tcl --try-toolchain=foss,2015b --buildpath=/home/padua/easybuild_buildpath NWChem-6.5.revision26243-intel-2015b-2014-09-10-Python-2.7.10.eb --robot`

which runs fine through all the dependencies and it gives error when starts to build the NWChem package...

> == processing EasyBuild easyconfig /gpfs/iowraptest/software_manager/easybuild_installation/software/EasyBuild/3.1.0/lib/python2.6/site-packages/easybuild_easyconfigs-3.1.0-py2.6.egg/easybuild/easyconfigs/p/Python/Python-2.7.10-foss-2015b.eb
> == building and installing Python/2.7.10-foss-2015b...
> == fetching files...
> == creating build dir, resetting environment...
> == unpacking...
> == patching...
> == preparing...
> == configuring...
> == building...
> == testing...
> == installing...
> == taking care of extensions...
> == installing extension setuptools 16.0 (1/26)...
> == installing extension pip 7.0.1 (2/26)...
> == installing extension nose 1.3.6 (3/26)...
> == installing extension numpy 1.9.2 (4/26)...
> == installing extension scipy 0.15.1 (5/26)...
> == installing extension blist 1.3.6 (6/26)...
> == installing extension mpi4py 1.3.1 (7/26)...
> == installing extension paycheck 1.0.2 (8/26)...
> == installing extension argparse 1.3.0 (9/26)...
> == installing extension pbr 1.0.1 (10/26)...
> == installing extension lockfile 0.10.2 (11/26)...
> == installing extension Cython 0.22 (12/26)...
> == installing extension six 1.9.0 (13/26)...
> == installing extension dateutil 2.4.2 (14/26)...
> == installing extension deap 1.0.2 (15/26)...
> == installing extension decorator 3.4.2 (16/26)...
> == installing extension arff 2.0.2 (17/26)...
> == installing extension pycrypto 2.6.1 (18/26)...
> == installing extension ecdsa 0.13 (19/26)...
> == installing extension paramiko 1.15.2 (20/26)...
> == installing extension pyparsing 2.0.3 (21/26)...
> == installing extension netifaces 0.10.4 (22/26)...
> == installing extension netaddr 0.7.14 (23/26)...
> == installing extension mock 1.0.1 (24/26)...
> == installing extension pytz 2015.4 (25/26)...
> == installing extension pandas 0.16.1 (26/26)...
> == postprocessing...
> == sanity checking...
> == cleaning up...
> == creating module...
> == permissions...
> == packaging...
> == COMPLETED: Installation ended successfully
> == Results of the build can be found in the log file(s) /gpfs/iowraptest/software_manager/easybuild_installation/software/Python/2.7.10-foss-2015b/easybuild/easybuild-Python-2.7.10-20170224.154850.log
> == processing EasyBuild easyconfig /tmp/eb-hOTyxs/tweaked_easyconfigs/NWChem-6.5.revision26243-foss-2015b-2014-09-10-Python-2.7.10.eb
> == building and installing NWChem/6.5.revision26243-foss-2015b-2014-09-10-Python-2.7.10...
> == fetching files...
> == creating build dir, resetting environment...
> == unpacking...
> == patching...
> == preparing...
> == configuring...
> == building...
> == FAILED: Installation ended unsuccessfully (build directory: /home/padua/easybuild_buildpath/NWChem/6.5.revision26243/foss-2015b-2014-09-10-Python-2.7.10): build failed (first 300 chars): cmd " make -j 8  COPTIMIZE='-O2 -march=native'  FOPTIMIZE='-O2 -march=native -fdefault-integer-8'  BLASOPT='-L/gpfs/iowraptest/software_manager/easybuild_installation/software/GCC/4.9.3-binutils-2.25/lib64 -L/gpfs/iowraptest/software_manager/easybuild_installation/software/GCC/4.9.3-binutils-2.25/li
> == Results of the build can be found in the log file(s) /tmp/eb-hOTyxs/easybuild-NWChem-6.5.revision26243-20170224.154850.NrABv.log
> ERROR: Build of /tmp/eb-hOTyxs/tweaked_easyconfigs/NWChem-6.5.revision26243-foss-2015b-2014-09-10-Python-2.7.10.eb failed (err: 'build failed (first 300 chars): cmd " make -j 8  COPTIMIZE=\'-O2 -march=native\'  FOPTIMIZE=\'-O2 -march=native -fdefault-integer-8\'  BLASOPT=\'-L/gpfs/iowraptest/software_manager/easybuild_installation/software/GCC/4.9.3-binutils-2.25/lib64 -L/gpfs/iowraptest/software_manager/easybuild_installation/software/GCC/4.9.3-binutils-2.25/li')

I tried also to set one more env variable for ARMCI but doesn't work.
I attach the log. 
[NWChem-6.5.revision26243-20170224.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/799826/NWChem-6.5.revision26243-20170224.txt)

Have you already seen this? How can this be fixed?

Thanks!

**Comment by boegel** [comment]
relevant problem:

```
configure: searching for OPENIB...
checking infiniband/verbs.h usability... yes
checking infiniband/verbs.h presence... yes
checking for infiniband/verbs.h... yes
checking for library containing ibv_open_device... no
configure: error: test for ARMCI_NETWORK=OPENIB failed
make[1]: *** [build/config.status] Error 1
make: *** [libraries] Error 1
```

@fedepad Can you find a `config.log` that provides more information?

@hajgato Any ideas on this?

**Comment by fedepad** [comment]
@boegel Where would I get the `config.log` from?

**Comment by boegel** [comment]
Somewhere in the build directory, maybe run a `find . -name config.log` in `/home/padua/easybuild_buildpath/NWChem/6.5.revision26243/foss-2015b-2014-09-10-Python-2.7.10`?

I'm not sure there will be a `config.log` though, but there should be a log file with more information in it somewhere... I hope.

**Comment by boegel** [comment]
@fedepad maybe the update to the NWChem easyblock at https://github.com/hpcugent/easybuild-easyblocks/pull/1104 is relevant? It certainly looks like it may be relevant... What do you think @akesandgren?

You can try download `nwchem.py` from there, and test it using `eb --include-easyblocks nwchem.py` to check if it helps with your issue.

**Comment by fedepad** [comment]
@boegel I will check it out and see if it solves the issue. I'll report back once done!

**Comment by akesandgren** [comment]
ARMCI with OPENIB is one of the problems i was solving with the nwchem.py update, so it should hopefully fix that problem.

**Comment by fedepad** [comment]
Unfortunately it doesn't. 
I attach the easybuild log that shows the same error and the config.log from NWChem.
Worth (maybe) mentioning that all the dependencies were already installed from the build attempts with the "old" easyblock and those are kept and only the NWChem package builds.  
It detects that that one is the only one needed.  

[easybuild_nwchem_new_log.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/801138/easybuild_nwchem_new_log.txt)

[new_nwchem_config_log.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/801140/new_nwchem_config_log.txt)

**Comment by akesandgren** [comment]
The problem is here...
"checking for library containing ibv_open_device... no"
You're missing the libibverbs-dev package, or libibverbs-devel if you're on RH-ish.

**Comment by akesandgren** [comment]
So, if you don't have infiniband you need to change the easyconfig for nwchem to use another ARMCI interface.

**Comment by fedepad** [comment]
@akesandgren The library is there and the symbol is there:

> strings /usr/lib64/libibverbs.so | grep "open"
> ibv_cmd_open_xrcd
> ibv_cmd_open_qp
> ibv_open_device
> opendir
> dlopen
> fopen

that's why was a strange error for me to see. I will check again.

**Comment by boegel** [comment]
@fedepad check with `nm /usr/lib64/libibverbs.so | grep ibv_open_device`, and maybe also check the `libibverbs.a`, maybe NWChem is looking for that specifically?

**Comment by fedepad** [comment]
@boegel Done, symbols are there and installed the static `libibverbs.a` but still gets stuck at configure time for checking `ibv_open_device`.

**Comment by akesandgren** [comment]
Then take a closer look at src/tools/build/config.log in the build dir and see what it is really complaining about.

**Comment by fedepad** [comment]
@akesandgren @boegel Thanks!
I was able to overcome the mentioned configure errors looking at the config.log which actually complained about `libibumad` , so I installed `libibumad` and `libibumad-devel`.
I would suggest to add that library as a dependency probably for this build configuration maybe as it seems to move the build process forwards.
Although those errors go away, the nwchem tests all fail and I do not know whether https://github.com/hpcugent/easybuild-easyblocks/pull/275 was supposed to "fix" that.

I attach the log showing all the failing test cases at the end of the build/check process.
[NWChem-6.5.revision26243-20170227_completelog_failing_tests.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/810401/NWChem-6.5.revision26243-20170227_completelog_failing_tests.txt)

**Comment by akesandgren** [comment]
In the upcoming nwchem 6.6 i have added those as osdeps already. It's however still pending a few PR's for its dependecies.

**Comment by akesandgren** [comment]
No idea why it failed.
The just pushed nwchem 6.6 looks like it only failed 1 of 31 tests on my laptop at least.
Haven't built it on the cluster yet.

**Comment by boegel** [comment]
@fedepad @akesandgren OK to close since we include OS deps in recent NWChem easyconfigs now (cfr. #4231 & #5069)?

**Comment by akesandgren** [comment]
Ok with me.
