### ISSUE TITLE
QuantumESPRESSO: Checksum verification fails and build stops

### ISSUE THREAD

**Issue by fedepad** [easybuilders/easybuild-easyconfigs#4208]
Trying to build QuantumESPRESSO I get the following

> == 2017-02-27 17:38:03,786 build_log.py:216 INFO unpacking...
> == 2017-02-27 17:38:03,786 easyblock.py:2279 INFO Starting source step
> == 2017-02-27 17:38:03,787 easyblock.py:2282 INFO Running method checksum_step part of step source
> == 2017-02-27 17:38:03,825 easyblock.py:1537 INFO Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/espresso-5.4.0.tar.gz using 8bb78181b39bd084ae5cb7a512c1cfe7 passed.
> == 2017-02-27 17:38:03,834 easyblock.py:1537 INFO Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/wannier90-1.2.tar.gz using a1e9611b9a82941c23426028d112186e passed.
> == 2017-02-27 17:38:03,838 easyblock.py:1537 INFO Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/atomic-5.4.0.tar.gz using 24dc0d8bf5cf4eb4dc38e1c18a80b3ee passed.
> == 2017-02-27 17:38:03,839 easyblock.py:1537 INFO Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/neb-5.4.0.tar.gz using 254f929259fb06036b78c493cf18e5d6 passed.
> == 2017-02-27 17:38:03,842 easyblock.py:1537 INFO Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/PHonon-5.4.0.tar.gz using f641fe9dcf0ec8f1e47d74e3c7c39705 passed.
> == 2017-02-27 17:38:03,843 easyblock.py:1537 INFO Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/pwcond-5.4.0.tar.gz using 31c1cd8cd76752833a9205d456093d0a passed.
> == 2017-02-27 17:38:03,862 easyblock.py:1537 INFO Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/tddfpt-5.4.0.tar.gz using 2101533a627644ef467b60d400977eab passed.
> == 2017-02-27 17:38:03,910 build_log.py:147 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/want-2.5.1-base.tar.gz using ac365daebbe380bf4019235eacf71079 failed. (at easybuild/framework/easyblock.py:1535 in checksum_step)
> == 2017-02-27 17:38:03,910 easyblock.py:2511 WARNING build failed (first 300 chars): Checksum verification for /home/padua/.local/easybuild/sources/q/QuantumESPRESSO/want-2.5.1-base.tar.gz using ac365daebbe380bf4019235eacf71079 failed.
> == 2017-02-27 17:38:03,911 easyblock.py:276 INFO Closing log for application name QuantumESPRESSO version 5.4.0

so it looks like the checksum verification fails. This happens for two easyconfigs that I tried:
QuantumESPRESSO-6.0-intel-2016b.eb
QuantumESPRESSO-5.4.0-intel-2016.02-GCC-4.9.eb

**Comment by boegel** [comment]
@fedepad The auto-downloading of QuantumESPRESSO sources is known to be troublesome, see also https://github.com/hpcugent/easybuild-easyblocks/pull/618 (which was supposed to fix this problem, but it never got finished/merged).

EasyBuild cycles through a couple of URLs for downloading sources, and in this case downloads an HTML page rather than the intended source tarball.

The only way to fix that for now is to manually download the tarball, and copy it to where EasyBuild would download it (i.e., the source path, see `eb --show-config`).

**Comment by Micket** [comment]
This issue should just be closed, qe-forge is getting discontinued and hosting has moved to github and/or gitlab. #618 should just be dropped as well.
