### ISSUE TITLE
list of easyconfigs that still need to import a python module (which fails style checks)

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-easyconfigs#4273]
* ANSYS-15.0.eb
  * `import os` to get `EB_ANSYS_LICENSE_SERVER` and `EB_ANSYS_LICENSE_SERVER_PORT`
* BFAST-0.7.0a-*.eb
  * `import string` in order to use `string.lowercase + string.uppercase` in `rstrip`
  * in this case, I'd just replace `string.lowercase + string.uppercase` with literal string `'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'`
* CP2K-20111205-goolf-1.4.10-psmp.eb
  * import os in order to set `OMP_NUM_THREADS` for tests
* MATLAB-*.eb
  * `import os` in order to get `EB_MATLAB_LICENSE_SERVER`, `EB_MATLAB_LICENSE_SERVER_PORT` and `EB_MATLAB_KEY`

**Comment by cstackpole** [comment]
I think this can be completed. I think @boegel already fixed them! :-)
ANSYS and MATLAB were updated with 9bd59ff89be6be1afc70ecb2dedab11c139fd7e0
BFAST was updated with afe72ba5206fdc3b6d16f8a926c039a11c0222ee
CP2K was updated with 941823b7588db56f33fa954e623f0171cbb863d0

**Comment by boegel** [comment]
Indeed, thanks a lot for pointing this out @cstackpole!
