### ISSUE TITLE
New htslib release

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#4345]
An issue to track that I will be submitting PRs for the new `SAMtools` and related `1.4` releases.

**Comment by verdurin** [comment]
Someone has already provided `SAMtools` 1.4 (good), but we still need:

- [ ] bcftools
- [ ] htslib

which probably need updated easyblocks too.

**Comment by boegel** [comment]
@verdurin Any updates?

**Comment by Micket** [comment]
We've had many htslibs since this issue was opened.
