### ISSUE TITLE
Intel-Modules INTEL_LICENSE_FILE 

### ISSUE THREAD

**Issue by henkela** [easybuilders/easybuild-easyconfigs#4420]
Hi, 
there's a problem with the intel-modules. 
Example: 
```
module load compiler/icc 
module load tools/VTune 
```
Each of the modules call: 
prepend-path    INTEL_LICENSE_FILE 

Now, if I unload icc INTEL_LICENSE_FILE is empty and VTunes doesn't work anymore. 

What could be a solution to prevent empty INTEL_LICENSE_FILE variable if one of several intel-modules are unloaded?

**Comment by boegel** [comment]
This is not so much an EasyBuild problem, but rather a problem with modules in general...

Although we could add some logic in the modules to prevent ending with up an empt `$INTEL_LICENSE_FILE` environment variable, it would be quite tricky to get it right.

If I'm not mistaken, Lmod may support reference counting for environment variables in the near future, which would fix this exact problem..

**Comment by rtmclay** [comment]
Until reference counting is available you could use pushenv instead of prepend_path()

**Comment by henkela** [comment]
I see. Then I have to see if we should switch to lmod since we're using EnvironmentModulesC currently. 
Thanks.

**Comment by DirkdeDraak** [comment]
Another option would be to have a dependency on a module called: _licenses/intel_.
That will set INTEL_LICENSE_FILE.
If you unload one of the Intel components it will not unload that module (dependent on how you have coded the loading clause for the license).

**Comment by Micket** [comment]
Intel is free now.
