### ISSUE TITLE
Can't get X11/20160819-intel-2016b to successfully build

### ISSUE THREAD

**Issue by pol** [easybuilders/easybuild-easyconfigs#4465]
I could really use some guidance on this one, I am sure the fix is simple, but I have had zero luck with my attempts to resolve it. 

The easyconfig fails on:

`installing bundle component bigreqsproto v1.1.2 (3/71)...`

The log file states:

```
configure: error: C compiler cannot create executables
See `config.log' for more details
```

The config.log states:

```
[easybuild@hyalite ~]$ grep error -SNIP-/X11/20160819/intel-2016b/bigreqsproto-1.1.2/config.log
icc: command line error: no files specified; for help type "icc -help"
ld: cannot find gcc: error: ./crtbegin.o: No such file or directory
configure:3173: error: in `-SNIP-/X11/20160819/intel-2016b/bigreqsproto-1.1.2':
configure:3175: error: C compiler cannot create executables
```

I have tried many things to get the compiler to see `crtbegin.o`.  It's a pretty common file. It's in the intel compiler libraries, and the GCCcore libraries:

```
[easybuild@hyalite ~]$ ls -SNIP-/icc/2016.3.210-GCC-5.4.0-2.26/lib/intel64/crt/
crtbegin.o  crtend.o
[easybuild@hyalite ~]$ ls -SNIP-/GCCcore/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/
crtbegin.o   crtend.o       crtprec32.o  finclude       install-tools     libgcc.a     libgfortranbegin.a
...
```

I have tried adding all sorts of env vars (LD_LIBRARY_PATH, LIBRARY_PATH, INCLUDE_PATH) to the modulefiles with the relevant paths, but it doesn't seem to matter.  I added a "prepend_path LDFLAGS" command to the GCCcore modulefile with its own path in it, and that does show up in the "icc -L..." compilation line in the config.log, but the error is the same.

Any help would be greatly appreciated.

**Comment by wpoely86** [comment]
That's a weird thing. So you got everything before X11 compiling just fine? What kind of system are you doing this on? Local filesystem or network?

Can you show the full `config.log` (put it on github gists). Normally, the `crtbegin.o` should be found by icc or gcc without setting any special variable.

**Comment by pol** [comment]
Yeah, everything before that works fine.  

Here's the gist: https://gist.github.com/pol/be813488f98f07c8ea52b2ee4e108c1d

**Comment by wpoely86** [comment]
After a quick look, I noticed one thing:
```
configure:3073: icc -v >&5
icc version 16.0.3 (gcc version 3.2.0 compatibility)
```
This is weird. On my system that gives:
```
icc version 16.0.3 (gcc version 5.4.0 compatibility)
```
Can you try to compile something simple with icc (hello world should do) using:
```
icc -v hello.c -o test123
```
and show the output?

**Comment by pol** [comment]
Here's the run (it might be more than you need):

https://gist.github.com/pol/6704866aec20ba23a73d8122753d9806

**Comment by wpoely86** [comment]
```
-D__GNUC__=3 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0
```
So for some reason, your icc install picked up an older GCC (the system one?). Why that makes that one `configure` failed is beyond me. You could try to add `-v` in the `$CFLAGS` through `preconfigopts` and see what that tells you. But I think something went wrong with your icc install.

**Comment by pol** [comment]
I think you are correct, this is probably the root of the problem.

For this particular instance, how would I specify the preconfigopts? Is it just passed to "icc"?

In general, I think I want to repair ICC itself.  I think there would be two ways to go about this:

1. Find out where those -D options are set  and change them. Presumably it's somewhere in the eb/apps/icc/... files somewhere, and I could just edit them by hand?
2. Reinstall the icc modules through easybuild and make sure that the options are set correctly. 

Do you have an opinion on which would be better, and if so, do you have any guidance on following through on it?

**Comment by wpoely86** [comment]
I would first try (2) and see if that helps. It's the easiest thing to do.

**Comment by boegel** [comment]
@pol to answer your question on `preconfigopts`: that's an easyconfig parameter you can define in the easyconfig file you are using (see http://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html)

**Comment by pol** [comment]
@boegel woudl you recommend that I edit the icc easyconfig file directly (the one that is part of the easybuild distribution) or would i copy it somewhere else and modify it?  If I were to do the latter, where would be the best place to put it so that others would be able to find it?

**Comment by boegel** [comment]
@pol Well, it's up to you, but I'd recommended to copy & update the easyconfig file, and make sure that EasyBuild picks up on it by updating your EasyBuild configuration to extend the robot search path (see http://easybuild.readthedocs.io/en/latest/Using_the_EasyBuild_command_line.html#controlling-robot-search-path).

In this case though, this is mostly about debugging, so you can just use a temporary copy?

BTW, I think @wpoely86 suggested to add `-v` to `$CFLAGS` in the `X11` easyconfig rather than the `icc` easyconfig?

**Comment by wpoely86** [comment]
Yes, but first try to reinstall `icc` and try X11 again.

**Comment by pol** [comment]
I have tried reinstalling icc twice, once with cleared modules (no loaded modules) and once with the GCC 5.4.0 modules loaded.  Both times, intel still shows up with `-D__GNUC__=3 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0` when I do a test compile.

Am I reinstalling correctly?  I am using this command:

eb icc-2016.3.210-GCC-5.4.0-2.26.eb --rebuild

Is there a way to complete delete the existing installed module and then rebuild, in case it is not actually doing a rebuild?

And is this where I should try adding -v to the CFLAGS to get more info?

**Comment by boegel** [comment]
With `--rebuild`, EasyBuild will throw away the module file and installation directory, and redo the installation.

There should be no need to load the `GCC` module yourself up front, EasyBuild will do that for you (since `GCC` is listed as a dependency).

To inject `-v` into `$CFLAGS`, you should include something like this in an easyconfig file where you use the Intel compilers:

```python
prebuildopts = 'export CFLAGS="$CFLAGS -v" && '
```

**Comment by pol** [comment]
How can I get more detail about why the intel compiler is relying on GCC 3.2.0 even though it's being compiled within the easybuild environment which is loading 5.4.0?    Should I use the prebuildops for the icc easyconfig to get that information?

I have been unable to get icc to build and have anything other than GCC 3.2.0 show up.  

Note, not even the system GCC is 3.2.0 (/usr/bin/gcc is 4.4.7).  Where is that 3.2.0 coming from?

**Comment by pol** [comment]
What other options should I try, none of the installations have given me any different result.  Is there either something I could use to debug the eb installation or some way to make sure things are happening as they should?  Maybe all icc installations use these GCC flags for a compile?  Could one of you try it out and post what I should be seeing from the -D__GNUC__... flags?

**Comment by boegel** [comment]
@pol Sorry for the lack of follow-up here... Did you figure this out in the end?

**Comment by Micket** [comment]
Long since outdated (or maybe resolved?)
