### ISSUE TITLE
netCDF-4.4.1 not installing netcdf_par.h (shouldn't it?)

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#4475]
When trying to compile Trilinos  (using my own easyconfig, based on the existing ones (just version-bumped)) I come across a compile error, caused by netcdf_par.h missing.

As far as I can tell, when building netCDF4 through easybuild, the logs state that ENABLE_PARALLEL4 is indeed set by the main CMakeLists.txt for netCDF, but when the "include/CMakeLists.txt" runs, it skips the netcdf_par.h file.

**Comment by Micket** [comment]
It seems this only happens with the 4.4.1 release, and it is fixed in the 4.4.1.1 version.

The cmake file that installs the header used the variable "HAS_PARALLEL" in 4.4.1, but this was never set (it's supposed to be HAS_PARALLEL4, and is indeed so in 4.4.1.1).

The EB-config should add a check for "include/netcdf_par.h" so that problems like these will be caught sooner in the future.

**Comment by boegel** [comment]
@Micket So, this was a bug in netCDF 4.4.1? Any way to fix it (so we can include a patch in the netCDF 4.4.1 easyconfigs)?

**Comment by Micket** [comment]
@boegel, I think so, yes. I think it's easier to just fix the eb-config by specifying the extra flag.
"-DENABLE_PARALLEL=ON " to configopts (only for 4.4.1) is how i worked around it.

**Comment by Micket** [comment]
All recent netCDF's have this header file, so this has been long since resolved.
