### ISSUE TITLE
OpenBLAS seems to be configured wrong

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-easyconfigs#4524]
There are two potential mistakes that @ocaisa and me found:

* Sometimes  `NO_AFFINITY=1` is used in `buildopts`. This is useless as it is already defined in `Makefile.rule`. It doesn't do any harm though. However, it gives the feeling that you can actually disable it with `NO_AFFINITY=0`, which is wrong. To disable it you have to edit the file and comment out that line (OpenBLAS does a `ifdef` to check for `NO_AFFINITY`, so `NO_AFFINITY=0` and `NO_AFFINITY=1` are equivalent)

* Without setting `USE_OPENMP=1` in `buildopts` OpenBLAS won't respect the parent mask, and will use all the cores available. That is wrong in a job with multiple processes per node, where you can significantly oversubscribe cores by mistake, and end up with a very slow execution. Building OpenBLAS with `USE_OPENMP=1` seems to solve the problem.

**Comment by ocaisa** [comment]
You can see the impact of setting `USE_OPENMP=1` at https://github.com/xianyi/OpenBLAS#set-the-number-of-threads-with-environment-variables

**Comment by boegel** [comment]
These issues have been fixed in the new OpenBLAS 0.2.20 easyconfig that is included in #4768, so OK to close @damianam, @ocaisa?

**Comment by ocaisa** [comment]
Yes, good to close as far as I can see
