### ISSUE TITLE
Rmpi 0.6-6 for R 3.3.3 with Intel toolchain does not have patch for -lmpich

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-easyconfigs#4622]
The installation of `Rmpi 0.6-6` in `R-3.3.3-intel-2017a-X11-20170314.eb` fails with:

`ld: cannot find -lmpich` 

because of missing patch file option which was present until `R 3.3.1`.

**Comment by vanzod** [comment]
By adding the patch it compiles correctly. Added it back in #4623

**Comment by boegel** [comment]
@vanzod I just tried reinstalling Rmpi without the patch in `R/3.3.3-intel-2017a-X11-20170314`, and it worked fine for me...

Also, `$EBROOTIMPI/lib64/libmpich.so` *is* there in the `impi` installation that is a part of `intel/2017a`, so `ld` should be able to link with `-lmpich`...

So, I'm quite confused why it doesn't work for you, but does for me... I don't have `libmpich.*` in the OS.

**Comment by vanzod** [comment]
@boegel Ping

**Comment by boegel** [comment]
Merged #4623 after testing that it doesn't do any harm, OK to close?

**Comment by vanzod** [comment]
Issue solved. Closing
