### ISSUE TITLE
Building Python 2.7.13 in foss 2017a breaks on one cluster

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#4626]
Hi,

I am having a strange issue when trying to build Python 2.7.13 for foss 2017a (using the Python-2.7.13-foss-2017a.eb in EB 3.2.1).  It works on one of our clusters but breaks on the other one.  The clusters should be identically (apart from individual packages (e.g. prerequisite) that might have been build with different version of EB).

On the troubled cluster I succeeded in building Python 3.6.1 for foss 2017a using the Python-3.6.1-intel-2017a.eb easyconfig with a “try-toolchain”.

The critical error in the logs seems to be (I get a large number of these lines):

```
/sw/easybuild/software/Compiler/GCCcore/6.3.0/binutils/2.27/bin/ld.gold: error: /sw/easybuild/software/Core/ncurses/6.0/lib/libncurses.a(lib_termcap.o): requires dynamic R_X86_64_PC32
 reloc against '_nc_setupterm' which may overflow at runtime; recompile with -fPIC
```

Not sure I fully understand that message, but I force rebuild ncurses and that doesn’t fix anythings.  As far as I can make out from the logs both ncurses (old and new) are build with -fPIC.

**Comment by boegel** [comment]
@jhein32 The error tells me that `ncurses` was not built with `-fPIC`.

Do you mind sending me (mail is fine) the `ncurses` log after the rebuild (a `--debug` log if possible)?

**Comment by jhein32** [comment]
Hi Kenneth 

@boegel  I rebuild ncurses using:
```
eb ncurses-6.0-GCCcore-6.3.0.eb --robot --use-existing-modules --force  --debug
```
after which I could build the Python package (also using debug mode).  
```
eb Python-2.7.13-foss-2017a.eb --robot --use-existing-modules --debug
```
the intention was to sent you detailed logs for both, but now, I am not sure how to progress this.

Before rebuilding I checked carefully, which ncurses the python build was picking up and that this had dates of yesterday.  Is `--debug` disabling parallel builds?

**Comment by boegel** [comment]
@jhein32 `--debug` only affects how verbose the logs are, it has no side-effects.

Maybe the previous rebuild of `ncurses` was done with an old easyconfig file (that doesn't enable `-fPIC`)?

**Comment by jhein32** [comment]
@boegel 

I just checked.  There is no ncurses in our "homegrown" easyconfig repository.  As I wrote, I only rebuild it yesterday and it didn't help (unless caching is to blame).  When was fpic added to the ncurses?    As far as I can make out from the logs, ncurses for gcccore 6.3 was added and never changed.  I assume the line 

```
toolchainopts = {'pic': True}
```
Is the relevant switch.

**Comment by boegel** [comment]
@jhein32 `pic` has been enabled for `ncurses` since the dawn of time (I stopped checking the `git log` after hitting commits from 2013 where it was already there...)
