### ISSUE TITLE
Salmon patch needs to be updated

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#4671]
The patch for `Salmon` to use external `Jellyfish` needs to be updated for `0.8.2`. 

I noticed in passing that it even builds `bzip2`, if left to its own devices. 

I will look at this when I can, but wanted to log the problem here.

**Comment by SethosII** [comment]
@verdurin Please take a look at the pull request #4810. I updated the patch for `Jellyfish` there. The build with this EasyConfig reported for `bzip2`: `Found libbz2 library: /usr/lib/x86_64-linux-gnu/libbz2.a`. So it doesn't build it's own but also doesn't use the one from EasyBuild.

**Comment by verdurin** [comment]
@SethosII thanks. Did you see any problems with the 'Bloom' tests, incidentally?

**Comment by SethosII** [comment]
@verdurin Yes, these tests need `bc` and this is not installed by default on a Ubuntu 16.04 server (for whatever reason). See here for details: https://github.com/gmarcais/Jellyfish/issues/91.

**Comment by nortex** [comment]
Hi,

Im trying to install Salmon version 1.0.0 on 2017.02 intel toolchain, both of the patches fail to apply(jellyfish and intel compiler).

While trying to install without patches, during configuration i receive this message:

```
CMake Error at /data/apps/Easybuild/apps/CMake/3.7.2-intel-2017.02/share/cmake-3.7/Modules/FindLAPACK.cmake:354 (message):
  A required library with LAPACK API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:96 (find_package)


-- Configuring incomplete, errors occurred!
See also "/data/sources/build/Salmon/1.0.0/intel-2017.02-Python-2.7.12/SALMON-v.1.0.0/CMakeFiles/CMakeOutput.log".
See also "/data/sources/build/Salmon/1.0.0/intel-2017.02-Python-2.7.12/SALMON-v.1.0.0/CMakeFiles/CMakeError.log".
 (at easybuild/tools/run.py:481 in parse_cmd_output)
== 2018-05-24 11:41:09,694 easyblock.py:2688 WARNING build failed (first 300 chars): cmd " cmake . -DCMAKE_INSTALL_PREFIX=/data/apps/Easybuild/apps/Salmon/1.0.0-intel-2017.02-Python-2.7.12 -DCMAKE_C_COMPILER='icc' -DCMAKE_Fortran_FLAGS='-O2 -xSSE2 -ftz -fp-speculation=safe -fp-model source -fPIC' -DCMAKE_CXX_FLAGS='-O2 -xSSE2 -ftz -fp-speculation=safe -fp-model source -fPIC' -DCMAKE
== 2018-05-24 11:41:09,694 easyblock.py:279 INFO Closing log for application name Salmon version 1.0.0
```

Any thoughts how to fix it?

Thanks,
Igor

**Comment by SethosII** [comment]
Where do you have Salmon 1.0 from (the latest release on Github is 0.9.1) and what easyconfig did you use?

**Comment by nortex** [comment]
@SethosII I built it on a platform of Salmon-0.5.1-intel-2015b-Python-2.7.10.eb

Contents of my Salmon-1.0.0-intel-2017.02-Python-2.7.12.eb:

`easyblock = 'CMakeMake'

name = 'Salmon'
version = '1.0.0'

homepage = 'https://github.com/COMBINE-lab/salmon'
description = """Salmon is a wicked-fast program to produce a highly-accurate,
 transcript-level quantification estimates from RNA-seq data."""

toolchain = {'name': 'intel', 'version': '2017.02'}
toolchainopts = {'optarch': True, 'pic': True}

sources = ['v%(version)s.tar.gz']
source_urls = ['https://github.com/COMBINE-lab/salmon/archive/']

#patches = [
#  'Salmon-%(version)s_Intel-compilers.patch',
#   'Salmon-%(version)s_skip-included-Jellyfish.patch',
#]

python = 'Python'
pyver = '2.7.12'
versionsuffix = '-%s-%s' % (python, pyver)

dependencies = [
    ('Boost', '1.63.0', versionsuffix),
    ('tbb', '2017_U6-intel-2017.02', '', True),
    ('Jellyfish', '2.2.3'),
]
builddependencies = [('CMake', '3.7.2')]

parallel = 1

moduleclass = 'bio'`

**Comment by SethosII** [comment]
@nortex The Salmon software referred to in this issue is a bioinformatics tool: https://combine-lab.github.io/salmon/. I don't know anything about your Salmon but the dependencies and patches will definitely be different.

**Comment by Micket** [comment]
Latest Salmon don't seem to be using jellyfish at all, so no patching is required anymore.
