### ISSUE TITLE
util-linux-2.29.2-intel-2017a.eb failing: identifier "__NR_sched_getattr" is undefined

### ISSUE THREAD

**Issue by jasonsydes** [easybuilders/easybuild-easyconfigs#4673]
Hi there,

I'm doing a pretty fresh install, and I'm seeing util-linux-2.29.2-intel-2017a.eb fail to build.  Odd, since I'm pretty sure I've been able to get util-linux to build under the foss-2017a and foss-2016b toolchains (if I'm remembering correctly).

Find a snippet of the error below.   I've also attached the full build logs...

This is my first time reporting a possible bug to EasyBuild.  Let me know if I should be doing anything differently!

Here's a snippet of the error:
```
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
  CCLD     switch_root
  CCLD     hwclock
  CCLD     fsck.minix
  CCLD     mkfs.minix
  CCLD     mkfs
remark #11074: Inlining inhibited by limit max-size
remark #11074: Inlining inhibited by limit max-total-size
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
  CCLD     mkfs.bfs
schedutils/chrt.c(98): error: identifier "__NR_sched_setattr" is undefined
        return syscall(SYS_sched_setattr, pid, attr, flags);
                       ^

schedutils/chrt.c(103): error: identifier "__NR_sched_getattr" is undefined
        return syscall(SYS_sched_getattr, pid, attr, size, flags);
                       ^

compilation aborted for schedutils/chrt.c (code 2)
make[2]: *** [schedutils/chrt.o] Error 2
```

I did find this discussion, which may or may not be related:
https://stackoverflow.com/questions/41257902/util-linux-2-28-1-schedutils-chrt-c8817-error-nr-sched-setattr-undecl

In case it is, here's the ncurses installed on our system:
```
$ rpmquery -a |grep ncurs
ncurses-5.9-13.20130511.el7.x86_64
ncurses-devel-5.9-13.20130511.el7.x86_64
ncurses-base-5.9-13.20130511.el7.noarch
ncurses-term-5.9-13.20130511.el7.noarch
ncurses-libs-5.9-13.20130511.el7.i686
ncurses-static-5.9-13.20130511.el7.x86_64
ncurses-libs-5.9-13.20130511.el7.x86_64
```

And more:
```
∴ cat slurm-20125.out
ERROR: Build of /projects/ebb/software/Core/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.2.1-py2.7.egg/easybuild/easyconfigs/u/util-linux/util-linux-2.29.2-intel-2017a.eb failed (err: 'build failed (first 300 chars): cmd " make -j 56 " exited with exitcode 2 and output:\nmake  all-recursive\nmake[1]: Entering directory `/gpfs/projects/ebb/build/utillinux/2.29.2/intel-2017a/util-linux-2.29.2\'\nMaking all in po\nmake[2]: Entering directory `/gpfs/projects/ebb/build/utillinux/2.29.2/intel-2017a/util-linux-2.29.2/po\'\nma')
== temporary log file in case of crash /tmp/eb-Ty0lip/easybuild-w98wH_.log
== resolving dependencies ...
== processing EasyBuild easyconfig /projects/ebb/software/Core/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.2.1-py2.7.egg/easybuild/easyconfigs/u/util-linux/util-linux-2.29.2-intel-2017a.eb
== building and installing MPI/intel/2017.1.132-GCC-6.3.0-2.27/impi/2017.1.132/util-linux/2.29.2...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== FAILED: Installation ended unsuccessfully (build directory: /projects/ebb/build/utillinux/2.29.2/intel-2017a): build failed (first 300 chars): cmd " make -j 56 " exited with exitcode 2 and output:
make  all-recursive
make[1]: Entering directory `/gpfs/projects/ebb/build/utillinux/2.29.2/intel-2017a/util-linux-2.29.2'
Making all in po
make[2]: Entering directory `/gpfs/projects/ebb/build/utillinux/2.29.2/intel-2017a/util-linux-2.29.2/po'
ma
== Results of the build can be found in the log file(s) /projects/ebb/tmp-logdir/easybuild-util-linux-2.29.2-20170606.084556.YKLZR.log
```
And finally, the full log:

UPDATE: I copied all of the full log into a gist here:

https://gist.github.com/jasonsydes/9c094f1f0d223cfe06365f2d58a01384

UPDATE: Here's the test report as well:

https://gist.github.com/jasonsydes/7597afa78f771a254583181c49d115d4

**Comment by jasonsydes** [comment]
Update: I checked, and it turns out I was incorrect:  I was **not** able to build util-linux previously...

**Comment by jasonsydes** [comment]
By adding the following line to util-linux-2.29.2-intel-2017a.eb, I was able to get it to build successfully:
```
configopts += "--disable-schedutils "
```
I can send along the (successful) build log upon request...

**Comment by jasonsydes** [comment]
Figuring out the gist test report thing now...  Here's the test report for the failed build:

https://gist.github.com/jasonsydes/7597afa78f771a254583181c49d115d4

**Comment by boegel** [comment]
@jasonsydes Thanks for the detailed bug report!

I haven't seen this issue pop up recently, and I'm not fully sure what's going on.

I'm also a bit puzzled you're seeing this on RHEL7.3, while we are not seeing it on CentOS 7.3.1611, while we also have ncurses installed in the OS:

```
ncurses-libs-5.9-13.20130511.el7.x86_64
ncurses-devel-5.9-13.20130511.el7.x86_64
ncurses-base-5.9-13.20130511.el7.noarch
ncurses-5.9-13.20130511.el7.x86_64
```

You do have more `ncurses` RPMs installed though...

Have you looked into the impact of using `--disable-schedutils`?

**Comment by boegel** [comment]
@jasonsydes Can you check whether you have similar problems with util-linux v2.30 which was released a couple of days ago?

**Comment by jasonsydes** [comment]
@boegel Apologies for the delay!

Ok, I was able to successfully build (with easybuild) util-linux v2.30 under my both my foss/2017a and intel/2017a toolchains.  All I did was make a copy of util-linux-2.29-intel-2016b.eb or util-linux-2.29-foss-2016b.eb and then modify the version numbers in there (i.e. to v2.30 and 2017a).

Would you like the *eb files or the test_reports or the build logs?

**Comment by boegel** [comment]
In that case, I suggest we just close this issue, I don't think there's much value in trying to figure out the problem for older versions of `util-linux`...

**Comment by jasonsydes** [comment]
I would agree!

**Comment by jasonsydes** [comment]
Thank you again! We are running curriculum off EasyBuild's software installations. We do appreciate your work.
