### ISSUE TITLE
singularity permissions problem

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#4804]
I saw errors like this when trying to import an image from Docker, when using the `Singularity` easyconfig:
```
DEBUG   [U=<my UID>,P=6879] singularity_runtime_rootfs()             Returning container_directory: /camp/apps/eb/dev/software/Singularity/2.3.1-GCC-6.3.0-2.27/var/singularity/mnt/container
ERROR   [U=<my UID>,P=6879] main()                                   Could not change to working directory: /camp/apps/eb/dev/software/Singularity/2.3.1-GCC-6.3.0-2.27/var/singularity/mnt/container
ABORT   [U=<my UID>,P=6879] main()                                   Retval = 255
```
This is with the updated easyconfig I just submitted (edit: #4803)

**Comment by wpoely86** [comment]
Did you set the suid bit on the correct binaries?

**Comment by boegel** [comment]
Usually the error is different when there's a permission issue...

@verdurin is the `var/singularity/mnt/container` there in your `Singularity` installation? And if so, which permissions are on it?

**Comment by verdurin** [comment]
I did set the suid bit.

@boegel yes, that path is within the installation.

The permissions are:
```
drwxr-xr-x+ 2 huffmaa domain_users 4096 Jul  2 22:51 var/singularity/mnt/container
```
Not sure why it's using that path, when it users `/var/singularity/mnt/container` on my laptop.

**Comment by boegel** [comment]
@verdurin Any updates on this?

**Comment by verdurin** [comment]
@boegel used the more recent `easyconfig` this week and didn't see this problem, so I'll close.
