### ISSUE TITLE
double unpacking/nested archives

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-easyconfigs#4830]
Is there a way to tell EasyBuild that it should unpack the downloaded file multiple times?

What I'm trying to accomplish is to build the software [bcl2fastq](https://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software.html) and for no good reason they provide a `.tar.zip` which unpacks into a `.tar.gz` (and they deleted previous versions that were `.tar.gz`, changed the URL and changed the way it is build ...)

**Comment by boegel** [comment]
@SethosII You can specify a custom extract command if the one derived by `eb` is not correct (or not sufficient, in this case), see http://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html?highlight=extract_cmd#alternative-formats-for-sources

**Comment by verdurin** [comment]
I'm sure someone has already dealt with a case like this. Can't remember right now.

**Comment by boegel** [comment]
@SethosII Do let us know if you're questions is answered now. If so, please mention the solution you used here for future reference, and close the issue.

**Comment by SethosII** [comment]
I didn't get around to test this over the weekend.

Yes, the option `extract_cmd` works. I used this: `'extract_cmd': 'unzip -p %s | tar -xzvf -'`
