### ISSUE TITLE
segmentation fault when trying to load some R extensions (kernel bug)

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#4833]
I'm seeing segmentation faults pop up on our system for some R extensions, including:

* `RWeka`
* `RWekajars`
* `xlsx`

Problem can be reproduced easily outside of EasyBuild as well, for example

```
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
$ uname -r
3.10.0-514.21.2.el7.ug.x86_64
$ module load R/3.4.0-intel-2017a-X11-20170314
$ R -q --no-save
> library(RWeka)
Segmentation fault
```

The problem is apparently caused by a security fix in recent versions of the Linux kernel, see:

* https://lists.ubuntu.com/archives/ubuntu-devel-discuss/2017-June/017507.html
* https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1698919

A workaround that seems to dance around the problem for me (from https://github.com/s-u/rJava/issues/110):

```shell
$ export _JAVA_OPTIONS="-Xss2560k -Xmx2g"
$ R -q --no-save
> library(RWeka)
Picked up _JAVA_OPTIONS: -Xss2560k -Xmx2g
> quit()
```

The bug is fixed is more recent Linux versions, so just logging this here for reference, it's a temporary issue linked to particular versions of the Linux kernel, so little we can do about it.

**Comment by verdurin** [comment]
Seeing this while building those extensions, so thought I should mention it here.

**Comment by boegel** [comment]
@verdurin Can you confirm that the workaround works?

I'm not sure if it's worth the trouble to keep this issue open if it works, since I don't considering this our problem to fix, giving that it's a kernel bug?

**Comment by verdurin** [comment]
Well, I didn't see a method of applying the workaround for individual extensions...

**Comment by boegel** [comment]
Hmm, even though you can now control easyconfig parameters on a per-extension basis, I'm not sure you can just put the custom `$_JAVA_OPTIONS` value in place for only the extensions where it's required.

Is that worth the trouble though?

**Comment by boegel** [comment]
Kernel update fixed this for us, so I'm closing this.
