### ISSUE TITLE
OpenFOAM-4.1-intel-2017a.eb : irresolvable dependencies?

### ISSUE THREAD

**Issue by backelj** [easybuilders/easybuild-easyconfigs#4879]
Hi all,

I wanted to install OpenFOAM-4.1-intel-2017a.eb (from the master tree) but it failed with several irresolvable dependencies:

```
eb -d OpenFOAM-4.1-intel-2017a.eb
== resolving dependencies ...
ERROR: Irresolvable dependencies encountered: CMake/3.8.0-intel-2017a, X11/20170314-intel-2017a, libpng/1.6.29-intel-2017a, Autotools/20150215-intel-2017a
```

I don't see these files anywhere, so I'm wondering: how did this file got in the master tree without all of it's [currently irresolvable] dependencies?

-- Regards,

Franky

**Comment by boegel** [comment]
@backelj These dependencies can be resolved via a subtoolchain of `intel/2017a`, e.g. `GCCcore/6.3.0`.

The error message is indeed a bit confusing since it specifies the the full toolchain explicitly.

If you provide the easyconfigs for these dependencies that use `GCCcore/6.3.0` in your robot search path, EasyBuild will pick them up and be happy.

The easiest thing you can do is to update to the just released EasyBuild v3.3.1, which will include everything that is required out of the box.

**Comment by backelj** [comment]
Aah, I forgot to mention that I _am_ using EasyBuild v.3.3.1 ;-)

Then again, it probably has to do with the fact that we are using an alternative intel/2017a (all in one directory) module. That said, how does EasyBuild know that GCCcore/6.3.0 is a subtoolchain of intel/2017a? Maybe that's missing in our intel/2017a module file...

**Comment by boegel** [comment]
@backelj It does that based on the components listed in the easyconfig file for `intel-2017a.eb`.

So, by changing how `intel/2017a` is installed, you probably broke that mechanism...

**Comment by backelj** [comment]
@boegel Well, if I exclude our intel-2017a.eb from the robot path, then it starts to build, so indeed it comes down to a change in our intel-2017a.eb.

However, if I look at our intel-2017a.eb, it also contains GCCcore/6.3.0:

```
$ diff our/intel-2017a.eb orig/intel-2017a.eb
< intelver = '2017.1.132'
<     ('icc', intelver, gccsuff),
<     ('ifort', intelver, gccsuff),
<     ('impi', intelver, '', ('iccifort', '%s%s' % (intelver, gccsuff))),
<     ('imkl', intelver, '', ('iimpi', version)),
---
>     ('icc', 'phony'),
>     ('ifort', 'phony'),
>     ('impi', 'phony'),
>     ('imkl', 'phony'),
```

The part of GCCcore/6.3.0 has not been changed, so shouldn't that be recognized as the subtoolchain of intel/2017a? That is, what is needed to recognize it as a subtoolchain?

**Comment by boegel** [comment]
@backelj EasyBuild uses the `get_toolchain_hierarchy` function (see https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/framework/easyconfig/easyconfig.py#L139) for this, which will check the easyconfig file for `intel-2017a.eb` and try to figure out the version for the first subtoolchain (`iimpi`, see https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/toolchains/intel.py#L44) based on the dependencies. And then it does the same for `iccifort` and `GCCcore`, in that order.

Somehow you have broken that mechanism by redefining the toolchain...
