### ISSUE TITLE
Bowtie compiler options are passed twice

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-easyconfigs#4909]
I build bowtie and mentioned that the options (-O2 -march=corei7 -fPIC) are passed twice. Bowtie was built with `eb --buildpath=/dev/shm --optarch=march=corei7 --prefix=/easybuild/test Bowtie-1.2.1.1-foss-2016b.eb -dr` (this EasyConfig is from pull request #4905) on Ubuntu 16.04 and EasyBuild 3.3.1:

```
> bowtie --version
bowtie-align version 1.2.1.1
64-bit
Built on node018
Tue Jul 18 09:37:50 CEST 2017
Compiler: gcc version 5.4.0 (GCC) 
Options: -O3 -m64  -Wl,--hash-style=both -DWITH_TBB -DPOPCNT_CAPABILITY -O2 -march=corei7 -fPIC  -O2 -march=corei7 -fPIC 
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```

I also looked at a previously built Bowtie, which also had this behaviour. This was built with `eb --buildpath=/dev/shm --optarch=march=corei7 --prefix=/easybuild/16.04 --try-toolchain=foss,2016b Bowtie-1.1.2-foss-2016a.eb -dr` and EasyBuild 3.0.2.

This is not the case with Bowtie2 (in case this helps).

**Comment by boegel** [comment]
@SethosII This is probably because Bowtie picks up both `$CFLAGS` and `$CXXFLAGS`, or something funky like that?

I checked both the `EB_Bowtie` easyblock, and the Bowtie easyconfig file, we're not specifying that in a duplicate way anywhere...

**Comment by SethosII** [comment]
@boegel I built `bowtie` manually with `$CFLAGS` and `$CXXFLAGS` set and found the same behaviour. So this seems to be a problem with bowtie picking up both variables.

**Comment by boegel** [comment]
OK, in that case we can consider unsetting one of them in the `Bowtie` easyblock, but that needs to be done with some care I guess...

On the other hand: it's not really a problem at all?

**Comment by SethosII** [comment]
Yes, there is no problem when passing them twice. So we can just leave it like it is. Maybe I should open an issue in the `bowtie` repository so it gets solved there.
