### ISSUE TITLE
PLUMED hangs on configure

### ISSUE THREAD

**Issue by reedts** [easybuilders/easybuild-easyconfigs#4955]
Using `EasyBuild 3.3.1` I'm struggling to install `PLUMED-2.3.0-intel-2016b.eb` on our machine. It just hangs in the configure step forever and I have no error message. All I could get out of the log:

```
== 2017-07-24 08:50:50,627 templates.py:151 DEBUG config: <easybuild.framework.easyconfig.easyconfig.EasyConfig object at 0x28cded0>
== 2017-07-24 08:50:50,627 templates.py:175 DEBUG version found in easyconfig is 2.3.0
== 2017-07-24 08:50:50,628 templates.py:219 DEBUG name: github_account, config: None
== 2017-07-24 08:50:50,628 templates.py:219 DEBUG name: name, config: PLUMED
== 2017-07-24 08:50:50,628 templates.py:219 DEBUG name: version, config: 2.3.0
== 2017-07-24 08:50:50,628 templates.py:219 DEBUG name: versionsuffix, config: 
== 2017-07-24 08:50:50,629 templates.py:219 DEBUG name: versionprefix, config: 
== 2017-07-24 08:50:50,629 easyblock.py:2347 INFO Running method configure_step part of step configure
== 2017-07-24 08:50:50,629 run.py:132 DEBUG run_cmd: running cmd env FC=$MPIF90 LIBS="$LIBLAPACK $LIBS"  ./configure --prefix=/Applic.HPC/software/MPI/intel/2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181/PLUMED/2.3.0  --exec-prefix=/Applic.HPC/software/MPI/intel/2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181/PLUMED/2.3.0 --enable-gsl (in /tmp/easybuild-j_bigg01/PLUMED/2.3.0/intel-2016b/plumed2-2.3.0)
== 2017-07-24 08:50:50,630 run.py:157 INFO running cmd: env FC=$MPIF90 LIBS="$LIBLAPACK $LIBS"  ./configure --prefix=/Applic.HPC/software/MPI/intel/2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181/PLUMED/2.3.0  --exec-prefix=/Applic.HPC/software/MPI/intel/2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181/PLUMED/2.3.0 --enable-gsl
```
Any advice?
reedts

**EDIT:** Both `PLUMED-2.3.0-foss-2016b.eb` and `PLUMED-2.3.0-foss-2017a.eb` build and install successfully, so maybe it's a compiler issue?

**Comment by boegel** [comment]
@reedts EasyBuild buffers the output of commands by default, which makes this a bit hard to figure out...

One thing you can do is kill the `./configure` process, which will make EasyBuild spit out the output in the log, maybe that provides a clue?

**Comment by boegel** [comment]
@reedts I'm hitting the same problem now, but I'm only seeing it when trying to build `PLUMED` with `intel` in a SLURM job environment.

Do you recall if that also was the case for you? Did you figure out a solution to this?

I've seen similar issues with `h5py` for example, see also https://github.com/h5py/h5py/issues/917, but that's because an `python -c "import h5py"` does an MPI init when `h5py` was built with parallel support...

**Comment by ocaisa** [comment]
This is an old issue, and now that we know the source of the problem I'm going to close it.

**Comment by benczaja** [comment]
Hi @ocaisa can you elaborate on which SLURM VARIABLES you unset in order to make the configuration step? 
I am having the same problem with PLUMED configuration step. (PLUMED 2.9.0)

**Comment by ocaisa** [comment]
@benczaja Unset all variables in the environment that start with `SLURM` (`env | grep SLURM`)
