### ISSUE TITLE
Installation of GROMACS-2016.1-foss-2017a-PLUMED.eb 

### ISSUE THREAD

**Issue by vas2201** [easybuilders/easybuild-easyconfigs#4960]
Hi,

I am using easybuild (new user) to install the gromacs with plumed by issuing the following commands in my account on HPC. I don't have root privileges.  i am getting following errors. could anyone please me help to fix this errors ?.  

I am always getting following error. whatever i do.
**# One or more OS dependencies were not found:** [('libibverbs-dev', 'libibverbs-devel')]******

[srp106@hpc1 software]$ eb -S GROMACS-2016.1-foss-2017a-PLUMED.eb
CFGS1=/home/srp106/software/easybuild/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.3.1-py2.7.egg/easybuild/easyconfigs/g/GROMACS
 * $CFGS1/GROMACS-2016.1-foss-2017a-PLUMED.eb
[srp106@hpc1 software]$ eb GROMACS-2016.1-foss-2017a-PLUMED.eb --try-toolchain=foss,2017a --robot
== temporary log file in case of crash /tmp/eb-uYYjg7/easybuild-YOway2.log
### # **== resolving dependencies **...**

****ERROR: Failed to process easyconfig /home/srp106/software/easybuild/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.3.1-py2.7.egg/easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb: One or more OS dependencies were not found:** [('libibverbs-dev', 'libibverbs-devel')]****

[srp106@hpc1 software]$ eb GROMACS-2016.1-foss-2017a-PLUMED.eb --try-toolchain=foss,2017a-no-OFED --robot
== temporary log file in case of crash /tmp/eb-LCQwIw/easybuild-VV3INo.log
== resolving dependencies ...

**ERROR: Irresolvable dependencies encountered: CMake/3.7.2-foss-2017a-no-OFED, zlib/1.2.8-foss-2017a-no-OFED, foss/2017a-no-OFED, flex/2.6.3-foss-2017a-no-OFED, Bison/3.0.4-foss-2017a-no-OFED, libtool/2.4.6-foss-2017a-no-OFED, binutils/2.27-foss-2017a-no-OFED, M4/1.4.18-foss-2017a-no-OFED, ncurses/6.0-foss-2017a-no-OFED**

This is EasyBuild 3.3.1 (framework: 3.3.1, easyblocks: 3.3.1) on host hpc1.

[srp106@hpc1 software]$ uname -a
Linux hpc1 2.6.32-696.3.1.el6.x86_64 #1 SMP Thu Apr 20 11:30:02 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

Linux version 2.6.32-696.3.1.el6.x86_64 (mockbuild@x86-042.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 **(Red Hat 4.4.7-18) (GCC)** ) #1 SMP Thu Apr 20 11:30:02 EDT 2017

Thanking you !

**Comment by verdurin** [comment]
@vas2201 With the error `One or more OS dependencies were not found` you need to ask the administrator of the system to install the ibverbs headers.

**Comment by vas2201** [comment]
Dear Verdurin,
Thanks for your reply ! we could not find the these files libibverbs-dev', 'libibverbs-devel tar.gz files.
if anyone have information about these file, could you please send to me here ! 
Thanking you !

**Comment by verdurin** [comment]
@vas2201 They're not tarballs. They're packages for your OS. In this case, either 'libibverbs-dev' for Debian/Ubuntu, or 'libibverbs-devel' for CentOS/RHEL.
