### ISSUE TITLE
Possible dutch english spotted

### ISSUE THREAD

**Issue by mmterpstra** [easybuilders/easybuild-easyconfigs#4964]
Minor style thing maybe change this sentence (the english have better words for that (facilitates, enables or allows)):

> HDF5 is a unique technology suite that **makes possible** the management of
 extremely large and complex data collections.

to

> HDF5 is a data model, library, and file format for storing and managing data.
 It supports an unlimited variety of datatypes, and is designed for flexible
 and efficient I/O and for high volume and complex data.

**Comment by bldrvnlw** [comment]
As a native speaker I can confirm that "makes possible" is perfectly good English. As evidence I offer this link to the BBC (one of may I could have chosen) http://www.bbc.co.uk/radio4/science/arthurcclarke.shtml 

> Thus it makes possible radio communications with fixed receivers on the ground such as the satellite TV dishes springing up on millions of homes.

The Dutch "iets mogelijk maken" sounds similar, but English and Dutch are sometimes not so different :-)

**Comment by boegel** [comment]
I agree with @mmterpstra that the other description is more useful, so I've changed it in #5182
