### ISSUE TITLE
Cannot install Boost-1.58.0-intel-2017.02-Python-2.7.9.eb

### ISSUE THREAD

**Issue by nortex** [easybuilders/easybuild-easyconfigs#4981]
Hi,

I am trying to build ABySS-1.3.7-intel-2015a-Python-2.7.9.eb with --try-toolchain=intel,2017.02.

All goes O.K until the Boost-1.58.0-intel-2017.02-Python-2.7.9.eb Dependency.

I recieve this error:

`...failed intel-linux.compile.c++ bin.v2/libs/mpi/build/intel-linux/release/threading-multi/python/py_nonblocking.o`

Does anyone familiar with that? here is the ./bjam configuration EasyBuild installing with:

`
== 2017-08-06 18:09:31,207 easyblock.py:2574 WARNING build failed (first 300 chars): cmd "./bjam  --prefix=/data/sources/build/Boost/1.58.0/intel-2017.02-Python-2.7.9/obj cxxflags='-O2 -xSSE2 -ftz -fp-speculation=safe -fp-model source -fPIC' linkflags='-L/data/apps/Easybuild/apps/icc/2017.2.174-GCC-6.3.0-2.27/lib/intel64 -L/data/apps/Easybuild/apps/imkl/2017.2.174-iimpi-2017.02-GCC-  `

Could the problem be with the -L line linkinx to -L/data/apps/Easybuild/apps/imkl/2017.2.174-iimpi-2017.02-GCC-

I do not have that path, only: 

/data/apps/Easybuild/apps/imkl/2017.2.174-iimpi-2017.02-GCC-6.3.0-2.27/

What can i do? Thanks.

**Comment by boegel** [comment]
@nortex The path you're mentioning is not the complete path being used, you're looking at a partial error message (see the `first 300 chars`)...

It's not clear what the actual problem is from the provided information (there's no clear error message).

Can you collect a debug log (using `eb --debug`), upload the full log file somewhere (e.g. via gist.github.com) and mention the location to it here?

**Comment by nortex** [comment]
Hi Kenneth,

Here is my log with --debug mod: https://gist.github.com/nortex/ad0d7dcc267a39f8501b16abe152a901

**Comment by boegel** [comment]
Seems like the more recent version of the Intel compilers are more picky, this is the actual error:

```
libs/mpi/src/python/py_nonblocking.cpp(166): error: no suitable conversion function from "boost::optional<<unnamed>::status_value_iterator>" to "bool" exists
        return test_all(requests.begin(), requests.end(), 
               ^
```

which leads to:

```
compilation aborted for libs/mpi/src/python/py_nonblocking.cpp (code 2)

    "icpc" -c -xc++ -w1 -inline-level=2 -O3 -ip -pthread -fPIC -m64 -O2 -xSSE2 -ftz -fp-speculation=safe -fp-model source -fPIC -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker /data/apps/Easybuild/apps/impi/2017.2.174-iccifort-2017.2.174-GCC-6.3.0-2.27/intel64/lib/release_mt -Xlinker -rpath -Xlinker /data/apps/Easybuild/apps/impi/2017.2.174-iccifort-2017.2.174-GCC-6.3.0-2.27/intel64/lib -Xlinker -rpath -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib/release_mt -Xlinker -rpath -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib -DBOOST_ALL_NO_LIB=1 -DBOOST_MPI_DYN_LINK=1 -DBOOST_MPI_PYTHON_DYN_LINK=1 -DBOOST_PYTHON_DYN_LINK=1 -DNDEBUG -I"." -I"/data/apps/Easybuild/apps/Python/2.7.9-intel-2017.02/include/python2.7" -I"/data/apps/Easybuild/apps/impi/2017.2.174-iccifort-2017.2.174-GCC-6.3.0-2.27/intel64/include"   -c -o "bin.v2/libs/mpi/build/intel-linux/release/threading-multi/python/py_nonblocking.o" "libs/mpi/src/python/py_nonblocking.cpp"

...failed intel-linux.compile.c++ bin.v2/libs/mpi/build/intel-linux/release/threading-multi/python/py_nonblocking.o...
```

If you want to get this working, you'll need to patch Boost 1.58.0.

I think updating to a more recent version of Boost is probably easier...

**Comment by Micket** [comment]
We have recent versions of Boost, ABySS and Python with no seeming issues, so this problem has been resolved already.
