### ISSUE TITLE
Modules with the same toolchain having conflicting dependencies (HDF5/1.8.16-foss-2016a and R/3.3.1-foss-2016a)

### ISSUE THREAD

**Issue by pol** [easybuilders/easybuild-easyconfigs#4994]
Trying to load first `HDF5/1.8.16-foss-2016a` then `R/3.3.1-foss-2016a` throws the following error:

```
HDF5/1.8.17-foss-2016a(13):ERROR:150: Module 'HDF5/1.8.17-foss-2016a' conflicts with the currently loaded module(s) 'HDF5/1.8.16-foss-2016a'
HDF5/1.8.17-foss-2016a(13):ERROR:102: Tcl command execution failed: conflict HDF5
```

You can insert `module rm cURL/7.47.0-foss-2016a` between the calls and the error is resolved, but this seems nonintuitive.  Is there a recommended way to resolve this issue other than just editing the modulefiles to point to the same versions?

**Comment by pol** [comment]
I need to dig into this some more.  This issue is nonsensical as stated.  Sorry.

**Comment by boegel** [comment]
I don't see how unloading `cURL` could ever allow you to load two different versions of HDF5 together?

**Comment by pol** [comment]
Indeed!  But... it appears that you can just module load twice (without unloading curl) and it will let you load conflicting modules without an error.  The unloading of curl was a red herring. That's a different problem, though. 

The core issue was that I had a custom module that loaded older HDF5 and NetCDF modules.  The curl conflict came out of that. Full Example:

```
[d86r845@hyalite ~]$ module purge
[d86r845@hyalite ~]$ module load HDF5/1.8.16-foss-2016a
[d86r845@hyalite ~]$ module load netCDF/4.4.0-foss-2016a
[d86r845@hyalite ~]$ module load R/3.3.1-foss-2016a
cURL/7.49.1-foss-2016a(21):ERROR:150: Module 'cURL/7.49.1-foss-2016a' conflicts with the currently loaded module(s) 'cURL/7.47.0-foss-2016a'
cURL/7.49.1-foss-2016a(21):ERROR:102: Tcl command execution failed: conflict cURL

netCDF/4.4.1-foss-2016a(15):ERROR:150: Module 'netCDF/4.4.1-foss-2016a' conflicts with the currently loaded module(s) 'netCDF/4.4.0-foss-2016a'
netCDF/4.4.1-foss-2016a(15):ERROR:102: Tcl command execution failed: conflict netCDF

```

Weirdly, if you just try to load R again, the netCDF error goes away, but the cURL one sticks around.  So I thought the problem was with cURL.  The original issue should have been with NetCDF, not HDF5 (I picked the wrong one).  HDF5 doesn't use cURL as a dependency.  

Ultimately the problem is solved by just updating my modules to load the right ones.  I assume the weird reload-and-it-works behavior is a bug in our version of module.
