### ISSUE TITLE
libpng linking issue

### ISSUE THREAD

**Issue by andreas-h** [easybuilders/easybuild-easyconfigs#5033]
I'm running into a strange problem with libpng and intel/2017a.  I'm trying to create an easyconfig for [ecCodes](https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home).  According to the debug log, the problem happens with the command

>cd /dev/shm/eb-build/ecCodes/2.4.1/intel-2017a-Python-3.6.1/easybuild_obj/examples/F90 && /home/eb/software/CMake/3.8.2-GCCcore-6.3.0/bin/cmake -E cmake_link_script CMakeFiles/eccodes_f_grib_copy_namespace.dir/link.txt --verbose=1
/home/eb/software/ifort/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/ifort  -L/home/eb/software/icc/2017.1.132-GCC-6.3.0-2.27/lib/intel64 -L/home/eb/software/imkl/2017.1.132-iimpi-2017a/lib -L/home/eb/software/imkl/2017.1.132-iimpi-2017a/mkl/lib/intel64 -L/home/eb/software/imkl/2017.1.132-iimpi-2017a/lib -L/home/eb/software/JasPer/2.0.12-intel-2017a/lib64 -L/home/eb/software/libpng/1.6.29-GCCcore-6.3.0/lib -L/home/eb/software/netCDF/4.4.1.1-intel-2017a-HDF5-1.8.18/lib64 -L/home/eb/software/Python/3.6.1-intel-2017a/lib    -Wl,--disable-new-dtags -O2 -xHost -ftz -fp-speculation=safe -fp-model source -qopenmp -O2 -g -heap-arrays 32 CMakeFiles/eccodes_f_grib_copy_namespace.dir/grib_copy_namespace.f90.o  -o eccodes_f_grib_copy_namespace -Wl,-rpath,/dev/shm/eb-build/ecCodes/2.4.1/intel-2017a-Python-3.6.1/easybuild_obj/lib ../../lib/libeccodes_f90.so ../../lib/libeccodes.so /home/eb/software/libpng/1.6.29-GCCcore-6.3.0/lib/libpng.so /usr/lib64/libz.so /usr/lib64/libm.so -lpthread 

The error is 

>/home/eb/software/libpng/1.6.29-GCCcore-6.3.0/lib/libpng.so: undefined reference to `inflateValidate@ZLIB_1.2.9'

>make[2]: *** [examples/F90/eccodes_f_grib_copy_namespace] Error 1
>make[2]: Leaving directory `/dev/shm/eb-build/ecCodes/2.4.1/intel-2017a-Python-3.6.1/easybuild_obj'
>make[1]: *** [examples/F90/CMakeFiles/eccodes_f_grib_copy_namespace.dir/all] Error 2
>make[1]: Leaving directory `/dev/shm/eb-build/ecCodes/2.4.1/intel-2017a-Python-3.6.1/easybuild_obj'
>make: *** [all] Error 2

I don't understand why there is a reference to `@ZLIB_1.2.9` in my libpng, even though the libpng easyconfig depends on zlib 1.2.11 ...

Any ideas?

**Comment by andreas-h** [comment]
Interesting. The build succeeds if I add zlib 1.2.11 to the dependencies of my ecCodes easyconfig.  Even though libpng 1.6.29 is a dependency, and the libpng/1.6.29-GCCcore-6.3.0 module loads the zlib/1.2.11-GCCcore-6.3.0 module.

Any ideas why this is happening?  I'm on CentOS7

**Comment by boegel** [comment]
@andreas-h Also specifying `zlib` as a direct dependency makes a difference, since the `/lib` paths for direct dependencies also get listed in `$LDFLAGS`...

**Comment by andreas-h** [comment]
I see, thanks, @boegel !

**Comment by boegel** [comment]
To further clarify: this is usually not a problem, because the modules generated by EasyBuild also update `$LIBRARY_PATH` (not to be confused by `$LD_LIBRARY_PATH`), which the compiler/linker usually considers as well when linking in libraries (in this case `-lz`).

For some reason, that's not sufficient here, but including the location to `libz.*` in `$LDFLAGS` (by listing `zlib` as a direct dependency), is...
