### ISSUE TITLE
cairo-1.14.6-foss-2016a.eb > Sanity check failed: no file of ('include/cairo/cairo-xcb.h',)

### ISSUE THREAD

**Issue by shawarden** [easybuilders/easybuild-easyconfigs#5070]
When trying to build R-bundle-Bioconductor-3.2-foss-2016a-R-3.2.3.eb > R-3.2.3-foss-2016a.eb > I needed to add cairo as a dependency (along with libGLU) for the rgl and cairo extensions.

When trying to build cairo-1.14.6-foss-2016a it fails on the sanity check because it can't find include/cairo/cairo-xcb.h

.../easybuild/build/cairo/1.14.6/foss-2016a/cairo-1.14.6/src/cairo.xcb-h exists but it's not being copied to where it's expected to be: .../easybuild/software/cairo/1.14.6-foss-2016a/include/cairo/cairo-xcb.h

[easybuild-cairo-1.14.6.logs.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/1262147/easybuild-cairo-1.14.6.logs.zip)

Seems to be the same issue as https://github.com/easybuilders/easybuild-easyconfigs/issues/3363

**Comment by boegel** [comment]
In more recent `cairo` easyconfigs, we include `--enable-xlib-xcb` in `configopts`, maybe you need this here too?

I think this works sometimes if you happen to have certain `xcb-*` packages installed on the OS. In more recent `cairo` easyconfigs, we include a fat `X11` bundle as a dependency to cairo, which solves that.

**Comment by Micket** [comment]
cair-xcb.h header is present, in fact we sanity check for it in all recent builds. I believe this issue has long since been resolved.
