### ISSUE TITLE
Trilinos-10.12.2-goolf-1.4.10-Python-2.7.3.eb build error on centos7

### ISSUE THREAD

**Issue by vwkoppejan** [easybuilders/easybuild-easyconfigs#5110]
I'm trying to build Trilinos-10.12.2-goolf-1.4.10-Python-2.7.3.eb on centos7 on a dell T3610 workstation. It results in an error but I can't figure out what's wrong. Could someone point me in the right direction?

Thanks in advance,

Victor Koppejan

[easybuild-GCC-4.7.2-20170911.195007.wahax.log.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/1293524/easybuild-GCC-4.7.2-20170911.195007.wahax.log.txt)

**Comment by boegel** [comment]
@vwkoppejan Ugh, I just noticed this didn't receive an answer...

For what it's worth, this seems to be the culprit:

```
echo timestamp > gcc.pod
perl ../../gcc/../contrib/texi2pod.pl ../../gcc/doc/invoke.texi > gcc.pod
../../gcc/doc/cppopts.texi:806: @itemx must follow @item
make[3]: *** [doc/cpp.info] Error 1
```

That's a problem that occurs when building old GCC versions on a recent OS, see also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60961 .

I've just opened a pull request for the latest version of Trilinos with the more recent `foss/2018a` toolchain, that should result in a better experience on recent OS versions... See #6843, (which requires updates to the `Trilinos` easyblock, see https://github.com/easybuilders/easybuild-easyblocks/pull/1486). The plan is to include this in the upcoming EasyBuild v3.7.0...

**Comment by vwkoppejan** [comment]
No worries, thanks for looking into it.

**Comment by boegel** [comment]
@vwkoppejan How shall we proceed with this? Is it good to close?
