### ISSUE TITLE
EMBOSS needs X11 libs

### ISSUE THREAD

**Issue by hajgato** [easybuilders/easybuild-easyconfigs#5116]
`EMBOSS` needs `X11` libs, or have to define `--without-x` for `confugure` 

```
X11 graphics have been selected but no X11 header files
have been found.

This error usually happens on Linux/MacOSX distributions
where the optional X11 development files have not been installed.
On Linux RPM systems this package is usually called something
like xorg-x11-proto-devel whereas on Debian/Ubuntu it may
be called x-dev. On MacOSX installation DVDs the X11 files
can usually be found as an explicitly named optional
installation.

After installing the X11 development files you should do a
'make clean' and perform the configure stage again.

Alternatively, to install EMBOSS without X11 support, you can add
the --without-x switch to the configure command.
```

**Comment by llity** [comment]
Hello, did you solve this issue? thanks!

**Comment by hajgato** [comment]
`EMBOSS` with 2018b toolchains solved this issue.

**Comment by llity** [comment]
@hajgato Thanks for your reply, could U provide more detail for that, How I can fix it. Thanks.

**Comment by boegel** [comment]
@llity Recent easyconfig files for `EMBOSS` like `EMBOSS-6.6.0-foss-2018b.eb` include `X11` as a dependency, see https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/e/EMBOSS/EMBOSS-6.6.0-foss-2018b.eb#L36 .
