### ISSUE TITLE
Boost 1.64.0 and DBD-mysql

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#5146]
I am trying to build 

     DBD-mysql-4.042-intel-2017a-Perl-5.24.1.eb

which depends on Boost 1.64.0, which suffers from (part of) the get_data.hpp issue, which we discussed in May.  Then we expected 1.64.0 to resolve the issue, but it isn’t.  I checked that I can build

      Boost-1.65.0-intel-2017a-Python-2.7.13.eb

and do not suffer from the issue.  

Possible resolutions may be:

- Move the MariaDB to boost 1.65.0
- Patch the boost according to https://svn.boost.org/trac10/ticket/12516 and https://github.com/boostorg/serialization/commit/1d86261581230e2dc5d617a9b16287d326f3e229

**Comment by boegel** [comment]
@jhein32 should be fixed by #5148, let's follow up there...
