### ISSUE TITLE
Missing files when bootstrapping EasyBuild with bootsrap_eb.py

### ISSUE THREAD

**Issue by bldrvnlw** [easybuilders/easybuild-easyconfigs#5168]
Some files that need to be downloaded from pypi seems to be missing. For example: 

https://pypi.python.org/packages/source/v/vsc-install/vsc-base-2.5.8.tar.gz
https://pypi.python.org/packages/source/v/vsc-install/easybuild-framework-3.4.0.tar.gz 
 https://pypi.python.org/packages/source/e/easybuild-framework/easybuild-easyblocks-3.4.0.tar.gz 

The logfile is here:
[easybuild-EasyBuild-3.4.0-20170925.161049.OVEKg.log](https://github.com/easybuilders/easybuild-easyconfigs/files/1329887/easybuild-EasyBuild-3.4.0-20170925.161049.OVEKg.log)

**Comment by bldrvnlw** [comment]
Some more information: The file that could not be unpacked (bootstrap expected a file at /home/bvanlew/EasyBuild/sources/e/EasyBuild/vsc-install-0.10.26.tar.gz)  was actually successfully downloaded, i.e. it isn't one of the list above. 

Instead of being put in the target $EASYBUILD_PREFIX/sources/e/EasyBuild directory the file was placed in a temporary directory with path: /tmp/tmpaZM4PW/$HOME/EasyBuild/sources/e/EasyBuild/vsc-install-0.10.26.tar.gz. The `tar xvf $HOME/EasyBuild/sources/e/EasyBuild/vsc-install-0.10.26.tar.gz"` could not find the file.

The $EASYBUILD_PREFIX is defined but is there another setting needed to prevent this failure? The path containing $HOME is very unexpected. ($HOME is defined as an environment variable by the way)

**Comment by bldrvnlw** [comment]
Managed to workaround the issue by downloading the sources from pypi 

`pip download vsc-base --no-deps
pip download vsc-install --no-deps
pip download easybuild-framework --no-deps
pip download easybuild-easyblocks --no-deps
pip download easybuild-easyconfigs --no-deps
`

To a temp directory (<download_temp_dir>) and then defining `export EASYBUILD_BOOTSTRAP_SOURCEPATH=<download_temp_dir>`

and running the bootstrap.

Still don't understand why the default for ----sourcepath is '$HOME/EasyBuild/sources' with unresolved '$HOME'

**Comment by boegel** [comment]
@bldrvnlw This is weird...

How exactly did you run the bootstrap script to get the hard `$HOME` being used?

It seems like you specified `$HOME` in single quotes as a part of the path where EasyBuild should be bootstrapped into?

W.r.t. the failing downloads: EasyBuild cycles through a list of source URLs, and tries to download the sources while trying each of them in turn. As long as each source file can be downloaded through one of them, there should be no issue. I do admit we could approach this more intelligently though...

**Comment by bldrvnlw** [comment]
@boegel 
Running the script was as follows: 
`python bootstrap_eb_orig.py $EASYBUILD_PREFIX`

where EASYBUILD_PREFIX is EASYBUILD_PREFIX=/home/bvanlew/EasyBuild and $HOME=/home/bvanlew The only other EASYBUILD environment variable was EASYBUILD_BOOTSTRAP_DEBUG=1

For reference the headnode where I''m running system is
lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by bldrvnlw** [comment]
I think I've found the problem:  there was an old ~/.config/easybuild/config.py (from a previous install attempt) file containing the line `sourcepath=$HOME/EasyBuild/sources`. So in future - I need to be sure to cleanup before running the bootstrap. Sorry for the noise but perhaps it will help someone else.

**Comment by boegel** [comment]
@bldrvnlw Ah, that indeed explains it... Thanks for the update!
