### ISSUE TITLE
xorg-macros-1.19.0-foss-2016b: os dependencies

### ISSUE THREAD

**Issue by naveau** [easybuilders/easybuild-easyconfigs#5174]
Hi,

Can someone explain the reason behind adding `('perl-Thread-Queue', 'libthread-queue-any-perl')` as an os dependency for xorg-macros foss-2016b? The other build configs do not require it, why the foss-2016b does?

https://github.com/easybuilders/easybuild-easyconfigs/blob/dd3a496e6dd8e28bd2b31b86fb50be9786997caf/easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.0-foss-2016b.eb#L15

I successfully build it without the osdependencies but I don't know how to test it. @verdurin, could you give me some hints on this?

Best,

Mikaël

**Comment by boegel** [comment]
Hmm, seems like this slipped through in https://github.com/easybuilders/easybuild-easyconfigs/pull/4030/files#diff-ea82939868d5325477a4213e2514f07bR15, indeed by @verdurin.

More context in https://github.com/easybuilders/easybuild-easyconfigs/issues/4025.

If it works for you without having either of those dependencies installed, I guess we should remove it.

Thoughts @verdurin?

**Comment by verdurin** [comment]
If it builds now without those, then I agree they should be removed.

**Comment by boegel** [comment]
@naveau Seems like it's actually require for `Automake`, see #1822...

**Comment by boegel** [comment]
@naveau Which OS are you using? Apparently `Thread::Queue` was split off in a separate package since CentOS7 (or any other RHEL7-based variant), see https://github.com/easybuilders/easybuild-easyconfigs/issues/1822#issuecomment-285697262...

**Comment by naveau** [comment]
```
$ cat /etc/centos-release 
CentOS release 6.7 (Final)
```
My first idea was to add perl as a dependency because my system does not provide `perl-Thread-Queue`, then I realized that this osdependency was not mentioned in the other eayconfig files of xorg-macros and I gave it a try...
I didn't checked that `Thread::Queue` was indeed included in the perl distribution... My bad.

Nevertheless, the dependency here is somewhat misleading if it's a problem related to automake, isn't it?

**Comment by boegel** [comment]
@naveau Well, maybe it's relevant to both `Automake` and `xorg-macros`, that's not clear to me (we *have* `Thread::Queue` available on our CentOS7 systems, so I never noticed).

**Comment by Micket** [comment]
All the deps are like they should be for X11, autotools and perl nowadays.
