### ISSUE TITLE
Libffi module is missing include path to $CPATH env var

### ISSUE THREAD

**Issue by renatopancheri** [easybuilders/easybuild-easyconfigs#5270]
after loading libffi module, $CPATH is not updated with the libffi include dir,
this issue seems to me independent from the version/toolchain used to install the module.
I assume the problem is that the include dir is not at default path,
i solved this with the help of of freenode chat adding
modextrapaths = {'CPATH': ['lib/libffi-%(version)s/include']}
to easyconfig file.

**Comment by boegel** [comment]
Fixed in #5271, thanks for reporting this @renatopancheri!
