### ISSUE TITLE
numactl source problems

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#5285]
The old `oss.sgi.com` FTP site for `numactl` seems to have disappeared.

There is a site on GitHub, though it doesn't have a proper release tarball, just the automatically generated one which requires `configure` to be created manually.

https://github.com/numactl/numactl

**Comment by verdurin** [comment]
Cf. https://web.archive.org/web/20171011123404/http://www.oss.sgi.com/

**Comment by verdurin** [comment]
Addressed in #5286

**Comment by boegel** [comment]
fixed in #5285, #5296, #5297
