### ISSUE TITLE
Failure Building ATLAS

### ISSUE THREAD

**Issue by jpc2350** [easybuilders/easybuild-easyconfigs#5293]
Hi Guys,

I'm trying to build ATLAS (I'm hoping this will fix my Numpy build issue)

ATLAS configures correctly (using easybuild, and manually), but I then get a build failure with easybuild:

```
make -f Make.top build
make[1]: Entering directory 'easybuild/build/ATLAS/3.10.3/GCCcore-6.4.0/ATLAS/obj'
Make.top:1: Make.inc: No such file or directory
make[1]: *** No rule to make target 'Make.inc'. Stop.
make[1]: Leaving d
```
With the log file reporting back the following:
```
Makefile:106: recipe for target 'atlas_run' failed
make[1]: *** [atlas_run] Error 1
Makefile:117: recipe for target 'IRun_comp' failed
make: *** [IRun_comp] Error 2
ERROR 512 IN SYSCMND: 'make IRun_comp args="-v 0 -o atlconf.txt -O 1 -A 31 -Si nof77 0 -V 976  -C ic 'gcc' -Fa ic '-fPIC' -Fa sm '-fPIC' -Fa dm '-fPIC' -Fa sk '-fPIC' -Fa dk '-fPIC' -Fa xc '-fPIC' -Fa gc '-fPIC' -C if 'gfortran' -Fa if '-fPIC' -b 64"'
Makefile:541: recipe for target 'startup' failed
make: *** [startup] Error 2
== 2017-11-03 13:53:45,893 run.py:484 WARNING Found 7 errors in command output (output: Makefile:106: recipe for target 'atlas_run' failed, make[1]: *** [atlas_run] Error 1, Makefile:117: recipe for target 'IRun_comp' failed, make: *** [IRun_comp] Error 2, ERROR 512 IN SYSCMND: 'make IRun_comp args="-v 0 -o atlconf.txt -O 1 -A 31 -Si nof77 0 -V 976  -C ic 'gcc' -Fa ic '-fPIC' -Fa sm '-fPIC' -Fa dm '-fPIC' -Fa sk '-fPIC' -Fa dk '-fPIC' -Fa xc '-fPIC' -Fa gc '-fPIC' -C if 'gfortran' -Fa if '-fPIC' -b 64"', Makefile:541: recipe for target 'startup' failed, make: *** [startup] Error 2)
```

Any Idea's as to what could be causing this?

**Comment by boegel** [comment]
@jpc2350 Which version ATLAS are you trying to build here, and which easyconfig file are you using? Can you provide it?

Any reason you're favouring ATLAS over OpenBLAS?

**Comment by jpc2350** [comment]
HI @boegel, 
I'm trying to build ATLAS 3.10.3, I've duplicated the 3.10.2 recipe and simply updated the packages (using LAPACK-3.7.1 aswell).

Mainly i'm trying to get Numpy working, it's doing alot of complaining about ATLAS not being available.

**Comment by jpc2350** [comment]
Hi @boegel,
I've not had a problem with Atlas since moving to FOSS-2017b... I'll close the ticket.

**Comment by boegel** [comment]
@jpc2350 Did you mean `numpy` rather than `Atlas`? Using both `Atlas` & `foss/2017b` is a bit strange, since `foss/2017b` already includes `OpenBLAS` + `LAPACK`?
