### ISSUE TITLE
Feature request: easyconfigs parameters to set Lmod functions : 'pushenv', 'set_alias' and 'LmodMessage'

### ISSUE THREAD

**Issue by guest1604** [easybuilders/easybuild-easyconfigs#5330]
Hello,

It could be useful to have the possibility to set `pushenv`, `set_alias` and `LmodMessage` Lmod functions in module files through the easyconfigs.

Thanks !

**Comment by Micket** [comment]
These are (at least nowdays) all supported:
```
modaliases = ...
modloadmsg = ...
modextravars['TEST_PUSHENV'] = {'value': '123', 'pushenv': True}
```

I don't believe we actually document that last option anywhere though, and no easyconfig has ever felt the need to use it.
