### ISSUE TITLE
'import dolfin' in DOLFIN sanity check fails on SL5

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#541]
For same strange reason, `import dolfin` Python statement no longer works during the DOLFIN sanity check. It has worked fine during previous EB regtest runs, on the same systems.

The problem can be easily reproduced outside of EB:

```
-bash-4.1$ python -c "import dolfin"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<DOLFIN>/lib/python2.7/site-packages/dolfin/__init__.py", line 23, in <module>
    from dolfin.cppimports import *
  File "<DOLFIN>/lib/python2.7/site-packages/dolfin/cppimports.py", line 4, in <module>
    import dolfin.cpp as cpp
  File "<DOLFIN>/lib/python2.7/site-packages/dolfin/cpp.py", line 30, in <module>
    _cpp = swig_import_helper()
  File "<DOLFIN>/lib/python2.7/site-packages/dolfin/cpp.py", line 26, in swig_import_helper
    _mod = imp.load_module('_cpp', fp, pathname, description)
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by <DOLFIN>/lib/python2.7/site-packages/dolfin/_cpp.so)

$ ldd  <DOLFIN>/lib/python2.7/site-packages/dolfin/_cpp.so | grep libstdc++
    libstdc++.so.6 => <software>/GCC/4.7.2/lib64/libstdc++.so.6 (0x00002aaab09f7000)
```

Note that using `ldd`, the expected and correctly working `libstdc++.so.6` is found, but not when using `import dolfin` in a Python shell.

I've already spent quite a bit of time trying to figure out this problem, and I've been unable to pinpoint the exact problem.

I find this strange result, however (all collected in the same session, `$LD_LIBRARY_PATH` contains the path to `<software>/GCC/4.7.2/lib64`):

```
$ ldd  <DOLFIN>/lib/python2.7/site-packages/dolfin/_cpp.so | grep libstdc++
    libstdc++.so.6 => <software>/GCC/4.7.2/lib64/libstdc++.so.6 (0x00002aaab09f7000)
# libmpi.so picks up the system libstdc++.so.6 for some reason
$ ldd <software>/OpenMPI/1.6.4-GCC-4.7.2/lib/libmpi.so | grep stdc++
    libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002aaaae8c5000)
# libtorque is required by libmpi.so, picks up our libstdc++.so.6
$ ldd /usr/lib64/libtorque.so.2 | grep stdc++
    libstdc++.so.6 => <software>/GCC/4.7.2/lib64/libstdc++.so.6 (0x00002aaaacad2000)
```

Something is making `libmpi.so` pick up the `libstdc++.so.6` in `/usr/lib64` rather than the one provided by our `GCC` build. Since that version is required/used by `libmpi.so`, it also ends up being used by during `import dolfin`.

**Comment by boegel** [comment]
Also occurs on SL6...

**Comment by branfosj** [comment]
Software specific issue on an ancient operating system, so closing.
