### ISSUE TITLE
Python 2.7.x incompatible with OpenSSL 1.1.0 (Debian 9)

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-easyconfigs#5614]
When trying to use `Python-2.7.12` built against `OpenSSL-1.1.0`, errors similar to this can happen:

```
Traceback (most recent call last):
  File "/opt/easybuild/software/MPI/GCC/5.4.0-2.26/OpenMPI/1.10.3/Python/2.7.12/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[_since much has changed in `OpenSSL`_func_name] = __get_hash(__func_name)
  File "/opt/easybuild/software/MPI/GCC/5.4.0-2.26/OpenMPI/1.10.3/Python/2.7.12/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
```

The bug and the relative patch are documented here:
https://bugs.python.org/issue26470

I have successfully tested `Port-Python-2.7-s-SSL-module-to-OpenSSL-1.1.0-3.patch` on Debian 9, but additional tests are required to establish if this patch would affect installations against previous version of `OpenSSL`.

**Comment by Micket** [comment]
This is long since outdated now for many reasons (python2 being dead, openssl/1.1 wrapper, and toolchain and fixes are long since merged).
