### ISSUE TITLE
nettle needs builddep M4

### ISSUE THREAD

**Issue by michaelkarlcoleman** [easybuilders/easybuild-easyconfigs#5701]
This failed for me on `nettle/3.3-intel-2017a`, but it's probably true for all versions.  Since I was just starting out, I resolved it by installing the OS `m4` and continuing.  (Maybe most users already have the OS version installed?)

```
checking if we should use a .note.GNU-stack section... yes
checking if .align assembly directive is logarithmic... no
checking for m4... /usr/bin/m4
checking for makeinfo... not-found
checking for BF_ecb_encrypt in -lcrypto... yes
checking for library containing clock_gettime... none required
configure: creating ./config.status
config.status: creating config.make
config.status: creating config.m4
```

**Comment by Micket** [comment]
This was added to the easyconfigs in #1ed329b964c, but this issue was never closed.
