### ISSUE TITLE
Poor performance when compiling OpenMPI-* with --disable-dlopen

### ISSUE THREAD

**Issue by m0zes** [easybuilders/easybuild-easyconfigs#5716]
I reported this in the #easybuild channel earlier, and my tester just got back to me with a writeup:   We compiled OpenMPI 2.1.1 using the EasyBuild configuration
for CentOS as below and tested on Mellanox QDR hardware.

./configure --prefix=/homes/daveturner/libs/openmpi-2.1.1c
                 --enable-shared
                 --enable-mpi-thread-multiple
                 --with-verbs
                 --enable-mpirun-prefix-by-default
                 --with-mpi-cxx
                 --enable-mpi-cxx
                 --with-hwloc=$EBROOTHWLOC
                 --disable-dlopen

The red curve in the attached NetPIPE graph shows the poor performance above
8 kB for the uni-directional tests with bi-directional and aggregate
tests also showing similar problems.  When I compile using the same
configuration but with the --disable-dlopen parameter removed then the
performance is very good as the green curve in the graph shows.

![image](https://user-images.githubusercontent.com/592874/35314332-16590e9e-008b-11e8-8b4d-8c26f5cd1667.png)

We see the same problems with OpenMPI 2.0.2.
Replacing --disable-dlopen with --disable-mca-dso showed good performance.
Replacing --disable-dlopen with --enable-static showed good performance.
So it's only --disable-dlopen that leads to poor performance.

As I mentioned in the channel, it feels like an OpenMPI bug, but maybe we should think about removing --disable-dlopen from the configs

**Comment by m0zes** [comment]
It has also been reported on the OpenMPI developer's list.

https://www.mail-archive.com/devel@lists.open-mpi.org//msg20479.html

**Comment by chrissamuel** [comment]
It's worth noting that this --disable-dlopen option also breaks interoperability with Slurm for PMI2 support. Basically you're telling OMPI you can't load shared libraries and it really needs to do that for this.

We had to remove that option here today to get OMPI codes working with srun, and I wonder why this option was set in the first place?

All the best,
Chris

**Comment by akesandgren** [comment]
Just noticed in the OpenMPI users mailing list:

"did you configure Open MPI with --disable-dlopen ?
It was previously reported that this option disable the patcher (memory registration),
which impacts performance negatively. "

One more reason to not use that option probably.

**Comment by boegel** [comment]
We started using `--disable-dlopen` to fix a problem with `Rmpi` years ago, see #186 .

I'm certainly up for re-considering that, but we should assess the impact on `Rmpi` (part of the `R` easyconfigs we have).

In any case, I consider the performance of `OpenMPI` more important than the functionality of `Rmpi`, since I think `Rmpi` isn't used very much...

**Comment by akesandgren** [comment]
Rmpi was used enough here to warrant a special build to use for Rmpi.
So when we need it I see no problem adding a -Rmpi builds of OpenMPI locally at least.

With a bit of luck they could have fixed Rmpi to not need --disable-dlopen any longer... (Yeah, know I'm dreaming...)

**Comment by boegel** [comment]
Found the discussion that led to use including `--disable-dlopen` to fix the `Rmpi` issue: https://www.mail-archive.com/devel@lists.open-mpi.org/msg10852.html .

I just tried rebuilding `Rmpi` on top of `foss/2017b` after rebuilding the `OpenMPI` included in there *without* `--disable-dlopen`, and that worked just fine now, so it seems like the problem that we intend to dance around with `--disable-dlopen` has been fixed some other way.

Hence, I think it's safe to just drop the `--disable-dlopen` configure flag from the (recent) OpenMPI easyconfigs, with recent meaning all 2.x + 3.x versions, and 1.10.x (which covers `foss` toolchains until `foss/2016a`)...

**Comment by boegel** [comment]
`--disable-dlopen` dropped in recent `OpenMPI` easyconfigs in #6060, let's follow up there...
