### ISSUE TITLE
Perl DateTime >=1.36 module requires namespace::autoclean >=0.19

### ISSUE THREAD

**Issue by m0zes** [easybuilders/easybuild-easyconfigs#5820]
The DateTime module included in the following easybuilds is unusable, as the easybuild doesn't also include namespace::autoclean >= 0.19.

Perl-5.24.1-foss-2017a.eb
Perl-5.24.1-GCCcore-6.3.0.eb
Perl-5.24.1-intel-2017a.eb
Perl-5.26.0-foss-2017b.eb
Perl-5.26.0-GCCcore-6.4.0.eb
Perl-5.26.0-intel-2017b.eb
Perl-5.26.0-intel-2018.00.eb
Perl-5.26.0-intel-2018.01.eb

To get DateTime to load with Perl 5.26.0-intel-2017b, I needed the following modules, and their requisite dependencies:
cpan namespace::autoclean
cpan Devel::OverloadInfo
cpan Specio::Exporter
cpan Params::ValidationCompiler
cpan File::ShareDir

**Comment by Micket** [comment]
As these old easyconfigs have already been deprecated and removed, and the newest bundles include DateTime just fine, i believe this was fixed as some unknown point.
