### ISSUE TITLE
Python-3.6.4-foss-2018a trying to write to system location

### ISSUE THREAD

**Issue by ebirn** [easybuilders/easybuild-easyconfigs#5971]
Python install tries to write to /lib/python3.6 when running ensure pip. I have not been able to work around this yet.

see build log: https://gist.githubusercontent.com/ebirn/95c7bb64507fb1c51ecdd39196ece9d3/raw/f6182c645072d9921dedc73016b1308b848fec40/easybuild.log

Currently I assume the problem is here: https://github.com/python/cpython/blob/v3.6.4/Makefile.pre.in#L1084
Where $(DESTDIR) is not set so it tries to install to /.

I tried both (pre)installopts = 'DEST=%(installdir)s' but still get the same error.

Also the configure step:
```
== 2018-03-07 12:47:55,065 run.py:486 INFO cmd " ./configure --prefix=/net/gmi.oeaw.ac.at/software/mendel/intel-x86_64-sandybridge-avx/software/Python/3.6.4-foss-2018a  --with-threads --enable-shared  --enable-unicode=ucs4 " exited with exit code 0 and output:
configure: WARNING: unrecognized options: --enable-unicode
[...]

If you want a release build with all stable optimizations active (PGO, etc),
please run ./configure --enable-optimizations
```
I'm not familiar with the build details of python, but wondering if ~~this option is missing (even though unrelated to the above issue) and~~ the --enable-unicode should be removed.
I can open a PR for this, but I think it will take me quite some time to figure out the ensurepip problem.

Best,
Erich

**Comment by ebirn** [comment]
This was an error on SLES12 with a misconfig in the software installation user's $HOME/.pydistutils.cfg file.
The report can be disregarded, Python installations works after removing the incorrect prefix= stanza.

**Comment by boegel** [comment]
@ebirn Do you think it's worthwhile to enhance EasyBuild to detect this & warn about it?
