### ISSUE TITLE
AUGUSTUS needs an initial 'make clean' to force rebuild of binaries

### ISSUE THREAD

**Issue by tutufan** [easybuilders/easybuild-easyconfigs#6044]
Because the upstream tarball is shipped with binaries already built, a `make clean` is needed to force a rebuild.  In particular, the upstream binaries won't even run unless you happen to have matching library versions.

Something like this seems to work:

```
prebuildopts = "make clean && unset LDFLAGS && unset LIBS && "
```

**Comment by boegel** [comment]
@tutufan Please submit a pull request for the (single) existing `AUGUSTUS` easyconfig we have?

**Comment by tutufan** [comment]
Submitted PR https://github.com/easybuilders/easybuild-easyconfigs/pull/6049

**Comment by boegel** [comment]
Follow-up in #6049, thanks @tutufan!
