### ISSUE TITLE
GOOLF Toolchain OpenBLAS and core affinity is wrong with R and potentially others.

### ISSUE THREAD

**Issue by pforai** [easybuilders/easybuild-easyconfigs#605]
There is an issue at least with R when it calls into OpenBLAS, OpenBLAS sets the thread's affinity to the first cpu core (0x1) and each subsequently call into OpenBLAS does the same, so effectively builds of R that run BLAS routines are pinned to the same core. 

Not sure if this problem persists with other software that uses OpenBLAS in the same manner as R. 

The problem is fixed if OpenBLAS is recompiled with NO_AFFINITY=1, which is not set by default. This might surprise some users, especially the ones that use the multicore package in R to do data parallel computing and R is compiled with OpenBLAS.

The default ICTCE builds don't have that issue, but for them the sequential MKL is linked in in the default block.

**Comment by boegel** [comment]
Fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/916 by setting `NO_AFFINITY=1` when building OpenBLAS, so closing this.
