### ISSUE TITLE
GCCcore's use of gold by default fails on some platforms

### ISSUE THREAD

**Issue by edmondac** [easybuilders/easybuild-easyconfigs#6097]
We have a GPFS [AFM cache](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/General%20Parallel%20File%20System%20(GPFS)/page/Active%20File%20Management%20(AFM)) for some of our compute nodes. The filesystem presented by this AFM cache doesn't support [fallocate](http://man7.org/linux/man-pages/man1/fallocate.1.html)

ld.gold uses fallocate when linking - and thus a gcc or gfortran built with gold by default fails on those nodes that use the AFM cache.

The error message isn't very enlightening, but looks like this:
`...software/binutils/2.28-GCCcore-6.4.0/bin/ld.gold: fatal error: a.out: No space left on device `

The strace output is more useful:
```
[pid 32308] stat("a.out", 0x7fff5ba6b310) = -1 ENOENT (No such file or directory)
[pid 32308] open("a.out", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0777) = 25
[pid 32308] fstat(25, {st_mode=S_IFREG|0700, st_size=0, ...}) = 0
[pid 32308] fallocate(25, 0, 0, 8264)   = -1 ENOSPC (No space left on device)
```

So, my question... do we have to enable the gold linker by default in the gcc easyblock, or could we stop that? I have changed it in my local copy anyway...

**Comment by edmondac** [comment]
FYI, here's my change:
```
diff --git a/easybuild/easyblocks/g/gcc.py b/easybuild/easyblocks/g/gcc.py
index ed399eb..e2f492e 100644
--- a/easybuild/easyblocks/g/gcc.py
+++ b/easybuild/easyblocks/g/gcc.py
@@ -279,9 +279,13 @@ class EB_GCC(ConfigureMake):
         self.configopts += " --enable-shared=yes --enable-static=yes "
         # use POSIX threads
         self.configopts += " --enable-threads=posix "
-        # use GOLD as default linker, enable plugin support
-        self.configopts += " --enable-gold=default --enable-plugins "
-        self.configopts += " --enable-ld --with-plugin-ld=ld.gold"
+
+        # Use the standard linker instead of gold, due to
+        #   https://github.com/easybuilders/easybuild-easyconfigs/issues/6097
+        # EasyBuild prefers gold here, but I've disabled it. ACE 29/3/18.
+
+        # Enable plugin support
+        self.configopts += " --enable-plugins "
 
         # enable bootstrap build for self-containment (unless for staged build)
         if not self.stagedbuild:

```

**Comment by boegel** [comment]
@edmondac We can certainly avoid hard-coding `--enable-gold=default` & co, and make it optional (yet enabled by default), so you can disable it more easily (using an easyconfig parameter in your GCC easyconfigs).

**Comment by edmondac** [comment]
Sounds good!

**Comment by boegel** [comment]
Support for `use_gold_linker` custom easyconfig parameter is being added in https://github.com/easybuilders/easybuild-easyblocks/pull/1555.

Once that is included, you can avoid that `gold` is the default linker via `use_gold_linker = False`

**Comment by edmondac** [comment]
I can confirm that this works on our AFM cache - thanks!

**Comment by boegel** [comment]
Thanks for the confirmation @edmondac!

I'll go ahead and close this issue then...
