### ISSUE TITLE
NLopt tries to install plugins in matlab/octave dirs if it finds them

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-easyconfigs#6124]
found this by accident but if matlab/octave is for some reason discoverable (the executable being in the path seems to be enough) during build, NLopt tries to install plugins into their directories (and since those would not have been installed via easybuild, fails due to lack of permissions).

If the plugins are not wanted, adding `--without-matlab --without-octave` solves this issue.

If on the other hand the plugins are wanted, it seems to be possible to pass arguments to `cmake` to tell it to install the plugins somewhere else, in principle, within the NLopt install dir (and then one would tell Matlab/Octave where to find them)

**Comment by boegel** [comment]
I would add `--without-matlab --without-octave`, since neither `MATLAB` nor `Octave` are listed as dependency.

It should be obvious that needs to be removed in case people want to install `NLopt` with `MATLAB` and/or `Octave` bindings...

**Comment by boegel** [comment]
fixed in #6132
