### ISSUE TITLE
EasyBuild/3.5.3,  binutils-2.25.eb,  Sanity check failed: no file of ('lib/libbfd.a',)

### ISSUE THREAD

**Issue by pmatousu** [easybuilders/easybuild-easyconfigs#6161]
Aparently, the files ends in lib64 and not in lib, but the sanity check expect them in lib.
I am on x86_64 SLED12.2.

== FAILED: Installation ended unsuccessfully (build directory: /home/petrm/Documents/build/eb/build/binutils/2.25/dummy-): build failed (first 300 chars): Sanity check failed: no file of ('lib/libbfd.a',) in /home/petrm/opt/eb/software/binutils/2.25, no file of ('lib/libbfd.so',) in /home/petrm/opt/eb/software/binutils/2.25, no file of ('lib/libopcodes.a',) in /home/petrm/opt/eb/software/binutils/2.25, no file of ('lib/libopcodes.so',) in /home/petrm/
== Results of the build can be found in the log file(s) /tmp/eb-13vUi8/easybuild-binutils-2.25-20180417.105639.lpnEh.log
ERROR: Build of /home/petrm/opt/eb/software/EasyBuild/3.5.3/lib/python2.7/site-packages/easybuild_easyconfigs-3.5.3-py2.7.egg/easybuild/easyconfigs/b/binutils/binutils-2.25.eb failed (err: "build failed (first 300 chars): Sanity check failed: no file of ('lib/libbfd.a',) in /home/petrm/opt/eb/software/binutils/2.25, no file of ('lib/libbfd.so',) in /home/petrm/opt/eb/software/binutils/2.25, no file of ('lib/libopcodes.a',) in /home/petrm/opt/eb/software/binutils/2.25, no file of ('lib/libopcodes.so',) in /home/petrm/")

**Comment by boegel** [comment]
@pmatousu Hmm, it's surprising we haven't seen this before...

Please try with the updated `binutils` easyblocks from https://github.com/easybuilders/easybuild-easyblocks/pull/1399, as follows:

* download `binutils.py` from https://github.com/boegel/easybuild-easyblocks/blob/binutils_lib64/easybuild/easyblocks/b/binutils.py
* use `--include-easyblocks binutils.py` to instruct EasyBuild to use this updated easyblock

Please let us know whether this fixes the problem you're seeing.

**Comment by pmatousu** [comment]
It looks good. See below.

    9956 >eb binutils-2.25.eb -r --include-easyblocks /home/petrm/Documents/eb.issues/binutils.py 
    == temporary log file in case of crash /tmp/eb-exES6w/easybuild-Kw8f9n.log
    == resolving dependencies ...
    == processing EasyBuild easyconfig /home/petrm/opt/eb/software/EasyBuild/3.5.3/lib/python2.7/site-packages/easybuild_easyconfigs-3.5.3-py2.7.egg/easybuild/easyconfigs/b/binutils/binutils-2.25.eb
    == building and installing binutils/2.25...
    == fetching files...
    == creating build dir, resetting environment...
    == unpacking...
    == patching...
    == preparing...
    == configuring...
    == building...
    == testing...
    == installing...
    == taking care of extensions...
    == postprocessing...
    == sanity checking...
    == cleaning up...
    == creating module...
    == permissions...
    == packaging...
    == COMPLETED: Installation ended successfully
    == Results of the build can be found in the log file(s) /home/petrm/opt/eb/software/binutils/2.25/easybuild/easybuild-binutils-2.25-20180417.115104.log
    == Build succeeded for 1 out of 1
    == Temporary log file(s) /tmp/eb-exES6w/easybuild-Kw8f9n.log* have been removed.
    == Temporary directory /tmp/eb-exES6w has been removed.

**Comment by boegel** [comment]
Excellent, thanks for the feedback, and for reporting this issue.

We'll follow up on this in https://github.com/easybuilders/easybuild-easyblocks/pull/1399 and get it merged for inclusion in the upcoming EasyBuild v3.6.0

**Comment by pmatousu** [comment]
I thank you.
