### ISSUE TITLE
refresh versions of existing easyconfigs to XSEDE compliant ones

### ISSUE THREAD

**Issue by fgeorgatos** [easybuilders/easybuild-easyconfigs#618]
ref.
http://www.hpcwire.com/off-the-wire/xsede-distributes-tools-help-researchers/
and http://cb-repo.iu.xsede.org/xsederepo/

This is more of a work-in-progress status, for fast results, just hold your horses :-)
(ticked box implies that the task should be easily doable with existing reciPYs)
- [x]  BEDTools-2.15.0-1.el6.x86_64.rpm
- [x]  GraphicsMagick-1.3.18-2.el6.x86_64.rpm
- [x]  GraphicsMagick-c++-1.3.18-2.el6.x86_64.rpm
- [x]  ant-1.7.1-13.el6.x86_64.rpm
- [x]  arpack-3.1.3-1.el6.x86_64.rpm
- [x]  atlas-3.8.4-2.el6.x86_64.rpm
- [x]  boost-1.41.0-17.el6.x86_64.rpm
- [x]  boost-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-date-time-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-filesystem-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-graph-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-iostreams-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-program-options-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-python-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-regex-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-serialization-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-signals-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-system-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-test-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-thread-1.41.0-17.el6_4.x86_64.rpm
- [x]  boost-wave-1.41.0-17.el6_4.x86_64.rpm
- [x]  bowtie-0.12.7-2.el6.x86_64.rpm
- [x]  bwa-0.5.9-1.el6.x86_64.rpm
- [ ]  charm-6.0-0.x86_64.rpm
- [ ]  charm-debuginfo-6.0-0.x86_64.rpm
- [ ]  compat-gcc-34-g77-3.4.6-19.el6.x86_64.rpm
- [x]  espresso-ab-1.0-1.el6.x86_64.rpm
- [x]  fftw-3.2.1-3.1.el6.x86_64.rpm
- [x]  fftw2-2.1.5-21.el6.x86_64.rpm
- [ ]  flac-1.2.1-6.1.el6.x86_64.rpm
- [x]  fltk-1.1.10-1.el6.x86_64.rpm
- [x]  gcc-gfortran-4.4.7-3.el6.x86_64.rpm
- [x]  gd-2.0.35-11.el6.x86_64.rpm
- [ ]  giflib-4.1.6-3.1.el6.x86_64.rpm
- [x]  glpk-4.40-1.1.el6.x86_64.rpm
- [x]  gmp-4.3.1-7.el6.x86_64.rpm
- [x]  gnuplot-4.2.6-2.el6.x86_64.rpm
- [x]  gnuplot-common-4.2.6-2.el6.x86_64.rpm
- [x]  gromacs-4.5.7-1.el6.x86_64.rpm
- [x]  gromacs-common-4.5.7-1.el6.noarch.rpm
- [x]  gromacs-libs-4.5.7-1.el6.x86_64.rpm
- [x]  hdf5-1.8.5.patch1-7.el6.x86_64.rpm
- [ ]  infinipath-psm-3.0.1-115.1015_open.1.1.el6_4.x86_64.rpm
- [x]  java-1.7.0-openjdk-1.7.0.45-2.4.3.2.el6_4.x86_64.rpm
- [ ]  jline-0.9.94-0.8.el6.noarch.rpm
- [ ]  jpackage-utils-1.7.5-3.12.el6.noarch.rpm
- [ ]  libTAU-1.0.0-1.el6.x86_64.rpm
- [ ]  libTAU-devel-1.0.0-1.el6.x86_64.rpm
- [x]  libXfont-1.4.5-2.el6.x86_64.rpm
- [x]  libXpm-3.5.10-2.el6.x86_64.rpm
- [x]  libXtst-1.2.1-2.el6.x86_64.rpm
- [ ]  libasyncns-0.8-1.1.el6.x86_64.rpm
- [ ]  libesmtp-1.0.4-15.el6.x86_64.rpm
- [x]  libfontenc-1.0.5-2.el6.x86_64.rpm
- [x]  libgtextutils-0.6-5.el6.x86_64.rpm
- [x]  libibverbs-1.1.6-5.el6.x86_64.rpm
- [ ]  libicu-4.2.1-9.1.el6_2.x86_64.rpm
- [ ]  libogg-1.1.4-2.1.el6.x86_64.rpm
- [ ]  librdmacm-1.0.17-0.git4b5c1aa.el6.x86_64.rpm
- [ ]  libsndfile-1.0.20-5.el6.x86_64.rpm
- [x]  libtool-ltdl-2.2.6-15.5.el6.x86_64.rpm
- [ ]  libvorbis-1.2.3-4.el6_2.1.x86_64.rpm
- [x]  lua-5.1.4-4.1.el6.x86_64.rpm
- [x]  mpfr-2.4.1-6.el6.x86_64.rpm
- [x]  mpi4py-common-1.3-5.el6.noarch.rpm
- [ ]  mpi4py-mpich2-1.3-5.el6.x86_64.rpm
- [x]  mpi4py-openmpi-1.3-5.el6.x86_64.rpm
- [x]  mpich2-1.2.1-2.3.el6.x86_64.rpm
- [x]  ncl-6.0.0-3.el6.x86_64.rpm
- [x]  ncl-common-6.0.0-3.el6.noarch.rpm
- [x]  nco-4.0.5-2.el6.x86_64.rpm
- [x]  netcdf-4.1.1-3.el6.4.x86_64.rpm
- [x]  numactl-2.0.7-6.el6.x86_64.rpm
- [x]  numpy-1.4.1-9.el6.x86_64.rpm
- [x]  octave-3.4.3-1.el6.x86_64.rpm
- [x]  openmpi-1.5.4-1.el6.x86_64.rpm
- [x]  papi-4.1.3-3.el6.x86_64.rpm
- [ ]  plplot-5.9.7-3.el6.1.x86_64.rpm
- [ ]  pulseaudio-libs-0.9.21-14.el6_3.x86_64.rpm
- [x]  python-2.6.6-37.el6_4.x86_64.rpm
- [x]  qhull-2003.1-14.el6.x86_64.rpm
- [ ]  qrupdate-1.1.2-1.el6.x86_64.rpm
- [ ]  rhino-1.7-0.7.r2.2.el6.noarch.rpm
- [x]  samtools-0.1.18-2.el6.x86_64.rpm
- [x]  scalapack-common-1.7.5-17.el6.1.x86_64.rpm
- [x]  scons-2.0.1-1.el6.noarch.rpm
- [x]  sparsehash-devel-1.7-3.el6.noarch.rpm
- [x]  tcl-8.5.7-6.el6.x86_64.rpm
- [ ]  ttmkfdir-3.0.9-32.1.el6.x86_64.rpm
- [ ]  tzdata-java-2013g-1.el6.noarch.rpm
- [x]  udunits-1.12.11-1.el6.x86_64.rpm
- [x]  valgrind-3.8.1-3.2.el6.x86_64.rpm
- [ ]  wxBase-2.8.12-1.el6.centos.x86_64.rpm
- [ ]  wxGTK-2.8.12-1.el6.centos.x86_64.rpm
- [ ]  wxGTK-devel-2.8.12-1.el6.centos.x86_64.rpm
- [ ]  xorg-x11-font-utils-7.2-11.el6.x86_64.rpm
- [ ]  xorg-x11-fonts-Type1-7.2-9.1.el6.noarch.rpm

**Comment by Micket** [comment]
Long since outdated. Closing.
