### ISSUE TITLE
ParaView installation fails because of missing 'xmlpatterns' binary in Qt installation

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#6302]
Problem: installation of `ParaView-5.4.1-foss-2017b-mpi.eb` fails with:

```
[ 91%] Compiling Qt help project SurfaceLIC.qhp
cd /tmp/ParaView/5.4.1/foss-2017b-mpi/easybuild_obj/Plugins/SurfaceLIC/doc && /LUSTRE/home/patrice/easybuild/software/CMake/3.10.0-GCCcore-6.4.0/bin/cmake -E copy_directory /tmp/ParaView/5.4.1/foss-2017b-mpi/ParaView-v5.4.1/Plugins/SurfaceLIC/doc /tmp/ParaView/5.4.1/foss-2017b-mpi/easybuild_obj/Plugins/SurfaceLIC/doc
/bin/sh: line 0: cd: /tmp/ParaView/5.4.1/foss-2017b-mpi/easybuild_obj/Plugins/SurfaceLIC/doc: No such file or directory
```

https://public.kitware.com/pipermail/paraview/2017-February/039360.html suggests that this occurs because the `xmlpatterns` binary is not provided by the Qt installation being used.

It turns out that's correct: the Qt 4.8.7 provided through EasyBuild via `Qt-4.8.7-foss-2017b.eb` does not provide `$EBROOTQT/bin/xmlpatterns`.

This issue went unnoticed on our systems because `xmlpatterns` is available in the system:

```
$ which xmlpatterns
/usr/bin/xmlpatterns
$ rpm -q --whatprovides $(which xmlpatterns)
qt-devel-4.8.5-15.el7_4.x86_64
```

It seems like this can be fixed by simply configuring `Qt` to also install `xmlpatterns`, by using the `-xmlpatterns` configuration option, for example by changing the `Qt` easyconfig to include:

```python
configopts = "-xmlpatterns"
```

We should probably enable that in the `Qt` easyblock, and enhance the sanity check?

**Comment by lpouillo** [comment]
Hi @boegel, I have encounter the same issue and use the 
```
configopts = "-xmlpatterns"
```
in the Qt eb file and I succesfully built ParaView/5.4.1-foss-2017b-mpi.

Thanks

**Comment by boegel** [comment]
fixed in `Qt` easyblock with https://github.com/easybuilders/easybuild-easyblocks/pull/1437

**Comment by damianam** [comment]
I am closing the issue since the fix has been merged.
