### ISSUE TITLE
Not being able to rename extension sources on download

### ISSUE THREAD

**Issue by hajgato** [easybuilders/easybuild-easyconfigs#6326]
I was running into a problem when a main program and one of its extensions have the same filename. I solved a problem with renaming the main program source code name (using `filename` and `download_filename`), but it does not work for the extensions. In case two extensions have the same source filename, it cannot be handled without manual work (downloading and renaming extensions by hand)

**Comment by Micket** [comment]
This does work for extensions (at least now):
E.g.
```
    ('torchdata', '0.7.1', {
        'source_urls': ['https://github.com/pytorch/data/archive'],
        'sources': [{'download_filename': 'v%(version)s.tar.gz', 'filename': '%(name)s-%(version)s.tar.gz'}],
        'checksums': ['ef9bbdcee759b53c3c9d99e76eb0a66da33d36bfb7f859a25a9b5e737a51fa23'],
    }),
```
