### ISSUE TITLE
GCC 7.3.0 fails to build on CentOS 6.x

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-easyconfigs#6374]
as also seen with 8.1.0 on #6296, the solution there was to add GCC 6.4.0 as builddependency

(the issue seems to be with mpfr 4.x, where Link Time Optimization is enabled by default but not supported by the system GCC in CentOS 6.x, so an alternative solution could patch mpfr to disable LTO on CentOS 6.x)

**Comment by boegel** [comment]
I'm more in favor of adding `GCCcore` 6.4.0 as a build dependency for `GCCcore` 7.3.0, like we did for `GCCcore` 8.1.0, but I'd like to get some feedback from others on this...

It's important to get this right, since GCC 7.3 is likely to be the base for the `2018b` toolchain (I got feedback from Intel support that they are not aware of any big issues when using it with Intel compilers 2018 update 2, i.e. latest).

@geimer, @wpoely86, @akesandgren: thoughts?

**Comment by akesandgren** [comment]
I would make that a site dep only. CentOS 6 should've been scrapped long ago.

**Comment by boegel** [comment]
@akesandgren It seems CentOS 6 is still used at various sites, so I think we should do a minimal amount of effort to keep supporting it (at least in EasyBuild v3.x).

If we do include `GGCcore` 6.4.0 as a build dep for `GCCcore` 7.3.0 (like we already do for `GCCcore` 8.1.0 to be included with EasyBuild v3.6.1), we may need to find a way to break that cycle though, we don't want to have a whole stack of `GCC` installations to compile to get to the GCC we actually want...

**Comment by boegel** [comment]
Hmm, I wonder why nobody has brought that up yet... Can somebody test that? @akesandgren, @vanzod?

If so, that's certainly a problem, and a reason to consider making the use of a recent GCC conditional to only CentOS 6 somehow...

**Comment by akesandgren** [comment]
Why are you talking about 2.26 for GCC 6.4.0?? EB uses 2.28 for GCC-6.4.0...eb

**Comment by akesandgren** [comment]
Ooops, shouldn't read and reply when brain is otherwise engaged...

**Comment by vanzod** [comment]
I do not like much the solution of adding `GCCcore/6.4.0` as default dependency. Having it optional for CentOS 6 users seem a cleaner way to me. If a comment in the easyconfig file may be ignored by users, how about adding a system GCC version check in the easyblock and automatically add the `GCCcore/6.4.0` dependency if the version is too old?

**Comment by boegel** [comment]
see https://github.com/easybuilders/easybuild-easyblocks/pull/1435

**Comment by boegel** [comment]
@geimer w.r.t. compilation issues for GCC 6.4, see https://github.com/easybuilders/easybuild-easyconfigs/pull/6432

**Comment by boegel** [comment]
fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/1435
