### ISSUE TITLE
sha3 compilation failure when installing Python 3 with Intel compilers

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#6484]
(fleshed out from https://github.com/easybuilders/easybuild-easyconfigs/pull/6447)

For some people, the installation of Python 3 is partially failing with errors like:

```
Traceback (most recent call last):
File
"/home/niflheim/schiotz/easybuild/nehalem/software/Python/3.6.2-iomkl-2017b/lib/python3.6/hashlib.py",
line 121, in __get_openssl_constructor
f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_224'
```

This failure is non-fatal for the Python installation, since the Python build procedure just ignores these failures, but it leaves the installation crippled: `hashlib` is missing from the Python standard library:

```
$ python -c 'import hashlib'
ERROR:root:code for hash sha3_224 was not found.
Traceback (most recent call last):
  File "/prefix/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_224'

...
```

Relevant references:

* https://software.intel.com/en-us/forums/intel-c-compiler/topic/759078
* https://bugs.python.org/issue33174

cc @schiotz, @edmondac, @vanzod, @verdurin

**Comment by boegel** [comment]
A patch was posted on the EasyBuild mailing list by @edmondac for this (and included in #6447), cfr. https://lists.ugent.be/wws/arc/easybuild/2018-02/msg00043.html .

The changes were approved by the Python core devs in https://bugs.python.org/issue33174, except for the `-O0` being used to compile `_sha3/sha3module.c`, that was considered a blocker for the patch (rightfully so imho).

**Comment by boegel** [comment]
Turns out I wasn't seeing this issue because we have `ulimit -s unlimited` set in our systems, which dances around this problem. I was able to trigger the issue by building `Python-3.6.2-intel-2017b.eb` in an environment where the stack limit was set to a specific (low) value (e.g. using `ulimit -s 10240`).

Vice versa, @vanzod confirmed that he was able to dance around the problem by running `ulimit -s unlimited`.

**Comment by boegel** [comment]
Action plan:

* enhance the easyblock used to install `Python`:
  * also test with `import hashlib` in the sanity check
  * detect active `ulimit` setting & emit a proper warning, or try to use `ulimit -s unlimited`?

**Comment by boegel** [comment]
@schiotz @edmondac @vanzod @verdurin What does `ulimit -s` print out for you, on a system where the stack size was *NOT* set to `unlimited` either by running `ulimit -s unlimited` or `* - stack unlimited` in `/etc/security/limits.conf`?

**Comment by boegel** [comment]
I've enhanced the `Python` easyblock in https://github.com/easybuilders/easybuild-easyblocks/pull/1441 so this issue can be fixed (in most environments) by including `ulimit_unlimited = True` in the `Python` easyconfig (which results in prefixing the build command with "`ulimit -s unlimited &&`" when possible & required), and to (correctly) check whether `import hashlib` doesn't produce any errors...

**Comment by edmondac** [comment]
Yes, "ulimit -s" is 8192 on the first system I tried here. I'll check that it builds with unlimited. That's a much nicer solution!

**Comment by schiotz** [comment]
ulimit -s is also 8192 here.  This is undoubtedly the problem.

**Comment by schiotz** [comment]
@boegel 
Currently, your easyblock tests if there is a hardlimit and then emits a warning since it cannot set the stack limit to `unlimited`.  Maybe if there is a hard limit, it could set the stack limit to that limit (but still emit a warning since it *may* not be enough).

```
$ eb --include-easyblocks python.py Python-3.6.4-iomkl-2018.02.eb --rebuild
== temporary log file in case of crash /tmp/eb-jImK4K/easybuild-jtMaFw.log
== processing EasyBuild easyconfig /home/niflheim/schiotz/development/modules/iomkl-2018-02/Python-3.6.4-iomkl-2018.02.eb
== building and installing Python/3.6.4-iomkl-2018.02...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...

WARNING: Current stack size limit is 8192, and can not be set to unlimited due to hard limit of 50000000; this may break part of the compilation (e.g. hashlib)...
```

I will now test if I can build successfully with that hard limit in place (by increasing the softlimit correspondingly).

**Comment by boegel** [comment]
@schiotz Hmm, good suggestion, but I'm not sure if that'll work though, even if the stack limit is quite high. Let me know how your experiment works out.

**Comment by schiotz** [comment]
@boegel Even with this very high stack limit, compilation fails.

**Comment by schiotz** [comment]
@boegel My previous report was incorrect, I accidentally loaded the wrong module when testing.  With a stack limit of 50000000 compilation succeeds.

Perhaps you could make the easyblock use any wiggling room it has when it comes to stack size :)

**Comment by boegel** [comment]
@schiotz Done, see https://github.com/easybuilders/easybuild-easyblocks/pull/1441/commits/613eface52e60636420d1ec80b25cff7d22220d8, please test again?

I'll look into submitting a test report for your PR #6447 on top of the modified `Python` easyblock

**Comment by schiotz** [comment]
I am late, I know, but just for the record:  The lastest version works as expected.
* With a low soft limit and a high hard limit, the soft limit is raised and compilation succeeds.
* With a both limits low, compilation completes incompletely, and the sanity check fails as it should.

**Comment by boegel** [comment]
Thanks for the feedback @schiotz & co!
