### ISSUE TITLE
do not compile ParaView/VTK on /dev/shm

### ISSUE THREAD

**Issue by hajgato** [easybuilders/easybuild-easyconfigs#6541]
When I tried to install `VTK-8.1.0-foss-2018a-Python-2.7.14`, the installation failed with:
```
/dev/shm/1596678/build/VTK/8.1.0/foss-2018a-Python-2.7.14/VTK-8.1.0/ThirdParty/hdf5/vtkhdf5/src/H5detect.c:87:19: error: unknown type name ‘sigjmp_buf’
 #define H5JMP_BUF sigjmp_buf
                   ^
/dev/shm/1596678/build/VTK/8.1.0/foss-2018a-Python-2.7.14/VTK-8.1.0/ThirdParty/hdf5/vtkhdf5/src/H5detect.c:163:8: note: in expansion of macro ‘H5JMP_BUF’
 static H5JMP_BUF jbuf_g;
        ^~~~~~~~~
```

I searched the net, and I found the following webpage: https://public.kitware.com/pipermail/paraview-developers/2017-March/005202.html , where they claim that it can be solved using `gnu99` standard instead of `c99` one, but the error only occurs if the compilation is done in the memory (`/dev/shm` directory). Sounds fun, right? I can confirm this on a CentOS 7.5 System (`Linux nic170 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by akesandgren** [comment]
So, does it run out of filespace in /dev/shm? Much more likely than anything else.

**Comment by hajgato** [comment]
@akesandgren No. It is clearly a compilation error. And then I apply a patch which changes `-std=c99` to `-std=gnu99` (on the same, empty node), then it compiles without an error. Its also reproducible (at least in our systems with the above OS with nodes having CPUs AMD magnycours, buldozer and Intel ivybridge, broadwell, haswell, skylake, memory ranging from 64-256Gb)

**Comment by akesandgren** [comment]
Interesting...

**Comment by boegel** [comment]
@hajgato I assume you've opened this issue mainly to have this on record?

Or do you want to change something to prevent this from happening?

**Comment by hajgato** [comment]
@boegel No, I do not want to change, just I wanted a record (in case somebody have the same issue)

**Comment by boegel** [comment]
@hajgato OK, but then this issue can be closed?
