### ISSUE TITLE
ncurses module breaks /bin/bash

### ISSUE THREAD

**Issue by ghost** [easybuilders/easybuild-easyconfigs#655]
easybuild@hpclogin2:~> ldd /bin/bash
        linux-vdso.so.1 =>  (0x00007fff7e9ff000)
        libreadline.so.5 => /lib64/libreadline.so.5 (0x00007f9220f3b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9220d37000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f92209be000)
        libncurses.so.5 => /lib64/libncurses.so.5 (0x00007f9220776000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f92211b9000)
easybuild@hpclogin2:~> ml iomkl/6.11.106/OpenFOAM/2.2.0
easybuild@hpclogin2:~> ldd /bin/bash
        linux-vdso.so.1 =>  (0x00007fff9efff000)
        libreadline.so.5 => /lib64/libreadline.so.5 (0x00007f62e9ba7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f62e99a3000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f62e962b000)
        libncurses.so.5 => /csc/minerva/software/iomkl/6.11.106/ncurses/5.9/lib/libncurses.so.5 (0x00007f62e93c0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f62e9e26000)
        libiomp5.so => /csc/minerva/software/imkl-11.1.1.106-openmpi-1.6.5/lib/intel64/libiomp5.so (0x00007f62e90a5000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f62e8e88000)
        libimf.so => /csc/minerva/software/imkl-11.1.1.106-openmpi-1.6.5/lib/intel64/libimf.so (0x00007f62e89c0000)
        libsvml.so => /csc/minerva/software/imkl-11.1.1.106-openmpi-1.6.5/lib/intel64/libsvml.so (0x00007f62e7dc9000)
        libirng.so => /csc/minerva/software/imkl-11.1.1.106-openmpi-1.6.5/lib/intel64/libirng.so (0x00007f62e7bc2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f62e7948000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f62e7732000)
        libintlc.so.5 => /csc/minerva/software/imkl-11.1.1.106-openmpi-1.6.5/lib/intel64/libintlc.so.5 (0x00007f62e74dc000)
easybuild@hpclogin2:~> ml --force purge
sh: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory
sh: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory
sh: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory
sh: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory

**Comment by Micket** [comment]
Closing as this has long since been resolved/outdated. (This type of issue can still occur, though we go through extra effort to ensure OS compatibility as far as we can)
