### ISSUE TITLE
OpenMPI 3.1.1 might benefit from fix in https://github.com/open-mpi/ompi/pull/5374

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyconfigs#6552]
I'm doing a quick test of this to see if open-mpi/ompi#5374 is something we should include here. We've been seeing multiple codes having problems with OpenMPI getting hung.

The fix doesn't seem to be Power9 specific so I'm hoping it will fix our problems (unless 3.1.1 itself fixes it)

**Comment by boegel** [comment]
@akesandgren Any updates?

**Comment by akesandgren** [comment]
This can be ignored, my actual problem is solved by OpenMPI 3.1.1 without patches by the looks of it.
