### ISSUE TITLE
AUGUSTUS-3.3-foss-2018a.eb dependency issues

### ISSUE THREAD

**Issue by nortex** [easybuilders/easybuild-easyconfigs#6560]
Hi,

I was trying to compile AUGUSTUS-3.3-foss-2018a.eb taken from github easybuild-easyconfigs.

While trying to execute the program with:

eb AUGUSTUS-3.3-foss-2018a.eb -D --robot --debug

I get the following error:

Irresolvable dependencies encountered: zlib/1.2.11-foss-2018a, Boost/1.66.0-foss-2018a, GSL/2.4-foss-2018a, lpsolve/5.5.2.5-foss-2018a, SuiteSparse/5.1.2-foss-2018a-METIS-5.1.0, BamTools/2.5.1-foss-2018a, SQLite/3.21.0-foss-2018a, foss/2018a (at easybuild/tools/robot.py:351 in resolve_dependencies)

As i understand there is some problem with my easyconfig repository that doesn't have all those dependency easyconfings. How can i update the default easybuild repository?

Thanks.

**Comment by boegel** [comment]
@nortex Which EasyBuild version are you using here? What does `eb --show-config` produce as output?

Can you provide a full debug log for this?

**Comment by nortex** [comment]
Providing full log file:
[easybuild-HDm5jl.log](https://github.com/easybuilders/easybuild-easyconfigs/files/2173473/easybuild-HDm5jl.log)

**Comment by nortex** [comment]
Ok, i found the problem, i had an old robot path from an older version... Is there a variable that will update automatically the robot path after easybuild update?

Thanks.

**Comment by boegel** [comment]
@nortex Sorry for never answering your last question...

By default, EasyBuild will automatically have the location of the easyconfigs included with the installation in `robot-paths`, so you don't need to add it yourself.

If you want to include additional paths, you can only prepend/append to the default robot search path, see https://easybuild.readthedocs.io/en/latest/Using_the_EasyBuild_command_line.html#robot-search-path-prepend-append
