### ISSUE TITLE
Intel compiled Guile causes Meep to seg fault

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyconfigs#673]
Easyconfig guile-1.8.8-ictce-5.3.0.eb builds as a dependency of Meep-1.2-ictce-5.3.0.eb. However when running a test case of the resulting executable, there is a seg fault which is attributed to guile. It turns out this is a known issue with guile (at JSC) and previous installations of Meep here have mixed a GCC-compiled version of guile with an Intel installation.
For those wishing to test Meep, here's the contents of a sample file (simulation.ctl):

```
(set! geometry-lattice (make lattice (size 16 5 no-size)))
(set! geometry (list 
(make block (center 0 0) (size 14 1 infinity) 
(material (make dielectric (epsilon 3)))))) 
(set! pml-layers (list (make pml (thickness 1.0)))) 
(set! sources (list 
(make source (src (make continuous-src (wavelength 2))) 
(component Ez) (center -7 0)))) 
(set! resolution 10) 
(run-until 2 
(at-beginning output-epsilon) 
(to-appended "ez" (at-every 1 output-efield-z)))
```

To run it just pass the file name as a parameter to the executable when you mpirun/mpiexec.

**Comment by Micket** [comment]
Long since outdated/resolved.
