### ISSUE TITLE
Recipe to install git doesn't install manual pages & help

### ISSUE THREAD

**Issue by chrissamuel** [easybuilders/easybuild-easyconfigs#6746]
Hi there,

After a query from a user we've noticed that the EB recipe for git doesn't seem to do the extra targets needed to install the manual pages.  We've found that this change to our local recipe fixes that issue.

```
+# Necessary to install documentation
+buildopts = "doc"
+installopts = "install-doc"
```
Hope this helps!

All the best,
Chris

**Comment by boegel** [comment]
fixed in #6751
