### ISSUE TITLE
hwloc does not install on powerpc

### ISSUE THREAD

**Issue by micaeljtoliveira** [easybuilders/easybuild-easyconfigs#6833]
I'm trying to install the foss-2018a toolchain on a powerpc. The installation step of hwloc-1.11.8 is failing because the hwloc-dump-hwdata utility is not found after installation. According to the hwloc documentation  [here](https://www.open-mpi.org/projects/hwloc/doc/v1.11.8/a00292.php) this is a x86 specific tool, so it's not surprising that it's not being built in this case.

I'm not sure what is the best way to fix this. The quick and dirty fix would be to remove the sanity check. A better way would be to only check if the utility is properly installed when building on a x86 architecture. Is there a simple way to do this?

Thanks!

**Comment by akesandgren** [comment]
The simple solution is to just drop the test of that being installed. It is not important to test everything that gets installed, just enough to be sure the install didn't fail or something important is missing.

**Comment by boegel** [comment]
+1, I think it's OK to change the `hwloc` easyconfigs to stop checking for `'sbin/hwloc-dump-hwdata`.

Making this platform-aware would involve create a custom easyblock for `hwloc`, which seems like overkill to me...

@micaeljtoliveira Are you up for opening a pull request to make that change to (all, to keep it consistent) `hwloc` easyconfigs?

**Comment by micaeljtoliveira** [comment]
Ok, so I'll go for the simple solution.

> @micaeljtoliveira Are you up for opening a pull request to make that change to (all, to keep it consistent) `hwloc` easyconfigs?
Sure, will do.

**Comment by ocaisa** [comment]
Resolved with #6836
