### ISSUE TITLE
libXp is not in X11 (but should probably be)

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-easyconfigs#6861]
`libXp` is currently an stand alone module used by just 2 other easyconfigs. IMO it should be part of `X11`. I suggest to move it inside that bundle.

**Comment by damianam** [comment]
Also `printproto`

**Comment by boegel** [comment]
@damianam The existing `libXp` and `printproto` easyconfigs we have date from before we introduced the `X11` bundle, and there apparently wasn't a need up until now for `libXp` or `printproto` in the `X11` bundle.

So, I'm all for adding both.

**Comment by boegel** [comment]
fixed in #6873
