### ISSUE TITLE
XML-Parser module sanity check fails on non x86_64 systems

### ISSUE THREAD

**Issue by micaeljtoliveira** [easybuilders/easybuild-easyconfigs#6866]
The sanity check of the XML-Parser Perl module checks for the existence of the following directory:

`lib/perl5/site_perl/%(perlver)s/x86_64-linux-thread-multi/XML`

This will fail on non x86_64 systems.

This issue is somehow similar to #6833, but I don't think the same solution can be applied here, as this would result in no sanity check being performed at all. Any ideas on how to fix this?

**Comment by boegel** [comment]
Any idea what the equivalent directory looks like on e.g. POWER?

**Comment by micaeljtoliveira** [comment]
@boegel On ppc64le it looks like this 

`lib/perl5/site_perl/%(perlver)s/ppc64le-linux-thread-multi/XML`

The perl easyblock seems to have a function  `get_site_suffix` that one can use to get this information, but I have no idea how to make use of it in this case.

**Comment by mstud** [comment]
I also stumbled across this while trying to build on Power9. Is there a variable that EasyBuild provides containing the platform string (uname -i) which we could just insert here maybe?

**Comment by boegel** [comment]
We could add a constant that exposes the architecture, we already have a function in `easybuild.tools.systemtools` for this, i.e. `get_cpu_architecture`.

But how would you leverage this in an easyconfig file though?

It seems like we would need to add a custom easyblock for `XML-Parser`?

**Comment by JackPerdue** [comment]
You and your damn fetish with putting everything in an easyblock.  :)  Can't we just get an %(arch) tag that is set appropriately (e.g. ppc64 vs. x86_64) that could be used in an easyconfig?

**Comment by mstud** [comment]
@boegel As I already suggested, the "platform string" that is also output by `uname -i` is pretty generic, used in many places, and contains `ppc64le` in this case. Having this available as a template variable would be a good thing, I believe.

**Comment by micaeljtoliveira** [comment]
@mstud Just a small comment. On my powerpc, `uname -i` returns `unknow`. To get `ppc64le`, I need `uname -m`.

**Comment by boegel** [comment]
@mstud @micaeljtoliveira Is `ppc64le` included in the output of `python -c "from platform import uname; print uname()"` for you (please share the output you get)?

**Comment by mstud** [comment]
@boegel Yes it is:
`('Linux', 'ml5', '4.14.0-49.13.1.el7a.ppc64le', '#1 SMP Mon Aug 27 07:37:11 EDT 2018', 'ppc64le', 'ppc64le')`

**Comment by micaeljtoliveira** [comment]
@boegel Here is the result on my system:
`('Linux', 'mpsd-srv-ppc-001', '4.9.0-6-powerpc64le', '#1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02)', 'ppc64le', '')
`

**Comment by boegel** [comment]
Support for `%(arch)s` template is implemented in https://github.com/easybuilders/easybuild-framework/pull/2728, should go in in time for EasyBuild 3.8.1 .

Anyone up for following up on that by changing `sanity_check_paths` in the `XML-Parser` easyconfigs accordingly?

**Comment by JackPerdue** [comment]
It's not just XML-Parser:

find $EBROOTEASYBUILD -name \*.eb | xargs grep x86_64 | grep dirs

Could you add a test in the pull request approval scripts (e.g. --check-style) that at least alerts to architecture specific code like that (or just rejects it unless they use %(arch))?????

**Comment by boegel** [comment]
@JackPerdue We can certainly start working on that, but I doubt it'll be as simple as replacing `x86_64` with `%(arch)s` everywhere... Although it won't change much on `x86_64` systems, of course.

**Comment by boegel** [comment]
Hardcoding in `XML-Parser` easyconfigs fixed in #7450

**Comment by boegel** [comment]
Closing this since the problem originally reported here is fixed with #7450, to be included in EasyBuild v3.8.1.

Other similar instances can be fixed via separate pull requests.
