### ISSUE TITLE
modloadmsg without trailing newline printed poorly

### ISSUE THREAD

**Issue by zao** [easybuilders/easybuild-easyconfigs#6968]
As reported and forgotten in #4013, if the recipe specifies a `modloadmsg = "like this"`, when loading the generated module the shell prompt may be printed on the same line as the last line of the module load message.
We should probably pad the message with a trailing newline if there is none to begin with to avoid this.

(Edit: sorry for posting this in easyconfigs, thought I was reporting against framework)

**Comment by boegel** [comment]
Fix for this is in https://github.com/easybuilders/easybuild-framework/pull/2613

I also fixed the problem where the 2nd to last lines of a multi-line module load message were being indented, i.e. using `modloadmsg = "one\two\nthree"` lead to output like:

```
$ ml test
one
    two
    three$
```

whereas now it'll give what you'd expect:

```
$ ml test
one
two
three
$
```

**Comment by boegel** [comment]
fixed in https://github.com/easybuilders/easybuild-framework/pull/2613, thanks for the reminder @zao!
