### ISSUE TITLE
Add CMake support to Eigen

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#6981]
I see the following error when trying to build an application using the `Eigen` module built with EB:
```
CMake Error at CMakeLists.txt:146 (FIND_PACKAGE):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
```
This appears to be because the `share` directory is not included when building `Eigen`.
That directory includes:
`Eigen3Config.cmake  Eigen3ConfigVersion.cmake  Eigen3Targets.cmake  UseEigen3.cmake`
which would then be found by `CMake` in the application.

**Comment by boegel** [comment]
@verdurin Which CMake & Eigen versions are being used here?

Also, how was `Eigen` installed, was that done using `CMake`? Cfr. #6756

**Comment by verdurin** [comment]
Closing this because a rebuild with up to date easyblocks and a fix to the local easyconfig has fixed the omission.
