### ISSUE TITLE
Qt5-5.10.1-foss-2018a with EB 3.7.1: no file found at 'lib/libQt5WebEngine.so' 

### ISSUE THREAD

**Issue by sassy-crick** [easybuilders/easybuild-easyconfigs#7166]
Dear all,

whilst building Qt5-5.10.1-foss-2018a with EB 3.7.1 I get this error message:
Sanity check failed: no file found at 'lib/libQt5WebEngine.so' 

I managed to build Qt5-5.10.1-foss-2018a by removing the line:
check_qtwebengine = True
from the easybuild file but this might have unintended consequences.

The log file can be found here:
https://gist.github.com/sassy-crick/8580d3715175cba12e04b0d64d304195

Let me know if you require more information.

Regards

Jörg

**Comment by boegel** [comment]
@sassy-crick Can you check whether this problem is fixed by adding `gperf` as a dependency, as was done in #7086?

That change is not included yet in the easyconfigs that are included with EasyBuild 3.7.1...

**Comment by sassy-crick** [comment]
@boegel I have added ('gperf', '3.1'), as outlined in  #7086 and that is working now for me. 
Thanks for your help and sorry for the slow reply!
