### ISSUE TITLE
Molden-5.8-foss-2018a.eb: checksum incorrect

### ISSUE THREAD

**Issue by tardigradus** [easybuilders/easybuild-easyconfigs#7223]
Looks like the checksum has changed - again :-(

Was: a17bac0901f279e0d89aaf15174875e0695ad7596c5878233946b438d09d93b7
Is: d9dbfbe2430890e2e9bd0c81625d76d97221daba91c318cc47196c87cc72f217

**Comment by boegel** [comment]
Confirmed, I'm seeing the same thing... Someone should slap these people with a large trout.

**Comment by boegel** [comment]
Fixed in #7251
