### ISSUE TITLE
cp2k: change of download location of source code

### ISSUE THREAD

**Issue by sassy-crick** [easybuilders/easybuild-easyconfigs#7239]
The download location for the cp2k source code has changed from the source forged webpage to github:
https://github.com/cp2k/cp2k/releases
I would be good to change that in the easybuild-files as well. 
I was testing this with Easybuild version 3.7.1.
Thanks!

**Comment by sassy-crick** [comment]
Great! Thanks for doing this!

**Comment by boegel** [comment]
fixed in #7240
