### ISSUE TITLE
libUUID problems

### ISSUE THREAD

**Issue by hajgato** [easybuilders/easybuild-easyconfigs#7253]
Regardigto the `libUUID` issue in #6962 which is solved in #6963, it is mentioned that the `X11` stack need not to be recompiled. Well, if `X11` a dependency, and a software uses `libtool` the problem persists, because it might* find the old `libUUID/lib/libuuid.{a,so}` library. Either `X11` and deps  using `libtool` should be recompiled, or the `.la` files should be modified accordingly.

Just had to recompile `cairo`, for example. 

`libXmu`, `libXaw`, `libXft`, and `libXt` for sure affected, if those are not used,then even using `libtools` will not be a problem.

**Comment by boegel** [comment]
@hajgato What kind of errors were you running into exactly here?

While building `Pango-1.42.4-foss-2018b.eb` from #7255, I ran into these problems:

```
/prefix/software/fontconfig/2.13.0-GCCcore-7.3.0/lib/libfontconfig.so: error: undefined reference to 'uuid_copy', version 'UUID_1.0'
/prefix/software/fontconfig/2.13.0-GCCcore-7.3.0/lib/libfontconfig.so: error: undefined reference to 'uuid_generate_random', version 'UUID_1.0'
/prefix/software/fontconfig/2.13.0-GCCcore-7.3.0/lib/libfontconfig.so: error: undefined reference to 'uuid_unparse', version 'UUID_1.0'
/prefix/software/fontconfig/2.13.0-GCCcore-7.3.0/lib/libfontconfig.so: error: undefined reference to 'uuid_parse', version 'UUID_1.0'
30859 collect2: error: ld returned 1 exit status
```

The fix was indeed to rebuild `cairo-1.14.12-GCCcore-7.3.0.eb` after `fontconfig-2.13.0-GCCcore-7.3.0.eb` was rebuilt with the fix from #6963 .

**Comment by hajgato** [comment]
@boegel Yes, I got those. The problem that `libtools`  picks up the "old" libuud (from libUUID) from the `.la` files. (so the errors are the same as in PR #6962)

**Comment by boegel** [comment]
@hajgato Anything left to do with this? I think it's good to have this "on record", but it's clear now how to fix the problem, so this issue can be closed?
