### ISSUE TITLE
Software needs to build with MesonNinja will clash with Python2

### ISSUE THREAD

**Issue by hajgato** [easybuilders/easybuild-easyconfigs#7254]
`MesonNinja` only works with `Python3`, so anything needs `Python2` will not be able to be built. 
For example `ATK 2.30.0` and `Gdk-Pixbuf 2.38.0` have to be build with `MesonNinja`, and with `GObject-introspection`, which only works with `Python2`

**Comment by Micket** [comment]
Fortunately, python2 is now dead. Hurray!
