### ISSUE TITLE
ImageMagick source download

### ISSUE THREAD

**Issue by sassy-crick** [easybuilders/easybuild-easyconfigs#7274]
Downloading the source tarball from 
https://www.imagemagick.org/download/releases/
means that version 7.0.7-30 from the distributed easybuild file could not been downloaded as it does not exist there. 
However, it does exist on Github.
I suggest the following changes in the 
ImageMagick-7.0.7-30-GCCcore-6.4.0-Ghostscript-9.22-cairo-1.14.12.eb file:

---  source_urls = ['https://www.imagemagick.org/download/releases/']
+++ source_urls = ['https://github.com/ImageMagick/ImageMagick/archive/']

--- sources = [SOURCE_TAR_GZ]
+++sources = ['%(version)s.tar.gz']

--- checksums = ['8d3aca87b13dc1c17d28f83326201529e5a2936e9b8ee289377a247c615f272c']
+++ checksums = ['dd98d9e1bab678b7e86b292b7903b2f357d01a5ee4932883d816cebea5d43c94']

Note: the downloaded filename also changed from ImageMagick-7.0.7-30.tar.gz to 7.0.7-30.tar.gz

This way, we might avoid future problems, hopefully.

Jörg

**Comment by sassy-crick** [comment]
@boegel I noticed the change of the checksum but decided to ignore it as it comes from an official repository. Shame they don't provide the checksum on the webpage. 

I will contact them and see what they reply.

**Comment by boegel** [comment]
@sassy-crick Please include a reference to the issue you open in here.

**Comment by sassy-crick** [comment]
@boegel thanks for reminding me, I will.

**Comment by sassy-crick** [comment]
I posted this on the ImageMagick forum:
https://imagemagick.org/discourse-server/viewtopic.php?f=2&t=35150

**Comment by sassy-crick** [comment]
I posted this on the ImageMagick forum:
https://imagemagick.org/discourse-server/viewtopic.php?f=2&t=35150

**Comment by boegel** [comment]
@sassy-crick Can this be closed since #7301 is merged?

**Comment by sassy-crick** [comment]
@boegel Yes, please close it. Thanks!
