### ISSUE TITLE
Doxygen: URL to download source

### ISSUE THREAD

**Issue by sassy-crick** [easybuilders/easybuild-easyconfigs#7280]
The URL to download the source tarball for doxygen is no longer working:
http://ftp.stack.nl/pub/users/dimitri/
The domain ftp.stack.nl does not resolve any more. 

It might be a good idea to move either to the Sourceforge one:
https://sourceforge.net/projects/doxygen/files/
or directly from Doxygen:
doxygen.nl/files

I leave that up to the developers. 

Thanks!

**Comment by willfurnass** [comment]
@sassy-crick In PR #7324 I've proposed using `doxygen.nl/files`.

**Comment by boegel** [comment]
@sassy-crick The tests in #7324 are complaining because there are no checksums included in the Doxygen easyconfigs, not because they don't match (this is not checked automatically)

**Comment by boegel** [comment]
Fixed in #7324, thanks @willfurnass!
