### ISSUE TITLE
fix the download URL for pigz-2.3.4-GCCcore-6.4.0.eb

### ISSUE THREAD

**Issue by murfreesboro** [easybuilders/easybuild-easyconfigs#7338]
The download link in pigz-2.3.4-GCCcore-6.4.0.eb does not exist anymore. However, I found the pigz 2.3.4 is available through the author's github page: https://github.com/madler/pigz/releases/tag/v2.3.4 . Please fix the url.

**Comment by boegel** [comment]
The source tarball served via GitHub is not perfectly equivalent (different SHA256 checksum).

I've contacted the author (@madler) to ask if the source tarballs for the old `pigz` releases are still available for download somewhere else...

**Comment by madler** [comment]
https://zlib.net/pigz/fossils/ has all the old versions.

**Comment by boegel** [comment]
Thank you very much for the feedback @madler!

Fixed in #7346

**Comment by boegel** [comment]
#7346 is merged to be included in EasyBuild v3.8.1, so closing this...
