### ISSUE TITLE
R-3.5.0-iomkl-2018a-X11-20180131.eb build fails because of clValid_0.6-6.tar.gz checksum

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#7472]
R-3.5.0-iomkl-2018a-X11-20180131.eb build fails because of clValid_0.6-6.tar.gz checksum.

How do we go along?  I just submit a PR with an updated checksum?
Joachim

**Comment by boegel** [comment]
@jhein32 Checksums look OK to me for a fresh download:

```
$ curl -OL https://cran.r-project.org/src/contrib/clValid_0.6-6.tar.gz

$ sha256sum clValid_0.6-6.tar.gz
c13ef1b6258e34ba53615b78f39dbe4d8ba47b976b3c24a3eedaecf5ffba19ed  clValid_0.6-6.tar.gz
```

Are you seeing something different?

For genuine upstream checksum changes, we should:

* fix the checksum in all affected `R` easyconfigs
* complain to the package author about the in-place update (ideally)

**Comment by jhein32** [comment]
@boegel Thanks for looking into this.  Following your message, I "fixed" the clValid, to get the same issue with another extension package.  I renamed the folder with the extension sources, which forced EB into recreating the folder for the extensions and downloading everything again.  Now it builds an R installation.

Not sure what happened, why I got files with wrong checksums when I did the original download.  I would go along with closing this and having a deeper look in case we get more issue reports like this.  The question would be, how do we memorise this for the day such a report comes?

J.

**Comment by boegel** [comment]
@jhein32 You could have just used ` --force-download` to make EasyBuild re-download all requires sources.

If this happens again, please make sure the downloads are actually tarballs (and not HTML files or similar), by running `file` on them. EasyBuild can/should do that for you and properly report an error, but nobody has implemented a check like that yet.

Someone will (hopefully) remember this issue when a similar problem pops up in the future (it should pop up when searching for `checksum` in any case).
