### ISSUE TITLE
Fix OpenFOAM-v1812-cleanup.patch (develop branch)

### ISSUE THREAD

**Issue by guest1604** [easybuilders/easybuild-easyconfigs#7486]
There is an error in `OpenFOAM-v1812-cleanup.patch` file (develop branch) : https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1812-cleanup.patch

In order to build ParaView plugins to use paraFoam, we have to replace :
`+#ParaView_VERSION=$EBVERSIONPARAVIEW`
by :
`+ParaView_VERSION=$EBVERSIONPARAVIEW`

```
$ diff -Nru OpenFOAM-v1812-cleanup.patch_20190124 OpenFOAM-v1812-cleanup.patch
--- OpenFOAM-v1812-cleanup.patch_20190124	2019-01-22 13:10:01.000000000 +0100
+++ OpenFOAM-v1812-cleanup.patch	2019-01-24 07:25:18.000000000 +0100
@@ -249,7 +249,7 @@
  
 -ParaView_VERSION=5.6.0
 +##Easybuild## settings
-+#ParaView_VERSION=$EBVERSIONPARAVIEW
++ParaView_VERSION=$EBVERSIONPARAVIEW
  ParaView_QT=qt-system
  cmake_version=cmake-system
  
```

**Comment by boegel** [comment]
Ah, I misread the description. The issue wasn't that `paraFoam` were missing, but that the ParaView plugins were missing.

Where are those located @guest1604, can you give an example?

**Comment by guest1604** [comment]
This directory were missing : `$EBROOTOPENFOAM/OpenFOAM-v1812/platforms/linux64GccDPInt32Opt/lib/paraview-5.4`. This is the `PV_PLUGIN_PATH`.

So `paraFoam` didn't launch ParaView :

```
$ paraFoam
Cannot use ParaView reader module library (PVFoamReader)
The PV_PLUGIN_PATH environment value is not set
Continuing with builtin reader:  paraFoam –vtk
```
