### ISSUE TITLE
snappy missing shared library

### ISSUE THREAD

**Issue by renatopancheri** [easybuilders/easybuild-easyconfigs#7502]
All of `snappy` easyconfig files build only the static library,
i've encountered a software that needs the shared library so i've added:
`configopts = ' -DBUILD_SHARED_LIBS=ON'`
to the snappy easyconfig but this way static library does not get built.
Looking at the code of snappy there is no param to build both,
i tried `-DBUILD_STATIC_LIBS=ON` but it gets ignored.
Is there a way to build both static and shared lib changing only easyconfig file
without creating custom easyblock?

**Comment by boegel** [comment]
We're building both shared and static libraries in all recent `snappy` easyconfigs, so closing this...
