### ISSUE TITLE
nwchem and libibumad-dev on centos 7.5

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#7526]
HI,

I am currently trying to install the NWchem NWChem-6.8.revision47-intel-2018a-2017-12-14-Python-2.7.14.eb on centos 7.5.

The build fails because of the os dependencies::
`One or more OS dependencies were not found: [('libibumad-dev', 'libibumad-devel')]`
We have the "non-dev" version on our cluster, but yum seems unavailable to locate a dev or devel version of the package.  Any comments/hints?

Thanks
   Joachim

**Comment by jhein32** [comment]
Hi,

One of my colleagues came back saying this should be included in rdma-core-devel, which have installed.  I can check in the next days whether we can build against rdma-core-devel.  I would need some help with syntax on how to provide a PR to fix the issue.

**Comment by akesandgren** [comment]
See for instance latest openmpi easyconfig

**Comment by jhein32** [comment]
Your suggestions is of remover the libibumad alltogether?  The openmpi easyconfigs do not reference this.

**Comment by akesandgren** [comment]
No, it's just an example of how a trippel osdep looks like.
In your case it should probably be
('libibumad-dev', 'libibumad-devel', 'rdma-core-devel')

**Comment by Micket** [comment]
Åkes suggestion is how osdeps should be handled. Also, newer NWChem's seem to not have any of them (or it was moved into the easyblock, regardless it is not an issue anymore)
