### ISSUE TITLE
MATLAB does not use the Java dependency defined in the easyconfig

### ISSUE THREAD

**Issue by smoors** [easybuilders/easybuild-easyconfigs#7574]
MATLAB/2017a uses the JVM shipped with MATLAB and not the Java that is loaded:
```
>> version -java

ans =

    'Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'
```

We should either remove the Java dependency in the easyconfig or set this env var:
export MATLAB_JAVA=$EBROOTJAVA/jre

**Comment by vanzod** [comment]
I confirm this issue. The same happens in our `MATLAB` installation and using the `MATLAB_JAVA` environment variable works.

**Comment by akesandgren** [comment]
We dropped the Java dep for MATLAB a while back.

**Comment by boegel** [comment]
If there's no significant benefit in using an external Java, I think dropping the dependency and just letting MATLAB use the one it ships makes most sense...

**Comment by vanzod** [comment]
Are there any security concerns of using the internal Java instead of the latest and greatest?

**Comment by boegel** [comment]
@vanzod I guess that would be the main reason we could come up with to use an external Java.

But under the assumption that MATLAB is installed with user permissions, I'm not sure how big of a problem an outdated Java internal to MATLAB is.

**Comment by vanzod** [comment]
And we can always blame it on `MATLAB`. Sounds good to me.
I will go ahead and purge out the Java dependencies from the existing easyconfig files.

**Comment by Micket** [comment]
This is long since resolved. All recent MATLAB easyconfigs have dropped Java (or never included it in the first place)
