### ISSUE TITLE
Python-3.6.4-golf-2018a.eb considered harmful?

### ISSUE THREAD

**Issue by mstud** [easybuilders/easybuild-easyconfigs#7809]
Hi all, we are using --minimal-toolchains by default, and since the introduction of a Python easyconfig that is built with the golf toolchain in #6080, this get's picked up as a dependency for every Python dep because it is more minimal than foss. However, some software requires mpi4py (e.g. Trilinos) which is obviously missing from this Python-golf installation, and this has caused us a lot of trouble.  Maybe this has not been considered when this new EasyConfig was introduced?

**Comment by boegel** [comment]
Thoughts on this @bartoldeman?

@mstud Does `--use-existing-modules` help?

**Comment by Micket** [comment]
Yes having save packaes at multiple toolchain levels is going to be painful. We don't do this with any package (i think) nowadays, and I wouldn't merge a PR that did this. The python in this PR is now deprecated (as well as the toolchain itself), so i will just close this issue.
