### ISSUE TITLE
xorgproto replacing *proto in X11 package

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-easyconfigs#7872]
`xorgproto` (https://gitlab.freedesktop.org/xorg/proto/xorgproto) replaces all the `*proto` packages used in the `X11` easyconfig. Will be handy for the next update

**Comment by Micket** [comment]
I did so in #7874
I suspect that xcb-proto is not part of xorgproto though so I still kept that one.

**Comment by boegel** [comment]
@damianam Can this be closed since `xorgproto` is used in #7874?

**Comment by damianam** [comment]
Yes. Actually I used it already in our setup.
