### ISSUE TITLE
SQLite-3.20.1-GCCcore-6.4.0 'rl_completion_matches' build error

### ISSUE THREAD

**Issue by patbel-pwr** [easybuilders/easybuild-easyconfigs#7942]
EB 3.8.1
while trying to build SQLite with command:
`eb SQLite-3.20.1-GCCcore-6.4.0.eb --robot --debug`
on Scientific Linux 6.10

I encountered 'rl_completion_matches' error which is in logs:
[sqllite-3.20.log](https://github.com/easybuilders/easybuild-easyconfigs/files/2996036/sqllite-3.20.log)

Modyfing SQLite-3.20.1-GCCcore-6.4.0.eb file by adding:
`configopts = "--disable-editline"`
solved the issue for me.

**Comment by Micket** [comment]
This is long since deprecated toolchain so it's hard for anyone to ever test this again. I haven't seen anyone having problems with recent up to date version, so I'm assuming the problems are no longer present.
