### ISSUE TITLE
open-mpi.org links broken

### ISSUE THREAD

**Issue by patbel-pwr** [easybuilders/easybuild-easyconfigs#7943]
EB 3.8.1
Scientific Linux 6.10

while building Rosetta-3.7-foss-2016b.eb I've encountered few openmpi dependencies download problems:

1. HWLOC
"build failed (first 300 chars): Couldn't find file hwloc-1.11.3.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /usr/local/easybuild/python-2.7.15-gcc7.4.0/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.8.1-py2.7.egg/easybuild/easyconfigs/h/hwloc/h/hwloc/hwloc-1.1"

.eb file looks for:
source_urls = ['http://www.open-mpi.org/software/hwloc/v%(version_major_minor)s/downloads/']

correct address is: 
https://download.open-mpi.org/release/hwloc/v1.11/hwloc-1.11.3.tar.gz

2. OPENMPI
ERROR: Build of /usr/local/easybuild/python-2.7.15-gcc7.4.0/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.8.1-py2.7.egg/easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-GCC-5.4.0-2.26.eb failed (err: "build failed (first 300 chars): Couldn't find file openmpi-1.10.3.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /usr/local/easybuild/python-2.7.15-gcc7.4.0/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.8.1-py2.7.egg/easybuild/easyconfigs/o/OpenMPI/o/OpenMPI/ope")

.eb file looks for:
source_urls = ['http://www.open-mpi.org/software/ompi/v%(version_major_minor)s/downloads']
correct address is: 
https://download.open-mpi.org/release/open-mpi/v1.10/openmpi-1.10.3.tar.gz

regards,
Patryk.

**Comment by boegel** [comment]
Yeah, we should really get rid of these `http://` URLs.

The fact that we now require checksums in all easyconfig files we touched makes this a bit painful though...

**Comment by boegel** [comment]
Fixed in #8013, #8014, #8015, #8016, so closing this.

Thanks again for reporting this @patbel-pwr!
