### ISSUE TITLE
Wannier90: Checksum verification fails and build stops

### ISSUE THREAD

**Issue by patbel-pwr** [easybuilders/easybuild-easyconfigs#7944]
Hi, 

EB 3.8.1

build of  Wannier90-2.1.0-intel-2017b.eb ends up with checksum verification error. Same applies if you download file from wannier website and put it in sources. 

Moreover, when I added `--ingore-checksum` to cmd, build stopped with error complaining that it can't extract file, as it is not a gzipped archive, which is true: 
`> file wannier90-2.1.0.tar.gz
 wannier90-2.1.0.tar.gz: POSIX tar archive (GNU)`

Workaround:
I had to untar original file:
`tar xvf wannier90-2.1.0.tar.gz`
and tar it again with compression:
`tar -czf wannier90-2.1.0.tar.gz wannier90-2.1.0`
and finally copy the result .tar.gz file to EB sources dir to 'sources' dir and execute:
`eb Wannier90-2.1.0-intel-2017b.eb --robot --debug --ignore-checksum`

Excuse me for not providing logs, I accidentaly overwritten them with correct build log. 

Regards,
Patryk.

**Comment by Micket** [comment]
This sounds like it was really only ever an issue with the website not providing the sources correctly. Whatever it might have been, it's long since outdated and hasn't shown itself to be an issue anymore. Closing.
