### ISSUE TITLE
where to download the l_mpi_2017.1.132.tgz

### ISSUE THREAD

**Issue by upuil** [easybuilders/easybuild-easyconfigs#7949]
I try to install `netCDF-4.4.1.1-intel-2017a-HDF5-1.10.1.eb` but can't download the require file.

**Comment by boegel** [comment]
You need to download Intel MPI from Intel, see https://software.intel.com/en-us/mpi-library.

And then put this tarball in the EasyBuild "source path", so EasyBuild can find it (it won't try to download it in that case); see also https://easybuild.readthedocs.io/en/latest/Configuration.html#sourcepath

**Comment by upuil** [comment]
Thank you, another question: I also can't download single icc or ifor, only can download the fully package.

**Comment by boegel** [comment]
The tarballs for the single components are publicly downloadable, see for example https://github.com/jeffhammond/HPCInfo/blob/master/buildscripts/icc-release.sh

**Comment by Flamefire** [comment]
Note for anyone else searching for this: It is no longer available on the Intel website, only newer versions are.

**Comment by hkhorasani** [comment]
I'm also looking for l_mpi_2017.1.132.tgz
I will also need some other packages for Intel 2017.1.132 that I google them hoping to find them in some corner of web! can somebody help us by providing a link to this software?

**Comment by hkhorasani** [comment]
here is the link for future users:
https://registrationcenter-download.intel.com/akdlm/irc_nas/ZArchive/11014/l_mpi_2017.1.132.tgz
