### ISSUE TITLE
CUDA-aware OpenMPI 4.0.0 linking to libcudart

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#8071]
Hi,

I just adapted an (older) easyconfig file to install OpenMPI/4.0.0-GCC-6.4.0-2.28 together with CUDA/10.1.105. However, when I check the libraries linked against e.g. mpicc, I see that libcuart.so.10.1 is correctly linked, but at the bottom of the list , libcudart.so.10.0 is not found, which is expected (some paths are truncated):

```
**$> 4.0.0-GCC-6.4.0-2.28-CUDA-10.1.105$ ldd bin/mpicc
        linux-vdso.so.1 =>  (0x00007ffdfbb06000)
        libopen-pal.so.40 => /software/OpenMPI/4.0.0-GCC-6.4.0-2.28-CUDA-10.1.105/lib/libopen-pal.so.40 (0x00002b9ae01f5000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00002b9ae03f5000)
        libutil.so.1 => /usr/lib64/libutil.so.1 (0x00002b9ae05fd000)
        libhwloc.so.15 => /software/hwloc/2.0.2-GCCcore-6.4.0/lib/libhwloc.so.15 (0x00002b9ae02cd000)
        libpciaccess.so.0 => /software/libpciaccess/0.14-GCCcore-6.4.0/lib/libpciaccess.so.0 (0x00002b9ae0319000)
        libcudart.so.10.1 => /software/CUDA/10.1.105/lib64/libcudart.so.10.1 (0x00002b9ae0800000)
        libxml2.so.2 => /software/libxml2/2.9.7-GCCcore-6.4.0/lib/libxml2.so.2 (0x00002b9ae0a7c000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00002b9ae0be4000)
        libz.so.1 => /usr/lib64/libz.so.1 (0x00002b9ae0de8000)
        liblzma.so.5 => /software/XZ/5.2.3-GCCcore-6.4.0/lib/liblzma.so.5 (0x00002b9ae0325000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00002b9ae0ffe000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00002b9ae1300000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00002b9ae151c000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b9ae01d1000)
        libcudart.so.10.0 => not found**
```

So, I'm wondering whether this is an expected linking?

The problem is when I build a simple MPI+CUDA application ("simpleMPI" from the CUDA/10.1.105 samples), I get an error like the following: 

```
**$> make
/software/OpenMPI/4.0.0-GCC-6.4.0-2.28-CUDA-10.1.105/bin/mpicxx -I../../common/inc
   -stdlib=libstdc++ -o simpleMPI_mpi.o -c simpleMPI.cpp
/software/OpenMPI/4.0.0-GCC-6.4.0-2.28-CUDA-10.1.105/bin/mpicxx: error while loadin
g shared libraries: libcudart.so.10.0: cannot open shared object file: No such file or directory
make: *** [simpleMPI_mpi.o] Error 127**
```

I am also attaching the easyconfig file I used.

How can I exclude the dependency on libcudart.so.10.0 from the MPI compilers?

Thanks for your support,
Ehsan

[OpenMPI-4.0.0-GCC-6.4.0-2.28.eb.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3079571/OpenMPI-4.0.0-GCC-6.4.0-2.28.eb.zip)

**Comment by boegel** [comment]
@akesandgren Any ideas on this? Is this the same problem as you were hitting with TensorFlow because `*.so*` files in CUDA 10.1 were renamed?

**Comment by akesandgren** [comment]
No, nothing similar here. This is likely a problem with some of the libs in the ldd output above having been force linked to libcudart.10.0

Use objdump -x on each of them in turn (and start with mpicc) and check where that libcudart.so.10.0 actually comes from.

Our /hpc2n/eb/software/Compiler/GCC-CUDA/8.2.0-2.31.1-10.1.105/OpenMPI/3.1.3/bin/mpicc only lists libcudart.so.10.1

**Comment by boegel** [comment]
@akesandgren This must be a problem in OpenMPI itself, right? All we are doing is specifying where it is installed via `--with-cuda=$EBROOTCUDA`.

@moravveji Have you tried with OpenMPI 4.0.1 to see if that release includes a fix for this?

Maybe try reporting this via https://github.com/open-mpi/ompi/issues, I don't see how this could be a problem in EasyBuild, especially since `OpenMPI` is built with the `ConfigureMake` easyblock (which doesn't know about `CUDA` at all), and you're using a toolchain that doesn't include `CUDA` (so it can't be an issue in EasyBuild framework either).

**Comment by akesandgren** [comment]
I think it's more like a leftover from a previous use of CUDA 10.0 building hwloc.
Esp check hwloc since that might be cuda aware too.

**Comment by moravveji** [comment]
@akesandgren: thanks for the hints; Firstly, I stepped down from OpenMPI/4.x to v. 3.1.4, and I immediately noticed a prograss. Secondly, my hwloc was indeed built against cuda. So, I reinstalled hwloc from source without cuda. As a result of this, now I can built OpenMPI with or without hwloc/UCX/CUDA, and I am ready to begin testing them.
closing this ticket for now
