### ISSUE TITLE
Lets merge icc and ifort and just have iccifort

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#8082]
I didn't spot any other issues for this, other then easybuilders/easybuild-framework#1076
Rather then trying to fix that, can't we just use iccifort instead?
It doesn't look like intel will be splitting the release schedule for them anymore.
Starting with 2019b maybe?

With HMNS, it's particularly bad to have them split. It lets users load just the icc to get access to modules. But this leads to broken software, as anything built with ifort requires the user to load ifort as well.
Worse yet, `module spider` actually gives these this as a suggestion (as it just tells you what is needed to load the module).

I have been manually modifying my old modules, moving the modulepath into the iccifort module instead, but that's tedious, and ugly, and a bit fragile (it i ever had to rebuilt modules etc.)

**Comment by bartoldeman** [comment]
I would be happy with that, but in a conversation with @ocaisa he mentioned that Intel can sell icc and ifort separately. You can actually get "Intel System Studio" for free (with some strings attached) but that only includes C and C++, not Fortran.

Both FZ Julich and us at Compute Canada use a custom HMNS where icc and ifort modules are hidden dependencies of iccifort and only the iccifort module (renamed to intel, but that is an implementation detail) extends `$MODULEPATH`

**Comment by akesandgren** [comment]
Could you share that HMNS def?

**Comment by Micket** [comment]
@bartoldeman I suppose we don't need to remove the individual `icc`, `ifort` (if someone else really wants it)?
Just make `iccifort` standalone. Because, anyone who gets just `icc` or `ifort` standalone, would have to construct their own toolchains. It wouldn't be of `intel`-ish toolchains anymore anyway.

My manual fiddling with configs, got me into trouble when building intelcuda/2019a (which prompted me to write this issue).

**Comment by bartoldeman** [comment]
@akesandgren 
The Julich MNS is here:
https://github.com/easybuilders/JSC/tree/master/Custom_MNS
Compute Canada's is here:
https://github.com/ComputeCanada/easybuild-computecanada-config

**Comment by bartoldeman** [comment]
@Micket I agree. Something similar was done in the past to with Clang: there are ClangGCC toolchains where the Fortran is provided by gfortran; and this was before GCCcore was introduced. With GCCcore you could in principle promote `icc` to a compiler-only toolchain where GCCcore provides `gfortran`, and keep `iccifort` independent of `icc`.

**Comment by boegel** [comment]
This was also suggested by (I think) @damianam in a recent EasyBuild conf call.

Makes perfect sense to me, and the way to do it should be using a `Bundle`, and including `icc` and `ifort` as `components` (similar to what we do with `X11`).

**Comment by bartoldeman** [comment]
An alternative to the `Bundle` method is to use one of the larger tarballs to install (e.g. 
`parallel_studio_xe_2019_update3_composer_edition.tgz`, which is the smallest that contains both `icc` and `ifort`)

**Comment by boegel** [comment]
done in https://github.com/easybuilders/easybuild-easyconfigs/pull/8879 and used in `intel/2019b` included in EasyBuild v4.0.0, so closing this...
