### ISSUE TITLE
SAMtools/cURL conflict

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-easyconfigs#8100]
`SAMtools/1.9-foss-2018b` doesn't work when `cURL/7.60.0-GCCcore-7.3.0` is loaded:

```
$ ml SAMtools/1.9-foss-2018b
$ ldd /easybuild/18.04/software/SAMtools/1.9-foss-2018b/bin
/samtools
...
libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f2e38d14000)
...
$ samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
$ ml cURL/7.60.0-GCCcore-7.3.0
$ ldd /easybuild/18.04/software/SAMtools/1.9-foss-2018b/bin
...
libcurl.so.4 => /easybuild/18.04/software/cURL/7.60.0-GCCcore-7.3.0/lib/libcurl.so.4 (0x00007fe3116e8000)
...
$ samtools --version
samtools: /easybuild/18.04/software/cURL/7.60.0-GCCcore-7.3.0/lib/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by samtools)
```

`SAMtools` is linked against `libcurl.so.4` but it doesn't include it as a dependency. So it uses the system lib but when you load some other module which includes `cURL` it uses this and the error above happens. I couldn't find out what needs to be changed to make easybuilds `cURL` work with `SAMtools`.

**Comment by boegel** [comment]
@SethosII Can you check if including `cURL` as a dependency in the `SAMtools` easyconfig file and rebuilding it fixes the issue you're seeing?

**Comment by SethosII** [comment]
@boegel Thank you, adding `cURL` as a dependency and rebuilding worked! Should I open a pull request for this?

**Comment by boegel** [comment]
@SethosII Yes please!

**Comment by SethosII** [comment]
I opened a pull request at https://github.com/easybuilders/easybuild-easyconfigs/pull/8131.
