### ISSUE TITLE
OpenBLAS 0.3.5 problems on Skylake-SP (AVX512 dgemm)

### ISSUE THREAD

**Issue by robertschade** [easybuilders/easybuild-easyconfigs#8197]
OpenBLAS-users have reported (https://github.com/xianyi/OpenBLAS/pull/2061) problems with the version 0.3.5 on systems with AVX512 (Skylake-SP). 
However, OpenBLAS 0.3.5 is included in foss 2019a and might cause issues on these systems. 
How to handle this problem?

**Comment by bartoldeman** [comment]
Generically the patch in that issue could be included.

You can also set TARGET=HASWELL in buildopts but that disables more.

**Comment by boegel** [comment]
I guess pulling in that patch makes most sense... We can clearly mention in the release notes of EasyBuild v3.9.1 that people should reinstall `OpenBLAS/0.3.5` if they've built it already?

@vanzod Up for tackling this this week?

**Comment by akesandgren** [comment]
#8227 should fix the problem.

**Comment by boegel** [comment]
fixed with #8227, which will be included with EasyBuild v3.9.1

**Comment by michaellass** [comment]
It seems like dgemm wasn't the only problematic kernel. See https://github.com/xianyi/OpenBLAS/issues/1955#issuecomment-489428403 and https://github.com/xianyi/OpenBLAS/pull/2111.

**Comment by boegel** [comment]
See also https://github.com/JuliaLang/julia/pull/30661/files

**Comment by boegel** [comment]
Patch for OpenBLAS 0.3.5 extended in #8263, so closing again...
