### ISSUE TITLE
ELPA 2016.11.001  build fails with foss-2018b on CentOS 6

### ISSUE THREAD

**Issue by dithwick** [easybuilders/easybuild-easyconfigs#8282]
Hi All,

I'm trying to build ELPA-2016.11.001.pre-foss-2018b.eb on CentOS 6 so I can build QuantumESPRESSO-6.3-foss-2018b.eb but the build of ELPA is failing with on linking with the error message:

```
/software/Compiler/GCCcore/7.3.0/libxml2/2.9.8/lib/libxml2.so: error: undefined reference to 'gzopen64', version 'ZLIB_1.2.3.3'
```
There is a version of zlib installed on the system that doesn't seem support ZLIB_1.2.3.3 but I can't see how that's being picked up and the zlib dependency for libxml2-2.9.8-GCCcore-7.3.0.eb (zlib-1.2.11-GCCcore-7.3.0.eb) obviously does support it. We have several other foss-2018b packages that didn't show this error during build including GROMACS/2018.3. Any suggestions?

As a side note, ELPA-2016.11.001.pre-foss-2018b.eb seems to reference EBROOTIMKL but MKL isn't loaded as a dependency (unless I'm missing something).

Thanks for your help

**Comment by Micket** [comment]
the MKL stuff definitely looks like an oversight, but, probably, a bad include flag probably doesn't negatively change anything.

But, you should be getting libxml2 due to the foss toolchain itself, but this should also bring in zlib as a dependency. I'd be curious about the output from 

```
module load foss/2018b
module list
ldd /software/Compiler/GCCcore/7.3.0/libxml2/2.9.8/lib/libxml2.so
```

I just tried building `ELPA-2016.11.001.pre-foss-2018b.eb`, and there was no problems (eb 3.9.0). If you can repeat this again, please upload the entire log as gist.

**Comment by dithwick** [comment]
Hi, sorry for the slow response (and thanks for responding). module list gives me

```
Currently Loaded Modules:
  1) EasyBuild/3.9.0   4) GCC/7.3.0-2.30   7) XZ/5.2.4           10) hwloc/1.11.10   13) FFTW/3.3.8
  2) GCCcore/7.3.0     5) zlib/1.2.11      8) libxml2/2.9.8      11) OpenMPI/3.1.1   14) ScaLAPACK/2.0.2-OpenBLAS-0.3.1
  3) binutils/2.30     6) numactl/2.0.11   9) libpciaccess/0.14  12) OpenBLAS/0.3.1  15) foss/2018b
```
And ldd gives me

```
 ldd /csc/tinis/software/Compiler/GCCcore/7.3.0/libxml2/2.9.8/lib/libxml2.so
	linux-vdso.so.1 =>  (0x00007fff415ff000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002af4fb272000)
	libz.so.1 => /software/Compiler/GCCcore/7.3.0/zlib/1.2.11/lib/libz.so.1 (0x00002af4fb476000)
	liblzma.so.5 => /software/Compiler/GCCcore/7.3.0/XZ/5.2.4/lib/liblzma.so.5 (0x00002af4fb48e000)
	librt.so.1 => /lib64/librt.so.1 (0x00002af4fb4b6000)
	libm.so.6 => /lib64/libm.so.6 (0x00002af4fb6be000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002af4fb942000)
	libc.so.6 => /lib64/libc.so.6 (0x00002af4fbb60000)
	/lib64/ld-linux-x86-64.so.2 (0x00000039f2400000)
```
I'll try the build again and upload the log as a gist.
Thanks.

**Comment by boegel** [comment]
I wouldn't be surprised if ELPA has a hardcoded `-L/usr/lib64` somewhere that is causing this problem...

Can you check on that in the log @dithwick?

**Comment by dithwick** [comment]
I can't for the life of me work out where AC_FC_LIBRARY_LDFLAGS is adding -L/lib/../lib64 -L/usr/lib/../lib64 from but in the end I discovered that adding zlib as a build dependency seemed to fix it. I'm happy to do a PR for the change if you think it's worthwhile? It occurred to me this could still be happening on CentOS 7 but is showing as an issue because the version of zlib is new enough.

**Comment by Micket** [comment]
CentOS 6 is fortunately very dead now. Closing this.
