### ISSUE TITLE
VASP/5.4.4 fails during build

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#8392]
Dear all,

I have adapted the easyconfig file for VASP/5.4.4 (including a new patch), and tried to easybuild it. However, the compilation fails at the build step with the following error message
```bash
ifort: error #10236: File not found:  '=sequential'
```
which comes from this line
```bash
mpiifort =sequential -lstdc++ -o vasp c2f_interface.o base.o <... etc ...>
```
My first raw guess is that some compiler flag(s) is missing. How can I fix this?

I have uploaded the EB log (with truncated paths). Do I normally have to provide any extra logs, or this is enough?

Thanks
Ehsan
[easybuild-VASP.log](https://github.com/easybuilders/easybuild-easyconfigs/files/3226578/easybuild-VASP.log)

**Comment by moravveji** [comment]
Hey guys,
Any update on this?

**Comment by zao** [comment]
I believe the culprit is the following part of the easyconfig which doesn't handle arguments of the form `-mkl=sequential`:
```python
# remove mkl flag to prevent mixing dynamic libs with the static libs in LIBBLACS/SCALAPACK
prebuildopts += 'sed -i "s|-mkl||" makefile.include && '
```

In the discussion about the intel-2018b build in #7697 there seems to be an alternate form that handles the full argument:
```python
# remove mkl flag to prevent mixing dynamic libs with the static libs in LIBBLACS/SCALAPACK
prebuildopts += 'sed -i "s|-mkl[^ ]*||" makefile.include && '
```

**Comment by moravveji** [comment]
Thanks @zao for the correct fix. EB just built VASP flawlessly.
