### ISSUE TITLE
PETSc configure fails for SCOTCH issue(?)

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#8455]
Dear colleagues,

I am attempting to build PETSc/3.11.1-intel-2018a on our SkyLake partition, but I am receiving the following error which starts to terminate the configure step:
```bash
TESTING: check from config.libraries(/easybuild/PETSc/3.11.1/intel-2018a/petsc-3.11.1/config/BuildSystem/config/libraries.py:154)
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
--with-ptscotch-dir=/software/SCOTCH/6.0.6-intel-2018a did not work
*******************************************************************************

 (at easybuild/tools/run.py:444 in parse_cmd_output)
== 2019-06-07 13:58:36,679 easyblock.py:2577 WARNING build failed (first 300 chars): cmd " ./configure --prefix=/software/PETSc/3.11.1-intel-2018a --LIBS="$LIBS -lrt" --with-cc="mpiicc"  --with-cxx="mpiicpc" --with-c++-support  --with-fc="mpiifort"  --CFLAGS="-O2 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC"  --CXXFLAGS="-O2 -xHost -ftz -fp-specu
```
Full configure.log and EB log are attached (with path prefixes pruned). We have a slightly older version of SCOTCH (i.e. 6.0.4). Do you believe downgrading the dependency would resolve this issue?

Kind regards,
Ehsan
[petsc.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3265858/petsc.zip)

**Comment by boegel** [comment]
@moravveji The `configure.log` shows:

```
ld: cannot find -lptscotchparmetis
```

Can you check whether your SCOTCH installation has that library? Here's what I have:

```
$ ls /software/SCOTCH/6.0.6-foss-2018a/lib/
libesmumps.a  libptesmumps.a  libptscotch.a  libptscotcherr.a  libptscotcherrexit.a  libptscotchparmetis.a  libscotch.a  libscotcherr.a  libscotcherrexit.a  libscotch_group.a  libscotchmetis.a
```

If `libptscotchparmetis.a` is not there, please check the installation log of `SCOTCH` 6.0.6 for compilation errors, or perhaps try to re-install it if that's an option?

I don't think downgrading is the best alternative here, you should try and figure out the actual cause of the problem.

**Comment by moravveji** [comment]
Thanks Kenneth for the catch. Indeed, libscotchmetis.a was missing from the `lib` folder, and it still is, after having reinstalled the same SCOTCH/6.0.6-intel-2018a. Looking at the installation log (attached), it seems like the static library is created, but somehow, it doesn't make it the installation folder.
[easybuild-SCOTCH-6.0.6-20190611.log.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3275241/easybuild-SCOTCH-6.0.6-20190611.log.zip)

**Comment by wpoely86** [comment]
@moravveji can you rerun with `--debug`? Normally the easyblock should copy those files to the install directory.

**Comment by moravveji** [comment]
Thanks @wpoely86 for the tip. I tried with `--debug`, and the end result was the same as before: still no `libptscotchparmetis.a` inside the `lib` folder.

**Comment by wpoely86** [comment]
Can you show the debug log?

Normally SCOTCH should install all those libraries in a local directory and the easyblock should copy them over.

**Comment by moravveji** [comment]
Please ...
[easybuild-SCOTCH-6.0.6-20190613.112924.log.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3285921/easybuild-SCOTCH-6.0.6-20190613.112924.log.zip)

**Comment by wpoely86** [comment]
@moravveji you're using an old version of the easyblock. Please update and try again.

**Comment by moravveji** [comment]
Alright ... I updated my EB to v. 3.9.2 and also the easyblocks to the latest. When trying to build scotch, it fails during the sanity check. For that, I opened a separate ticket not to mix stuff: https://github.com/easybuilders/easybuild-easyconfigs/issues/8509

Once that is resolved, I follow up on this again.

**Comment by moravveji** [comment]
After the issue with SCOTCH was resolved (https://github.com/easybuilders/easybuild-easyconfigs/issues/8509), the built of PETSc went on flawlessly. Thanks for your support here. 
I am closing this ticket now.
E.

**Comment by boegel** [comment]
:+1:
