### ISSUE TITLE
Why is RStan not included in R?

### ISSUE THREAD

**Issue by wookietreiber** [easybuilders/easybuild-easyconfigs#8473]
[RStan](https://github.com/easybuilders/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/r/RStan) is currently included with a separate easyconfig. Why is it not included in the main [R](https://github.com/easybuilders/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/r/R) easyconfig, i.e. could this be changed to just be included in the main R easyconfig?

**Comment by fizwit** [comment]
My users request RStan also.  I will open a PR for 3.6.0 to add it.  How do you feel about the tidyverse? I would also like to add TidyModel.

**Comment by boegel** [comment]
@wookietreiber Sorry for the long delay in responding to this...

I'm not aware of a good reason not to include `RStan` as an extension in the `R` easyconfig.

It was contributed as a stand-alone installation via #7996, and the question was never raised, so it got merged like that.

Maybe @vanzod can pitch in here, since he added `RStan`?

**Comment by boegel** [comment]
@fizwit Adding `tidyverse` and `TidyModel` makes sense to me too (as long as they don't require additional dependencies being added, that could be a can of worms).

**Comment by fizwit** [comment]
RStan should be added to R, it is a very popular package. I get lots of
requests from users at my site for it. But I would also caution against
adding too many packages to the base R. A solution to support local
additions to the base R is to use Bundle with RPackage.  The link below is
an example of how you can extend R for your local site, which is based on
the EasyBuild R.

https://github.com/FredHutch/easybuild-life-sciences/blob/master/fh_easyconfigs/r/R/R-3.6.0-foss-2016b-fh1.eb

**Comment by Micket** [comment]
Nowadays we add now very little to base R and people are free to add more stuff to the R package bundles instead (or separate packages of course).
