### ISSUE TITLE
Perl-5.28.1-GCCcore-8.2.0.eb fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by asa1** [easybuilders/easybuild-easyconfigs#8499]
Trying to build Perl-5.28.1-GCCcore-8.2.0.eb with EasyBuild 3.9.2 with Ubuntu 18.04 fails with this error:

`Can't locate File/ShareDir/Install.pm in @INC (you may need to install the File::ShareDir::Install module) (@INC contains: /sw/ebpkgs/software/Perl/5.28.1-GCCcore-8.2.0/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi /sw/ebpkgs/software/Perl/5.28.1-GCCcore-8.2.0/lib/perl5/site_perl/5.28.1 /sw/ebpkgs/software/Perl/5.28.1-GCCcore-8.2.0/lib/perl5/5.28.1/x86_64-linux-thread-multi /sw/ebpkgs/software/Perl/5.28.1-GCCcore-8.2.0/lib/perl5/5.28.1) at Makefile.PL line 13.`

The same error occurs trying to build Perl-5.28.0-GCCcore-7.3.0.eb

The full build log is attached.
[perl-failed.log](https://github.com/easybuilders/easybuild-easyconfigs/files/3301908/perl-failed.log)

**Comment by boegel** [comment]
@vanzod @akesandgren Any idea what may be wrong here?

I consider you guys more of an expert on Ubuntu than I am...

**Comment by akesandgren** [comment]
Haven't had time to look at it due to disaster recovery... I will look at it in the not too distant future.

**Comment by asa1** [comment]
I tried building this again in 3.9.3, and it failed with a different error this time. I don't recall anything else changing with the system since trying it with 3.9.2. Build log is attached. Thanks!
[perl_build_3.9.3.log](https://github.com/easybuilders/easybuild-easyconfigs/files/3444721/perl_build_3.9.3.log)

**Comment by asa1** [comment]
I was able to build Perl successfully by moving my Easybuild directory to local storage. It was originally being built on a new BeeGFS mount, and I think that may have caused the problem. I was unable to verify this from the build logs, but I suspect it may be due to a BeeGFS limitation that doesn't allow hard links outside of the same directory.

I hope I didn't waste anyone's time with this, thanks to all the EasyBuild contributors!

**Comment by boegel** [comment]
@asa1 It's not the first time that using BeeGFS is being reported as problematic...

Thanks for the update! Please don't hesitate to let us know if you run into other problems...
