### ISSUE TITLE
M4-1.4.17 installation fails

### ISSUE THREAD

**Issue by evohringer** [easybuilders/easybuild-easyconfigs#8501]
Hi,

trying to install M4-1.4.17 on ubuntu 18.10 (GNU/Linux 4.18.0-20-generic x86_64) but I get the following error in the building phase:
gcc  -I.   -fgnu89-inline  -g -O2 -MT isnanl.o -MD -MP -MF $depbase.Tpo -c -o isnanl.o isnanl.c &&\
mv -f $depbase.Tpo $depbase.Po
freadahead.c: In function 'freadahead':
freadahead.c:91:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."

I found a similar problem with the M4-1.4.18 version related to glibc version 2.28 as Issue #7384 and tried to the M4_glibc_2.28.patch file but without success ( I edited the version to match 1.4.17).

I´m new to easybuild and hep is really appreciated.

**Comment by boegel** [comment]
Just editing the version in the patch file is likely not enough to make the patch apply on M4 1.4.17, you (or someone) will actually have to make a patch file for M4 1.4.17 that makes the same changes as in the M4 1.4.18 patch.

Basically, the steps are:

* download the M4 1.4.17 tarball and unpack it to say `m4-1.4.17` (a directory)
* copy the unpacked sources to say `m4-1.4.17.orig`
* make the necessary changes in the files in `m4-1.4.17`
* create a patch file using `diff -ru m4-1.4.17.orig m4-1.4.17 > M4-1.4.17_glibc_2.28.patch
* edit the patch file to add a header explaining what the patch does (you can basically copy this from `M4-1.4.18_glibc_2.28.patch`)

@evohringer Are you up for giving this a try?

**Comment by evohringer** [comment]
Hi @boegel,
Thanks for the quick help. 

I created a patch file and now it works!! 

Please find attached the patch file to may be included in the official version.


[M4-1.4.17_glibc_2.28.patch.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3307665/M4-1.4.17_glibc_2.28.patch.zip)

**Comment by evohringer** [comment]
Next problem was with Bison-3.0.4 and created also a patch file to make it work which is attached. I changes the Bison-3.0.4.eb respectively.

[Bison-3.0.4_glibc_2.28.patch.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3307749/Bison-3.0.4_glibc_2.28.patch.zip)

**Comment by boegel** [comment]
@evohringer Are you up for making a pull request to include that patch? See https://easybuild.readthedocs.io/en/latest/Contributing.html#contributing-easyconfig-files

**Comment by evohringer** [comment]
Still struggling trying to get everything else working. Once I have succeded installing I will try the pull request.

**Comment by boegel** [comment]
@evohringer Sure, no problem.

If you need help, I can highly recommend joining our Slack/IRC channel (see https://easybuild.readthedocs.io/en/latest/#getting-help).

**Comment by boegel** [comment]
Patch for `M4-1.4.17.eb` added in #8666 (will add the patch consistently to all M4 1.4.17 easyconfigs later).

**Comment by boegel** [comment]
With both #8666 and #8675 merged, the problems should be fixed for both M4 1.4.17 and Bison 3.0.4, so I'll go ahead and close this issue...

Thanks a lot for reporting this @evohringer!

**Comment by Raman2407kumar** [comment]
Bison requires m4 as prerequisite. I directly installed bison using command sudo apt-get install bison flex

Installing m4 was throwing error "Please port gnulib freading.c to your platform!"
