### ISSUE TITLE
V8 R library is missing V8 dependency

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-easyconfigs#8596]
The easyconfig file added with #8592 is missing the required `V8` dependency. I suspect `libv8` was installed with the OS in the systems where it was tested. Here is the error message on a minimal OS system:
```
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because  was not found. Try installing:
 * deb: libv8-dev or libnode-dev (Debian / Ubuntu)
 * rpm: v8-devel (Fedora, EPEL)
 * brew: v8 (OSX)
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘V8’
```

@lexming Do you have an easyconfig for installing `V8`? If not we may have to consider reverting the PR merge.

@smoors Thoughts on this?

**Comment by smoors** [comment]
@vanzod `V8` is part of `nodejs`, but its installation needed some changes to make it accessible, see here:
https://github.com/easybuilders/easybuild-easyconfigs/pull/8546
Did you update `nodejs` to include the changes?

**Comment by vanzod** [comment]
@smoors Thanks. That was it. Sorry for the noise
