### ISSUE TITLE
installation QuantumEspresso 6.4.1 intel/2019a, bzip2-1.0.6.tar.gz can not be found or donwloaded

### ISSUE THREAD

**Issue by alchemroz** [easybuilders/easybuild-easyconfigs#8607]
I was trying to install QuantumEspresso with --robot, when it arrives to download of https://fossies.org/linux/misc/bzip2-1.0.6.tar.gz

easybuild said was impossible to download bzip2-1.0.6.tar.gz. Actually it is right, in the site they changed to bzip2-1.0.8.tar.gz. I downloaded by another site, then I added to the search path. Now it started to work properly again. Maybe you want to correct the dependence. 

Bests,
Simone

**Comment by boegel** [comment]
@alchemroz Sorry for the late reply... Thanks a lot for reporting this!

The download issues for `bzip2` 1.0.6 have been fixed in #8614 (to be included with the upcoming EasyBuild v3.9.4), and we'll start using more recent `bzip2` versions going forward...
