### ISSUE TITLE
Strange OS dependency check failure on Fedora 30

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#8661]
Trying to build Python on a Fedora 30 machine, and it's failing at the OS dependency check, even though `openssl-devel` is installed:
```
== 2019-08-02 06:32:03,467 easyconfig.py:614 INFO Validating easyconfig
== 2019-08-02 06:32:03,467 easyconfig.py:619 INFO Checking OS dependencies
== 2019-08-02 06:32:03,467 filetools.py:396 INFO Command rpm found at /usr/bin/rpm
== 2019-08-02 06:32:03,468 run.py:173 DEBUG run_cmd: running cmd rpm -q openssl-devel (in /home/huffmaa)
== 2019-08-02 06:32:03,468 run.py:192 INFO running cmd: rpm -q openssl-devel 
== 2019-08-02 06:32:03,474 run.py:542 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)
== 2019-08-02 06:32:03,475 filetools.py:396 INFO Command dpkg found at /usr/bin/dpkg
== 2019-08-02 06:32:03,475 run.py:173 DEBUG run_cmd: running cmd dpkg -s openssl-devel (in /home/huffmaa)
== 2019-08-02 06:32:03,475 run.py:192 INFO running cmd: dpkg -s openssl-devel 
== 2019-08-02 06:32:03,483 run.py:542 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)
== 2019-08-02 06:32:03,483 filetools.py:409 WARNING Could not find command 'openssl-devel' (with permissions to read/execute it) in $PATH (['/home/huffmaa/.local/easybuild/software/Python/3.7.2-GCCcore-8.2.0/bin', '/home/huffmaa/.local/ea
sybuild/software/XZ/5.2.4-GCCcore-8.2.0/bin', '/home/huffmaa/.local/easybuild/software/SQLite/3.27.2-GCCcore-8.2.0/bin', '/home/huffmaa/.local/easybuild/software/Tcl/8.6.9-GCCcore-8.2.0/bin', '/home/huffmaa/.local/easybuild/software/libre
adline/8.0-GCCcore-8.2.0/bin', '/home/huffmaa/.local/easybuild/software/ncurses/6.1-GCCcore-8.2.0/bin', '/home/huffmaa/.local/easybuild/software/bzip2/1.0.6-GCCcore-8.2.0/bin', '/home/huffmaa/.local/easybuild/software/binutils/2.31.1-GCCc
ore-8.2.0/bin', '/home/huffmaa/.local/easybuild/software/GCCcore/8.2.0/bin', '/home/huffmaa/.local/easybuild/software/EasyBuild/3.9.3/bin', '/usr/lib64/qt-3.3/bin', '/usr/lib64/ccache', '/usr/local/bin', '/usr/local/sbin', '/usr/bin', '/u
sr/sbin', '/var/lib/snapd/snap/bin', '/opt/dell/srvadmin/bin', '/home/huffmaa/.local/bin', '/home/huffmaa/bin'])
```

Here is evidence that it is installed:
```
rpm -q openssl-devel
openssl-devel-1.1.1c-2.fc30.x86_64
```

**Comment by boegel** [comment]
@verdurin Can you make that a debug log, so it shows the output/exit code of the `rpm -q openssl-devel` command it runs?

The final error message could definitely be improved here; there's a (silly) fallback to trying to run the OS dep as a command to check whether it's available, but that shouldn't produce the actual error message, it should say something like "Failed to find 'openssl-devel' OS dependency"`, and maybe list the things it tried to check...

**Comment by zao** [comment]
When building `eb Python-2.7.15-foss-2018b.eb --robot`, when building the first extension `setuptools`, with my own added log entry:
`== 2019-08-18 16:40:51,561 systemtools.py:593 WARNING Dependency openssl-devel searched with rpm with command line 'rpm -q openssl-devel: False result'`

When running in a standalone Python interpreter:
```
[zao@freja ~]$ python -c "from easybuild.tools.run import run_cmd; print(run_cmd('rpm -q openssl-devel', simple=True, log_all=False, log_ok=False, force_in_dry_run=True, trace=False, stream_output=False))"
True
```

**Comment by zao** [comment]
A-ha!
Command output when building the `setuptools` extension is:
``("rpm: /hp/eb/software/Compiler/GCCcore/7.3.0/XZ/5.2.4/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.8)\n", 1)``

**Comment by zao** [comment]
We have apparently run into this in the past with different versions: https://github.com/easybuilders/easybuild-easyconfigs/issues/4036

Feels strange that our environment should contain any of the currently builing package dependencies when running the system packaging tool to check for OS deps.

**Comment by zao** [comment]
If I remove that patch from my XZ builds, `rpm` can run in the presence of the EasyBuild. This assumedly breaks the CentOS mentioned in the other report, so it's not a solution.

**Comment by akesandgren** [comment]
In other words we need  to clear the env before runing OS commands from within EB

**Comment by boegel** [comment]
Fixed by skipping re-validation of easyconfig when installing extensions in https://github.com/easybuilders/easybuild-framework/pull/3071
