### ISSUE TITLE
Autoconf/2.69 requires perl-Data-Dumper

### ISSUE THREAD

**Issue by mstud** [easybuilders/easybuild-easyconfigs#8704]
Just installed EasyBuild on a fresh CentOS 7.6 installation and tried to do some installation, but it failed at Autoconf-2.69-GCCcore-8.2.0.eb:

```
autom4te_perllibdir='..'/lib AUTOM4TE_CFG='../lib/autom4te.cfg'         ../bin/autom4te -B '..'/lib -B '..'/lib         --language M4sh --cache '' --melt ./autoconf.as -o autoconf.in
mv autoupdate.tmp autoupdate
Can't locate Data/Dumper.pm in @INC (@INC contains: ../lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ../lib/Autom4te/C4che.pm line 33.
BEGIN failed--compilation aborted at ../lib/Autom4te/C4che.pm line 33.
```

Installing the yum package `perl-Data-Dumper` resolved it, so maybe this should be added as an osdependency?

**Comment by boegel** [comment]
We're aware of this, but haven't gotten around to fix it yet; see also #1822 .

The best way to fix it would be to simply provide `Perl` as a dep (like in #5300), but that's quite "heavy".

Thanks for bringing this up again, this has been bugging me for a while, we should go and get it dealt with.

**Comment by verdurin** [comment]
@boegel thoughts on how to tackle this one?

**Comment by JensTimmerman** [comment]
if you don't want to bring in perl, you should bring in `perl-Data-Dumper` as an os dependency?
I'm also running into this on clean centos7.7 install

**Comment by JensTimmerman** [comment]
adding `    ('Perl', '5.30.0'),` as a dependency for Autoconf made my build succeed. So it might be a core perl module, it's included somwhere in eb's Perl, but centos packages up separately.
