### ISSUE TITLE
CheMPS2 fails to pass tests 

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#8705]
Dear all

I would like to install CheMPS2/1.8.9-intel-2018a as a dependency for PSI4. however, it does not pass the tests:

`== testing...
== FAILED: Installation ended unsuccessfully (build directory: /mem/easybuild/CheMPS2/1.8.9/intel-2018a): build failed (first 300 chars): cmd "export OMP_NUM_THREADS=1 &&  make test " exited with exit code 2 and output:
Running tests...
Test project /mem/easybuild/CheMPS2/1.8.9/intel-2018a/easybuild_obj
      Start  1: test1
 1/14 Test  #1: test1 ............................   Passed   17.04 sec
      Start  2: test2
 2/1
== Results of the build can be found in the log file(s) /tmp/eb-eseXXF/easybuild-CheMPS2-1.8.9-20190809.111917.UOLSt.log
ERROR: Build of /myData/easybuild/work/CheMPS2/CheMPS2-1.8.9-intel-2018a.eb failed (err: 'build failed (first 300 chars): cmd "export OMP_NUM_THREADS=1 &&  make test " exited with exit code 2 and output:\nRunning tests...\nTest project /mem/easybuild/CheMPS2/1.8.9/intel-2018a/easybuild_obj\n      Start  1: test1\n 1/14 Test  #1: test1 ............................   Passed   17.04 sec\n      Start  2: test2\n 2/1')`

I have attached the logs and the EB config file.

Thanks
Ehsan
[CheMPS2.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3486307/CheMPS2.zip)

**Comment by boegel** [comment]
Several of the tests segfaulted:

```
The following tests FAILED:
      2 - test2 (SEGFAULT)
      3 - test3 (SEGFAULT)
     10 - test10 (SEGFAULT)
     13 - test13 (SEGFAULT)
Errors while running CTest
make: *** [test] Error 8
```

Figuring this one out is going to be... fun.

Maybe the memory limits that were in place on the system where this build was done were insufficient, is that possible?

Does it help at all if you add this to the easyconfig file?

```python
toolchainopts = {'optarch': False}
```

If not, what about

```python
toolchainopts = {'optarch': False, 'noopt': True}  # compile with -O0, *NOT* for production installs!

**Comment by boegel** [comment]
Another possible cause is the different toolchain... We're not seeing these failing tests when using the `intel/2018b` or `intel/2019a` common toolchains, so it could be simply a miscompile with `intel/2018a`.

**Comment by moravveji** [comment]
I tried twice with the two above `toolchainopts` options, and it failed both times. Given that our 2018a is our base/most complete toolchain, I prefer to compile it with intel/2018a. 
Is there a chance we can get this compiling still under the 2018a?

**Comment by moravveji** [comment]
correction: I just figured out that on tier-1 we still do not have 2018b or 2019a toolchains at all. So, 2018a is my only bet!

**Comment by boegel** [comment]
@moravveji If the problem still occurs when using `noopt` (which implies compiling with `-O0`), that's a strong indicator that you're triggering a compiler bug, and then the only viable fix is to use a more recent compiler version imho...

**Comment by boegel** [comment]
Closing this, I don't see another option here than using a more recent compiler version...
