### ISSUE TITLE
pytest fails to import itself!

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#8707]
Hey all,

I am trying to build pytest/4.4.0-intel-2018a-Python-3.6.4. However, the sanity check fails with the following message:

`== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/easybuild/pytest/4.4.0/intel-2018a-Python-3.6.4): build failed (first 300 chars): Sanity check failed: no file found at 'bin/pytest' in /myApps/software/pytest/4.4.0-intel-2018a-Python-3.6.4
extensions sanity check failed for 1 extensions: pytest
failing sanity check for 'pytest' extension: command "python -c "import pytest"" failed; output:
Traceback (most r
== Results of the build can be found in the log file(s) /tmp/eb-C76axS/easybuild-pytest-4.4.0-20190809.142930.BXAPZ.log
ERROR: Build of /myData/easybuild/work/pytest/pytest-4.4.0-intel-2018a-Python-3.6.4.eb failed (err: 'build failed (first 300 chars): Sanity check failed: no file found at \'bin/pytest\' in /myApps/software/pytest/4.4.0-intel-2018a-Python-3.6.4\nextensions sanity check failed for 1 extensions: pytest\nfailing sanity check for \'pytest\' extension: command "python -c "import pytest"" failed; output:\nTraceback (most r')`

The debug logfile is attached.

Thanks
Ehsan
[pytest.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3486344/pytest.zip)

**Comment by boegel** [comment]
Hmm, the output from the actual installation command looks very fishy...

```
== 2019-08-09 11:25:02,279 run.py:506 INFO cmd " pip install --prefix=/myApps/software/pytest/4.4.0-intel-2018a-Python-3.6.4  --no-deps  --ignore-installed  ." exited with exit code 0 and output:
Processing /memory/easybuild/pytest/4.4.0/intel-2018a-Python-3.6.4/pytest/pytest-4.4.0
Installing collected packages: UNKNOWN
  Running setup.py install for UNKNOWN: started
    Running setup.py install for UNKNOWN: finished with status 'done'
Successfully installed UNKNOWN-4.4.0
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Was anything actually installed? Is there anything at all in `/myApps/software/pytest/4.4.0-intel-2018a-Python-3.6.4`?

**Comment by moravveji** [comment]
@boegel: Thanks Kenneth for your notice.
In fact, the lib directory seems to be populated with the relevant files:

`ll /myApps/pytest/4.4.0-intel-2018a-Python-3.6.4/lib/python3.6/site-packages/
UNKNOWN-4.4.0-py3.6.egg-info/             attrs-19.1.0-py3.6.egg-info/              pluggy-0.9.0-py3.6.egg-info/
__pycache__/                              more_itertools/                           py/
_scandir.cpython-36m-x86_64-linux-gnu.so  more_itertools-5.0.0-py3.6.egg-info/      py-1.8.0-py3.6.egg-info/
atomicwrites/                             pathlib2/                                 scandir-1.10.0-py3.6.egg-info/
atomicwrites-1.3.0-py3.6.egg-info/        pathlib2-2.3.3-py3.6.egg-info/            scandir.py
attr/                                     pluggy/
`
Is there any other test I must carry out?

E.

**Comment by boegel** [comment]
I have no idea why the `UNKNOWN` thing is popping up, or why `bin/pytest` is not there...

**Comment by boegel** [comment]
@moravveji Did you ever figure out this issue?

**Comment by moravveji** [comment]
In fact not.
I even do not recall why I needed that, and who asked for it!
The ticket maybe closed, if you will.

Thanks
