### ISSUE TITLE
Build Error: OpenBLAS-0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0.eb

### ISSUE THREAD

**Issue by alchemroz** [easybuilders/easybuild-easyconfigs#8844]
[easybuild-OpenBLAS-0.2.15-20190827.102317.sXCbM.log](https://github.com/easybuilders/easybuild-easyconfigs/files/3545115/easybuild-OpenBLAS-0.2.15-20190827.102317.sXCbM.log)
Dear all, 
              I am trying to build  
eb IOR-3.0.1-foss-2016a-mpiio.eb --robot 

this time on a centos 7.  I got an error when I arrive to build the OpenBLAS. In attachment the log. Thanks for your help. 

Bests

**Comment by alchemroz** [comment]
Dear all, probably this ticket went not noticed. Please, can you give me some hints ?

Thanks

**Comment by akesandgren** [comment]
It fails to detect CPU type. What CPU are you using?

And why use such an old toolchain? EasyBuild 4.0.0 have foss/2019b

Using something based on GCC4 is not recommended.

**Comment by alchemroz** [comment]
Hello @akesandgren, 
                                    thank you for the reply. In attachment there are the characteristics of my CPU. 
[lscpu.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/3712735/lscpu.txt)

Actually I would be totally fine to use a more recent toolchain but unfortunately I need to install IOR and the only available version in the current software list is 

EasyBuild/4.0.0/easybuild/easyconfigs/i/IOR/IOR-3.0.1-foss-2016a-mpiio.eb
  
I was using EasyBuild 3.9 in the last log, I tried also with  EasyBuild 4.0.0 but I had same problem 

[easybuild-OpenBLAS-0.2.15-20191010.143205.MyVkJ.log](https://github.com/easybuilders/easybuild-easyconfigs/files/3712776/easybuild-OpenBLAS-0.2.15-20191010.143205.MyVkJ.log)

If there is not an easy way to fix it can you help me to install an updated IOR with a more recent toolchain ? I would like to learn how to contribute.

Thanks

**Comment by akesandgren** [comment]
That cpu is likely way too new for that old version of openblas. 

The simple way in this case is to use (as long as you have already built foss-2019b.eb, if not, build that one first)
eb IOR-3.0.1-foss-2016a-mpiio.eb --try-toolchain-version=2019b

Or use some other existing toolchain version of foss. Or if you have intel you can use --try-toolchain=intel,2019b or what ever version you have.

Meanwhile I'll upload a version based on foss/2019b

**Comment by akesandgren** [comment]
Or, even simpler
eb --from-pr=9109 --robot
that will build IOR 3.2.1 with foss/2019b and foss/2019b if you don't already have it.

See, PR #9109 for details

**Comment by alchemroz** [comment]
Dear @akesandgren, 
                                   thanks, I followed your suggestions PR #9109, correctly IOR installed, it worked nicely. 

Thanks,
Simone

**Comment by akesandgren** [comment]
The PR has changed as of 10 minutes ago using a lower toolchain (gompi instead of foss) and adds HDF5 support. That HDF5 easyconfig is however not in easybuild 4.0.0 but will be in 4.0.1.

So lets close this issue.

**Comment by boegel** [comment]
@alchemroz Sorry for not responding to this, I've been "snowed under" for a while now, it's hard to keep up with questions being posted.

Thanks a lot @akesandgren for tackling this one!
