### ISSUE TITLE
OpenCV missing its ant dep

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#8877]
`OpenCV` depends upon `ant-1.10.5`.

The oldest version available at the active upstream site is `1.10.6`.

1.10.5 is still available at: https://archive.apache.org/dist/ant/binaries/

What's the least intrusive fix for this? Fix the URL in the existing easyconfig, or update it and then update `OpenCV` (plus any other consumers of `ant`)?

**Comment by Micket** [comment]
This has been long since fixed. All OpenCV's since 2019a seem to have a proper ant dependency.
