### ISSUE TITLE
gdk-pixbuf requires docbook stylesheet OS dep if building offline

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#8893]
I found that when building `gdk-pixbuf` on a system without unregulated outbound access, I needed to install (on CentOS 7):
```
docbook-style-xsl
```
in order for the `xsltproc` command that runs as part of the installation to work.

Debatable whether this should be added to the `easyconfig` as an `osdependency`, or just a note for such systems.

For reference, the error is:
```
[22/173] Generating gdk-pixbuf-csource-man with a custom command.
FAILED: docs/gdk-pixbuf-csource.1
/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.38.1/docs/gdk-pixbuf-csource.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
[23/173] Generating gdk-pixbuf-query-loaders-man with a custom command.
FAILED: docs/gdk-pixbuf-query-loaders.1
```

**Comment by migueldiascosta** [comment]
hit this on generoso... (https://github.com/easybuilders/easybuild-easyconfigs/issues/8893)

I think the problem is not only for regulated network access, `xsltproc` is being called with `--nonet`, so `docbook-style-xsl` is always required, no?

**Comment by boegel** [comment]
@migueldiascosta So let's add an OS dep? Not sure if added it as a proper dep is going to be easy...

**Comment by lexming** [comment]
* On the positive side, we already have an easyconfig for `libxslt`.
* On the negative, the installation of `docbook-style-xsl` seems messy (https://src.fedoraproject.org/rpms/docbook-style-xsl/blob/master/f/docbook-style-xsl.spec) and it also needs `docbook-dtd-xml`

**Comment by stevenvdb** [comment]
By specifying ` -Dman=false` in configopts, you disable generating the man pages (which requires xlstproc) and the build proceeds.

**Comment by verdurin** [comment]
Installing the OS version of `docbook-style-xsl` fixed the build for me on Fedora 32.
