### ISSUE TITLE
MTL4 download url is broken

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#89]
(originally by @JensTimmerman)

The MTL download url in the example .eb's is broken.

http://www.simunova.com/downloads/mtl4/MTL-all-4.0.8878-Linux.tar.gz returns a 404
This is because MTL4 updates their tarbals every thursday to the latest svn revision.
If you want a fixed version you should use their public svn
svn checkout https://simunova.zih.tu-dresden.de/svn/mtl4/trunk mtl4

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb-pg-login02 - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/cf1f02bca416320b9dbd1f1c0d756610 for a full test report.

**Comment by boegel** [comment]
@branfosj How did you manage to upload a test report to an issue? :D

**Comment by Micket** [comment]
Closing this as noone seems to eager on updating the easyconfigs for this anyway. If they ever do, i'm sure they would find the github page: https://github.com/simunova/mtl4
