### ISSUE TITLE
2 different programs with the same name SNAP

### ISSUE THREAD

**Issue by smoors** [easybuilders/easybuild-easyconfigs#8946]
There are currently 2 different programs in the EB repo with the same name SNAP:
`SNAP-2013-11-29-GCC-6.4.0-2.28.eb` (Semi-HMM-based Nucleic Acid Parser)
`SNAP-1.0beta.23-intel-2017b.eb` (Scalable Nucleotide Alignment Program)

**Comment by boegel** [comment]
@smoors That's not our fault, is it? ;)

**Comment by smoors** [comment]
@boegel indeed, but it's confusing for the users. maybe we can change the name for one of them?

**Comment by boegel** [comment]
@smoors Can we come up with a better suited name for one of them?

Also, wouldn't that still confuse users, since they would look for SNAP with `module avail SNAP/`, and not find they expect?

**Comment by smoors** [comment]
@boegel we could rename the first as `SNAP-HMM`.
that way if users do `module avail SNAP` (without the slash) they will see both.

**Comment by boegel** [comment]
@smoors Up for tackling this yourself?

**Comment by smoors** [comment]
@boegel sure, I was waiting for your approval regarding my renaming proposal :)
