### ISSUE TITLE
Boost/1.70.0-foss-2018a fails to compile

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#8948]
Hi

As a dependency for BLAST+, I am trying to compile Boost/1.70.0 with foss/2018a toolchain on Breniac. On the broadwell login node, I could easily compile the Boost; however, on a SkyLake compute node, I fail to do so using the same easyconfig file. The brief error message from the bootstrap.py reads:

`###
###
rm -rf bootstrap
mkdir bootstrap
gcc -o bootstrap/jam0 command.c compile.c constants.c debug.c execcmd.c frames.c function.c glob.c hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c object.c option.c output.c parse.c pathsys.c regexp.c rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c class.c cwd.c native.c md5.c w32_getreg.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modules/order.c execunix.c fileunix.c pathunix.c
gcc: internal compiler error: Illegal instruction (program as)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.`

Hence, I am reaching out to you guys for help, before reaching out to the GNU community. I have attached the compressed log files.

Thanks in advance
Ehsan

[boost-log.tar.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/3631607/boost-log.tar.gz)

**Comment by boegel** [comment]
@moravveji The `Illegal instruction` error suggests you are using a tool that was built for a recent processor architecture (Intel Skylake) on a system with an older processor architecture (Intel Broadwell, for example).
Since it's `as` throwing the `Illegal instruction` error, it seems like it's the `binutils` installation causing this...
