### ISSUE TITLE
libxc webpage and download link changed

### ISSUE THREAD

**Issue by zao** [easybuilders/easybuild-easyconfigs#9061]
The webpage and download location for libxc seems to have changed.
The previous "octopus" URL redirects for the homepage, but not for the download.

The new URLs seem to be:
https://www.tddft.org/programs/libxc/
https://www.tddft.org/programs/libxc/down.php?file=4.3.4/libxc-4.3.4.tar.gz

(the website links to a http:// download, but it seems to accept https:// )

**Comment by Micket** [comment]
This webpage is also now dead and we use the gitlab page instead.
