### ISSUE TITLE
Error while building Qt4 with intel2017a compiler

### ISSUE THREAD

**Issue by satish1820** [easybuilders/easybuild-easyconfigs#9179]
Hi,

I am getting following error. I tried multiple times but facing same error. Also I changed the Qt4 version from 4.8.7 to 4.8.6 but same error.

Please have a look.
--------------------------------
iitmlogin5:/gpfs1/home/ibm $ eb ParaView-5.4.1-intel-2017a-mpi.eb $ROBOT
== temporary log file in case of crash /tmp/eb-0_6ave/easybuild-uE4SZE.log
== resolving dependencies ...
== processing EasyBuild easyconfig /gpfs1/home/ibm/.local/easybuild/software/EasyBuild/3.9.3/lib/python2.6/site-packages/easybuild_easyconfigs-3.9.3-py2.6.egg/easybuild/easyconfigs/q/Qt/Qt-4.8.6-intel-2017a.eb
== building and installing Qt/4.8.6-intel-2017a...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== FAILED: Installation ended unsuccessfully (build directory: /gpfs1/home/ibm/.local/easybuild/build/Qt/4.8.6/intel-2017a): build failed (first 300 chars): cmd " LD_LIBRARY_PATH=/gpfs1/home/ibm/.local/easybuild/build/Qt/4.8.6/intel-2017a/qt-everywhere-opensource-src-4.8.6/lib:$LD_LIBRARY_PATH  make -j 32 " exited with exit code 2 and output:
cd src/tools/bootstrap/ && make -f Makefile
cd src/3rdparty/webkit/Source/ && /gpfs1/home/ibm/.local/easybuild/
== Results of the build can be found in the log file(s) /tmp/eb-0_6ave/easybuild-Qt-4.8.6-20191017.161953.ceJzH.log
ERROR: Build of /gpfs1/home/ibm/.local/easybuild/software/EasyBuild/3.9.3/lib/python2.6/site-packages/easybuild_easyconfigs-3.9.3-py2.6.egg/easybuild/easyconfigs/q/Qt/Qt-4.8.6-intel-2017a.eb failed (err: 'build failed (first 300 chars): cmd " LD_LIBRARY_PATH=/gpfs1/home/ibm/.local/easybuild/build/Qt/4.8.6/intel-2017a/qt-everywhere-opensource-src-4.8.6/lib:$LD_LIBRARY_PATH  make -j 32 " exited with exit code 2 and output:\ncd src/tools/bootstrap/ && make -f Makefile \ncd src/3rdparty/webkit/Source/ && /gpfs1/home/ibm/.local/easybuild/')

--------------------------------------

I have attached the log file along with this please let me know what is causing for this error.

Regards,
Satish Sherikar
HPC Application Engineer
IBM India Pvt Ltd
[easybuild-Qt-4.8.6-20191017.161953.ceJzH.log](https://github.com/easybuilders/easybuild-easyconfigs/files/3742496/easybuild-Qt-4.8.6-20191017.161953.ceJzH.log)

**Comment by zao** [comment]
I have no solution, but the problem that fails the build is an internal compiler error in the Intel compiler when building `JSParser.o`, as shown on line 36693 of your log.

**Comment by boegel** [comment]
There's little EasyBuild can do about an internal compiler error...

I think the best way forward here is to use a more recent version of the Intel compilers, or avoid compiling `Qt` with it (see also #8003)
