### ISSUE TITLE
local tensorflow_datasets unusable with Tensorflow 2 package

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9207]
I encountered a problem with https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0-foss-2019a-Python-3.7.2.eb

- The dependency python package `google.protobuf` is installed as an `*.egg` folder
- A `__init__.py` is created inside the google folder (in that egg-folder)
- Installing `tensorflow_datasets` via `pip install --user` afterwards (after module is loader) installs googleapis-common-protos with packages `google.[api, logging, ...]` **without** an `__init__.py` in the (local) `google` folder
- A subsequent load of tensorflow `python -c "import tensorflow"` will fail with `No module named 'google.protobuf'`

I traced this to the `__init__.py` in the installed egg package. Removing it makes this work.

AFAIK `google` itself is **not** a package, so `import protobuf from google` is not supposed to work, only `import google.protobuf` which is slightly different as it looks for the package "google.protobuf" but **not** for a package "google" which there is none.

However I failed to reproduce this with combinations of installing the packages into pyenv, user, and PYTHONPATH folders, so I believe this is something related to the egg folder.

It might be that the real solution would be that [googleapis-common-protos/](https://pypi.org/project/googleapis-common-protos/) fixes some issue, but in none of my experiments I could get protobuf to be imported with the EB installed tensorflow.

I tried:

- Adding `__init__.py` to .local/lib/pythonxx/site-packages/google
- Move EBINSTALL/site-packages/proto*.egg/google to EBINSTALL/site-packages/google
- Move the EGGINFO folder renaming to  EBINSTALL/site-packages/protobuf*.distinfo
- Installing various other google packages

In the end nothing but deleting the `__init__.py` worked so I conclude that this is an issue in the EB install which should not have the `__init__.py` file and probably just use `pip` to install the package.

**Comment by Flamefire** [comment]
I just found that adding the `__init__.py` is actually wrong in Pyten >= 3.3: http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html

> This has changed in Python 3.3: now any directory on sys.path with a name that matches the package name being looked for will be recognised as contributing modules and subpackages to that package.

And: 

> if a subdirectory encountered on sys.path as part of a package import contains an __init__.py file, then the Python interpreter will create a single directory package containing only modules from that directory, rather than finding all appropriately named subdirectories as described in the previous section.

Hence: The `__init__.py` is wrong and should be removed/not created for that EB config

**Comment by boegel** [comment]
@akesandgren Thoughts on this, since letting the `TensorFlow` easyblock add the `__init__` was done by you in https://github.com/easybuilders/easybuild-easyblocks/commit/1f2e517ddfd1b00a342c6abb55aef3fd93671a2b (via #1453)?

I guess we can make that conditional so it's only done for older Python versions?

**Comment by akesandgren** [comment]
I don't know python well enough to answer this. I think it was @zao that originally ran into this problem with __init__ and protobuf-python

**Comment by Flamefire** [comment]
> I don't know python well enough to answer this.

That's why I put the link above and the quote with the important bits. I'm no expert in Python packages too but the official source clearly (to me) states to avoid package-level `__init__.py` to allow multiple "repo-paths" to be considered (in this case: System, EB and User)
