### ISSUE TITLE
Python on GCCcore, PIP can't build wheel for package

### ISSUE THREAD

**Issue by shawarden** [easybuilders/easybuild-easyconfigs#9227]
The more recent versions of Python, using GCCcore instead of foss, seem unable to build wheel for packages.

```
Collecting pysam
  Using cached https://files.pythonhosted.org/packages/15/e7/2dab8bb0ac739555e69586f1492f0ff6bc4a1f8312992a83001d3deb77ac/pysam-0.15.3.tar.gz
Building wheels for collected packages: pysam
  Building wheel for pysam (setup.py): started
  Building wheel for pysam (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1
   command: /resource/easybuild/software/Python/3.7.4-GCCcore-8.3.0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ouloegc_/pysam/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ouloegc_/pysam/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8scwdssd --python-tag cp37
...
  /tmp/ccWd3mbv.s: Assembler messages:
  /tmp/ccWd3mbv.s:10: Error: unknown .loc sub-directive `view'
  /tmp/ccWd3mbv.s:10: Error: junk at end of line, first unrecognized character is `-'
  /tmp/ccWd3mbv.s:12: Error: unknown .loc sub-directive `view'
  /tmp/ccWd3mbv.s:12: Error: unknown pseudo-op: `.lvu1'
  /tmp/ccWd3mbv.s:13: Error: unknown .loc sub-directive `view'
...
  /tmp/ccWd3mbv.s:78760: Error: unknown pseudo-op: `.lvu25751'
  /tmp/ccWd3mbv.s:78761: Error: unknown .loc sub-directive `view'
  /tmp/ccWd3mbv.s:78761: Error: unknown pseudo-op: `.lvu25752'
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pysam
  Running setup.py clean for pysam
Failed to build pysam
```

[log.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/3812189/log.txt)

**Comment by boegel** [comment]
@shawarden Can you share the easyconfig file you were using?

It looks like you're building `Pysam` with the `GCCcore` toolchain, but without having `binutils` included as build dependency? That's crucial when using the `GCCcore` toolchain...

**Comment by shawarden** [comment]
I installed Python using the stock 4.0.1 easyconfig Python/Python-3.7.4-GCCcore-8.3.0.eb which lists `binutils` as a build dependency only.

We are attempting to install a set of packages via `pip install package`. Some of those packages (or their dependencies) require wheel, as in this example with `pysam` but it fails to compile.

I have added `binutils/.2.32` to the module as a normal dependency and it now works. I have gone back and added it to other Python modules built on GCCcore and they now work as desired.

Thank you.

**Comment by boegel** [comment]
@shawarden Thanks for the details!

This has come up before I think, we should indeed promote `binutils` are a runtime dep for `Python` to ensure that `pip install` that involves compilation works.

**Comment by akesandgren** [comment]
@boegel something like this?
https://github.com/akesandgren/easybuild-easyconfigs/commit/31d1f1ec7e3e88f8ba75462306263195ae3f53c6

**Comment by boegel** [comment]
@akesandgren :+1:

**Comment by akesandgren** [comment]
Now in PR #9402
