### ISSUE TITLE
R-bundle Bioconductur 3.9, dependency error.

### ISSUE THREAD

**Issue by HerderB** [easybuilders/easybuild-easyconfigs#9241]
Hello,

Trying to install R-bundle-Bioconductor-3.9-foss-2019a-R-3.6.0.eb but getting the following error. This is on EasyBuild 4.0.1. Logs are included in the attachment. Could anyone tell me what I need to do to install this package correctly?
[easybuild-R-bundle-Bioconductor-3.9-20191108.093521.rLRwj.log](https://github.com/easybuilders/easybuild-easyconfigs/files/3824491/easybuild-R-bundle-Bioconductor-3.9-20191108.093521.rLRwj.log)

ERROR: dependencies rda, threejs are not available for package MLInterfaces

**Comment by boegel** [comment]
@HerderB It looks like you've installed `R-3.6.0-foss-2019a.eb` with an earlier version of EasyBuild. That easyconfig was updated recently with a couple of additional extensions (see #8881), including `rda` and `threejs`.

You can let EasyBuild install (only) the missing extensions as follows:

```
eb --skip --force R-3.6.0-foss-2019a.eb
```

See also https://easybuild.readthedocs.io/en/latest/Partial_installations.html#installing-additional-extensions-using-k-skip

**Comment by HerderB** [comment]
That did the trick! thnx!
