### ISSUE TITLE
easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-ictce-5.3.0.eb should have -gpfs suffix

### ISSUE THREAD

**Issue by JensTimmerman** [easybuilders/easybuild-easyconfigs#926]
easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-ictce-5.3.0.eb depends on a HDFS with a versionsuffix, but it has no versionsuffix itsself, which causes confusion...

**Comment by Micket** [comment]
Indeed it should have (but this is now long since outdated and we don't have gpfs specific hacks to any HDF5 easyconfigs)
