### ISSUE TITLE
Decide how to specify framework to use with Horovod

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9262]
As discussed in https://github.com/easybuilders/easybuild-easyconfigs/pull/8952#issuecomment-552973290:

- Horovod is a `Distributed training framework for TensorFlow, Keras, PyTorch, and Apache MXNet.`, not only TensorFlow
- The current EC couples a specific Horovod version to a specific TensorFlow version w/o stating that in the module. How would you create a Horovod for TF 2?

The problem: It needs the frameworks installed before. See logic at https://github.com/horovod/horovod/blob/master/setup.py#L1369. It is not clear, how the dependency actually works, but I've seen logic to install different extensions depending on the version of PyTorch. I asked for clarification at https://github.com/horovod/horovod/issues/1508

For now it seems we need to couple the Horovod EC to a specific TF. How should that be done?

**Comment by boegel** [comment]
The obvious way would be to include the framework for which Horovod is installed in the `versionsuffix`, we leads to `Horovod-0.18.2-fosscuda-2019b-TensorFlow-2.0.0-Python-3.7.4.eb` in the case of #9301.

**Comment by boegel** [comment]
@Flamefire OK to close now #9301 got merged?
