### ISSUE TITLE
TensorFlow symlink patch does not work with CCache

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9325]
Unfortunately the patch from https://github.com/easybuilders/easybuild-easyconfigs/blob/b1e80bf0b1d94601a0d1435d436c596a1dd5ff78/easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.14.0_fix-cuda-build.patch does not work when using CCache (or any compiler wrapper) as it relies on the includes residing where the compiler is. When using a wrapper, that wrapper might be somewhere completely different.

I guess the real fix would be in Bazel to use realpaths everywhere and/or EB providing the location to the "system" headers (as per Bazel definition) by inspecting the loaded module(s)

**Comment by boegel** [comment]
fixed in #9333
