### ISSUE TITLE
NCL-6.6.2-intel-2018b.eb doesn't build with rpath support

### ISSUE THREAD

**Issue by casparvl** [easybuilders/easybuild-easyconfigs#9332]
So, we have EasyBuild enabled with ```RPATH``` support. As a result, during the sanity check, EasyBuild cleans the ```LD_LIBRARY_PATH``` and runs an ```ldd``` on all binaries to check if the ```RPATH``` has been set correctly. Currently, this fails for e.g. ```ncl``` for a few libraries:

```
        libpng16.so.16 => not found
        libjpeg.so.8 => not found
        libifcore.so.5 => not found
        libifport.so.5 => not found
```

For the first two, I will try to add 

```
    ('libpng', '1.6.34'),
    ('libjpeg-turbo', '2.0.0')
```

as dependencies and get back to you on if that works. For the other two: they are part of ```ifort``` and is actually located in

```
$EBROOTIFORT/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64
```

However, looking at the compile/link line actually used by NCL it does:

```
-L$EBROOTIFORT//compiler/lib/intel64
```

I found that ```NCL``` has a custom easyblock that does:

```
# adjust config file as needed
        ctof_libs = ''
        ifort = get_software_root('ifort')
        if ifort:
            if LooseVersion(get_software_version('ifort')) < LooseVersion('2011.4'):
                ctof_libs = '-lm -L%s/lib/intel64 -lifcore -lifport' % ifort
            else:
                ctof_libs = '-lm -L%s/compiler/lib/intel64 -lifcore -lifport' % ifort
```
So, that seems to be where it comes from, and it seems the ```$EBROOTIFORT/compiler/lib/intel64``` was the 'old' location (?).

Of course, I could correct this in the EasyBlock, but what I don't understand is why EasyBuild doesn't pick up on the ```LIBRARY_PATH```, which does include the correct directory, i.e.

```
$EBROOTIFORT/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64
```

Any clues what's going on here? And what is the 'most appropriate' way to fix this?

In addition, I had a second issue where it couldn't find ```yacc```. Not sure if it really posed problems (easybuild doesn't crash on it), but I figure including a ```Bison``` as build dependency in the EasyConfig should do the trick - I still have to test that.

**Comment by boegel** [comment]
> However, looking at the compile/link line actually used by NCL it does:
>
> -L$EBROOTIFORT/compiler/lib/intel64

I guess this was a symbolic link to the actual directory at some point...

The correct path for ifort 2018.3.222 seems to be `$EBROOTIFORT/compilers_and_libraries/linux/lib/intel64` (without the `/compiler/`).

> So, that seems to be where it comes from, and it seems the `$EBROOTIFORT/compiler/lib/intel64` was the 'old' location (?).

No, that's the (supposed) new location, check the condition again. :)

But it's wrong (see above).

> Any clues what's going on here? And what is the 'most appropriate' way to fix this?

What it looks like is that the `ifort` lib dir isn't getting RPATH'ed in because the one specified via `-L` doesn't exist...

This is not a problem when RPATH is not used, since then the required `-lifcore -lifport` is found anyway by the `$LIBRARY_PATH` being set by the `ifort` module...

If you use `eb --debug`, you should find an additional `rpath_wrapper_*.log` in the temporary directory used by that EasyBuild run, which hopefully gives more clues (I'd start by looking for lines with `lifport` in there).


For `yacc`, yes including `Bison` as a build dep should fix that.

**Comment by casparvl** [comment]
Ok, just a short update: I got it to build. Needed to make changes to both the block and config. This is what I wrote down in our own internal ticket:

EasyBlock changes

-A custom EasyBlock to fix the lib => lib64 error to make sure the correct rpath is set for the netCDFlibraries.
-Replaced the path to the intel libraries (libifcore.so.5 and libifport.so.5) to ``.../compilers_and_libraries/...```


EasyConfig changes

-A patch to add -Dlinux=linux to the ymake script to make sure the. A dirty workaround, but ok.
-Additional deps (libpng and libjpeg-turbo) and builddeps (Bison) to fix rpath-sanity check and missing yacc problem.

Anyway, since I also have a custom FSL EasyBlock that now works with FSL-6.0.2 (yeey), I really have to find some time to do the actual contributions/PRs... Feel free to remind/push me ;-)

**Comment by casparvl** [comment]
Ok, the ugly ```-Dlinux=linux``` is no longer needed, the EasyBlock now points to ```$EBROOTIFORT/lib/intel_64``` and this path thus no longer contains ```linux```.
