### ISSUE TITLE
Bazel-0.25.2-GCCcore-8.2.0.eb depends on Python to build.

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyconfigs#9334]
https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-unix-prereq makes it clear that Bazel requires Python. Most systems have python installed by default, but there are systems, like RHEL8, that no longer ship a system-python. In these situations, the EasyBuild python may not be available after env is cleaned up and $PATH is stripped.

Things to keep in mind:

- Bazel docs states support for both python2 and python3, but it is hard to know how far back this support goes for python3.
- This is (probably) just a build dependency.
- Using whatever Python the toolchain offers is a good idea.

**Comment by boegel** [comment]
@terjekv We've tackled this recent for recent `Bazel` versions, see #9223 and #9299, did we miss a spot?

**Comment by terjekv** [comment]
Ah yes, for newer Bazel there are some fixed versions in develop. As far as I can tell though, not for Bazel-0.25.2-GCCcore-8.2.0? https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/b/Bazel/Bazel-0.25.2-GCCcore-8.2.0.eb

**Comment by migueldiascosta** [comment]
fixed by #9342
