### ISSUE TITLE
GCCcore-6.4.0

### ISSUE THREAD

**Issue by ANaumann85** [easybuilders/easybuild-easyconfigs#9345]
Dear Easy-Builders,

I try to build the quite old compiler gcc-6.4.0 using

> eb GCCcore-6.4.0.eb

and that build fails. But the logfile, which is appended to the issue, contains only the first 300 characters, which show no error at all. Therefore I went to the corresponding build directory, run make again, and get the compiler error:

> ../../../../libsanitizer/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc: In function ‘int __sanitizer::TracerThread(void*)’:
../../../../libsanitizer/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:270:22: error: aggregate ‘sigaltstack handler_stack’ has incomplete type and cannot be defined
   struct sigaltstack handler_stack;

What puzzles me, is that there is already a [patch for that problem](https://gist.github.com/froland/322a3320fcabd46a5702bd4a2a228198) and the patch is there. The logfile also states, that it applies the patch.

Do you have any hints, what I could do to correct that, or what I do wrong?

I see also a small relation to the [issue easybuilders/easybuild-easyblocks#495 on easybuild](https://github.com/easybuilders/easybuild/issues/495), which got a response stating, that gcc 8.2 might lead to problems with binutils 2.30. My system has installed the gcc-7.4.0, which is also newer than the gcc-6.4.0. 

My easybuild-version is:

> eb --version
This is EasyBuild 4.0.1 (framework: 4.0.1, easyblocks: 4.0.1) on host moivre.

[easybuild-nEWZ6N.log](https://github.com/easybuilders/easybuild-easyblocks/files/3870451/easybuild-nEWZ6N.log)

**Comment by boegel** [comment]
@ANaumann85 There are indeed patches included for GCCcore-6.4.0, but the ones from https://gist.github.com/froland/322a3320fcabd46a5702bd4a2a228198 are not included yet at first sight...

**Comment by ANaumann85** [comment]
But the eb-file GCCcore-6.4.0.eb references the patch in line 34. That is why, I am wondering, why it is not applied.
And the logfile states in line 112 
> INFO Applying patch GCCcore-6.4.0_fix-linux-unwind-fix-ucontext.patch

that it does apply the patch.

**Comment by boegel** [comment]
@ANaumann85 Different patch, see https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0_fix-linux-unwind-fix-ucontext.patch

**Comment by ANaumann85** [comment]
Thank you very much for the hint! I found my mistake. There is a patch file with the name
> GCCcore-6.3.0_fix-sanitizer_linux.patch
and for a previous GCC version. 
Adding that file to the list of patches for GCC-6.4.0 fixes the problem.
In my opinion, we can close this issue. 
But one question remains. 
How should one use the EasyBuild infrastructure on new systems, if __Building old GCC versions on a recent OS is bound to be troublesome__ ? I hoped to use it for easier reproducability and building of software, instead of using container solutions.

**Comment by boegel** [comment]
> How should one use the EasyBuild infrastructure on new systems, if _Building old GCC versions on a recent OS is bound to be troublesome_ ? I hoped to use it for easier reproducability and building of software, instead of using container solutions.

Realistically speaking, I think it's unreasonable to expect that you'll be able to always build software  on future OSs without effort. EasyBuild helps in the sense that it fixes the versions of all dependencies (incl. compiler & co in the toolchain), but you're bound to run into problems sooner or later.
Containers are actually a good way to deal with this, since it takes the OS out of the equation.
You can combine EasyBuild & containers, see https://easybuild.readthedocs.io/en/latest/Containers.html .

We are working on support to more easily update to a new toolchain, but then you still may need to fiddle with compiler options, especially when dragging forward an old codebase.

**Comment by ANaumann85** [comment]
I think the hint to the containers answers the last question.
Thank you for your help and wish you nice weekend.

**Comment by boegel** [comment]
missing patch added in #9362, fix will be included in the upcoming EasyBuild v4.1.0
