### ISSUE TITLE
Patching Problem When Building QuantumEspresso

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#9352]
Hi.

I am trying to install the latest QE version on Tier-1 for a user. He forwarded me to the easyconfig files from UA. However, after adapting the EB config file [(to be found here,](https://raw.githubusercontent.com/hpcuantwerpen/UAntwerpen-easyconfigs/master/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-intel-2018b-hybrid.eb) I get the following error:

`== 2019-11-21 14:47:11,455 build_log.py:163 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Can't determine patch level for patch /myData/easybuild/work/QuantumEspresso/backports-6.4.1.diff from directory myShm/easybuild/QuantumESPRESSO/6.4.1/intel-2018a-hybrid (at easybuild/tools/filetools.py:1004 in apply_patch)
== 2019-11-21 14:47:11,455 easyblock.py:3050 WARNING build failed (first 300 chars): Can't determine patch level for patch /myData/easybuild/work/QuantumEspresso/backports-6.4.1.diff from directory myShm/easybuild/QuantumESPRESSO/6.4.1/intel-2018a-hybrid
`

I have attached the redirected log file, and the EB file

Br
Ehsan

[logs-qe.tar.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/3874995/logs-qe.tar.gz)

**Comment by boegel** [comment]
@moravveji This basically means the patch file is incorrect.

Did you spot this comment from the easyconfig file?

```
# patchfile backports downloaded from QE's github site; manually replace a/ and b/ by real path
```

**Comment by moravveji** [comment]
Thanks Kenneth for your comment. I am still not following! 
I have certainly downloaded the `backports-6.4.1.diff` from github, and have set the path in the EB file explicitly now:

`patches = [
#    '%(name)s-%(version)s_drop_LIBS_before_configure_of_fox.patch',
    'backports-6.4.1.diff',
#    'QuantumESPRESSO-5.4.0_yambo-fixes.patch',
]
`
Is that not enough? Only one patch file is needed?

To be 100% sure, I downloaded the same file again, and retried, and the errors are the same.

**Comment by boegel** [comment]
@moravveji The comment says that you need to edit the patch manually to make it apply.

**Comment by boegel** [comment]
I don't think EasyBuild can handle auto-downloading from a funky URL like http://qe-forge.org/gf/project/q-e/scmsvn/?action=browse&path=%2F%2Acheckout%2A%2Ftags%2FQE-5.2.1%2Fespresso%2Farchive%2Fplumed-1.3-qe.tar.gz&revision=11758 (yet), so manual download + putting it in the source path where `eb` will look for the file is the only way.

**Comment by moravveji** [comment]
> @moravveji This basically means the patch file is incorrect.
> 
> Did you spot this comment from the easyconfig file?
> 
> ```
> # patchfile backports downloaded from QE's github site; manually replace a/ and b/ by real path
> ```

I am still stuck with setting the correct paths in the patch file for "a/" and "b/". 
Shall a/ and b/ be different?
Where shall they point to?

**Comment by boegel** [comment]
What does the top of the patch file look like?

Usually EasyBuild is able to figure things out by itself, but it depends on the exact paths used in the patch, and from which directory the patch is being applied...

**Comment by moravveji** [comment]
The top of the patch file is:

`QuantumEspresso$> head backports-6.4.1.diff
diff --git a/FFTXlib/fft_types.f90 b/FFTXlib/fft_types.f90
`

The patch file sits besides the .eb file, and i presume it is applied from the same folder. Is there a way to tweak that?

**Comment by boegel** [comment]
@moravveji The patch is supposed to be applied in the unpacked `qe-6.4.1.tar.gz`, but because there are multiple source files EasyBuild doesn't start in the unpacked `qe-6.4.1.tar.gz` directory, but one level up.

So, you'll need to tell it that the patch should be applied in the correct directory. Try this:

```python
patches = [('backports-%(version)s.diff', 'qe-%(version)s')]
```

That tell EasyBuild to apply the patch from the `qe-6.4.1` subdirectory, rather than the current directory.
