### ISSUE TITLE
consider BLIS as replacement for OpenBLAS in foss toolchain?

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#9354]
see:

* https://twitter.com/kehoste/status/1197390357773901824
* https://github.com/flame/blis/blob/master/docs/Performance.md#skylakex-results

**Comment by omula** [comment]
It seems it is not yet ready for power9 https://github.com/flame/blis/issues/359

Should this stop the adoption for x86_64?

**Comment by bartoldeman** [comment]
Actually openblas git is now in a much better state. For dgemm it is comparable to mkl with the most recent merged PRs. So time can tell, hopefully a release before the 2020 toolchains.

**Comment by Micket** [comment]
With FlexiBLAS we no longer need to make this choice.
