### ISSUE TITLE
Bug between OpenFOAM-6 and the vader transport layer of OpenMPI

### ISSUE THREAD

**Issue by lexming** [easybuilders/easybuild-easyconfigs#9392]
`OpenFOAM` version 6 is affected by a bug with the `vader` transport layer on `OpenMPI` versions `>=2.1.3` and `>=3.1.0`. 

Bug report in openfoam.org: https://bugs.openfoam.org/view.php?id=3071
* Solved in OpenFOAM-6 by downgrading to `OpenMPI-3.0.2`.
* It might also affect OpenFOAM-7, where they solved it by downgrading to `OpenMPI-2.1.1` (commit https://github.com/OpenFOAM/OpenFOAM-7/commit/3a7b76198ef8d30a83396fc6a9910806922065cb#diff-b6e06c818a822d31a893f292608f72af)

The origin of the bug is not clear and seems to be related to some race condition that makes it difficult to reproduce. However, we have instances of this bug occurring in our cluster with `OpenFOAM-6` and just using 40 cores distributed on 5 nodes.

The solution would be to move `OpenFOAM-6-foss-2018b` to `foss/2017b`.

**Comment by boegel** [comment]
@akesandgren mentioned in Slack that the issue should be fixed in OpenMPI 3.1.3, which is included in `foss/2019a`, so upgrading the toolchain to `foss/2019a` or `foss/2019b` seems like a better solution?

**Comment by lexming** [comment]
@boegel I can confirm that a build of `OpenFOAM-6` with `foss/2019b` fixes OF bug 3071. The PR for it is already open.
I have not tried with `foss/2019a` because we do not currently have a build of ParaView in that toolchain and I do not think that it is worth the effort.
Regarding `OpenFOAM-6-foss-2018b`, what should be done with it? Do we remove the easyconfig as it is buggy?

**Comment by boegel** [comment]
I don't think we should try to remove an easyconfig file every time an issue arises with the software in particular circumstances (I don't think we'd have much left ;) ).

Especially not since there's a workaround in this case (using `mpirun --mca btl self,sm`).

**Comment by lexming** [comment]
Sure, I was just asking to know what is done in such cases. I will add a comment to `OpenFOAM-6-foss-2018b` to warn future users.
On the other hand, using `mpirun --mca btl self,sm` is not possible by default in `foss/2018b` as the shared memory BTL was removed in OpenMPI v3.0 (https://github.com/open-mpi/ompi/pull/3889)

**Comment by lexming** [comment]
Fixed in #9440 and #9445
