### ISSUE TITLE
CUDA 10.1.243 install broken on power9

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9437]
The installer from nvidia is broken: https://devtalk.nvidia.com/default/topic/1063995/cuda-setup-and-installation/cuda-10-1-243-10-1-update-2-ppc64le-run-file-installation-issue/

TLDR: It fails to install files like `include/cublas.h` and finally removes some files afterwards. No fix was released but NVIDIA refers to 10.2 instead.

I propose to redefine fosscuda/2019b (unreleased by now) to use CUDA 10.2 to avoid the issue.

ccing @boegel

**Comment by akesandgren** [comment]
fosscuda/2019b is already part of EB 4.0.1 and uses CUDA 10.1.243

**Comment by Flamefire** [comment]
Oh I see, my bad.

Then there is a problem :(

**Comment by branfosj** [comment]
@Flamefire We have a workaround in our local version. See https://github.com/bear-rsg/easybuild-easyconfigs/blob/2019b/easybuild/easyconfigs/c/CUDA/CUDA-10.1.243.eb - which sorts out putting the missing files in place before the check for them fails.

**Comment by Flamefire** [comment]
Thanks! I'm preparing to include this in the CUDA easyblock. Testing now, looks good so far
