### ISSUE TITLE
Crypthography python package broken on Power9 due to undefined symbol: pthread_atfork

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9446]
The post-install check fails with 

```
build_log.py:164 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Sanity check failed: extensions sanity check failed for 1 extensions: paramiko
failing sanity check for 'paramiko' extension: command "python -c "import paramiko"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "<...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/paramiko/transport.py", line 129, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "<...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/paramiko/transport.py", line 190, in Transport
    if KexCurve25519.is_available():
  File "<...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/paramiko/kex_curve25519.py", line 30, in is_available
    X25519PrivateKey.generate()
  File "<...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 38, in generate
    from cryptography.hazmat.backends.openssl.backend import backend
  File "<...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "<...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 74, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "<...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: <...>/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: pthread_atfork,  (at easybuild/framework/easyblock.py:2593 in _sanity_check_step)
```

This seems to be similar to  e.g. https://bugs.gentoo.org/630578 which was caused by 

> It looks like this is happening because we export the CC variable in the ebuild environment. This overrides the default python CC config var, which contains "-pthread".

And fixed by appending `-pthread`

Underlying bug report: https://github.com/pyca/cryptography/issues/5084

**Comment by Flamefire** [comment]
The issue is caused by Paramiko >= 2.5.0 where [this change](https://github.com/paramiko/paramiko/commit/02d4370ce7842a418ca27ba9307961d9ecf87397) introduced loading of cryptography/hazmat/bindings/_openssl.abi3.so at import of paramiko which always(?) ran into a missing symbol `pthread_atfork` probably caused by a wrongly positioned `-lpthread`, see https://ryanarn.blogspot.com/2011/07/curious-case-of-pthreadatfork-on.html for details

**Comment by Flamefire** [comment]
The issue can be solved by exporting `LDFLAGS=-pthread`. Where should this be done? In the python EasyBlock? In the PythonPackage EB? In a new cryptography EB? In (many) cryptography ECs?

**Comment by branfosj** [comment]
@Flamefire Sorry - I've not yet had an opportunity to pass back all of the changes we required to get these items built on Power9. For this we pass the relevant flag in during building the cryptography library during the Python install - https://github.com/bear-rsg/easybuild-easyconfigs/blob/2019b/easybuild/easyconfigs/p/Python/Python-3.7.4-GCCcore-8.3.0.eb#L119

**Comment by Flamefire** [comment]
Seems that `preinstallopts` is also an option. Any reason you chose CFLAGS over LDFLAGS and lpthread over pthread?

Downside of this solution: It is specific to this single EC although ALL ECs are affected hence my idea of putting it into an EB. Try to use the cryptography module on Power with Python 3.7.2 and you'll see...

**Comment by branfosj** [comment]
We put the line I link to in CFLAGS over LDFLAGS as adding that line in like that fixed a similar problem with an older version of Pytorch (2018b toolchain) and it fixed the problem here.

We have Python 3.7.2 installed - though that will be with an older paramiko and cryptography.

**Comment by Flamefire** [comment]
> adding that line in like that fixed a similar problem with an older version of Pytorch (2018b toolchain)

Oh? Do you still have the details on what exactly failed?

>  though that will be with an older paramiko and cryptography.

Doesn't matter for this bug. It only surfaced during the sanity check of importing paramiko after updating post 2.5, all versions of cryptography (cursory check only) are affected as none of them link pthread as they ought to. Testcase: `python -c "from cryptography.hazmat.bindings._openssl import lib"`

**Comment by branfosj** [comment]
> > adding that line in like that fixed a similar problem with an older version of Pytorch (2018b toolchain)
> 
> Oh? Do you still have the details on what exactly failed?

No. I can find the commit that adds the CFLAGS line, but no details of the exactly what fails.


> > though that will be with an older paramiko and cryptography.
> 
> Doesn't matter for this bug. It only surfaced during the sanity check of importing paramiko after updating post 2.5, all versions of cryptography (cursory check only) are affected as none of them link pthread as they ought to. Testcase: `python -c "from cryptography.hazmat.bindings._openssl import lib"`

Oh, sorry - I misunderstood where I'd see the issue and tested the wrong item. We've not had a user report of this causing an issue - hence why we only changed the Python-3.7.4-GCCcore-8.3.0.eb.
