### ISSUE TITLE
Bazel not installable on Power9 - Missing Java 11

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9450]
Bazel requires(?) Java and the EC depends on Java-11, which is not available for Power9 (hard-coded x86). There is Java-1.8 which has a Power9 EC however this fails to install on our system due to 

> ERROR: Failed to process easyconfig /home/s3248973/git/easybuild-easyconfigs/easybuild/easyconfigs/j/Java/Java-1.8_191-b26-OpenJDK.eb: One or more OS dependencies were not found: [('cups-devel',), ('alsa-lib-devel',)]

Possible solutions:
- Not loading the Java module makes Bazel use the system-java (trace output: `JAVAC=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.ppc64le/bin/javac`) which seems to work
- Downgrade to JDK8, which should be done anyway [JDK 8. You must install version 8 of the JDK. Versions other than 8 are not supported.](https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-bazel) but OS deps are a (possible) problem
- Allow overwrite of used Java to use system-Java where possible

**Comment by Flamefire** [comment]
It seems that Bazel does not (cleanly) work with JDK8 but only with JDK10+ even though their docu states otherwise: https://github.com/bazelbuild/bazel/issues/7943#issuecomment-489713647

**Comment by boegel** [comment]
I'd like to hear how @branfosj has dealt with this...

**Comment by branfosj** [comment]
For Java 11 we have gone with using the third party SAP builds of OpenJDK - as per #9371. There is also the possibility of producing a Java 11 equivalent of https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/j/Java/Java-1.8_191-b26-OpenJDK.eb

**Comment by Flamefire** [comment]
That would be possible too. It depends on what to rely on: The official Bazel docs or what was stated otherwise. IMO there is no need upgrading the required Java version if JDK8 still works. See https://github.com/easybuilders/easybuild-easyconfigs/pull/9454 (I was able to build Bazel with that)

**Comment by boegel** [comment]
@Flamefire Did you mean to refer to #9455 rather than #9454 (or are both relevant)?

**Comment by Flamefire** [comment]
Yes, both.
