### ISSUE TITLE
Bootstrap CMake in parallel

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9468]
The CMake ECs build slower than thy need to, the bootstrapping supports `--parallel=n` which heavily speeds up the process.

Proposal: Use it.

**Comment by boegel** [comment]
I see no reason not to use it, unless it causes problems, for example on systems with lots of cores (but the test reports in #9469 don't indicate any issues).

**Comment by boegel** [comment]
`--parallel` added to most recent CMake easyconfig in #9469

Is that enough to close this, or shall we make an effort to also use `--parallel` in older CMake easyconfigs?

**Comment by Flamefire** [comment]
Would be easy to add it to the other ECs to but testing them will be time consuming. And gotta check in which versions this was introduced. Maybe add it to CMake 3.10+ ECs? Or all GCCcore and system toolchain ones (easily testable, can't test with old intel compilers)

**Comment by boegel** [comment]
We can test this fairly easily, but changing this for all CMake 3.10+ easyconfigs + the ones using `system` toolchain makes sense to me, that's good enough going forward.
