### ISSUE TITLE
matplotlib/3.1.1 finds a conflict between intel and GCCcore Python

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#9487]
Hi.

I am trying to build matplotlib/3.1.1-intel-2018a-Python-3.7.2. However, I get the following error:

`== 2019-12-12 15:02:20,666 easyblock.py:294 INFO Closing log for application name matplotlib version 3.1.1
== 2019-12-12 15:02:20,667 build_log.py:252 INFO FAILED: Installation ended unsuccessfully (build directory: /dev/shm/easybuild/matplotlib/3.1.1/intel-2018a-Python-3.7.2): build failed (first 300 chars): Python/3.7.2-GCCcore-6.4.0(43):ERROR:150: Module 'Python/3.7.2-GCCcore-6.4.0' conflicts with the currently loaded module(s) 'Python/3.7.2-intel-2018a'
== 2019-12-12 15:02:20,667 build_log.py:252 INFO Results of the build can be found in the log file(s) /tmp/ca6569a93e/eb-Qdi1ae/easybuild-matplotlib-3.1.1-20191212.150219.erGTn.log
== 2019-12-12 15:02:20,668 build_log.py:163 ERROR EasyBuild crashed with an error (at ?:124 in __init__): build failed (first 300 chars): Python/3.7.2-GCCcore-6.4.0(43):ERROR:150: Module 'Python/3.7.2-GCCcore-6.4.0' conflicts with the currently loaded module(s) 'Python/3.7.2-intel-2018a' (at easybuild/main.py:115 in build_and_install_software)
== 2019-12-12 15:02:20,669 build_log.py:163 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Build of /myData/easybuild/work/matplotlib/matplotlib-3.1.1-intel-2018a-Python-3.7.2.eb failed (err: "build failed (first 300 chars): Python/3.7.2-GCCcore-6.4.0(43):ERROR:150: Module 'Python/3.7.2-GCCcore-6.4.0' conflicts with the currently loaded module(s) 'Python/3.7.2-intel-2018a'") (at easybuild/main.py:147 in build_and_install_software)`

I have attached the build logs and the easyconfig file. In the latter, I have made sure that none of the dependencies loads an unwanted Python; yet the issue is there.

Am I making a mistake somewhere?

Thanks for your help.
Ehsan
[matplotlib.log.tar.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/3956343/matplotlib.log.tar.gz)

**Comment by boegel** [comment]
It's a bit hard to tell since you didn't provide a debug log, but it seems like this is due to the hardcoded subtoolchain for `Tkinter` (which depends on `Python`).

So, first the `Python` dependency is resolved using `module load Python/3.7.2-intel-2018a`, and then `Tkinter` is resolved via `module load Tkinter/3.7.2-GCCcore-6.4.0` (which loads `Python/3.7.2-GCCcore-6.4.0` as a dependency).

This is self-inflicted as far as I can tell, since we don't have a `Python` 3.7.2 easyconfig with `intel/2018a`...

**Comment by moravveji** [comment]
That is actually true. Correct catch!
I am trying to build Tkinter with intel/2018a, to circumvent this issue. 
I will close this ticket.

Thanks for the tip.
