### ISSUE TITLE
Python2 & 3 Multi-deps and blacklisting

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyconfigs#9498]
I was asked to bring it to a separate issue discussion from here; (https://github.com/easybuilders/easybuild-easyconfigs/commit/0341ea48930c9f11352f17f755fe73fd3019e47c)

This comes from PyYaml, which, in a clean install, will install both Python2 and Python3, since it multi-depends on both.

I don't really understand the rationale of such a thing, since pretty much every other easyconfig file was dependent on a single version of Python, and if one has two pythons, having two PyYaml wasn't a big issue (at least smaller than having one full Python being brought back from the dead).

This is the quote from @boegel :

>  Reverting this is difficult now, since it implies also renaming the easyconfig with a versionsuffix.
> We can look into somehow telling EasyBuild to ignore Python 2.x used in multi_deps though, via a configure option like eb --multi-deps-blacklist or something along those lines.
> If you opt-in to that, your modules would obviously not be compatible with both Python 2 & 3 anymore.
> Please open an issue on this, since discussing this in a commit is a bit hard to track...

**Comment by Micket** [comment]
We no longer multi deps python 2 and 3.
