### ISSUE TITLE
Incorrect MASS 7.3-51.4 checksum value of R-3.6.0-foss-2019a.eb

### ISSUE THREAD

**Issue by sinonkt** [easybuilders/easybuild-easyconfigs#9602]
can't build R-3.6.0-foss-2019a.eb
```
    ('MASS', '7.3-51.4', {
        'checksums': 
              ['9911d546a8d29dc906b46cb53ef8aad76d23566f4fc3b52778a1201f8a9b2c74'],
        }),
```
this -> 9911d546a8d29dc906b46cb53ef8aad76d23566f4fc3b52778a1201f8a9b2c74
should be -> 844270a2541eaed420871dfb61d681aa67ee57126645fb6b144b436c25698eeb

**Comment by boegel** [comment]
@sinonkt Thank you for the bug report!

We've also hit this in #9519, where we investigated the issue, and found that the new source tarball only has a trivial difference in publication date, without any other changes (see https://github.com/easybuilders/easybuild-easyconfigs/pull/9519#issuecomment-568768235).

Therefore, we'll fix this by adding two acceptable checksums for this `MASS` version, as follows:

```python
```
