### ISSUE TITLE
SLEPc not building due to mpiCC used in PETSc dependency

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9610]
SLEPc does a configure check linking a C application against PETSc, which was build with CXX support and hence used `mpiCC`. But as a C application is built `mpicc` is used, which does not link `libmpi_cxx` and hence fails with `ERROR: Unable to link with PETSc`

**Comment by boegel** [comment]
@Flamefire With which `SLEPc`/`PETSc` versions (or easyconfigs) are you seeing this?

**Comment by Flamefire** [comment]
SLEPc 3.11.0-foss-2018b and 3.8.3-foss-2017b

Probably similar issue to https://github.com/easybuilders/easybuild-easyconfigs/issues/9640 as mpi_cxx is ... "not good"

**Comment by boegel** [comment]
I'm not seeing this with `SLEPc 3.11.0-foss-2018b.eb`, can you provide more context/details?

Full log available at https://gist.github.com/boegel/4aa9d5c874f6247180afd63c3f75b45f for successful installation on my end...

**Comment by Flamefire** [comment]
On your end it is using mpicc: `Using C/C++ linker: mpicc`, gotta check what is different on mine

**Comment by Flamefire** [comment]
Ok, found it. The relevant output is:

```
== 2020-01-13 12:36:10,424 build_log.py:164 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " ./configure --prefix=/scratch/ws/s3248973-EasyBuild/easybuild/eb/SLEPc/3.11.0-foss-2018b   " exited with exit code 1 and output:
Checking environment... done
Checking PETSc installation... 
ERROR: Unable to link with PETSc
ERROR: See "installed-arch-linux2-c-opt/lib/slepc/conf/configure.log" file for details
```

The issue is the same as #9640 that mpi-cxx is used in OpenMPI which adds the symbols

**Comment by Flamefire** [comment]
And even more confusing: The output of the failure in the mentioned log is:

```
/scratch/ws/s3248973-EasyBuild/easybuild/eb/PETSc/3.11.0-foss-2018b-downloaded-deps/lib/libpetsc.so: error: undefined reference to 'ompi_mpi_cxx_op_intercept'
/scratch/ws/s3248973-EasyBuild/easybuild/eb/PETSc/3.11.0-foss-2018b-downloaded-deps/lib/libpetsc.so: error: undefined reference to 'MPI::Comm::Comm()'
/scratch/ws/s3248973-EasyBuild/easybuild/eb/PETSc/3.11.0-foss-2018b-downloaded-deps/lib/libpetsc.so: error: undefined reference to 'MPI::Datatype::Free()'
/scratch/ws/s3248973-EasyBuild/easybuild/eb/PETSc/3.11.0-foss-2018b-downloaded-deps/lib/libpetsc.so: error: undefined reference to 'MPI::Win::Free()'
```

And indeed `ldd` on `libpetsc.so` does not mention libmpi_cxx.so. Even stranger: The build seems to only build with a C compiler, still the library contains MPI_cxx symbols (verified by grepping for the symbols)

**Comment by Flamefire** [comment]
Ok found: libpetsc links to a static library libsuperlu_dist.a which is probably compiled as C++ and hence pulls in that symbol. I'll try to compile PETSc with `-DOMPI_SKIP_MPICXX` now and see if that works.

**Comment by Flamefire** [comment]
One fix is in https://github.com/easybuilders/easybuild-easyblocks/pull/1917, see discussion https://github.com/easybuilders/easybuild-easyblocks/pull/1917#issuecomment-574658562 for other solutions

**Comment by Flamefire** [comment]
Fixed with https://github.com/easybuilders/easybuild-easyblocks/pull/1917
