### ISSUE TITLE
Lot's of regexps improperly escaped

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9616]
There are a lot of ECs and even the EC test itself which use a regexp in a regular string instead of a raw string which leads to invalid escape sequences like  `"\."`.

Proposal: Use pylint on CI in addition to flake8 and enable the corresponding check. Optionally check for other useful checks and enable them as well

**Comment by boegel** [comment]
Do you have a specific example?

**Comment by Flamefire** [comment]
CTRL+F first hit in the test is https://github.com/easybuilders/easybuild-easyconfigs/blob/31fd0f7dd764a93975e0f63ddf1a00895288f882/test/easyconfigs/easyconfigs.py#L435-L437. There are many more according to my pylint though. Also running the test loading the ECs spits out deprecationwarnings.

**Comment by boegel** [comment]
Easy to check with `pycodestyle` >= 2.5.0:

```
$ pycodestyle --select W605 easybuild
easybuild/tools/include.py:145:40: W605 invalid escape sequence '\('
easybuild/tools/include.py:145:44: W605 invalid escape sequence '\)'
easybuild/tools/include.py:145:47: W605 invalid escape sequence '\s'
easybuild/tools/module_generator.py:738:49: W605 invalid escape sequence '\['
easybuild/tools/module_generator.py:738:51: W605 invalid escape sequence '\]'
easybuild/tools/modules.py:677:35: W605 invalid escape sequence '\s'
easybuild/tools/modules.py:677:60: W605 invalid escape sequence '\s'
easybuild/tools/modules.py:942:23: W605 invalid escape sequence '\['
easybuild/tools/modules.py:942:25: W605 invalid escape sequence '\s'
easybuild/tools/modules.py:942:32: W605 invalid escape sequence '\s'
easybuild/tools/modules.py:942:39: W605 invalid escape sequence '\s'
easybuild/tools/modules.py:942:46: W605 invalid escape sequence '\s'
easybuild/tools/modules.py:942:53: W605 invalid escape sequence '\s'
easybuild/tools/modules.py:942:56: W605 invalid escape sequence '\]'
easybuild/tools/modules.py:1161:40: W605 invalid escape sequence '\s'
easybuild/tools/modules.py:1369:58: W605 invalid escape sequence '\('
easybuild/tools/modules.py:1369:87: W605 invalid escape sequence '\)'
easybuild/tools/run.py:337:15: W605 invalid escape sequence '\s'
easybuild/tools/systemtools.py:333:46: W605 invalid escape sequence '\d'
easybuild/tools/systemtools.py:457:53: W605 invalid escape sequence '\s'
easybuild/tools/systemtools.py:461:52: W605 invalid escape sequence '\s'
easybuild/tools/systemtools.py:699:35: W605 invalid escape sequence '\s'
easybuild/tools/systemtools.py:699:38: W605 invalid escape sequence '\('
easybuild/tools/systemtools.py:699:45: W605 invalid escape sequence '\)'
easybuild/tools/systemtools.py:699:47: W605 invalid escape sequence '\s'
easybuild/tools/systemtools.py:699:64: W605 invalid escape sequence '\s'
easybuild/tools/systemtools.py:699:69: W605 invalid escape sequence '\s'
easybuild/tools/module_naming_scheme/categorized_mns.py:58:47: W605 invalid escape sequence '\S'
easybuild/tools/module_naming_scheme/mns.py:165:42: W605 invalid escape sequence '\S'
easybuild/tools/containers/utils.py:81:22: W605 invalid escape sequence '\d'
easybuild/tools/containers/utils.py:81:25: W605 invalid escape sequence '\.'
easybuild/tools/containers/utils.py:81:27: W605 invalid escape sequence '\d'
easybuild/tools/containers/utils.py:81:31: W605 invalid escape sequence '\.'
easybuild/tools/containers/utils.py:81:33: W605 invalid escape sequence '\d'
easybuild/scripts/bootstrap_eb.py:611:53: W605 invalid escape sequence '\('
easybuild/scripts/bootstrap_eb.py:611:90: W605 invalid escape sequence '\)'
easybuild/toolchains/compiler/gcc.py:160:34: W605 invalid escape sequence '\d'
```

@Flamefire Are you up for taking a stab at fixing this yourself, by adding `pycodestyle --select W605 test easybuild` to `.travis.yml` and `.github/workflows/unit_tests.yml`, and then by fixing the reported issues (for each of the repos)?

It's important to fix this since Python is planning to promote this to a `SyntaxError` in future Python versions, see https://bugs.python.org/issue32912 .

**Comment by Flamefire** [comment]
Can do, but maybe not today. Looks like a lot of work

**Comment by boegel** [comment]
I wasn't expecting you to do that today.

I'm not sure if this will be a lot of work, since it's just using `r""` rather than `""` in the places that `pycodestyle` complains about, but it's mostly a manual job probably, that's true...

**Comment by Flamefire** [comment]
No need for another tool, flake8 seems to be able to detect this too. I'm wondering why this doesn't come up though. Especially for the EasyBlocks repo flake8 reports many issues with indentation and regexps locally but CI passes. Example: https://github.com/easybuilders/easybuild-easyblocks/pull/1922/files#diff-a97ee57f46b34f174cdf128acb3cc4b3R77 should have triggered flake8 due to indentation

**Comment by Flamefire** [comment]
To make this explicit: I'm proposing to enable flake8 stylecheck on all *.py files for all repos. Maybe there are some exclusions required for purposely mis-formated test files

**Comment by verdurin** [comment]
Further thoughts on fixing this?

**Comment by Flamefire** [comment]
I proposed enabling `flake8` on CI over the whole codebase and using `autopep8` to automatically fix >90% of the issues. Pending @boegel reply. See https://easybuild.slack.com/archives/C34UA1HT7/p1585218240086400?thread_ts=1585051909.413800&cid=C34UA1HT7

**Comment by boegel** [comment]
@Flamefire This is good to close now I think?

**Comment by Flamefire** [comment]
Yes, we have flake8 now on for all repos
