### ISSUE TITLE
extra_vars setup

### ISSUE THREAD

**Issue by fenz** [easybuilders/easybuild-easyconfigs#9629]
I was installing this easyconfig: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/i/impi/impi-2019.6.166-iccifort-2020.0.166.eb
using Easybuild 4.1.0 (current stable)

And I figured out there was an issue with the libfabric_rebuild, I saw this will be fixed in the new release (https://github.com/easybuilders/easybuild-easyblocks/pull/1896) but for the time being I decided to set the rebuild to False to solve the issue.
I saw some commented code:
```
# set up all the mpi commands to default to intel compilers
# set_mpi_wrappers_all = 'True'
```

and I set the variable like this:
`libfabric_rebuild = 'False'`

but nothing changed.
After spending some time I tried to assign a Boolean value instead of a string
`libfabric_rebuild = False`

And the installation ended successfully

So I have some questions:
1) Is it supposed to be like this?
2) Is there a rule to decide when to use a String and when a Boolean as type to assign to a variable?

**Comment by boegel** [comment]
@fenz `False` is a boolean value in Python, while `'False'` is a string value, (and any non-empty string is equivalent to `True` in Python:

```python
>>> bool(False)
False
>>> bool('False')
True
```

So if the easyblock does `if self.cfg['libfabric_rebuild']`, and the value for `libfabric_rebuild` is `'False'`, then the condition evaluates to `True`...

In general, for boolean easyconfig parameters you should use `True` or `False`, hopefully the help text mentioned in `eb -a -e EB_impi` (for example) makes it clear enough; usually the default value  is helpful too.

**Comment by fenz** [comment]
Thanks for the answer, I know the difference between Boolean and String, but it is still not clear how to understand when to use what. 
Let's take as example 3 vars used in the impi easyconfig, (let's consider an old easyconfig because the new one can have issues: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/i/impi/impi-5.1.2.150-iccifort-2016.1.150-GCC-4.9.3-2.25.eb). I run the command eb -a -e EB_impi and I get:
```
EASYBLOCK-SPECIFIC
------------------
libfabric_rebuild*               Rebuild the internal libfabric instead of using the provided binary [default: True]
set_mpi_wrappers_all*            Set (default) compiler for all MPI wrapper commands [default: False]

FILE-MANAGEMENT
---------------
dontcreateinstalldir   Boolean to create (False) or not create (True) the install directory [default: False]
```

From this output (looking at default values) it seems to me they are all Boolean but in the commented part of the easyconfig about set_mpi_wrappers_all is:
```
# set up all the mpi commands to default to intel compilers
# set_mpi_wrappers_all = 'True'
```
used as a string. Is this a wrong assignment example?
For `dontcreateinstalldir` the output explicitly says: "Boolean", but it is used as String:
`dontcreateinstalldir = 'True'`
Is this wrong as well?

So, I guess you can get why I was a bit puzzled.

**Comment by boegel** [comment]
In both cases it should be `True` rather than `'True'` (but since `bool('True') == True` it doesn't actually make a difference.

This would also work to disable rebuilding of `libfabric`:

```python
libfabric_rebuild = ''
```

but it's silly to specify it like that, of course.

We should fix those wrong examples, to avoid confusion, thanks for pointing that out.

**Comment by fenz** [comment]
It is clear now. Thanks a lot.

**Comment by boegel** [comment]
I got rid of the confusing `'True'` instances in #9657, so closing this...

Thanks again for opening the issue @fenz!
