### ISSUE TITLE
MathGL not linking due to HDF5 with MPI support

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9640]
I can't build MathGL-2.4.1-foss-2018a.eb because it fails with many undefined references to MPI und MPIxx functions. This is caused by HDF5 being build with MPI support (HDF5_PARALLEL) but mpicc/mpicxx is not used for building MathGL.

I'm wondering how this did ever work and passed review. Am I missing anything?

A couple of commandlines that helped in reproducing:

`cd /tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/easybuild_obj/udav && /sw/installed/GCCcore/6.4.0/bin/g++  -DHAVE_MEMRCHR -DMGL_SRC -DNO_COLOR_ARRAY -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/easybuild_obj/udav -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/mathgl-2.4.1/udav -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/easybuild_obj/udav/udav_autogen/include -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/mathgl-2.4.1/include -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/easybuild_obj/include -I/sw/installed/GSL/2.4-GCCcore-6.4.0/include -I/sw/installed/HDF5/1.10.1-foss-2018a/include -I/sw/installed/OpenBLAS/0.2.20-GCC-6.4.0-2.28/include -I/sw/installed/ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20/include -I/sw/installed/FFTW/3.3.7-gompi-2018a/include -I/sw/installed/zlib/1.2.11-GCCcore-6.4.0/include -I/sw/installed/Szip/2.1.1-GCCcore-6.4.0/include -I/sw/installed/libjpeg-turbo/1.5.3-GCCcore-6.4.0/include -I/sw/installed/libpng/1.6.34-GCCcore-6.4.0/include -I/sw/installed/Mesa/17.3.6-foss-2018a/include -I/sw/installed/FLTK/1.3.4-foss-2018a/include -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtCore -isystem /sw/installed/Qt5/5.10.1-foss-2018a/./mkspecs/linux-g++-64 -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtGui -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtWidgets -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtPrintSupport -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtOpenGL  -O2 -ftree-vectorize -march=native -fno-math-errno -fopenmp -fopenmp -O3 -DNDEBUG   -fPIC -std=gnu++11 -E /tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/mathgl-2.4.1/udav/text_pnl.cpp` shows that `mpi.h` is included via HDF5.

`cd /tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/easybuild_obj/udav && /sw/installed/GCCcore/6.4.0/bin/g++  -DHAVE_MEMRCHR -DMGL_SRC -DNO_COLOR_ARRAY -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/easybuild_obj/udav -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/mathgl-2.4.1/udav -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/easybuild_obj/udav/udav_autogen/include -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/mathgl-2.4.1/include -I/tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/easybuild_obj/include -I/sw/installed/GSL/2.4-GCCcore-6.4.0/include -I/sw/installed/HDF5/1.10.1-foss-2018a/include -I/sw/installed/OpenBLAS/0.2.20-GCC-6.4.0-2.28/include -I/sw/installed/ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20/include -I/sw/installed/FFTW/3.3.7-gompi-2018a/include -I/sw/installed/zlib/1.2.11-GCCcore-6.4.0/include -I/sw/installed/Szip/2.1.1-GCCcore-6.4.0/include -I/sw/installed/libjpeg-turbo/1.5.3-GCCcore-6.4.0/include -I/sw/installed/libpng/1.6.34-GCCcore-6.4.0/include -I/sw/installed/Mesa/17.3.6-foss-2018a/include -I/sw/installed/FLTK/1.3.4-foss-2018a/include -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtCore -isystem /sw/installed/Qt5/5.10.1-foss-2018a/./mkspecs/linux-g++-64 -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtGui -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtWidgets -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtPrintSupport -isystem /sw/installed/Qt5/5.10.1-foss-2018a/include/QtOpenGL  -O2 -ftree-vectorize -march=native -fno-math-errno -fopenmp -fopenmp -O3 -DNDEBUG   -fPIC -std=gnu++11 -E /tmp/s3248973-EasyBuild/MathGL/2.4.1/foss-2018a/mathgl-2.4.1/udav/text_pnl.cpp` shows that `-lmpi` is not linked and this fails with the undefined references.

Further info: CMake finds HDF5 and sets HDF5_IS_PARALLEL which seems to mean that one should build/link with MPI, but that has to be specified manually. CMake does parse the wrapper output of h5pcc but does not see through the mpi wrapper.

@hajgato Do you have your install logs or know why it worked?

I found that one workaround is to add `-DOMPI_SKIP_MPICXX=1` to skip MPICXX which removes the dependency to libmpi too.

**Comment by boegel** [comment]
`MathGL-2.4.1-foss-2018a.eb` still builds fine for me...

Full log available at https://gist.github.com/boegel/cf3eea75fd6039740d794b3c81023eef, let me know if that's helpful or if you need more information.

**Comment by Flamefire** [comment]
From my findings in the related issue https://github.com/easybuilders/easybuild-easyconfigs/issues/9610 I think this might be related to MPI being build with MPICXX support which keeps unused symbols around. Can you check our mpi.h for `#define OMPI_BUILD_CXX_BINDINGS 1`? It is in `OpenMPI/2.1.2-GCC-6.4.0-2.28/include/mpi.h` If this is 1 and you still don't see the issue then I got to investigate further.

**Comment by boegel** [comment]
```
$ grep OMPI_BUILD_CXX_BINDINGS /software/OpenMPI/2.1.2-GCC-6.4.0-2.28/include/mpi.h
#define OMPI_BUILD_CXX_BINDINGS 0
```

**Comment by verdurin** [comment]
@Flamefire @boegel any updates on this one?

**Comment by Flamefire** [comment]
Yes. See the PR closing this: https://github.com/easybuilders/easybuild-easyconfigs/pull/9703
