### ISSUE TITLE
HDF5-1.10.2-PGI-18.4-GCC-6.4.0-2.28 fails to compile

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9676]
Compilation fails with

> PGC-S-0039-Use of undeclared variable DBL_EPSILON (H5timer.c: 213)
PGC/x86-64 Linux 18.4-0: compilation completed with severe errors
make[2]: *** [H5timer.lo] Fehler 1

and 

> PGC-W-0095-Type cast required for this conversion (H5system.c: 1089)
PGC-W-0155-Pointer value created from a nonlong integral type  (H5system.c: 1089)
PGC/x86-64 Linux 18.4-0: compilation completed with severe errors

**Comment by Flamefire** [comment]
This is due to the failed check "checking for ANSI C header files" with the following output:

```
configure:5533: checking for ANSI C header files
   1 configure:5553: pgcc -c  -O2 -Mflushz -fPIC  -I/sw/installed/Szip/2.1.1-GCCcore-6.4.0/include -I/sw/installed/zlib/1.2.11-GCCcore-6.4.0/include conftest.c >&5
 configure:5553: $? = 0
 PREPRO-I-0222-Redundant definition for symbol __extension__ (/usr/include/sys/cdefs.h: 358)
 configure:5637: result: no
```

So it uses a system header which is why it may work or not

**Comment by Flamefire** [comment]
And finally traced to the environment variable `CPP` being set to `pgcc -Mcpp` by our sites module. Not sure if this is standard for PGI-18.4, if it is not these issues can be closed

**Comment by boegel** [comment]
I can't check on my end, the license I have for PGI is apparently expired for PGI 18.4...

**Comment by boegel** [comment]
This should probably be closed, doesn't seem worth the effort to still figure out...
