### ISSUE TITLE
GCCcore 8.2.0 has broken HTTPS link for ISL

### ISSUE THREAD

**Issue by zao** [easybuilders/easybuild-easyconfigs#9692]
The URL for isl-0.20 in GCCcore-8.2.0 has recently been changed to HTTPS in d93ef853012ef04e373cd19696e045408d8b5a8f but the server does not serve downloads over HTTPS, it just redirects to the HTTP HTML file listing on requests.

edit: issue introduced via #9591

**Comment by boegel** [comment]
cc @OleHolmNielsen

**Comment by boegel** [comment]
fixed in #9784
