### ISSUE TITLE
mvapich2 download paths incorrect

### ISSUE THREAD

**Issue by jabl** [easybuilders/easybuild-easyconfigs#973]
Trying to build the "gmvolf" toolchain fails with

== building and installing MVAPICH2/1.9-GCC-4.7.3...
== fetching files...
== FAILED: Installation ended unsuccessfully: build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/software/EasyBuild/1.14.0/lib/python2.6/site-packages/easybuild_framework-1.14.0-py2.6.egg/easybuild/framework/easyblock.py:562 in obtain_file): Couldn't find file mvapich2-1.9.tgz anywhere, and downloading it didn't work either...
Paths attempted (in or
== Results of the build can be found in the log file /tmp/easybuild-PljJbQ/easybuild-MVAPICH2-1.9-20140714.142731.ZoyXJ.log
ERROR: EasyBuild crashed with an error (at easybuild/software/EasyBuild/1.14.0/lib/python2.6/site-packages/easybuild_framework-1.14.0-py2.6.egg/easybuild/main.py:112 in build_and_install_software): Build of /share/apps/easybuild/software/EasyBuild/1.14.0/lib/python2.6/site-packages/easybuild_easyconfigs-1.14.0.0-py2.6.egg/easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-GCC-4.7.3.eb failed (err: "build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/software/EasyBuild/1.14.0/lib/python2.6/site-packages/easybuild_framework-1.14.0-py2.6.egg/easybuild/framework/easyblock.py:562 in obtain_file): Couldn't find file mvapich2-1.9.tgz anywhere, and downloading it didn't work either...\nPaths attempted (in or")

It seems the MVAPICH2 download URL's have changed. At least for the latest mvapich2 version 2.0 the URL seems to be http://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich2-2.0.tar.gz

**Comment by boegel** [comment]
@besserox has been trying to convince the MVAPICH2 team not to remove source tarballs for previous versions...

**Comment by besserox** [comment]
I will contact them right after the release of EasyBuild 2.7.0 and keep you updated.

**Comment by besserox** [comment]
Just a short update about this. 

The MVAPICH2 team confirmed to me that they will keep online their source tarballs from now on.
However, the old releases still appear to be missing. 

This is the current status:
- `mvapich2-1.7.tar.gz`    -> broken
- `mvapich2-1.8.1.tar.gz`  -> broken
- `mvapich2-1.9.tar.gz`    -> broken
- `mvapich2-1.9a2.tar.gz`  -> broken
- `mvapich2-1.9b.tar.gz`   -> broken
- `mvapich2-1.9rc1.tar.gz` -> broken
- `mvapich2-2.0.1.tar.gz`  -> OK
- `mvapich2-2.1.tar.gz`    -> OK
- `mvapich2-2.2b.tar.gz`   -> OK

**Comment by fgeorgatos** [comment]
@besserox : well done! thanks about this Xavier

**Comment by boegel** [comment]
+1, thanks for the effort @besserox 

W.r.t. the old versions: is it that they really don't want to provide them, or that they don't have them themselves anymore? If so, I can provide most of those... ;)

**Comment by besserox** [comment]
No idea. I asked, but I did not have an answer on this point.

**Comment by fgeorgatos** [comment]
for the record, gmvolf-1.7.20 is with a convenient version of mvapich (2.0.1) albeit with an older GCC; goolf-1.7.20 is used for recent hpcbios incarnations and gmvolf could well be a drop-in replacement, fi:
https://github.com/hpcbios/HPCBIOS-easyconfigs/tree/master/h/HPCBIOS_Climate ; tbc.

**Comment by Micket** [comment]
All these toolchains have been deprecated now.
