### ISSUE TITLE
ParMGridGen download broken

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#9837]
So, ParMGridGen homepage seems to be gone. Can't be downloaded from there anymore either.

I got a suggestion that this link works:
http://www.mgnet.org/mgnet/Codes/parmgridgen/ParMGridGen-1.0.tar.gz
which, while it works, doesn't seem super-reliable either, considering the dead links on http://www.mgnet.org/mgnet-codes-parmgridgen.html

I also found https://github.com/mrklein/ParMGridGen, though, it doesn't have a 1.0 release https://github.com/mrklein/ParMGridGen/issues/2

Should we just switch to that working link for now?

**Comment by boegel** [comment]
@Micket SHA256 checksum for http://www.mgnet.org/mgnet/Codes/parmgridgen/ParMGridGen-1.0.tar.gz matches with my cached download from Dec 14th 2019, so should be OK to use that for now?

**Comment by migueldiascosta** [comment]
@Micket see also https://github.com/easybuilders/easybuild-easyconfigs/pull/9963#issuecomment-594421599

**Comment by boegel** [comment]
@migueldiascosta @Micket fixed in #10019
