### ISSUE TITLE
Multiple ICU dependencies on GCCcore/8.3.0

### ISSUE THREAD

**Issue by lexming** [easybuilders/easybuild-easyconfigs#9841]
There is `ICU-64.2` and `ICU-65.1` in the `GCCcore/8.3.0` toolchain. Unexpectedly, we currently have different packages depending on these two version of ICU, making all check tests fail for any new easyconfig having a dependency on ICU.

* `R-3.6.2-foss-2019b` and `R-3.6.2-fosscuda-2019b` depend on `ICU-64.2`. Merged in #9519 
* `HarfBuzz-2.6.4-GCCcore-8.3.0` depends on `ICU-65.1`. Merged in #9726

The weird part is that PR for `HarfBuzz-2.6.4-GCCcore-8.3.0` was opened after the merge of `R-3.6.2`, so those tests should have failed.

Example of PR affected by this issue is #9793: where tests fail even though it does not directly depend on ICU but it hits it through `Pango/1.44.7-GCCcore-8.3.0` > `HarfBuzz-2.6.4-GCCcore-8.3.0` > `ICU-65.1-GCCcore-8.3.0`.

**Comment by lexming** [comment]
I suggest to fix `HarfBuzz-2.6.4-GCCcore-8.3.0` by changing its dependency to `ICU-64.2`
Fix in PR #9842

**Comment by boegel** [comment]
@lexming I'll check whether the tests missed this, I think it's important to figure that out before merging #9842 (which is the right way to fix this issue imho).

**Comment by boegel** [comment]
OK, it actually makes sense (sort of) that the tests didn't catch this...

* `HarfBuzz` uses `GCCcore/8.3.0` as toolchain, and depends on `ICU` 65.1
* `R` uses `foss*/2019b` as toolchain, and has depends on `ICU` 64.2

So, the check for one-dep-version-per-toolchain-version doesn't take into account that `GCCcore/8.3.0` is a subtoolchain of `foss/2019b`, it only checks for a single dep version per toolchain (`GCCcore/8.3.0` as `*/2019b` separately).

That's a bug I guess, which should be fixed, but it's not trivial...
Also, making that change now in the tests will likely result in more skeletons falling out of the closet.
We can look into this for the upcoming `2020a` generation of easyconfigs though...

**Comment by boegel** [comment]
follow-up in #9846...
