### ISSUE TITLE
define foss/2020a and intel/2020a common toolchains

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#9847]
Current plan:

* `foss/2020a`:
  * `GCC` 9.2.0 + `binutils` 2.32
  * `OpenMPI` 4.0.3 (see https://github.com/open-mpi/ompi/milestone/52)
  * `OpenBLAS` 0.3.8 (#9852, released on Feb 9th 2020: https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.8)
  * `FFTW` 3.3.8
  * ScaLAPACK 2.1.0

* `intel/2020a`
  * based on `GCCcore` 9.2.0 + `binutils` 2.32
  * `iccifort` 2020 initial release (2020.0.166, `icc`/`ifort` 19.1.0.166)
  * `impi` 2019.6.166
  * `imkl` 2020.0.166

**Comment by boegel** [comment]
Note: we're keeping the option open to jump to GCC 9.3 if that's released "in time".

**Comment by zerothi** [comment]
You have probably discussed this previously (I tried searching, to no avail), but what are the policy on easybuilds with Intel compilers and their GCC requirements?

For instance, ifort P-XE 2020, states "gcc 4.8.5 to gcc 9.0.1 and binutils 2.27 to binutils 2.31.1" [here](https://software.intel.com/en-us/articles/intel-fortran-compiler-191-for-linux-release-notes-for-intel-parallel-studio-xe-2020)

And ifort P-XE 2019, states "gcc 4.4 to gcc 7 and binutils 2.20 to binutils 2.29" [here](https://software.intel.com/en-us/articles/intel-fortran-compiler-190-for-linux-release-notes-for-intel-parallel-studio-xe-2019)

Your toolchains does not obey these release notes recommendations.

Now, I agree that it would be nicer to bump GCC versions. But on the other hand, Intel does not test with other GCC versions than what they list.
To add to the complication. icc typically have different requirements, P-XE 2020, "gcc versions 4.4 - 9.2" [here](https://software.intel.com/en-us/node/807141)
And P-XE 2019 "gcc versions 4.3 - 8.x", [here](https://software.intel.com/en-us/articles/intel-c-compiler-190-for-linux-release-notes-for-intel-parallel-studio-xe-2019)

**Comment by boegel** [comment]
@zerothi We usually double-check with Intel support before we go forward with a particular GCC version.

Frequently the release notes of the Intel compilers are outdated because GCC versions are released afterwards.

In addition, we test fairly extensive before we're happy with a specific toolchain definition.

**Comment by boegel** [comment]
`2020a` toolchains definitions are finalized in #10483 (`foss/2020a`) and #10494 (`intel/2020a`), to be included with EasyBuild v4.2.1, so closing this...
