### ISSUE TITLE
OpenBLAS/0.3.8-GCC-9.2.0 loss of accuracy errors in CPUs with AVX512

### ISSUE THREAD

**Issue by lexming** [easybuilders/easybuild-easyconfigs#9861]
We have detected a serious error in the build of OpenBLAS/0.3.8-GCC-9.2.0 (#9852) on a Skylake machine that leads to loss of accuracy

```
******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE ******* 
          EXPECTED RESULT   COMPUTED RESULT                             
      1      0.267033          0.267033                             
      2     -0.335365         -0.335365                             
      3     -0.308392         -0.308392                                  
      4      0.347952          0.347952                                 
      5     -0.476523E-01     -0.476523E-01                             
      6     -0.200500         -0.200500                                  
      7      0.276024          0.276024                                  
      8     -0.416284         -0.416284                                  
      9      0.419880          0.466533                                  
     10      0.383916          0.426573                                 
     11      0.410889          0.456543                                  
******* DGEMV  FAILED ON CALL NUMBER:                                    
  2176: DGEMV ('N', 11,  7, 0.0, A, 12, X, 1, 0.9, Y, 2)         .
```

The affected tests are:
* DGEMV
* DGBMV
* DSYMV
* DSBMV
* DSPMV
* cblas_dgemv

Following the update on the `openblas` easyblock (easybuilders/easybuild-easyblocks#1953), these errors are now caught by EB and it properly stops the installation. But previous easyconfigs of OpenBLAS might have issues.

The cause of the error in version 0.3.8 is the compilation option `-ftree-vectorize` added by EB. The issue has already been reported upstream at xianyi/OpenBLAS#2408.
Two different fixes for `dscal_kernel_8` have been proposed
* a) call with `noinline`
```
--- kernel/x86_64/dscal_microk_skylakex-2.c.orig        2020-02-09 17:16:28.000000000 -0500
+++ kernel/x86_64/dscal_microk_skylakex-2.c     2020-02-11 14:18:53.000000000 -0500
@@ -32,6 +32,8 @@
 #define HAVE_KERNEL_8 1
+static void dscal_kernel_8( BLASLONG n, FLOAT *alpha, FLOAT *x) __attribute__ ((noinline));
+
 static void dscal_kernel_8( BLASLONG n, FLOAT *alpha, FLOAT *x)
 {
        int i = 0;
```
* b) call with  `no-tree-vectorize`
```
--- kernel/x86_64/dscal_microk_skylakex-2.c.orig        2020-02-09 17:16:28.000000000 -0500
+++ kernel/x86_64/dscal_microk_skylakex-2.c     2020-02-11 14:18:53.000000000 -0500
@@ -32,6 +32,8 @@
 #define HAVE_KERNEL_8 1
+__attribute__((optimize("no-tree-vectorize")))  static void dscal_kernel_8( BLASLONG n, FLOAT *alpha, FLOAT *x);
+
 static void dscal_kernel_8( BLASLONG n, FLOAT *alpha, FLOAT *x)
 {
        int i = 0;
```

I have no idea of the different implications in terms of performance of these two patches. Tests are being carried out and feedback is welcome.

**Comment by boegel** [comment]
@lexming An easy way out would be to simply disable the use of `-ftree-vectorize` for building OpenBLAS 0.3.8?

```python
toolchainopts = {'vectorize': False}
```

All easyconfigs for OpenBLAS 0.3.x already use this, except for OpenBLAS 0.3.7 where is wasn't needed?

I would prefer that approach over patching OpenBLAS 0.3.8, certainly short term, unless the OpenBLAS maintainers come up with an official fix quickly.

There's no point in letting the "broken" easyconfig for OpenBLAS 0.3.8 sit in `develop` if we know a reasonable fix for it?

**Comment by boegel** [comment]
cc @bartoldeman

**Comment by bartoldeman** [comment]
Performance-wise it's better to leave the vectorizer on.

In terms of the two patches, which of the two to apply doesn't really matter. The one with noinline makes the skylake code consistent with the other arches so I prefer that for now. I'm doing some more debugging today to see if there's a GCC bug or something else.
