### ISSUE TITLE
Using %(pyshortver)s with Python multi-deps

### ISSUE THREAD

**Issue by casio888** [easybuilders/easybuild-easyconfigs#9863]
Hello,
I am currently in the proces of writing an EasyConfig for PySVN. It uses  `multi_deps = {'Python': ['3.7.2', '2.7.15']}`

For the configure comand I need to specify the python version in a path of PyCXX, and tried to use `configure --pycxx-src-dir=$EBROOTPYCXX/share/python%(pyshortver)s/CXX/`, which results in it being replaced by "2.7" for the whole process. This causes the Python 3 iteration to fail, as there is still "2.7" in the path. 

Is this the intended way this should work. Which way would work for this purpose?

**Comment by boegel** [comment]
@casio888 My apologies for the late reply to your question...

The installation procedure is executed twice when using `multi_deps` with two Python versions, and the `%(pyshortver)s` template should get resolved as expected (first with `3.7`, then with `2.7`).

Can you share the easyconfig file you're using here, so we can try and reproduce the issue?

**Comment by boegel** [comment]
closing since #9900 is closed due to lack of activity since Feb'20
