### ISSUE TITLE
Easyconfigs that might need an update before 2020a is merged

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyconfigs#9924]
This is a list of Easyconfig files that should get an update, if at all possible, before branch 2020a is merged into a release.

- [ ] UCX : 1.8.0
- [x] PMIx : 3.1.5 (#9930)
- [ ] GCC : 9.3.0
- [x] OpenMPI : 4.0.3
- [ ] R: 3.6.3 (due for release on 29th February)
- [x] Python: 3.8.2
- [ ] GCC 9.3.0 + binutils 2.34?
- [ ] cURL 7.69.1 (https://curl.haxx.se/mail/lib-2020-03/0032.html)

**Comment by bartoldeman** [comment]
Is UCX 1.8.0 out soon? I thought 1.7.0 is still quite recent?

**Comment by bartoldeman** [comment]
binutils also has a newer version: 2.34

**Comment by akesandgren** [comment]
I'm hoping that they will make 1.8.0 before we need to freeze 2020a.... I need the fix in there, but since that is usually handled by a hook it's not a big problem.
Just wanted to make sure it's available for users, if possible, when the release is made.
