### ISSUE TITLE
iccifort-2020.0.166.eb fails to install

### ISSUE THREAD

**Issue by tstrempel** [easybuilders/easybuild-easyconfigs#9935]
```
== 2020-02-26 15:36:30,736 run.py:219 INFO running cmd:  ./install.sh  -s /tmp/easybuild-build/iccifort/2020.0.166/system-system/parallel_studio_xe_2020_composer_edition/silent.cfg
== 2020-02-26 15:36:33,068 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " ./install.sh  -s /tmp/easybuild-build/iccifort/2020.0.166/system-system/parallel_studio_xe_2020_composer_edition/silent.cfg " exited with exit code 4 and output:
grep: write error: Broken pipe
--------------------------------------------------------------------------------
Error during the silent install. ACTIVATION_TYPE=exist_lic specified although no
existing license is found on the system. Please use other activation types.
--------------------------------------------------------------------------------
 (at easybuild/tools/run.py:529 in parse_cmd_output)
== 2020-02-26 15:36:33,068 easyblock.py:3109 WARNING build failed (first 300 chars): cmd " ./install.sh  -s /tmp/easybuild-build/iccifort/2020.0.166/system-system/parallel_studio_xe_2020_composer_edition/silent.cfg " exited with exit code 4 and output:
grep: write error: Broken pipe
--------------------------------------------------------------------------------
Error during the sil
== 2020-02-26 15:36:33,068 easyblock.py:295 INFO Closing log for application name iccifort version 2020.0.166
```

The silent install failed because of the wrong activation type. Shouldn't iccifort be configured to use the license server?

**Comment by boegel** [comment]
@tstrempel Which EasyBuild version are you using here?

Did you specify a license server somehow, for example by defining the `$INTEL_LICENSE_FILE` environment variable?

**Comment by tstrempel** [comment]
```
modextravars = {'INTEL_LICENSE_FILE': '/usr/local/intel/licenses'}
license_file = '/usr/local/intel/licenses'
```

I used my system specific path to my licenses, this path does work for `icc/2018.3.222-GCC-7.3.0-2.30` and `ifort/2018.3.222-GCC-7.3.0-2.30`.

I'm using EasyBuild v4.1.1, the error is also reproducible with v4.0.0. My guess is that the silent.cfg that EasyBuild normally provides, which includes using a license server as ACTIVATION_TYPE, is not used.

**Comment by akesandgren** [comment]
what you should do when installing intel is something like this
env INTEL_LICENSE_FILE=port@licserver eb intel-2019b.eb -r

It will then add the licens info to the installed modules.

**Comment by tstrempel** [comment]
@akesandgren Thanks for the tip, but that doesn't change my error / the issue with the silent.cfg.

**Comment by tstrempel** [comment]
@boegel Are there any news regarding this problem?

**Comment by akesandgren** [comment]
I see no problems with this using current develop tree.
Nor do I see any problems with current EB release, 4.2.0

Are you still seeing problems and what release are you using?

**Comment by akesandgren** [comment]
Hmm, are you perhaps running out of space in /tmp?

**Comment by tstrempel** [comment]
No, I'm not running out of space on /tmp. Everything else is working fine.
I also can't see anything wrong with the iccifort EasyBlock. 

I still have the same problems. I will update to v4.2.1, maybe it get's working again.

**Comment by akesandgren** [comment]
Then we'd need to see a debug build, i.e. add --debug flag and upload the complete log file to gist

**Comment by tstrempel** [comment]
Thanks for the help, here is the gist:
https://gist.github.com/tstrempel/94bad78c5a4d4cc2ca18673cbc5c8cd8

**Comment by tstrempel** [comment]
Same happens with iccifort-2020.1.217.eb:
https://gist.github.com/tstrempel/f4ca7ddd6586871068d52e52cbd27a27

**Comment by akesandgren** [comment]
Ok, can you take a copy of $EBROOTEASYBUILD/lib/python2.7/site-packages/easybuild/easyblocks/generic/intelbase.py
change line 322 to
```
lic_file_server_activations = [ACTIVATION_EXIST_LIC, ACTIVATION_LIC_FILE, ACTIVATION_LIC_SERVER]
```
And test again, this time with --include-easyblocks=path-to-modified-intelbase.py

**Comment by tstrempel** [comment]
https://gist.github.com/tstrempel/a98bbfb5db80106215accbfd93a41f2b

Now I'm getting proper error messages, there is a new problem that the Intel license manager is too old for 2020.x compilers.

I'll come back, when the license server was updated.

Thanks for the support!
